### ISSUE TITLE
attach react component to already rendered DOM (which is not rendered by react on server)

### ISSUE THREAD

**Issue by pcompassion** [facebook/react#7712]
I'd like to keep traditional server side rendering (not react rendering with node) and attach client side code.   
I believe the following statement might help to achieve that. I wonder if any work is being done.  
Or any help or guide on how to mix server rendered content (via server side template such as jinja2 ) with react at the moment would be greatly appreciated.

https://facebook.github.io/react/docs/top-level-api.html states that 

> ReactDOM.render() does not modify the container node (only modifies the children of the container). In the future, it may be possible to insert a component to an existing DOM node without overwriting the existing children.

**Comment by gaearon** [comment]
There is currently no support for React component reusing non-React-generated markup. Your next best bet would be to use server rendering for static non-React parts, and mount React components on the client side inside those DOM nodes.

**Comment by chrischrischris** [comment]
https://github.com/auniverseaway/react-dom-components may do what you are looking for.

**Comment by gaearon** [comment]
Technically React 16 *can* attach to non-React-generated markup although this is pretty fragile.

**Comment by tadeo** [comment]
> Technically React 16 _can_ attach to non-React-generated markup although this is pretty fragile.

@gaearon are you referring to Portals?
