### ISSUE TITLE
Log a warning when in development mode

### ISSUE THREAD

**Issue by threepointone** [facebook/react#7713]
**Do you want to request a _feature_ or report a _bug_?**
- feature 

Ref this tweet from Dan - 
https://twitter.com/dan_abramov/status/775647965197336576

It's currently too easy to use React in `development` mode while in production, and there's little warning from the library that this is happening. Further, it takes a fair bit of googling to know what to do, (it's tucked away under 'advanced performance' in the docs, _and_ doesn't include directions for webpack/browserify). 

As a start, I recommend that react _always_ log a message to console when it's in development mode. Something like - 

"running in development mode, use [production mode flags](https://facebook.github.io/react/docs/advanced-performance.html) to speed up your code"

This stands out, and I hope will prevent some, if not most, of these misses.

**Comment by anenthg** [comment]
I recently discovered that I was running one of my apps in development mode. A console message like the one suggested will definitely help!

**Comment by syranide** [comment]
Not disagreeing, but I can imagine a lot of people would be really upset by this. People don't like non-fixable messages in the console.

However, I thought we already had a warning for when you're running development mode in a minified bundle?

**Comment by gaearon** [comment]
>However, I thought we already had a warning for when you're running development mode in a minified bundle?

Good point, I forgot about that one! It seems like some people don’t read logs in production then.

Logging a warning *in development* would serve to educate them about different development/production modes. We already have a warning about DevTools so maybe we could change its wording to also make it clear this is dev version of React itself, and always show it?

**Comment by threepointone** [comment]
^ yes, repurposing the devtools message should do the trick. A link to a docs page with instructions for bundler of choice would be awesome too.

**Comment by syranide** [comment]
People have been plenty annoyed at the devtools message though. Also we do hide the devtools warning if you have the devtools installed so that's something to take into account as well.

**Comment by Aweary** [comment]
Expanding the copy of the devtools message is a reasonable middle ground. It targets users who might not be familiar with React's development experience or tools, which at the very least has a non-trivial overlap with users who don't know about production vs. dev in React.

Plus, at least you can make the devtools warning go away if you really want to.

**Comment by viniciusCamargo** [comment]
And how to actually change it for production?

**Comment by gaearon** [comment]
https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build

**Comment by viniciusCamargo** [comment]
Thank you! :D

**Comment by threepointone** [comment]
based on this tweet https://twitter.com/floydophone/status/820137822573232128
```jsx
if(process.env.NODE_ENV !== 'production'){
  let oldNow = performance.now.bind(performance),
  warned = false 
  performance.now  = (...args) => {
    if(!warned) {
      console.warn('It looks like you\'re trying to run a performance benchmark in dev mode. Boo.')
      warned = true 
    }
    return oldNow(...args)
  }  
}
```

**Comment by gaearon** [comment]
We now warn in DevTools and it's been working well.
We also have docs about it now.
