### ISSUE TITLE
Bug: False Positive "plain object" Warning  

### ISSUE THREAD

**Issue by spudly** [facebook/react#7718]
There is a bug in the logic for determining if `props` is a plain object. This bug results in a false positive, flooding the console with hundreds of instances of this warning: "Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored.".

The code that's failing is in [ReactElement.js, Line 210 in the v15.3.1 branch](https://github.com/facebook/react/blob/v15.3.1/src/isomorphic/classic/element/ReactElement.js#L210) (line number is probably different in master)

> config.__proto__ == null || config.__proto__ === Object.prototype,

This fails when the props object is created in one iframe, but uses an instance of React from another frame. Each browser window/tab/frame has it's own instance of the Object constructor. For instance, `document.querySelector('iframe').contentWindow.Object === Object` always results in `false`.

Check out this [demo](https://jsfiddle.net/05ugxo5f/4/), which shows the false-positive warning message.

**Comment by spudly** [comment]
FYI: I just checked, and lodash's `isPlainObject()` function behaves as expected for objects created in different frames.

To fix this issue, we could either import and use lodash's function, or copy the [isPlainObject() implementation](https://github.com/lodash/lodash/blob/4.15.0/lodash.js#L11717) into the React codebase.

**Comment by spicyj** [comment]
Ugh. I think we should just revert this warning. It's caused frustration in many cases.

**Comment by gaearon** [comment]
👍

**Comment by spudly** [comment]
Fine by me.

P.S. Sorry for the bizarre use case. I'm doing some pretty hacky stuff to isolate plugins inside an iframe.

**Comment by spicyj** [comment]
Okay, let's remove these lines and any associated tests:

https://github.com/facebook/react/blob/v15.3.1/src/isomorphic/classic/element/ReactElement.js#L207-L215

**Comment by Aweary** [comment]
@spudly do you want to submit a PR for this? 😃

**Comment by spudly** [comment]
Sure, seems simple enough. I'll take care of it.

**Comment by spudly** [comment]
Submitted #7724
