### ISSUE TITLE
state prop collecting geoloacation data even before component is mounted

### ISSUE THREAD

**Issue by kurtschlueter** [facebook/react#7719]
Ok so here is the problem. I have a Map component that gets someones current location every x seconds and stores the data in an array. When I launch my app, I am in a home scene with the option of opening the map in a new scene using the navigator. 

``` javascript
  startMemory() {
    this.props.navigator.push({
      component: Map,
      name: 'Map',
    })
  }
```

When I select this button, the route coordinates seem to have been collecting even before I rendered the map view. Here is what I have under component did mount.

``` javascript
  componentDidMount() {
      this.setState({
        routeCoordinates: []
      });

    navigator.geolocation.getCurrentPosition(
      (position) => {},
      (error) => alert(error.message),
      {enableHighAccuracy: true, timeout: 20000, maximumAge: 5000}
    );
    this.watchID = navigator.geolocation.watchPosition((position) => {
      const cp = {
        long: parseFloat(position.coords.longitude),
        lat: parseFloat(position.coords.latitude)
      }
      this.setState({
        routeCoordinates: this.state.routeCoordinates.concat({latitude: cp.lat, longitude: cp.long}),
        currentPosition: cp
      });
    });
  }
```

When I console log routCoordinates at the beginning of ComponentDidMount, it does give me an empty array as it should. The problem is that is seems to have been secretly rendering even before I navigated to the map component. I console logged the routeCoords immediately after the render(){...

``` javascript
  render() {
    console.log(this.state.routeCoordinates)
    return (
```

and so when I navigate to the map component the output gives me 

[]

[ { latitude: 37.33282574, longitude: -122.06131389 } ]

[ { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: 37.33230505, longitude: -122.05871525 } ]

[ { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: 37.33282574, longitude: -122.06131389 } ]

[ { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: [Getter/Setter], longitude: [Getter/Setter] },
  { latitude: 37.33282574, longitude: -122.06131389 } ]

And so on... all at once. Why is it doing this? I want to start fresh every time i mount this component. setState is irrelevant because it will set it to [] and then start collecting data even before ComponentDidMount gets run.

**Comment by Aweary** [comment]
Hey @kurtschlueter! It does seem like your component is starting being initially rendered with an empty array for `this.state.routeCoordinates` and then is updated by the function you registered with `geolocation.watchPosition`, which is called any time the position changes (which in your case seems to happen 4 times).

I'm not sure what you mean by it collecting data before `componentDidMount` is run. What are you initializing `this.state` to? FWIW you should be able to define your initial state in the `constructor` instead of adding another `setState` call

```js
constructor() {
  super();
  this.state = {
    routeCoordinates: []
  }
}
```

**Comment by aweary** [comment]
Closing since it doesn't appear to be an issue with React and there was no follow up
