### ISSUE TITLE
Skip comparing known constant props during reconciliation

### ISSUE THREAD

**Issue by jtadmor** [facebook/react#7720]
**Do you want to request a _feature_ or report a _bug_?**

_Feature_

**What is the current behavior?**

Currently, whether a prop is expected to change or not, it is passed through props. There is no way for us as developers to mark a prop as fixed (should never change over the lifecycle of a component).

**What is the expected behavior?**

These would _not_ be static properties, i.e. they can change from instance to instance. But they are created at initial render and never change (`===`) from the original. Ideally, though I'm not sure on implementation, they would also always be `deepEqual` to the original (perhaps something like `Object.freeze(Object.assign({}, originalObject))`.

Advantages to allowing props to be explicitly marked as fixed:
1. shouldComponentUpdate would be better if a lot if certain props automatically don't / can't change
2. Allow for errors / warnings when a prop marked as fixed is changed after the initial render.
3. Possible compiler / render optimizations knowing that particular props will never change over the course of multiple renders. In particular, if a component only has fixed props (including children), we know the render output is fixed, and we can just inline that output into the parent render output.

One possible API would allow a separate fixedProps category.

`React.createElement(MyComponent, { name: 'Hello' }, children, { message: 'Always this one string' })` (maintain signature)

For JSX, one (very mediocre) idea would be something like:
`<MyComponent name="Hello" $fixed.message="Always this one string" />`

Another would be a separate prop called $fixed or something similar.

`React.createElement(MyComponent, { name: 'Hello', $fixed: { message: 'Always this one string' } }, children)`
`<MyComponent name="Hello" $fixed={{ message: 'Always this one string' }} />`

It would be critical that `props` and `fixedProps` would be merged when the component is actually created. `this.props` would always contain all props, functional components still get one arg, and thus nobody has to rewrite render for any component.

**Comment by jedwards1211** [comment]
why pass fixed props in a different way than other ones?  After all, you can easily tag certain names in `propTypes` as fixed in your own code and print warnings if they change in your own `shouldComponentUpdate` helper.

**Comment by gaearon** [comment]
I don’t think we’ll ever do something like this as a public API, but it’s possible to do something like this as a compile target. @trueadm experimented with this in Inferno. I don’t think it gave a lot of benefit in real products compared to benchmarks but I might be wrong.

**Comment by jedwards1211** [comment]
@jtadmor One way to deal with this is use an HOC:

```js
const CompWithMessage = ({message}) => (props) => (
  <Comp {...props} message={message} />
)

const MyComp = CompWithMessage({message: 'Always this one string'})
```

Though I get tired of the extra step to instantiate HOCs...
I wish that the compiler would hoist props that are constant (including functions that don't depend on any variables from scope!) like `babel-plugin-transform-react-constant-elements` does for element subtrees that are constant.

**Comment by trueadm** [comment]
@jedwards1211 Is that really necessary? Strings are immutable anyway, so I guess it would make more sense with objects instead?

**Comment by jedwards1211** [comment]
@trueadm yes, and functions

**Comment by gaearon** [comment]
In this case it would be easier to hoist those functions when it’s safe (and thus ensure their identity)  than come up with workarounds in React.

**Comment by jedwards1211** [comment]
@gaearon true, is the Optimizing Compiler label about babel plugins or some other type of "compiler" within React itself?

**Comment by gaearon** [comment]
It's a generic label for potential optimizations a React-aware compiler *could* do. Not necessarily any existing ones.
