### ISSUE TITLE
JSX: alternative syntax for passing JSX content to props

### ISSUE THREAD

**Issue by danielearwicker** [facebook/react#7732]
Silly (but succinct) example:

```js
const If = ({test, yes, no}) => test ? yes : no;
```

Today we can say this:

```jsx
const eg1 = (
    <If test={allowed}
        yes={
            <button>Launch missiles</button>
        }
        no={
            <span>Access denied</span>
        } />
);
```

Proposal is to support this alternative, inspired by XAML:

```jsx
const eg2 = (
    <If test={allowed}>
        <If.yes>
            <button>Launch missiles</button>
        </If.yes>
        <If.no>
            <span>Access denied</span>
        </If.no>
    </If>
)
```

In short, if an element name contains `.` and the first part is the parent element's name, the second part is a prop name and the content becomes the value passed to that prop. Nothing else changes - it's merely an alternative way to specify the prop value.

It remains consistent with XML, where `.` is allowed; indeed, XAML was forced to do this in order to be an XML dialect and yet be flexible about how properties are specified on objects. JSX doesn't have that challenge, nevertheless in more complex examples it would lessen brain- and eye-strain to keep the structure of the tree obvious by staying in JSX syntax instead of `{ ... }` blocks stretching across many lines, and with a few layers of nesting alternating syntaxes.

And a further enhancement, say we have:

```jsx
const For = ({items, each}) => <div>{items.map(each)} </div>
```

Today we can say this:

```jsx
const eg3 = (
    <ul>
        <For items={things} 
            each={item => (
                <li>{item}</li>
            )} />
    </ul>
);
```

But how about:

```jsx
const eg4 = (
    <ul>
        <For items={things}>
            <For.each item>
                <li>{item}</li>
            </For.each>
        </For>
    </ul>
);
```

That is, in these "prop elements", which have no other purpose for their attributes, they can optionally specify valueless attributes. These become the parameter names of a function, and that function is then is passed to the prop. (Once again, it maps exactly to the previous example.) If no attributes are specified, as in `eg2`, then there is nothing variable for the content to depend on and hence it can just be a simple value rather than a function returning a value.

I found a prior issue https://github.com/facebook/react/issues/848 that seemed to be asking for something similar but wasn't as precisely mapped to existing concepts. Here I'm not talking about anything that changes the model, just a way of staying in JSX and reducing the mental overload of switching syntaxes when writing/reading trees.

**Comment by Aweary** [comment]
I believe proposals like this should be posted in [facebook/jsx](https://github.com/facebook/jsx) where the draft specification is defined.

**Comment by jimfb** [comment]
Also, I think what you're looking for is https://github.com/AlexGilleran/jsx-control-statements

**Comment by zpao** [comment]
Closing out since this isn't React specific.

FWIW, you are welcome to use that syntax already - it's valid JSX, you just need to build more knowledge into the components. It's highly unlikely the grammar of JSX will change to support the setting of props this way though.

**Comment by danielearwicker** [comment]
@Aweary - thanks, will post it there.

@jimfb - no, I don't specifically want conditionals, that's just an example.

**Comment by danielearwicker** [comment]
@zpao - can you explain how it is currently possible for a component to get its specific props to be set by different child element's content?

**Comment by zpao** [comment]
The props wouldn't get set, but it's possible to read from a child's props, so you could do `var yes = this.props.children[0].props.children` (note: don't assume props.children is an array use React.Children helpers).

That makes it possible to do this without changing the grammar. To make it set props with JSX you're going to have to do a lot more work and introduce some new concept to explain component namespacing actually maps to parent prop setting. It might be cool to do but adds a bunch of complexity for little actual value.
