### ISSUE TITLE
Fix Flow issues introduced in #7716

### ISSUE THREAD

**Issue by zpao** [facebook/react#7735]
We missed this because Flow wasn't being run properly on Travis but now that it is, it's clear that #7716 introduced a bunch of new Flow failures. Most of these shouldn't be too bad and I like to say "you break it you buy it" so this one is for you @Aweary :)

There were a couple other pre-existing Flow issues that @vjeux is going to fix, so mostly this should just be the TestRenderer issues.

**Comment by Aweary** [comment]
Was it just an issue with Flow on Travis? I didn't actually get any errors for flow locally in Nuclide, maybe something is wrong on my end there :)

I will fix this 👍

**Comment by vjeux** [comment]
The first three were introduced by https://github.com/facebook/react/pull/7649

```js
src/renderers/shared/stack/reconciler/ReactOwner.js:76
 76:     transaction,
         ^^^^^^^^^^^ parameter `transaction`. Missing annotation

src/renderers/testing/ReactTestMount.js:24
 24:   createNodeMock: (element: ReactElement) => Object,
                                 ^^^^^^^^^^^^ ReactElement. Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)

src/renderers/testing/ReactTestReconcileTransaction.js:60
 60: function ReactTestReconcileTransaction(testOptions) {
                                            ^^^^^^^^^^^ parameter `testOptions`. Missing annotation
```

The 17 others were introduced by https://github.com/facebook/react/pull/7716

So looks like all of them are yours @Aweary :)

Let me know if you need any help fixing them, I'd be happy to.

**Comment by vjeux** [comment]
@Aweary the issue was just on travis, running flow locally should show you all those errors.

**Comment by zpao** [comment]
You *should* be seeing the issue locally in Nuclide (I am right now), but it's possible they aren't there due to a version mismatch. Not sure how the integration works but maybe your global `flow` isn't the same version we're using in the flowconfig/package.json.

**Comment by Aweary** [comment]
@zpao it looks like there is a version mismatch, I've got `0.29.0` globally. Either way, I'll make sure to run flow in the terminal as well for future PRs 👍
