### ISSUE TITLE
Receiving user-entered input 

### ISSUE THREAD

**Issue by pfhayes** [facebook/react#7745]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
When serving controlled inputs serverside from ReactDOM, the user might have entered data already before the clientside React has executed. In this case, the data the user has entered gets overwritten by the initial value.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/k61pvqhk/

**What is the expected behavior?**
What mechanisms are available (or should be available) to capture this input? One natural solution I can imagine is some way to capture the user's entered text in `getInitialState` (or `componentWillMount`). We could hack this together by manually plucking the content from the DOM, but I'm interested to know if there is a more React-y solution if possible. The default of discarding the user's input is unlikely to be what is desired, for both the developer and the user.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I have not observed this working in previous versions of React. I see this in Chrome on Mac OS X with React 15.

**Comment by jackmarchant** [comment]
Could the solution be for the server to provide an initial state for the client side JavaScript to use for its initial render? 
This is a common pattern for server/client react applications where you want the client to "pick up" from the state the server knows about. 
For example, you could load the user value into an object in a script tag on the server, then load it into your component via props to set the initial state.

**Comment by pfhayes** [comment]
The problem here is not with the initial state - it's with picking up user input that the user has entered between the HTML being downloaded and between React initializing on the clientside. If we initialize a textbox to be empty, but then the user types something into the textbox before React initializes clientside, then their input will be wiped.

**Comment by alexeybondarenko** [comment]
@pfhayes I also think about this behavior. Do you have some solution for now for this case?

**Comment by gaearon** [comment]
It seems like more or less the same issue as https://github.com/facebook/react/issues/4293. Let’s keep the discussion there.
