### ISSUE TITLE
Note that `getInitialState` is not used in ES6 classes in docs

### ISSUE THREAD

**Issue by ssorallen** [facebook/react#7746]
Currently the the docs for [`getInitialState`](https://facebook.github.io/react/docs/component-specs.html#getinitialstate) do not mention that the method is not used in ES6 class syntax. It could use a note like the one for [`replaceState`](https://facebook.github.io/react/docs/component-api.html#replacestate) about the method not being available on ES6 classes.

This has caused at least a little confusion in a StackOverflow question about React + ES6: https://stackoverflow.com/questions/30720620/react-es6-getinitialstate-was-defined-on-a-plain-javascript-class/30721098#comment66352140_30721098

**Comment by gilchenzion** [comment]
@ssorallen happy to try and handle it. seems simple enough.

**Comment by zpao** [comment]
@gilchenzion Go for it!

**Comment by mbrevda** [comment]
seems this can be closed?

**Comment by gaearon** [comment]
Yep!
