### ISSUE TITLE
Use camelCase for event type name

### ISSUE THREAD

**Issue by souporserious** [facebook/react#7755]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`event.type` returns the original all lowercase event type name

**Description**
As a library or component author it would be nice to receive the event type as camelCase in the same way React requires the name to be camelCase when passing it through as a prop. This would allow authors to pass through props easier and allow people to still hook into these events.

**Example Usage**
```
_handleEvent = (e) => {
    const propEvent = this.props[`on${e.type}`]

    // library/component specific code

    if (typeof propEvent === 'function') {
      propEvent(e)
    }
  }
```

This is totally doable right now, but would require a third party add-on or function to keep track of new events added to React. It would be nice if React just provided the camelCase name for us :)

**Comment by ChBernat** [comment]
I'm on it.

**Comment by jimfb** [comment]
:/

This would be a breaking change anywhere that people check the event type:

```
function handleEvent(e) {
  if(e.type === 'onclick') doWhatever();
}
```

cc @gaearon @spicyj My intuition is that this is not worth the churn.  It's going to break too many things and I don't see a good migration path.

**Comment by spicyj** [comment]
Same. I don't think we'll do this, sorry.

**Comment by ChBernat** [comment]
I'm not react proffesionalist but I was on this issue for like 30 or even more minutes and to be honest in my opinion it's not that difficult to be accomplished.

I think that there's only one, last thing that keeps me away from achieving a result.

I have added a new property on a syntheticEvent object called cameCasedType and it's pretty much okay with all the examples except a JQuery one and there's some strange behaviour with clicks - to be more precise, every click-event is fired alright but when I'm clicking outside of a created component it throws me an error: 

`Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're setting the property `camelCaseType` on a released/nullified synthetic event. This is effectively a no-op. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.`

If anyone of you could provide me some information where can I find things that are in charge of those behaviours I would fix it and make a PR.

**Comment by spicyj** [comment]
Sorry, we don't want to make any change here. We don't want both `.type` and `.camelCaseType`, and the advantages of camel case here are too few in my opinion. To solve the original use case, you can write

```
onClick={(e) => this._handleEvent('onClick', e)}
```

or similar in your component code.

**Comment by ChBernat** [comment]
Okay, sounds fair to me. Just wanted to help. :)

**Comment by spicyj** [comment]
Yup, thank you!

**Comment by spicyj** [comment]
It can be tricky to work on issues if you don't know that a fix is wanted – you often end up wasting effort.
