### ISSUE TITLE
improve the tutuorial, remove the remarkable

### ISSUE THREAD

**Issue by wentin** [facebook/react#7758]
using remarkable is not helpful to a big portion of the reader, and it hurts the clarity and simplicity of a tutorial should have. This is a request to remove it.

**Comment by gaearon** [comment]
cc @lacker who plans to work on docs and I think also wanted to remove it.

**Comment by lacker** [comment]
Yes - I'm outlining what we want to do now, but we will probably replace that tutorial with a different one entirely. I agree that remarkable is a more-advanced and more-specialized thing than would ideally be in that tutorial.

**Comment by gaearon** [comment]
This tutorial is gone.
