### ISSUE TITLE
Feature request: Allow stateless components to render a plain String

### ISSUE THREAD

**Issue by joshfrench** [facebook/react#7760]
On occasion it would be cleaner to have a stateless functional component render a plain String (or perhaps any type that satisfies `React.PropTypes.node`) without needing to wrap it in an element. I can imagine this lending itself well to leaf components; I'm less sure that it would be possible to solve for plain nodes at the root, though.

(Sorry if this has been discussed before, I couldn't find any existing issues that looked related.)

**Comment by prasanna1211** [comment]
I would agree with the simplicity it creates, but I couldn't think of its impact on Reconciliation. Lets say we have a root component with simple string, how do we actually help the diff algorithm ( passing keys t elements?) The diffing algorithm will work based on the type of elements. Without elements I guess it would be tough.

**Comment by gaearon** [comment]
It works in 16.
