### ISSUE TITLE
Problem on iOS10 with <select> element

### ISSUE THREAD

**Issue by atorgfr** [facebook/react#7762]
I have a bug on iOS10 with Safari
I don't know if it's a react problem or react-router but this is my problem
You could reproduce it with this repo 
https://github.com/atorgfr/test_ios10_problem

At the beginning of this website, you will have two links Home and Select
Click on Select then change the value on this select element to anything. 
It will change this select with a new one.
If you click on Home, you should have this 

![image](https://cloud.githubusercontent.com/assets/1437106/18611744/d6601f92-7d43-11e6-855a-b1de0cc235e5.png)

There is no select on this "page"  but you still see this select open.

There was no problem with iOS 9.3.5 (13G36)

**Comment by atorgfr** [comment]
Ok it's not a react problem but a Safari problem 

Same problem with this
https://jsfiddle.net/pw7e2j3q/

**Comment by Aweary** [comment]
Thanks for the report @atorgfr, and for investigating this. I'm going to close this out since it's not an issue with React 👍

**Comment by atorgfr** [comment]
Yes no problem i should have done it before

Le dimanche 18 septembre 2016, Brandon Dail <notifications@github.com> a
écrit :
