### ISSUE TITLE
React github page localization issue

### ISSUE THREAD

**Issue by ryum91** [facebook/react#7763]
hello im korean,

Im being helped by [React korea page](https://facebook.github.io/react/docs/getting-started-ko-KR.html)

but, page sidebar is not translated (only english)

sidebar elements moved to the US when clicked

this is not only Korean issue (Japanese...)

i hope to be issue solved

Thanks

**Comment by zpao** [comment]
Sorry about that. Right now this isn't really possible without a ton of work and synchronization. We started #4633 as an attempt to solve this and expose translated documentation better but haven't had a chance to finish it. It's a known issue though, so we'll track it over there.
