### ISSUE TITLE
forceUpdate on defaultValue

### ISSUE THREAD

**Issue by tranv94** [facebook/react#7764]
So this is throwing me off. 

I was reading through a way (#3357) to update `defaultValue` and I saw one idea of using `forceUpdate`. I wanted to use key but the input I'm working doesn't change key. 
Here is what my input looks like

```
<input className="form-control"
                     placeholder="Minumum"
                     type="number"
                     value={arrMin[i]}
                     step="any"
                     onChange={this.handleChange.bind(this)}
```

And here is my `handleChange`

```
handleChange() {
    this.forceUpdate();
}
```

When I run  my program and type in the input box, I get:
`Uncaught TypeError: Cannot read property 'forceUpdate' of undefined`
But the thing is I can update `defaultValue` and rerender it, or atleast I think I am rerendering it. But the typed values are actually being applied and I can rerender them with a toggle.

UPDATE:
So I later debugged the problem further, and I just made `onChange={this.forceUpdate}`

So why is it still being called in my other function?
(btw if there's a better solution, I'd appreciate it :) )

**Comment by TryingToImprove** [comment]
Are you binding ´handleChange´

**Comment by tranv94** [comment]
@TryingToImprove  yup! I updated the code

**Comment by benjdlambert** [comment]
@tranv94 so, I can see that you're probably mapping over an array called `arrMin`, my question is where does that array come from?

Is it a `prop` passed into the component?

I don't really understand the use case or the problem, is there any way you could make a quick `jsfiddle` or something and outline your problem, and what the expected/actual is.

`/blam`

**Comment by gaearon** [comment]
Closing as there’s not enough info to help.
