### ISSUE TITLE
Add date created to docs

### ISSUE THREAD

**Issue by colinmegill** [facebook/react#7768]
Docs request: could dates be added to docs re: when and for what version they were written/introduced?

For instance:

https://facebook.github.io/react/warnings/unknown-prop.html

https://github.com/facebook/react/blob/5e3959e071b0750713bddf13e05319cd272a7b05/docs/warnings/unknown-prop.md

Could include a date this was written / introduced into the ecosystem.

**Comment by Aweary** [comment]
My one concern with this is that people may dismiss doc pages that were published a long time ago, even if their content still applies.

**Comment by colinmegill** [comment]
@Aweary You definitely have a point. I tried to think of the converse, a time when methods were sunset and their content *doesn't* still apply. I thought of mixins - the docs are still up without an 'deprecated' or 'not recommended' flag:

https://facebook.github.io/react/docs/reusable-components.html#mixins

but... 

@gaearon blogged: https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html

It may be too complicated to add a 'time' component to the docs, but there is a time component to what is recommended as the framework evolves and new methods are introduced. 

Just had a thought - rather than a date, docs could have a note: "Introduced in `15.3.2`" or "Not recommended as of `0.14.0`"

**Comment by Aweary** [comment]
@colinmegill our blog posts do have dates, FWIW. Ideally our docs would be updated if any of the content no longer applied. Docs should reflect the current API/patterns that are recommended by the core team. Blog posts are a little different, as they are often opinionated.

>  I thought of mixins - the docs are still up without an 'deprecated' or 'not recommended' flag:

In this case I think we should update the docs, even if its just a quick link to the blog post you mentioned.

**Comment by colinmegill** [comment]
Maybe it would be helpful to describe the specific context this thought came up, because it speaks to treating the docs as a reflection of the 'current' patterns. I was upgrading, hit some new error messages in console that led me to the page in the OP, and I was unsure of whether this was an API/error that had just been introduced in the latest version. 

Ie., docs aren't a central source of truth because there are multiple versions of the software in production. See lodash https://lodash.com/docs/4.16.1 as an example of best practices on versioning docs. 

But I think it's one or the other. If docs are a central source of truth, then the docs themselves have to be versioned. If the docs are all in one big blob (like now), then they should have some kind of flag denoting whether the method is active or deprecated, and for what versions the method applies.

**Comment by Aweary** [comment]
>  If the docs are all in one big blob (like now), then they should have some kind of flag denoting whether the method is active or deprecated, and for what versions the method applies.

Right, I agree that a versioned doc system would be ideal. For what we have now though, I'd prefer to add deprecation notices when applicable, over adding dates which might imply deprecation.

**Comment by gaearon** [comment]
cc @lacker

**Comment by lacker** [comment]
I think ideally you have some sort of selector that lets you pick different versions of the docs for different versions of the library. That probably wouldn't catch the "React warnings" pages which are a separate sort of system from all the other docs. Do you know what version of React introduced this specific warning for unknown props? - that would be a useful one line to add to this text, I just don't know what the correct answer is there.

**Comment by gaearon** [comment]
We removed outdated content from docs, deemphasized "legacy" practices, and added cautionary notes around them.

Versioning docs would be great but that is tangential to this issue.
