### ISSUE TITLE
Safari error! navigator.userAgent.indexOf is not a function

### ISSUE THREAD

**Issue by pengxueshan** [facebook/react#7775]
TypeError: navigator.userAgent.indexOf is not a function. (In 'navigator.userAgent.indexOf('Chrome')', 'navigator.userAgent.indexOf' is undefined)

**Comment by pengxueshan** [comment]
Safari: 9.1.3 (11601.7.8)
React: 0.13.3

**Comment by Aweary** [comment]
@pengxueshan we'll need some more information. Can you log out the value `navigator.userAgent`? It should always be a string. It's likely an issue with some other code overwriting the value or possibly an extension you're using.

**Comment by pengxueshan** [comment]
@Aweary   sorry, it's some other code overwriting the value of navigator.userAgent!!
Thanks for your reply.

**Comment by Aweary** [comment]
@pengxueshan good to know, thanks for the response!
