### ISSUE TITLE
in render(), is it possible to explicitly pass dom element to component method?

### ISSUE THREAD

**Issue by bochen2014** [facebook/react#7776]
this question can be better illustrated in code
```
class myComponent extends Component{
 constructor(props){
   this.state={ selectedOption: 'option1' }
}
   getClassName(e){
           return e.target.textConent === this.state.selectedOption ? 'selected' :''      
   }

   onNodeSelected(e){
      this.setState({selectedOption: e.target.contextText})
}


return(
   <div>
       <button className={ getClassName(??????)   onClick={this.onNodeSelected.bin(this)} >option1</button>
       <button className={ getClassName(??????)}  onClick={...>option2</button>
       <button className={ getClassName(??????)}  onClick={...>option3</button>
       <button className={ getClassName(??????)}  onClick={...>option4</button>
  </div> 
  )
}
```

I know I can model my options and do a Map, within the map function, I check the value then assign a className accordingly. that seems to be  the proper/standard solution. 
The problem is that I need to consider layout of different options, i.e. each option is actually wrapped within different <div> and those parent divs are assoicated with different css classes, which makes it very hard to model.

again, I know what i'm doing is anti-react (it's very angular 1.x -ish actually), I'm just wondering if there is a better way to achieve this, if not, does react provide another escape hatch

**Comment by bochen2014** [comment]
well, I don't think there is an answer to my question. within render(), the dom isn't ready yet ( in the inital load).  looks like the entire design is wrong.. 

happy to close it

**Comment by bochen2014** [comment]
ok. figure out one..
```
class myComponent extends Component{
 constructor(props){
   this.state={ selectedOption: 'option1' }
}

   onNodeSelected(e){
      this.setState({selectedOption: e.target.contextText})
}


return(
   <div>
       <button className={ 'option1' === this.state.selectedOption? 'active' :''  }   onClick={this.onNodeSelected.bin(this)} >option1</button>
       <button className={ 'option1' === this.state.selectedOption? 'active' :''  }   onClick={...>option2</button>   
  </div> 
  )
}
```

**Comment by bochen2014** [comment]
happy for any one to close it, or put some comments

**Comment by enaqx** [comment]
@bochen2014 If I understand correctly you are trying conditionally manipulate classnames. Have you explored classnames module?

https://github.com/JedWatson/classnames#usage-with-reactjs

**Comment by jimfb** [comment]
This is a usage question. We use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.

**Comment by bochen2014** [comment]
Refs don't work on Stateless Components : https://github.com/facebook/react/issues/4936
Non-static methos are not hoisted by @connect: 
https://github.com/reactjs/react-redux/pull/270

**Comment by bochen2014** [comment]
flow  module.name_maper: https://github.com/facebook/flow/issues/-2092

**Comment by bochen2014** [comment]
style-guidist
updatewebpack: https://github.com/styleguidist/react-styleguidist/issues/-110#issue-144363116

**Comment by bochen2014** [comment]
ref with stateless componenents. use function scope variables as the storage of `refs`

```js
import React, { Component } from 'react';
import {
    StyleSheet,
    View,
    Text,
    TouchableOpacity
} from 'react-native';
import { color, fontSize } from '../../common';

const optionLabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'];
const QuizAnswerOptionComponent = (props) => {
    let _text = null;
    const handlePressed = e => {
        _text.setNativeProps({
            style: {
                color: isCorrectAnswer ? color.green : color.red
            }
        });

    }

    const { index, text, hint, isCorrectAnswer } = props;
    return <TouchableOpacity onPress={handlePressed}>
        <Text ref={ref => _text = ref} style={styles.optionText}>{optionLabels[index] + '): ' + text}</Text>
    </TouchableOpacity>
}

const styles = StyleSheet.create({
    optionText: {
        fontSize: fontSize.default
    }
})
export default QuizAnswerOptionComponent;
```
