### ISSUE TITLE
deleting decimal values in number inputs

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#7781]
So I already chimed in about the problems here:

https://github.com/facebook/react/issues/6556

But there's another issue where you type out your number, such as `123.45` and then start deleting and once you delete that 4, the cursor jobs all the way over to the left

https://jsfiddle.net/wmhrdcad/

I think the problem has to do with the fact that `\d+\.` is not considered a valid number. I'm not sure if this came from react or the browser:

> The specified value "0." is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

**Comment by Aweary** [comment]
Thanks for the report @ccorcos, we're aware of this and tracking it in https://github.com/facebook/react/issues/7253#issuecomment-236074326

**Comment by nhunzaker** [comment]
Hey @ccorcos! 

I've been working on fixes for this issue (#7750, #7359). I listed quite a few cases here (and would be happy to add new cases to that list): https://github.com/facebook/react/issues/7253#issuecomment-236074326

Quite an annoying issue. I've got things sorted out for uncontrolled inputs, but there are still some outstanding issues to figure out for controlled inputs (https://github.com/facebook/react/pull/7359#issuecomment-246862734). The gist of it is that the value attribute is assigned on every value change, which isn't compatible with Chrome's number input. 

Would you be willing to take a look there and help me brain storm?

**Comment by nhunzaker** [comment]
@Aweary ack, sorry! Good timing :)

**Comment by ccorcos** [comment]
@nhunzaker awesome! just commented in the other PR.
