### ISSUE TITLE
jsfiddle from official website not working

### ISSUE THREAD

**Issue by DanielRuf** [facebook/react#7782]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
http://jsfiddle.net/fv6RD/3/ does not work, the code is not executed, there are two files loaded from the Facebook servers but they both return a 5xx error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Go to https://facebook.github.io/react/docs/why-react.html and then click the link at the bottom to go to https://facebook.github.io/react/blog/2013/06/05/why-react.html and then click on the link to jsfiddle in the text `Check out this jsFiddle to see an example of reconciliation in action.`

**What is the expected behavior?**
that there is some generated output in the result pane

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome (latest stable, Mac OS), Safari (Mac OS)

**Comment by gaearon** [comment]
That’s a pretty old blogpost. I’m not sure why the integration broke, but I recommend to look at more modern examples (e.g. https://facebook.github.io/react/docs/thinking-in-react.html is up to date).

**Comment by DanielRuf** [comment]
@gaearon Well, this blogpost is still linked at the bottom here: https://facebook.github.io/react/docs/why-react.html

So this is how I came there. By reading the guide and I thought I would get an uptodate guide with uptodate links ;-)

**Comment by gaearon** [comment]
Fixed now.
The new link is http://jsfiddle.net/2h6th4ju/.
It will appear in the blog post the next time we sync our docs.
Thanks!

**Comment by DanielRuf** [comment]
Great. Thanks too.
