### ISSUE TITLE
support slot attribute (ShadowDOM v1) on DOM elements

### ISSUE THREAD

**Issue by Hotell** [facebook/react#7784]
**Do you want to request a _feature_ or report a _bug_?**
feature ( I guess? )

**What is the current behavior?**
React doesn't support `slot` attribute which comes with shadowDom v1, so it will throw error and because of that, web component isn't working

code:

``` js
class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <div>
          <fancy-tabs background hello="World!">
            <button slot="title">Tab 1</button>
            <button slot="title" selected>Tab 2</button>
            <button slot="title">Tab 3</button>
            <section>content panel 1</section>
            <section>content panel 2</section>
            <section>content panel 3</section>
          </fancy-tabs>
        </div>
      </div>
    );
  }
}
```

rendered html with error

<img width="919" alt="screen shot 2016-09-21 at 2 05 47 pm" src="https://cloud.githubusercontent.com/assets/1223799/18717136/4d2fe7d2-801f-11e6-8205-795576144626.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

Support new DOM attribute standard

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.2 / Chrome 53 / OSX El Capitan

**Comment by kevinSuttle** [comment]
@Hotell Are you referring to the `<slot>` _element_? 

http://hayato.io/2016/shadowdomv1/#insertion-points-v0-vs-slots-v1

**Comment by Hotell** [comment]
Nope, as you can see in attached source, slot attribute is used to tell the shadow DOM in which slot it should be projected

**Comment by jimfb** [comment]
Yeah, the slot attribute can exist on virtually any element.

Related to #140
