### ISSUE TITLE
API suggestion: Extend React.Component.prototype

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react#7785]
As a component library _author_, there are constantly use cases where I want **every single component** to have one or more of the same properties. 

Polymer handles this by exposing the [`Polymer.Base`](https://www.polymer-project.org/1.0/docs/api/Polymer.Base)(Will most likely become `Polymer.Element` in [2.0](https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0.html)) static method. 

Examples: 
- Themes/Styles*
- Props
- Behaviors

I know the "recommended best practice" is to use HOC, but wrapping, or even decorating, every single component gets tedious and is to implicit to library consumers (*[much like context](https://facebook.github.io/react/docs/context.html)), and `cloneElement`.

Merging props is messy and not always reliable depending on the use case.  
I know I'm not the only one who would benefit from something like this (just search the React Discuss forums).

**Comment by gaearon** [comment]
Can you show a code example of what you mean by “having same properties”?

**Comment by kevinSuttle** [comment]
Simple: presentational components like buttons
```jsx
<Button theme="dark" />
```

Not as simple: Forms, components reliant on API endpoints 
```jsx
<Input validationEndpoint="" validationTrigger="blur" onValidate="displayValidationresult(ValidationObj.result)" >

```

etc.

**Comment by gaearon** [comment]
How would a base component class help here? Can you show the code you have in mind that would solve your problem?

**Comment by kevinSuttle** [comment]
Well, to be fair, this is doable now, but advised against because it's OOP. 

```jsx
class LibraryBaseComponent extends React.Component {
  static propTypes = {
    theme: React.PropTypes.oneOf(["light", "dark", "blue", "red"]),
    validationTrigger: React.PropTypes.oneOf(["change", "blur", "debouncedChange", "render" ]),
  }
...

class LibraryInput extends LibraryBaseComponent {} // etc.
```

**Comment by Aweary** [comment]
How would the API you're proposing differ from standard inheritance?

**Comment by kevinSuttle** [comment]
It's not futureproof if React is moving away from JS Classes.

**Comment by gaearon** [comment]
@kevinSuttle 

This doesn’t look like a complete example. Can you provide a full example?

If all you want is to share `propTypes`, you can do this already:

```js
// SharedPropTypes.js
export default {
    theme: React.PropTypes.oneOf(["light", "dark", "blue", "red"]),
    validationTrigger: React.PropTypes.oneOf(["change", "blur", "debouncedChange", "render" ])
}

// LibraryInput.js
import SharedPropTypes from './SharedPropTypes'
function LibraryInput(props) {
  // ...
}
LibraryInput.propTypes = {
  ...SharedPropTypes,
  myOwnPropType: React.PropTypes.string
}

// LibraryButton.js
import SharedPropTypes from './SharedPropTypes'
function LibraryButton(props) {
  // ...
}
LibraryButton.propTypes = {
  ...SharedPropTypes,
  someOtherPropType: React.PropTypes.string
}
```

Do you have some other use case that I missed?

**Comment by gaearon** [comment]
I guess it’s

>Merging props is messy and not always reliable depending on the use case.

that I don’t understand.

Are we talking about `props` or `propTypes` declarations? Can you show an example of what is messy?

**Comment by Aweary** [comment]
> It's not futureproof if React is moving away from JS Classes.

So you want an API to extend a component that might not be an ES6 class?

**Comment by kevinSuttle** [comment]
@gaearon Here's a more full example of the current state of things, albeit in Flow syntax, where to extend you end up having to merge proptypes over and over. 

https://gist.github.com/kevinSuttle/fb3d4b33c83e091e7f980dda9ff8df8e#file-labelediconbutton-jsx-L14

@Aweary See: https://twitter.com/dan_abramov/status/692026291982311424 in the context of this thread: https://twitter.com/dan_abramov/status/692027241887350785

**Comment by gaearon** [comment]
@kevinSuttle 

To be honest I don’t see harm in typing each component’s types explicitly. Spreading over propTypes encourages lazy design in my opinion, where unnecessary props, or props with unnatural names, are exposed just because it’s less lines of code than to specify specific props for each component.

**Comment by kevinSuttle** [comment]
It's really API sugar, and the point was to figure out what it was together, balancing the needs/desires of component developers and the React team.

**Comment by gaearon** [comment]
Sorry, I just don’t understand what exactly you are suggesting. The first comment is a bit vague and broad, and I answered to your specific example with an example of using spread for this. It’s not clear to me what is the issue you have in the gist, and how you propose to fix it in React. Maybe you could post some other examples?

**Comment by kevinSuttle** [comment]
I don't know how else to describe it.

**Comment by gaearon** [comment]
A complete example using the API you propose would help. 😉

**Comment by kevinSuttle** [comment]
http://stackoverflow.com/search?q=%5Breactjs%5D+props

**Comment by kevinSuttle** [comment]
Like I mentioned here: https://discuss.reactjs.org/t/official-recommendation-for-ui-theming-in-react/4865, there is a lot of info from FB about what _not_ to use.

**Comment by gaearon** [comment]
I'm afraid this discussion won't be productive unless you can show:

1) The code you are currently having problems with
2) The proposal you have in mind about how we could approach this on React side

This may be obvious to you because you've spent a lot of time thinking about this issue. It is much less obvious to me, and this is why I ask to help me understand by posting some (simplified) code to make your point. Unfortunately the links you posted aren't helping me understand what specifically you are asking for, but code will.
