### ISSUE TITLE
Flickering of UI while scrolling in React App

### ISSUE THREAD

**Issue by paramsingh88** [facebook/react#7787]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
I have built a react web app using React + Redux that is being rendered in a webview. I have a long paginated list to be rendered. It shows a flickering kind of behaviour in loading the UI when I scroll up or down on that page. When I scroll too fast, it takes a second or two to render the UI properly. Also, this problem is found in the Android webview only but not on browser.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Here's the link of the screencast I recorded [https://drive.google.com/open?id=0B9fJ9q7WyHl4NWljQ0NKclBCM3c](https://drive.google.com/open?id=0B9fJ9q7WyHl4NWljQ0NKclBCM3c)

**What is the expected behavior?**
There's shouldn't be any flickering while scrolling be it webview or browser.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "^15.1.0"
"redux": "^3.5.2"

Android Webview

**Comment by paramsingh88** [comment]
well because React is handling all the DOM dynamics on my app, that's why

**Comment by jimbolla** [comment]
[This does not seem to be a React-related issue](https://www.google.com/search?q=android+webview+scroll+flicker). Unless your app is changing the DOM in response to scroll events, you're just seeing WebView being WebView.

**Comment by gaearon** [comment]
I'm closing because React does nothing unusual to the DOM. If you can demonstrate this happens with React but doesn't happen without it, I'll be happy to reopen.
