### ISSUE TITLE
SVG switch tag

### ISSUE THREAD

**Issue by fibo** [facebook/react#7792]
This is a feature request

Are there plans and dows it make sense to add the SVG `switch` tag? See https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject for an example usage.

My use case is the following: I have [this script](https://github.com/fibo/flow-view/blob/master/examples/render/serverside.js) that thanks to ReactDOM renders svg server side, but in image context foreignobject is not rendered, so a swithc tag could be useful.

**Comment by jimfb** [comment]
@gaearon SVG whitelist.

**Comment by gaearon** [comment]
I don’t see why it wouldn’t work in React 16. Closing. If it doesn’t, please provide a reproducing case.
