### ISSUE TITLE
Documentation inconsistencies around Parent/Child vs Owner/Ownee 

### ISSUE THREAD

**Issue by mrscobbler** [facebook/react#7794]
**Do you want to request a *feature* or report a *bug*?**
Bug

Looking at the documentation here: https://facebook.github.io/react/docs/multiple-components.html#ownership it describes the difference between a parent/child relationship compared to an owner/ownee relationship. 

In the tutorial here: https://facebook.github.io/react/docs/tutorial.html#using-props It talks about the parent/child relationship when it should be an owner/ownee relationship.

Is the owner/ownee terminology commonly used? I feel like most of the time when I read tutorials I only read about parent/child relationships, even if the parent is passing props down to the child (which would be an owner/ownee relationship). 

I'm happy to make whatever changes need to be made in the documentation.

Tagging @lacker and @gaearon

**Comment by gaearon** [comment]
I think the biggest issue here is that owner/ownee almost never matters, but is awkward to mention in the introductory text. Maybe we can figure out how to remove these words from that text altogether while preserving the meaning. @mrscobbler Would you like to give that a try?

**Comment by mrscobbler** [comment]
Yes! I will work on the wording and submit a pull request.

**Comment by mrscobbler** [comment]
I've submitted a pull request for changes, let me know what you think.

**Comment by gaearon** [comment]
Thank you for the PR! I just merged it, and it will appear soon on the website.

We are working on new docs in another PR and we decided the scrap that tutorial completely.

Nevertheless this will be helpful in the meantime.

**Comment by mrscobbler** [comment]
Oh great! Can I help out with the new tutorial in any way? I'd love to contribute more to the documentation. Sometimes it's hard to keep documentation in sync with code changes.

**Comment by gaearon** [comment]
We are in a lockdown to rewrite it in #7864 and it’s in a messy state so it’s a bit hard to take outside contributions until it shakes out. However right after that is merged I’m sure there’ll be plenty of work possible around fixing/amending things we screwed up. 😄 I think until it is merged, it would be helpful if you could keep an eye on new PRs against `new-docs` branch and could comment on those. For example: #7869, #7881, #7878, #7875. They are still a work in progress but if you have any thoughts we'd love to hear them!

**Comment by mrscobbler** [comment]
Will do! I'd love to help out however I can.
