### ISSUE TITLE
enter, leave timeout on CSSTranstionGroup

### ISSUE THREAD

**Issue by f0rr0** [facebook/react#7805]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Everything works, only there is a warning in the console. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Using cssTransitionGroup for appear animation, not for enter or leave.

**What is the expected behavior?**
No need to provide those timeouts, just appear should suffice

**Comment by gaearon** [comment]
I will close this since you didn't provide a JSFiddle while the issue template explicitly asked you to. Thank you for your time!
