### ISSUE TITLE
How to pass inline CSS variables?

### ISSUE THREAD

**Issue by caub** [facebook/react#7808]
I tried `style={{'--border-color': 'red'}}` or `style={{'--borderColor': 'red'}}` and get warnings

I don't think React support them yet

**Comment by Aweary** [comment]
@caub thanks for the issue!
>I don't think React support them yet
Correct, this isn't supported at the moment. We have an issue open about it at https://github.com/facebook/react/issues/6411 if you want to track any updates/conversion on the topic 👍
