### ISSUE TITLE
Shape validation does not recognize deconstructed props attributes

### ISSUE THREAD

**Issue by nwikstrand** [facebook/react#7815]
Bug (?)

Shape validation does not recognize deconstructed props attribute.
`'bar.baz' PropType is defined but prop is never used react/no-unused-prop-types`

Failing example with deconstructed props:
```
const Foo = ({bar}) => (
  <div>
    {bar.baz}
  </div>
);

Foo.propTypes = {
  bar: React.PropTypes.shape({
    baz: React.PropTypes.string,
  }),
};
```

Working example with non deconstructed props:
```
const Foo = (props) => (
  <div>
    {props.bar.baz}
  </div>
);

Foo.propTypes = {
  bar: React.PropTypes.shape({
    baz: React.PropTypes.string,
  }),
};
```

**Comment by syranide** [comment]
That's an issue with the hinting-software you're using, specifically a react plugin for it. Not React.

**Comment by Aweary** [comment]
Looks like you're using eslint-plugin-react. You're best bet is to direct your question there https://github.com/yannickcr/eslint-plugin-react

**Comment by nwikstrand** [comment]
My bad, thanks for pointing that out :)
