### ISSUE TITLE
React fails to update TextNode in IE8

### ISSUE THREAD

**Issue by mnpenner** [facebook/react#7824]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

React fails to update text nodes in IE8

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

This is as close as I could get to a reproduction: https://fiddle.jshell.net/zrozubsb/1/show/

I think JSFiddle itself doesn't work in IE8 though, so it's masking the real problem, which you can see here:

![image](https://cloud.githubusercontent.com/assets/1112998/18934304/cdfe5038-858d-11e6-80cd-2e234c1d007d.png)

**What is the expected behavior?**

DOM updates/doesn't throw error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.1. Internet Explorer 8. Not sure if it ever worked; I have a feeling it didn't.

-----

I will be submitting a PR for this shortly as I know you aren't actively supporting IE8 any more, but it's actually a pretty simple fix. I hope I outlined the issue well enough.

**Comment by syranide** [comment]
https://github.com/facebook/react/pull/7826#issuecomment-250393700

**Comment by mnpenner** [comment]
Sorry, I made a mess of everything. I think I have a clean commit now: https://github.com/nucleuslabs/react/commit/3e91942fb355b6f855e32a5e04b304625a130f02

I guess I have to submit a new PR.

**Comment by syranide** [comment]
@mnpenner FYI, you can always reset a branch and start from scratch without closing the PR. Also yes, that commit looks fine to me 👍

**Comment by mnpenner** [comment]
It closed the PR automatically when I did a hard reset. I guess because my commit got wiped in the reset? But we didn't want that commit in the history, right?

**Comment by syranide** [comment]
@mnpenner Oh ok, that must be new GitHub-behavior or something...

**Comment by mnpenner** [comment]
I thought the new PR would automatically link here because I put the issue # in the commit, but I guess not.

[New PR is here](https://github.com/facebook/react/pull/7832)

**Comment by brandonaaskov** [comment]
React discontinued React DOM support for IE8 with v15. In your Fiddle you're using React DOM 15.3.2. Have you tried using an older version, like https://npmcdn.com/react-dom@0.14.8/dist/react-dom.js?

**Comment by mnpenner** [comment]
@brandonaaskov No, I have not tried reproducing this particular issue in React 0.14. Everything else seems to work in v15 though, so I'd rather stick with 15.x for as long as I can. It's only a 3-line fix to make it work.

**Comment by syranide** [comment]
@brandonaaskov @mnpenner IE8 is unofficially supported but not actively maintained for now, unless it breaks to the point where it's no longer worth the added code complexity.
