### ISSUE TITLE
Mobile friendly docs

### ISSUE THREAD

**Issue by thymikee** [facebook/react#7833]
I'd like to contribute to make React docs mobile friendly, because I cry every time I need to look up something on a phone 😢.

There had been and attempt to do that some time ago here: #5404 with this PR: #5512, but apparently it was abandoned by an author.

I'd like to wait with sending my PR until you accept the navigation design (the reset is pretty straight-forward I guess).

So, this is pretty much how I would see this (removed downloads tab, because we're on phone, but there's a place for that just in case):

![docs](https://cloud.githubusercontent.com/assets/5106466/18968064/d58a07a2-8687-11e6-8086-f3c1ee812b80.jpg)

And a little gif:

![docs](https://cloud.githubusercontent.com/assets/5106466/18968004/94ec5984-8687-11e6-8620-44f10ac0d9c1.gif)

It's almost identical as on React Native docs, so we would have kind of consistency here. 
But I'd rather like to avoid sticky header, as it takes too much space.

cc @lacker as @gaearon advised me to contact you on this one.

**Comment by lacker** [comment]
I think your vision here is pretty cool! I definitely agree our docs could be nicer on mobile. We were also thinking of altering some details of the overall layout, which might be a little conflicty here, but we have a meeting on Monday to see who's gonna work on that stuff out, so I'll report back to this issue after that.

**Comment by thymikee** [comment]
👍

**Comment by pmaojo** [comment]
I think it's so important. I came just for the same.

**Comment by lacker** [comment]
OK, so the React team is now working on overhauling the docs & the plan is to finish this doc-a-than by October 14. We're doing it in the new-docs branch. If there's a way to get what you want via some not-super-disruptive changes like CSS, feel free to send a pull request to that branch. If you'd rather someone from the React team take a look, @vjeux claims its not gonna be too hard to do it so I think we'll get to it in the next couple weeks.

**Comment by thymikee** [comment]
The changes are mostly in CSS and are definitely not super-disruptive :D. I'll send a PR later tomorrow.

**Comment by thymikee** [comment]
@lacker PR is there, you can have a look.

**Comment by gaearon** [comment]
Done now, thanks so much!
