### ISSUE TITLE
A group of radio button requires all to have defaultChecked attribute to work properly in Firefox

### ISSUE THREAD

**Issue by mjntan35** [facebook/react#7838]
https://jsfiddle.net/kwrdf44r/

**Comment by Udokah** [comment]
This is true, I just spent the last 3hours trying to fix a bug related to this.

**Comment by gaearon** [comment]
cc @aweary

**Comment by aweary** [comment]
I'll take a look at this when I'm back in town

**Comment by gaearon** [comment]
Still an issue in 16?

**Comment by aweary** [comment]
@gaearon nope https://jsfiddle.net/10Lmuhxs/
