### ISSUE TITLE
Error with preload attribute on video with IE11 and Windows 7

### ISSUE THREAD

**Issue by nmaves** [facebook/react#7839]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
We get an error when using the `preload="auto"` on a video element in react.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Here is a screenshot of the error https://www.evernote.com/l/AAHeugBoLWlP8aMcU3Ogyr-ktWRHdz0RPuw

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.3.1
IE 11
Windows 7

**Comment by syranide** [comment]
Try setting `video.setAttribute('preload', 'auto');` directly via JS on the video-node and see what happens, because it looks like the node is throwing the error. React itself really shouldn't be throwing any errors there.

**Comment by gaearon** [comment]
It seems like `video` tag support in IE11 is generally flaky. Not sure we can do anything about it. I would just suggest detecting IE and showing some fallback content.

**Comment by nmaves** [comment]
If only we could get the whole world to drop IE 11 for good :(

**Comment by gaearon** [comment]
Well, hopefully it won't take long for it to die. :-)
