### ISSUE TITLE
Log a warning if a user is setting DOM properties on a web component 

### ISSUE THREAD

**Issue by briandeheus** [facebook/react#7845]
**What is the current behavior?**
Using web components with React is cumbersome, as properties such as `className` are being copied as attributes without transforming them to `class`. [A lot](https://github.com/facebook/react/issues/4933#issuecomment-145951830) has been said about this, but it can be very confusing for developers who are trying to use web components using React.

**What is the expected behavior?**
Much like how using `class` as a property logs a warning, I suggest that if a property key exists in `DOMProperty.properties` we raise a similar when warning when `__DEV__` is `true`, so the user knows that what is happening is expected behavior, not a bug.

If my proposal is acceptable, I have a PR that is ready to be sent out. 

Thoughts?

**Comment by brigand** [comment]
The reason for class vs className is that both are valid properties on web components. Warnings are intended to be fixed, but in this case it might be impossible to fix since it's already correct. I think this should be solved with custom components that validate their props.

**Comment by briandeheus** [comment]
We can either scale down to say `debug` level (although I'm not sure if there is a debug level) or to update the documentation. I'm personally a big fan of web components and although I'm evidently biased, I think that more and more developers will run into this issue.

**Comment by gaearon** [comment]
This is now mentioned in the documentation. I agree it's not ideal but adding a warning would defeat the purpose of allowing `className`.
