### ISSUE TITLE
React lets access from the DOM to internal instances

### ISSUE THREAD

**Issue by bloodyowl** [facebook/react#7846]
**current behavior?**

In [ReactDOMComponentTree.js ](https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactDOMComponentTree.js), `internalInstanceKey` gives easy access to React internal instances, even if the property name is randomly generated.

For instance the following piece of code lets access to the redux state, placed in context. 

```javascript
let reactRoot = document.querySelector("[data-reactroot]")
reactRoot[Object.getOwnPropertyNames(reactRoot)[0]]._currentElement._owner._context.store.getState()
```

This might lead to some security issues with potentially malicious third-party scripts or self-XSS.

Is something like the following piece of code considerable in order not to expose these things?

```javascript
const instanceMap = {}

const setInstance = (node, instance) => {
  const id = nuid()
  node[internalInstanceKey] = id
  instanceMap[id] = instance
}

const removeInstance = (node) => {
  delete instanceMap[node[internalInstanceKey]]
}

const getInstance = (node) => {
  return instanceMap[node[internalInstanceKey]]
}
```

**Comment by gaearon** [comment]
>This might lead to some security issues with potentially malicious third-party scripts or self-XSS.

You should not treat any data you keep on the client in JavaScript memory as secure. A third-party script can do any kinds of things, including overriding React global (if you use one), pretending to be React DevTools, or overriding any native object behavior.

React offers no guarantees that its internal structures are not exposed to some third party code. In fact it is impossible (or, perhaps, extremely hard) to offer such a guarantee for React. For example, any `Object.prototype` or `Array.prototype` methods could have been altered, so in order for React to not “leak” internal data to them, it would have to use no JavaScript runtime functions at all.

So if you need to protect some data, don’t load it in JavaScript.

**Comment by bloodyowl** [comment]
Using `Object.create(null)` would do most of the work in fixing the `Object.prototype` issue.

If, or course, no security is guaranteed at all, it would be preferable not to expose the data directly but instead keep it in a closure IMO.

**Comment by gaearon** [comment]
Since we don’t offer that guarantee at all (e.g. DevTools *needs* a hook with that information anyway), I don’t see the point in adding half-measures to patch a few places. It’s better in my opinion to not guarantee something than to accept a patch that fixes one of hundreds places where we might rely on something like this. Especially considering that we don’t have any test suite guarding against future changes that might expose more such information.
