### ISSUE TITLE
Windows development issues

### ISSUE THREAD

**Issue by alisd23** [facebook/react#7849]
Having issues developing on windows (7) on a fresh install (master).

Running `npm test` causes all 118 test suites to fail with the error:

![image](https://cloud.githubusercontent.com/assets/5804010/19039654/bf3e3736-8978-11e6-9483-babae236e498.png)

Changing `testRegex` in the `package.json from`/**tests**/`to just`**tests**` seems to fix those issues, because the last character is an escape character, it's invalid regex.

There is another regex error though:

![image](https://cloud.githubusercontent.com/assets/5804010/19039859/873953e2-8979-11e6-84ff-fb93eb7a395c.png)

Not sure where that regex comes from though...

There is also a 3rd error

![image](https://cloud.githubusercontent.com/assets/5804010/19040014/1f051e04-897a-11e6-92a5-bd25752ddf3d.png)

which just looks like a unix -> git bash crossover issue. Possibly another escape character issue.

Does anyone run on windows and had similar issues?

**Comment by gaearon** [comment]
We're tracking Windows fixes for the build system in https://github.com/facebook/react/issues/9540, let's just make sure we fix tests there too.
