### ISSUE TITLE
ReactTestRenderer 15.4.0-rc.1 missing files

### ISSUE THREAD

**Issue by jasanst** [facebook/react#7880]
Installing ReactTestRenderer@15.4.0-rc.1 from npm just brings down an index.js file, the referenced lib folder does not exist.

**Comment by zpao** [comment]
Thanks for catching that - we need to add `lib/` to package.json `files` field.

**Comment by Aweary** [comment]
Closed by https://github.com/facebook/react/pull/7888 :tada:
