### ISSUE TITLE
Docs request: build a React component library

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react#7882]
This is an important section that I think a lot of folks end up piecemealing on their own. It would be super useful in terms of ecosystem support.

**Comment by gaearon** [comment]
Added this to https://github.com/facebook/react/issues/8060 for visibility. Let's track it there. Would you like to write this?

**Comment by kevinSuttle** [comment]
I can take a stab. Sure.

**Comment by laumair** [comment]
@kevinSuttle Any updates on this at your end? I can take this on.

**Comment by kevinSuttle** [comment]
Go ahead @laumair. Just got busy. Thanks.

**Comment by laumair** [comment]
@kevinSuttle All right thanks. Gonna start on this then. Any useful resources/suggestions that you have in mind regarding this? I'd appreciate if you'd share them. Would be a good starting point for me as well.
