### ISSUE TITLE
Thinking in React Tutorial Update

### ISSUE THREAD

**Issue by hnordt** [facebook/react#7885]
[Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html) is one of the most important and well written tutorials for beginners and even for advanced developers.

I would like to update it to ES6 and increase the readability.

Also I would like to replace JSFiddle with the React docs highlighter.

First suggestions:

```jsx
// Replace

var ProductCategoryRow = React.createClass({
  render: function() {
    return (<tr><th colSpan="2">{this.props.category}</th></tr>);
  }
});

// With

function ProductCategoryRow({ category }) {
  return (
    <tr>
      <th colSpan="2">{category}</th>
    </tr>
  );
}
```

```jsx
// Replace

var ProductRow = React.createClass({
  render: function() {
    var name = this.props.product.stocked ?
      this.props.product.name :
      <span style={{color: 'red'}}>
        {this.props.product.name}
      </span>;
    return (
      <tr>
        <td>{name}</td>
        <td>{this.props.product.price}</td>
      </tr>
    );
  }
});

// With

function ProductName({ product }) {
  return (
    <span style={{ color: product.stocked ? 'green' : 'red' }}>
      {product.name}
    </span>
  );
}

function ProductRow({ product }) {
  return (
    <tr>
      <td>
        <ProductName product={product} />
      </td>
      <td>{product.price}</td>
    </tr>
  );
}
```

Should I continue or it doesn't worth the effort?

**Comment by lacker** [comment]
Hey, I totally agree this should get updated to ES6. We have a bunch of folks working on the React docs this week on the new-docs branch and the format is a little bit different, so I can take this on.

**Comment by lacker** [comment]
OK this is in the new-docs branch now.
