### ISSUE TITLE
shallowCompare in stateless components

### ISSUE THREAD

**Issue by adamgruber** [facebook/react#7900]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug / confusion point

**What is the current behavior?**
Implementing `shallowCompare` inside `shouldComponentUpdate` will always return true if you do not pass `nextState` param.

``` js
// In a component without state you would not want to pass nextState
shouldComponentUpdate(nextProps) {
  return shallowCompare(this, nextProps) // => always true if you don't pass nextState
}
```

**What is the expected behavior?**
I would expect the `shallowCompare` method to handle cases where `nextState` is not passed in OR for the documentation to be more clear, stating that you MUST pass `nextState`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using React 15.2.0. This is not specific to any browser or OS.

**Comment by karczk** [comment]
The function expects three parameters, so you should pass all (for me it is documentation). With typescript this code would not compile.

Source of the "problem" comes from element creation `this.state = null` (react code) and missing argument for `shouldComponentUpdate` is `undefined`. Inside shallowCompare, there is shallowEqual, which use strict compare `===`. I use base ES6 class `ComponentWithShallowCompare` which extends `React.Component` (or for old way: `React.createClassWithShallowCompare`), so I don't need to write it anymore.

Warning in dev react version would be better than optional parameter. Later, if you add the state to component, it is very likely that you forget to pass an additional parameter to `shouldComponentUpdate`.

**Comment by adamgruber** [comment]
@karczk I agree. I think having a warning printed to the console and/or updating the documentation would be sufficient.

**Comment by gaearon** [comment]
We don't maintain that addon anymore.
