### ISSUE TITLE
*bug* <select value="NO"> sometimes selects last value in dropdown

### ISSUE THREAD

**Issue by jansoren** [facebook/react#7908]
When using <select value="NO"> with same value multiple times the selection differs. Here is a fiddle example of the issue - [https://jsfiddle.net/w77wsgno/](https://jsfiddle.net/w77wsgno/)

In chrome it selects the first option with the value "NO". Testing on iPhone it selects the last option with the value "NO". 

Is there a solution to this being consistent and always selecting the first option with the "NO" value?

**Comment by syranide** [comment]
You should not have multiple items with the same name. There's meant to be a warning for it, but it's not trivial to do it efficiently and correctly so it's not currently warned for.

**Comment by jansoren** [comment]
@syranide - ok, do you have any suggestions on how to solve the country example in the fiddle, where we want a favorite list at the beginning -> https://jsfiddle.net/w77wsgno/ ?

**Comment by syranide** [comment]
@jansoren If you want help with your code you'll need to use stackoverflow or the discussion board, we keep GH issues for bugs. But you'll simply need to give them a separate name (prefix or w/e) and use that to differentiate between them.

**Comment by Aweary** [comment]
>  But you'll simply need to give them a separate name (prefix or w/e) and use that to differentiate between them.

👍
