### ISSUE TITLE
dangerouslySetInnerHTML={someOfMyText} causes Chrome console(developer tool) to freeze.  No problem on firefox though

### ISSUE THREAD

**Issue by wickedrahul** [facebook/react#7924]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Aweary** [comment]
@wickedrahul can you please fill out the issue report template and provide steps to reproduce and/or a demo reproducing the issue?

Unfortunately we can't help you without more information.

**Comment by Aweary** [comment]
Closing out since there's no information and no response.
