### ISSUE TITLE
Page navigates to "/" path when component changes

### ISSUE THREAD

**Issue by Karthik248** [facebook/react#7928]
I am new to React and I have some which looks like this
[App.js](https://github.com/facebook/react/files/519494/App.txt)
[LoginForm.js](https://github.com/facebook/react/files/520988/LoginForm.txt)

`<App>`
`    { !this.state.login_status && <LoginForm callback={this.setLoginDetails.bind(this)}></LoginForm>}`
`    { this.state.login_status &&  <Header data={headerData}></Header>}</div>`
`</App>`

Expected Behavior: After the state of App is changed by the callback, the Header component should be rendered and should stay like that.

Current behavior: After the state is changed, Header is rendered, then the page is directed to localhost:8080/? automatically.
![capture](https://cloud.githubusercontent.com/assets/16217004/19242190/cb105e2e-8f2f-11e6-8ece-c350b487fc9f.PNG)

I dont know what to do now.
Any help is appreciated.

**Comment by williamboman** [comment]
Do you submit a tradition HTMLFormElement? In that case you need to [`preventDefault`](https://developer.mozilla.org/en/docs/Web/API/Event/preventDefault) the event passed to your submit handler.

**Comment by Karthik248** [comment]
Currently I am doing validation using local json file on client side with the event onClick. 
I have added links to the components I've used.

**Comment by Karthik248** [comment]
I can't believe how basic that was. I just needed to use the preventDefault.
