### ISSUE TITLE
Use ReactDOM.render target as an implicit JSX root

### ISSUE THREAD

**Issue by yaycmyk** [facebook/react#7932]
So currently when rendering, you must provide some top-most wrapper in addition to the node that has been designated as the reactroot. This introduces an unwanted extra layout element and can make styling a little irritating. 

It would be nice if the target for `ReactDOM.render(jsx, node)` _is_ the topmost node and you could pass an array as the first children right away.

**Comment by gaearon** [comment]
This already works in Fiber (#6170). We will not backport it to the existing reconciler.
Fiber is [not ready yet](http://isfiberreadyyet.com/) but we hope to ship it next year.
