### ISSUE TITLE
Making the view difference in the reuse markup error configurable.

### ISSUE THREAD

**Issue by PepijnSenders** [facebook/react#7939]
**Do you want to request a _feature_ or report a _bug_?**

I'm requesting a feature.

**What is the current behavior?**

Currently the way the reuse markup error is displayed the difference is hardcoded to 20 characters of code on each side. This should be a configurable property.

The code can be found here: https://github.com/facebook/react/blob/master/src/renderers/dom/client/ReactMount.js#L677

20 characters is sometimes a bit hard to debug, especially with css-in-js libraries where your div's usually also contain an obfuscated class name. Being able to make this a larger number could help with debugging where it went wrong.

**Comment by gaearon** [comment]
We don't show that particular warning anymore. For thoughts on future similar warning please post in https://github.com/facebook/react/issues/10085.
