### ISSUE TITLE
Props Validation for objects

### ISSUE THREAD

**Issue by aszwemin** [facebook/react#7945]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

After https://github.com/facebook/react/pull/5390/files you can't specify object with different type values, e.g. `PropTypes.objectOf({id: PropTypes.number, name: PropTypes.string})` so either you have to rely on the order of object now and specify it like `PropTypes.objectOf(PropTypes.number, PropTypes.string)` or unpack the object when passing it as props. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

It's not bug as such, but it makes fairly typical usage spitting warnings into the console.

**What is the expected behavior?**

Should be able to specify objectOf as before the attached PR.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.3.2

**Comment by gaearon** [comment]
Hey, thanks for filing an issue!

>After https://github.com/facebook/react/pull/5390/files you can't specify object with different type values, e.g. PropTypes.objectOf({id: PropTypes.number, name: PropTypes.string})

I don't think this was ever supported.
Aren't you looking for `shape`?

```js
PropTypes.shape({
  id: PropTypes.number,
  name: PropTypes.string
})
```

Does this help?
Cheers.

**Comment by aszwemin** [comment]
Hi, it may be that it didn't throw warnings before and we used it wrongly without realising. Will update the codebase to use shape. Thanks.
