### ISSUE TITLE
Allow HTML attributes to be dangerously set, without encoding

### ISSUE THREAD

**Issue by jcfrancisco** [facebook/react#7951]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
A React element like `<div data-foo={'&bar'} />` renders as `<div data-foo='&amp;bar'></div>`.

**What is the expected behavior?**
The above behavior is expected in the majority of cases; it is [strongly recommended on w3.org](http://www.w3.org/TR/xhtml1/guidelines.html#C_12).

However, in some scenarios (an automated parser that does not play nicely with encoded special characters, etc), a user may want to render arbitrary strings into attributes, without the automatic encoding.

In the same way that `dangerouslySetInnerHTML` is provided for entire elements, we could have a `dangerouslySetAttributes`: 

```
const getAttributes = () => ({ "data-foo": "&bar" });

<div dangerouslySetAttributes={{__attributes: getAttributes()}} />
```

Currently, a workaround I'm using is to `dangerouslySetInnerHTML` on the container element of the node. Being able to set the attribute specifically would be a bit safer.

Thoughts? I'm on the fence as to whether this is a good idea, since it opens up another avenue of inserting invalid HTML. Nevertheless, I'm interested in hearing if it can be justified on the same grounds as `dangerouslySetInnerHTML`.

**Comment by GoogleAssistant** [comment]
Hi, how can I help?

**Comment by syranide** [comment]
Unless I'm missing something this doesn't actually make a lot of sense, browsers perform the same encoding if you try to read `innerHTML` for obvious reasons. The encoding does not take place at run-time on the client either, it ONLY exists on the server to generate raw HTML to be rendered. So it doesn't really have any value other than "dealing with broken parsers".

And there's only so much you can do, quotes *have* to be encoded in attributes, so there's no way around that. So it seems that you should either you change/fix the parser or run a pre-process step that goes through the HTML and decodes some entities in attributes and then feeds it to your parser. There's no benefit to doing this in React.
