### ISSUE TITLE
Documentation: findDOMNode() in title, but not in paragraph

### ISSUE THREAD

**Issue by rickbeerendonk** [facebook/react#7958]
Documentation "bug".

"Working With the Browser" contains a subheading "Refs and findDOMNode()". The following paragraph however doesn’t contain any information about findDOMNode(). This was removed in commit 5ee8a93280987bf1547687f5d8665be89058f321

**Comment by lacker** [comment]
Thanks for pointing this out, you are totally correct! I actually have a PR out totally replacing this doc with an updated one: https://github.com/facebook/react/pull/7952 It fixes the reference to findDOMNode in there, so let's go with that PR. Any comment you have on there is welcome too btw.

**Comment by rickbeerendonk** [comment]
@lacker 👍
