### ISSUE TITLE
JSX variables shadowing gotcha

### ISSUE THREAD

**Issue by vjau** [facebook/react#7965]
I think i have discovered a jsx gotcha i see nowhere mentionned.
Let's say we have a component defined like this 

```jsx
const Comp = ({foo})=>{  
   const applyer = (foo)=>(
      <OtherComp stuff={foo}/>
   );
   const ResultComp = applyer(5);
   return (
      <div>
         {ResultComp}
      </div>
   );
};
```

Intended behaviour : in the rendered output, `<OtherComp/>` should be provided with stuff=5, but it receives instead the value of the foo prop provided to Comp, which means variable shadowing does not work.
I suspect this is relative to the template like behaviour of JSX, but since i have been bited by this gotcha, i think it should be mentionned in the docs.

The correct code to make this work is 
```jsx
const Comp = ({foo})=>{  
   const applyer = (fooNoConflict)=>(
      <OtherComp stuff={fooNoConflict}/>
   );
   const ResultComp = applyer(5);
   return (
      <div>
         {ResultComp}
      </div>
   );
};
```

**Comment by syranide** [comment]
This is a problem with the specific JSX-transform you're using, I'm testing with babeljs (which is the officially recommended one) and the final code looks just fine with correct shadowing.

What transform/tool are you using?

**Comment by vjau** [comment]
If this is not intended behaviour, i have got to investigate more, thanks.
