### ISSUE TITLE
Docs - Implementation notes - replaceChild args in worng order

### ISSUE THREAD

**Issue by igor-ribeiro** [facebook/react#7975]
The order of the arguments is wrong
```js
// how it is now
prevNode.parentNode.replaceChild(prevNode, nextNode);

// how it should be
prevNode.parentNode.replaceChild(nextNode, prevNode);
```

https://facebook.github.io/react/contributing/implementation-notes.html#updating-composite-components
https://developer.mozilla.org/en/docs/Web/API/Node/replaceChild

**Comment by gaearon** [comment]
Yeah I might've messed it up. Please send a PR?

**Comment by gaearon** [comment]
Fixed.
