### ISSUE TITLE
15.4.0-rc.4 mistakenly published as latest

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#7982]
**Bug**

**What is the current behavior?**

`npm view react` yields:
```
{ ...
  'dist-tags': {
    latest: '15.4.0-rc.4',
    '0.10.0-rc1': '0.10.0-rc1',
    '0.11.0-rc1': '0.11.0-rc1',
    next: '15.4.0-rc.3'
  },
  ...
}
```

As a result, `npm install react` installs 15.4.0-rc.4.

**What is the expected behavior?**

This looks like a publish mistake. `next` should point to 15.4.0-rc.4 and `latest` should point to 15.3.0.

**Comment by syranide** [comment]
cc @zpao

**Comment by gaearon** [comment]
Thanks for reporting!
Yes, it was a mistake during RC4 publish.
I just retagged 15.3.2 as latest, and it should be fine now.
