### ISSUE TITLE
Event listeners stop working if container moved to new document

### ISSUE THREAD

**Issue by robertknight** [facebook/react#7986]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug

**What is the current behavior?**

In React >= v15.0.0, if a container is moved to a different document and then the component tree is re-rendered, event listeners stop working.

In React <= 0.14.8 it was possible to move a container from one document to another via `document.adoptNode` and have the state of rendered components preserved and event listeners continued to work.

**Steps to reproduce**

Using test.html from https://gist.github.com/robertknight/a676fb552e8a8b4605e22fb7e4d54364
1. Click the counter button a few times
2. Click the 'Move to iframe' button
3. Click the counter a few more times. Note that the counter no longer responds to clicks.

**What is the expected behavior?**

Clicking the counter continues to increment it after it is moved to the iframe. This works in React v0.14.8 but not React >= v15.0.0

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Issue bisects to https://github.com/facebook/react/commit/796f8c353c2a68104672c61ec2cee457bf2de490 , which changed the logic that adds event listeners to use the cached Document value in  `instance._nativeContainerInfo._ownerDocument` instead of `container.ownerDocument`.

This hack resolves the issue:

``` patch
diff --git a/src/renderers/dom/shared/ReactDOMContainerInfo.js b/src/renderers/dom/shared/ReactDOMContainerInfo.js
index cbee0b5..16933fd 100644
--- a/src/renderers/dom/shared/ReactDOMContainerInfo.js
+++ b/src/renderers/dom/shared/ReactDOMContainerInfo.js
@@ -17,7 +17,9 @@ var DOC_NODE_TYPE = 9;

 function ReactDOMContainerInfo(node) {
   var info = {
-    _ownerDocument: node.nodeType === DOC_NODE_TYPE ? node : node.ownerDocument,
+    get _ownerDocument() {
+      return node.nodeType === DOC_NODE_TYPE ? node : node.ownerDocument;
+    },
     _tag: node.nodeName.toLowerCase(),
     _namespaceURI: node.namespaceURI,
   };
```

**Notes**

The original use case was preserving the state of components in an app that runs in a Chrome popup window when the pop closes, which unloads the window. The workaround involves moving the DOM node to the background page when the popup is closed and back again when it is next opened.

**Comment by aleskafka** [comment]
I have very similar issue, but without need of re-rendering React components. Everything is created in separated DocumentFragment and moved into main document later. Events are registered inside DocumentFragment and never fire after they are moved.

I looked into code and React registers event pair of event and document that it comes across in mounting process. When it is moved outside of React, Event system has no idea that it should listen on same event but in main document.

Following single-line change would correct this problem. I imagine it needs completely different change than this hack. Is it possible it could work correctly in future?

```diff
diff --git a/src/renderers/dom/stack/client/ReactDOMComponent.js b/src/renderers
index fbfd8cc..195ce42 100644
--- a/src/renderers/dom/stack/client/ReactDOMComponent.js
+++ b/src/renderers/dom/stack/client/ReactDOMComponent.js
@@ -152,6 +152,7 @@ function ensureListeningTo(inst, registrationName, transacti
   var isDocumentFragment = containerInfo._node && containerInfo._node.nodeType 
   var doc = isDocumentFragment ? containerInfo._node : containerInfo._ownerDocu
   listenTo(registrationName, doc);
+  listenTo(registrationName, document);
 }
 
 function inputPostMount() {
```

**Comment by gaearon** [comment]
I can’t reproduce the original case with React 16.

**Comment by robertknight** [comment]
I can confirm the issue is resolved in React 16 in the context of the original app. Thank-you for the great work on this release 👍
