### ISSUE TITLE
JSX Gotcha: Case Sensitivity

### ISSUE THREAD

**Issue by joearasin** [facebook/react#8008]
**Do you want to request a *feature* or report a *bug*?**

Documentation. Add something pertaining to this to the JSX Gotcha's page.

**What is the current behavior?**

```jsx
const foo = this.props.someCondition ? Component1 : Component2;
return (<foo bar={baz} />);
```

is not equal to 

```jsx
const Foo = this.props.someCondition ? Component1 : Component2;
return (<Foo bar={baz} />);
```

Which is rather unintuitive, considering that meaning isn't generally attached to case.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Aweary** [comment]
@joearasin thanks for the issue.

This is currently documented in [JSX in Depth](https://facebook.github.io/react/docs/jsx-in-depth.html), though not much is said about it.

>React's JSX uses the upper vs. lower case convention to distinguish between local component classes and HTML tags.

This might also be something that will/can be addressed more clearly in the new docs, cc @lacker @hramos.

**Comment by hramos** [comment]
cc @lacker who's updating the JSX in Depth guide.

**Comment by jverce** [comment]
I see it perfectly documented in this section now:
https://facebook.github.io/react/docs/jsx-in-depth.html#specifying-the-react-element-type

**Comment by gaearon** [comment]
Yeah, this is now documented in a few more places.
