### ISSUE TITLE
Warning: validateDOMNesting(...): <metadata> cannot appear as a child of <head>. See head > metadata.

### ISSUE THREAD

**Issue by thynson** [facebook/react#8014]
I believe this is a bug of the DOM validator.

I try to render an entire page with `ReactDOMServer.renderToStaticMarkup`, which there are `<metadata>` element inside `<head/>`, I got the above warnings. And the render result put `<metadata>` inside `<body/>`.

The expected behavior is, `ReactDOMServer.renderToStaticMarkup` should not warns about`<metadata>` appears in the `<head/>` and also should not move `<metadata>` elements into `<body/>`.

I'm using React 15.3.0. Not tested in previous version.

Updated: ReactDOM 0.14.8 renders correctly, but warns me as well.

**Comment by keyanzhang** [comment]
Hi @thynson, thanks for creating this issue. Just making sure I understand your question, did you intend to use `<metadata />` instead of `<meta />`?

**Comment by geterdunn** [comment]
I dud not know what i was doing

**Comment by thynson** [comment]
@keyanzhang You're right! Autocompletion provided a wrong tag name, `<metadata/>` is actually related to SVG. Thanks for your hint.
