### ISSUE TITLE
"npm run lint" fails on Windows

### ISSUE THREAD

**Issue by andrerpena** [facebook/react#8021]
"npm run lint" fails on Windows, at least Windows 7.

Error:

> Running "eslint" task
> [17:46:07] Using gulpfile C:\Projetos\Git\react\gulpfile.js
> [17:46:07] Starting 'eslint'...
> C:\Projetos\Git\react\node_modules.bin\eslint.cmd:1
> (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
>                                                               ^
> SyntaxError: Unexpected token ILLEGAL
>     at Object.exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:513:28)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)
>     at run (node.js:348:7)
>     at startup (node.js:140:9)
>     at node.js:463:3
>  [17:46:08] Lint failed
> Fatal error: Something went wrong running gulp:

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1581429/19534856/49f6a496-9624-11e6-85ba-2da9d3da803e.png)

I found this ["related" error in mocha](https://github.com/gotwarlost/istanbul/issues/90) but I couldn't fix it anyway.

What might it be?

**Comment by jddxf** [comment]
I encountered the same problem. If you look into the code in **gulp/tasks/eslint.js**, you'll find the following code:
```
spawn(
      process.execPath,
      [
        path.join('node_modules', '.bin', 'eslint' + extension),
        '.',
      ],
      {
        // Allow colors to pass through
        stdio: 'inherit',
      }
    )
```
which spawns a new process using the command "node node_modules\\.bin\eslint.cmd .". The command tries to interpret a batch file using node. However node can interpret js files only. That's why there's a SyntaxError.
A change like this should work as expected:
```
spawn(
      path.join('node_modules', '.bin', 'eslint' + extension),
      ['.'],
      {
        // Allow colors to pass through
        stdio: 'inherit',
      }
    )
```

**Comment by gaearon** [comment]
@jddxf Would you like to send a PR if you have a working fix?

**Comment by jddxf** [comment]
@gaearon Sure. I'll fix the same problem in gulp flow task too.

**Comment by gaearon** [comment]
I rolled this into https://github.com/facebook/react/issues/9540.
