### ISSUE TITLE
IE11, findParent fails with 'Unable to get property '__reactInternalInstance$...' of undefined or null reference

### ISSUE THREAD

**Issue by Ragnaroek** [facebook/react#8031]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Exception is thrown, rendering stops.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Doesn't seem to be determinstic, but it happens only in IE (at least in IE11).

**What is the expected behavior?**
Should not throw an exception and continue rendering.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.2.1, IE 11 on Windows 8.1

**Comment by Ragnaroek** [comment]
This PR tries to fix the symptoms: https://github.com/facebook/react/pull/8032

**Comment by Aweary** [comment]
@Ragnaroek thanks for the report!

> Doesn't seem to be determinstic, but it happens only in IE (at least in IE11).

Can you share a test case that reproduces it nondeterministically? Even if it isn't consistent, it's better than nothing. I would say fixing the symptoms and not the issue isn't a good idea here, as it may just hide a deeper issue or cause hard to debug problems somewhere else in the code path.

**Comment by Ragnaroek** [comment]
I agree that fixing the symptom this way was a bad idea.
As it turned out the problem was not React, but an exception in one of our promise handlers.

**Comment by Aweary** [comment]
@Ragnaroek thanks for the update, glad you figured it out 👍!
