### ISSUE TITLE
docs: list and key examples override Number

### ISSUE THREAD

**Issue by giuseppeg** [facebook/react#8034]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

In #8027 some [example](http://react-new-docs-temporary-preview.surge.sh/react/docs/lists-and-keys.html#extracting-components-with-keys)s  use `Number` as component name

```javascript
function Number(props) {
   // ...
}
```

Maybe it is a good idea to rename this component to `NumberItem` or something.

**Comment by gaearon** [comment]
Oops. I forgot it's a built-in thing.
I'll take a PR renaming it to `ListItem`.

**Comment by rthor** [comment]
I'll do it, if that's ok?
