### ISSUE TITLE
[feature/idea] rename context(types) to implicit props(types), and merge them.

### ISSUE THREAD

**Issue by slivcode** [facebook/react#8042]
Currently

``` js
// Parent
getChildContext = _ => ({theme: 'red'})
render = _ => <ThemedButton />

// Child
ThemedButton  = (props, ctx: {theme}) => <button color={theme}>BTN</button>
ThemedButton.contextTypes = {theme: PropTypes.string}
```

Effectively, context is an **implicit props**, i.e. it is _mostly_ equivalent for all Child under Parent, it just expect Child to ask for it.

``` js
// Parent
render = _ => <ThemedButton theme={parentToChildContext.theme} />
```

Interchangably, my Proposal/idea in mind.

``` js
// Child
ThemedButton  = (props:{theme}) => <button color={theme}>BTN</button>
ThemedButton.propTypes = {theme: PropTypes.string.allowImplicit}
```

it also imply, you can **override** the props if needed, for cases like testing/preview/...

``` js
<ThemedButton theme="green" /> {/*green button, explicit props have higher priority*/}
<ThemedButton /> {/*red button*/}
```

a sample enhancer implementation

``` js
export let withImplicitProps = (propsName) => (target) => {
  let o = {}
  propsName.forEach((k) => o[k] = PropTypes.any)
  let out: any = (props, ctx) => createElement(target, Object.assign({}, ctx, props))
  out.contextTypes = o
  return out
}
```

Feel free to point out flaws and edge cases, but whatever they are, context probably share the same issue. The idea is just more intuitive to introduce the concept.

P.S Also, I would proposal creating **constant** context values, to share fixed values, which never trigger Child update after mount.

**Comment by gaearon** [comment]
We're fairly happy with the "context" name.

We are already unnecessarily relying on PropTypes for defining context relationship, and I don't think we'll go further in that direction. In fact we'll probably decouple them in the future since many people don't use PropTypes at all.
