### ISSUE TITLE
Wrong Snippet code Uncontrolled Components: (Docs-Forms)

### ISSUE THREAD

**Issue by bayfaal** [facebook/react#8052]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by bayfaal** [comment]
Need to replace render section of snippet code as it it is in the codepen. Actually it renders an input text instead of the radio buttons (Docs--Forms--Uncontrolled Components)

**Comment by ericnakagawa** [comment]
Thanks for finding this @bayfaal. The [Codepen] has been updated -- I'll push an edit to the forms.md page so it matches the codepen.

**Comment by bayfaal** [comment]
Thanks for this feedback.
Good job ;)
