### ISSUE TITLE
[New Docs] Set Up Localization Effort

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8063]
We've deleted the old localized content because most of the docs changed too much.
We should set up proper infrastructure for localization because the old process was slow and ineffective.

cc @lacker

**Comment by wong2** [comment]
Would you consider using something like: https://www.transifex.com/ ?

**Comment by gaearon** [comment]
I heard from @zpao that @thejameskyle was building something for Yarn which we may then reuse.

**Comment by lacker** [comment]
@ericnakagawa is going to work with @thejameskyle to see if the Yarn solution will work for React.

**Comment by gbezyuk** [comment]
@translation-gang is ready to help with Russian translation, as soon there will be an infrastructure.

**Comment by gaearon** [comment]
That’s pretty awesome. We will keep you posted!

**Comment by JisuPark** [comment]
AWESOME. Just tell @little-big-programming when infra is ready. I'll jump into Korean translation.

**Comment by ericnakagawa** [comment]
Hi folks, we are making steady progress on a workflow for community driven localization. We've helped get one OSS project (@yarnpkg/website) working using the system! We've learned a lot and things should move along rather quickly from this point.

I'm hoping @JisuPark @gbezyuk and others on this thread are still able to assist. Thanks!

**Comment by spicyj** [comment]
Very happy to get localization in. What do you need from us?

**Comment by gbezyuk** [comment]
@ericnakagawa we totally are, just tell us what to do ;)

**Comment by JisuPark** [comment]
@ericclemmons Of course we are :) Just tell us what you need. Thanks.

**Comment by namkwon** [comment]
I wish I can do help for Korean localization. :)

**Comment by ferlopez94** [comment]
Hi! I'd like to help for translating docs to Spanish. I've been searching for guidelines to do this but I couldn't find them.

**Comment by gaearon** [comment]
We haven't started the process yet. We'll write in this issue when everything is ready.

**Comment by gaearon** [comment]
@ericnakagawa @hramos Is there anything we can do on our side to start the process? I don’t want to lose valuable effort like https://discountry.github.io/react/ which will get out of sync soon.

**Comment by hramos** [comment]
@gaearon ping Eric directly, he's been leading the localization effort for other sites

**Comment by leocabeza** [comment]
Hi. Just writing here to let anyone know I can help with spanish translations. I'll be watching this issue.

**Comment by gaearon** [comment]
Thanks! There‘s ongoing work to begin accepting translations in the coming weeks.

**Comment by ryouaki** [comment]
I am a Chinese . (^_^)v

**Comment by discountry** [comment]
@gaearon Do we have any progress now? We've been kept updating our [Chinese version docs](https://discountry.github.io/react/) to v15.6.1. And we are ready to catch up with the react@16 updates. When would there be any official localization plan to accept other languages translation?

**Comment by gaearon** [comment]
@bvaughn is working on a website revamp and we'll likely combine this with the localization setup effort. We might have something in a month or so. Stay tuned :-)

**Comment by ericnakagawa** [comment]
Hi folks, React documentation localization effort is ready for contributions.

Documentation is primed for localization. So far we've had great efforts from the Indonesian, Japanese, and Portuguese Brazilian communities.

Please direct interested members of your community to the official Crowdin project repo: [https://crowdin.com/project/react](https://crowdin.com/project/react)

@discountry Would you be interested in helping manage Chinese?
@ryouaki Please sign up!
@leocabeza @ferlopez94 Happy to accept your folks help!
@gbezyuk Are you folks able to help lead Russian translation?
@JisuPark Are you still able to help with Korean?

If you have any questions, please message me here in this thread, on CrowdIn, or on Twitter @ericnakagawa!

**Comment by spicyj** [comment]
cc past translations contributors @ivanzotov @alexzherdev @dotu @marocchino @zhangjg @kohei-takata @camsong if any of you are interested in helping with official translations

**Comment by gaearon** [comment]
What can I do to help with Russian translation? Happy to review etc.

**Comment by ericnakagawa** [comment]
@gaearon If you can review or help identify someone that can help manage reviewing that'd help this effort. It'll take some time to reach a high %.

**Comment by gaearon** [comment]
What do you generally recommend re: quality? Do we start with lower quality translations and iterate, or do we set a high bar from the beginning?

**Comment by ericnakagawa** [comment]
@gaearon Aiming for high quality initially is best!

**Comment by gaearon** [comment]
If there is a low quality translation, do we just wait for someone to contribute a better one? Reject it somehow?

**Comment by discountry** [comment]
@ericnakagawa I can help manage reviewing Chinese translation.

**Comment by FateRiddle** [comment]
@ericnakagawa I'd love to be part of Chinese simplified translation.
@discountry I love the current Chinese docs, and believe we can make the official one even better and concise. How do you prefer we contact and coordinate?

**Comment by discountry** [comment]
@FateRiddle Submit on CrowdIn or pull request to Chinese doc repo are both fine. We already have a group up to 50 members, you can find us on react-china.

**Comment by ericnakagawa** [comment]
@discountry Because of your work leading the Chinese React translation project I've added you as a reviewer!

**Comment by ryouaki** [comment]
I finished some translation about warnings, readme and others on CrowdIn.
@discountry we really have 50 members?

**Comment by keyanzhang** [comment]
@ericnakagawa would you mind adding me as a reviewer for simplified Chinese? Thanks :)

**Comment by smikitky** [comment]
@ericnakagawa Is there a convenient way for translators to test/preview the localized version before it's published? I'm seeing no `download` button on Crowdin, and the translations are pushed to nowhere on GitHub, right?

**Comment by sophiebits** [comment]
@discountry Are sites that use cloudflare (ex: yarnpkg.com, babeljs.io) accessible easily?

**Comment by discountry** [comment]
@sophiebits actually cloudflare is very slow when visiting from China.

**Comment by ericnakagawa** [comment]
@smikitky Hi, the new website is currently being developed. We don't have a preview site configured yet, but once they new site design is live we'll be working to allow live previews!

**Comment by ericnakagawa** [comment]
@keyanzhang I've added you. Please check your email.

**Comment by ericnakagawa** [comment]
Hi folks, update on our translation progress.

Japanese: 100%
Indonesian/Behasa: 60%
Chinese Simplified: 56%
Portuguese Brazilian: 51%
French: 11%
Spanish: 11%
Greek, Korean, Russian, Danish, German, Arabic, Bengali, Ukrainian, Czech, Polish, Turkish: < 10%

Details here: https://crowdin.com/project/react/settings#translations

**Comment by JisuPark** [comment]
@ericnakagawa Hello, Korean translation is progressing slower than I thought, but I'm still working. What do you think about adding a glossary page? Even if we want to translate, it is hard to unify expressions or words. At least I want to bring Korean in a consistent way, can you give me advice?

**Comment by ericnakagawa** [comment]
@JisuPark How do you think having a glossary page would help? Where should that live?

**Comment by gaearon** [comment]
I think it would make sense to create a Glossary page in docs themselves. There was some initial work in https://github.com/facebook/react/pull/8199. If we got that through, that could help anchor translations as well.

**Comment by ignatiusreza** [comment]
I would be happy to help with translation for Bahasa Indonesia :smiley_cat:

**Comment by JisuPark** [comment]
@ericnakagawa I think Glossary page will be in the docs, same as @gaearon's opinion.most of the React related article in Korean have different

**Comment by Beomi** [comment]
@ericnakagawa 
is https://crowdin.com/project/react official translation repo?

**Comment by smikitky** [comment]
A good glossary in the original document is desirable in the long run, but I think we don't have to wait for it. Japanese translators maintain a list of words so we can translate React jargon (such as "uncontrolled component") consistently: https://gist.github.com/smikitky/15f1332ec1d820b96159ccb56e6862a3

I'm saying this because making a glossary would be a nontrivial work. Forgive me to say this, but what I've found after reviewing the entire document was that the original document is not very consistent regarding the word usage. For example, `<div />` is referred to as "DOM component" in one place, but "component" only refers to user-defined components in another place (e.g., "Always start component names with a capital letter."), while "custom components" and "user-defined components" seem to be other (redundant?) synonyms used elsewhere. Nevertheless, even with these inconsistencies, all chapters are fully understandable and translatable if you have the basic knowledge of React. I doubt strictly consistent documentation is a priority of the core team; translators may have to move on without a "source-of-truth" glossary.

**Comment by bvaughn** [comment]
Migrating to reactjs/reactjs.org/issues/82

**Comment by gaearon** [comment]
We've launched our first translations, and many need more contributors.

https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html
