### ISSUE TITLE
Forms documentation should not hide relevant info :)

### ISSUE THREAD

**Issue by tarjei** [facebook/react#8068]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
![utvalg_272](https://cloud.githubusercontent.com/assets/211263/19635634/1059f71c-99c4-11e6-9d99-5e4caef4dd88.jpg)

http://react-new-docs-temporary-preview.surge.sh/react/docs/forms.html#examples

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**
The `defaultSelected` attribute should be shown within the code - you should not have to scroll to find it.

 
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not relevant.

**Comment by tarjei** [comment]
Also IMHO you should consider adding an example of how radiobuttons use the `selected` attribute and not just the defaultSelected attribute :)

**Comment by gaearon** [comment]
@ericnakagawa Can you please fix this?

**Comment by ericnakagawa** [comment]
Fixed line breaks.
