### ISSUE TITLE
Changing text element content in SVG doesn't work properly

### ISSUE THREAD

**Issue by ericflo** [facebook/react#807]
Here's a JSFiddle which demonstrates: http://jsfiddle.net/kb3gN/784/

Clicking on the "click me" button should update the svg <text> element's content to add more letters 'a', but instead it does nothing.  However the state is confirmed to be changing since we have other elements on the page which are updating properly.

(Note that if you put the text in an attribute on the <text> element, that attribute will update, so it has something to do with the element content.)

**Comment by gregorym** [comment]
Any update on this one?

**Comment by zpao** [comment]
The original issue has been fixed (#808 was relanded).

@gregorym - you are likely experiencing a different issue, perhaps #3972.

**Comment by kiranyedidi** [comment]
I have the same issue on both Safari and Chrome. It works just fine in FF. Any workarounds? Thanks!
