### ISSUE TITLE
Uncaught Invariant Violation: parentComponent must be a valid React Component

### ISSUE THREAD

**Issue by Taakn** [facebook/react#8074]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am seeing the following error on a page (that used to work). The stack doesn't say anything at all, so debugging is difficult. My request is not for you to help me debug my code, but to improve that error stack so that people who encounter that error can figure out where it's coming from.

Thanks

```
invariant.js:38 Uncaught Invariant Violation: parentComponent must be a valid React Component
invariant	@	invariant.js:38
renderSubtreeIntoContainer	@	ReactMount.js:343
renderLayer	@	RenderToLayer.js:141
componentDidUpdate	@	RenderToLayer.js:68
measureLifeCyclePerf	@	ReactCompositeComponent.js:74
(anonymous function)	@	ReactCompositeComponent.js:726
notifyAll	@	CallbackQueue.js:67
close	@	ReactReconcileTransaction.js:81
closeAll	@	Transaction.js:204
perform	@	Transaction.js:151
perform	@	Transaction.js:138
perform	@	ReactUpdates.js:90
flushBatchedUpdates	@	ReactUpdates.js:173
closeAll	@	Transaction.js:204
perform	@	Transaction.js:151
batchedUpdates	@	ReactDefaultBatchingStrategy.js:63
batchedUpdates	@	ReactUpdates.js:98
dispatchEvent	@	ReactEventListener.js:150
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome on Windows 10
React 15.2.1

**Comment by gaearon** [comment]
Doesn't the stack point to something called `RenderToLayer.js` (which presumably is your code?)

```
renderLayer @   RenderToLayer.js:141
componentDidUpdate  @   RenderToLayer.js:68
```

**Comment by Taakn** [comment]
I'm so sorry I slept for 4 hours, I'm working too much. Not my code but another package I'm using. Thanks a lot for replying, I'll be closing this issue covered in shame now

**Comment by gaearon** [comment]
Haha no worries. Cheers!
