### ISSUE TITLE
Add description of {false} caveat to docs/conditional-rendering.md

### ISSUE THREAD

**Issue by donriver** [facebook/react#8075]
**Do you want to request a *feature* or report a *bug*?**
documentation enhancement

We need to describe that if user wants to output string "false" for boolean property that is false, he should convert it to string or else it won't appear in the output.

**Comment by gaearon** [comment]
There is a paragraph saying:

>Therefore, if the condition is `true`, the element right after `&&` will appear in the output. If it is `false`, React will ignore and skip it.

We could add something more detailed to "JSX in Depth", would you like to make a PR? The last section in it mentions handling of `false` too.

**Comment by Dema** [comment]
Yep, sorry, my fault, I haven't read it yet. I think, yes, that section in JSX In Depth explicitly mentions this.

**Comment by gaearon** [comment]
Fixed via #8076, it's called out explicitly now.
