### ISSUE TITLE
Re-add the warning about PropTypes

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8080]
After a discussion with @spicyj we decided to keep the warning even though the functions will throw in production. The warning is the only way to learn about that.

We should also document how to pass the secret through in case you know what you're doing.

**Comment by spicyj** [comment]
> even though the functions will throw in production

particularly *because* the functions will throw in production

**Comment by stevewillard** [comment]
Out of curiosity, why will they throw errors in 16.0?

**Comment by gaearon** [comment]
Yes (but only in production).

**Comment by gaearon** [comment]
Because we will eliminate all that code in production. It doesn't seem to make sense to ship real code for PropTypes validators if it's normally never used in prod. Therefore we'll replace them all with an empty function. To make this behavior clear we'll make it throw so people don't rely on them for validating e.g. user input.

**Comment by thysultan** [comment]
You could also create PropTypes on demand, for example

```javascript
Object.defineProperties(api, {'PropTypes': {
	// only construct PropTypes when used
	get: function () {
		return (
			Object.defineProperty(
				this, 
				'PropTypes', 
				{ value: generatePropTypes() }
			),
			this.PropTypes
		);
	},
	configurable: true, 
	enumerable: true
....
```

**Comment by Kovensky** [comment]
That would defeat the point by including even more code, rather than making the production bundle smaller.
