### ISSUE TITLE
react-addons-css-transition-group give me a warning: transitionEnterTimeout wasn't supplied to ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by mrdulin** [facebook/react#8087]
Failed prop type: transitionEnterTimeout wasn't supplied to ReactCSSTransitionGroup: this can cause unreliable animations and won't be supported in a future version of React. See https://fb.me/react-animation-transition-group-timeout for more information.

How do I solve this warning ? Thanks

**Comment by gaearon** [comment]
Hey there!

To solve it, you can do exactly what the warning says.
Add `transitionEnterTimeout` like examples in the link do:

```js
        <ReactCSSTransitionGroup
          transitionName="example"
          transitionEnterTimeout={500}
          transitionLeaveTimeout={300}>
          {items}
        </ReactCSSTransitionGroup>
```


I hope this helps!

**Comment by mrdulin** [comment]
@gaearon I use like this:

```js
<ReactCSSTransitionGroup
            transitionName="example"
            transitionAppear={true}
            transitionAppearTimeout={500}>
            <h1>Fading at Initial Mount</h1>
        </ReactCSSTransitionGroup>
```

**Comment by gaearon** [comment]
My comment above is still valid, you need to add all the missing props

**Comment by evheniy** [comment]
Hi
Maybe we should change it in docs?
https://facebook.github.io/react/docs/animation.html#animate-initial-mounting

**Comment by gaearon** [comment]
We’re going to remove these docs anyway and redirect them to the new home of the transition group: https://github.com/reactjs/react-transition-group/tree/v1-stable

We are not maintaining this addon ourselves anymore. Feel free to submit a PR against the docs there though!
