### ISSUE TITLE
https://fb.me/react-warning-keys is redirected wrongly

### ISSUE THREAD

**Issue by hanssaurer** [facebook/react#8092]
The following Warning is not redirected correctly: (At least from Chrome debugger)

20547 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `List`. See https://fb.me/react-warning-keys for more information.

leads to: 
https://facebook.github.io/react/docs/composition-vs-inheritance.html
instead of:
https://facebook.github.io/react/docs/lists-and-keys.html

**Comment by gaearon** [comment]
I don't know how to change what `fb.me` links point to.
@spicyj Can you help me with this? 

We should make it point to https://facebook.github.io/react/docs/lists-and-keys.html#keys.

**Comment by hanssaurer** [comment]
When working in the chrome debugger and not attaching a unique key to iterated children the attached warning appears. The link https://fb.me/react-warning-keys is redirected subsequently. You can reproduce this by typing it in the address field of your browser. I don't know who redirects it and where to find the redirection table.

![bildschirmfoto 2016-10-26 um 16 21 24](https://cloud.githubusercontent.com/assets/9348544/19729853/af164a42-9b98-11e6-957d-05ac980ccfd8.png)

**Comment by gaearon** [comment]
Yes, I understand this, it's a valid issue and we need to fix it.
My comment was pointed towards @spicyj who knows how `fb.me` redirects are set up.

**Comment by gaearon** [comment]
It's fixed now. The old redirect is cached in my browser but I can verify it opens the right URL in an incognito tab.

**Comment by gaearon** [comment]
Thanks for bringing this to our attention!
