### ISSUE TITLE
Reusable Components Page Redirects Improperly

### ISSUE THREAD

**Issue by brandonaaskov** [facebook/react#8108]
The old page for Reusable Components (that went into great detail about the various PropTypes that can be used), now redirects to the wrong page:

**Original Page**
https://facebook.github.io/react/docs/reusable-components.html

**Now Redirects To**
https://facebook.github.io/react/docs/components-and-props.html

If, like me, you're looking for _something_ for now, you can see the original page from [Google cache](http://webcache.googleusercontent.com/search?q=cache:https://facebook.github.io/react/docs/reusable-components.html).

**Comment by gaearon** [comment]
Hi, thanks for feedback. The old "Reusable Components" page contained too many topics, and unfortunately we can't set up redirects for hash portion of the URL.

If you go to the [new docs website](https://facebook.github.io/react/) and use "Search" like this:

<img width="647" alt="screen shot 2016-10-26 at 17 12 01" src="https://cloud.githubusercontent.com/assets/810438/19734411/5436cf50-9b9f-11e6-9f52-d604aea1c5cd.png">

You will see that there is now a [whole separate guide dedicated to PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) as well as [a complete API reference](https://facebook.github.io/react/docs/react-api.html#typechecking-with-proptypes).

I hope this helps!
