### ISSUE TITLE
Children components cannot always be a blackbox to their parent.

### ISSUE THREAD

**Issue by davidnormo** [facebook/react#8111]
Perhaps this is already solved but I've had trouble finding a solution I'm happy with. Our scenario is as follows:

```
function A() {
  return <div>Hello world!</div>;
}

function Disable(props) {
  return <div className="disabled">{props.children}</div>;
}

function B() {
  return <Disable><A /></Disable>;
}
```

So component A doesn't know anything about being disabled or not. Component B, the owner, decides to disable component A by wrapping it in component Disable. Easy enough so far. We like this pattern, it means we can disable any component we like.

However we started getting into trouble when the div that Disable adds to the DOM starts to mess with styling, flexbox in most of our cases. Component A might have some styles such as `flex-shrink: 2` which now Disable needs to replicate some how.

I think our tidiest solution has been for Component A to expose a `className` prop, that can be used to pass down the "disabled" class. But this means any component we may want to disable needs to also expose a `className` prop. Is this the accepted approach to the problem? Or is there something I'm missing?

Thanks

**Comment by gaearon** [comment]
The tidiest solution is to have each component that is interested in supporting being disabled to accept a `disabled` prop. It could then choose to use a special `className`, or an inline style, or anything else, to get the relevant styles.

As an escape hatch your components may expose `className` prop but this breaks encapsulation and often leads to issues later on in the project.

I hope this helps!

PS We use issue tracker for bugs. It would be great if you could use [community resources](https://facebook.github.io/react/community/support.html) for asking questions. Thanks!

**Comment by davidnormo** [comment]
Thanks @gaearon, I'll continue the discussion on SO
