### ISSUE TITLE
HTML5 datepicker not updating after type change

### ISSUE THREAD

**Issue by richsoni** [facebook/react#8116]
When toggling an input's type between 'date' to 'datetime-local', there are strict formatting rules (at least in Chrome).

Here is a breaking example: http://jsbin.com/weyenof/edit?html,js,output

Changing React to version 15.1.0 in the example fixes the bug.

**Comment by rickbeerendonk** [comment]
It runs fine if I run it locally in React 15.3.2 and 15.3.0.
In jsbin I do indeed see the effect, but when I open the console I can see warnings that the value is not being set in the correct format. I don't see those errors locally.

**Comment by richsoni** [comment]
I just experienced the same.  I am going to do some more experimentation to see if I can figure out why its not working in the jsbin (and also in my actual code).

**Comment by nhunzaker** [comment]
@richsoni Thanks for providing the test case! I've incorporated this into our DOM test fixtures and I am unable to reproduce the issue. Still, this is a really fantastic test case. Thank you for providing it!

The PR for the addition is here:
https://github.com/facebook/react/pull/10154

And you can try it yourself here:
http://nh-date-locale-switch-fixture.surge.sh/date-inputs?version=15.6.1

**Comment by nhunzaker** [comment]
Also thanks for filing a fantastic issue :)
