### ISSUE TITLE
React does not support node 7.x for development

### ISSUE THREAD

**Issue by Shastel** [facebook/react#8134]
**What is the current behavior?**
```AssertionError: Current node version is not supported for development, expected                                                                                                                                   "7.0.0" to satisfy "4.x || 5.x || 6.x".```

**Steps to reproduce**
1. Install node 7.x
2. Clone [React repo](https://github.com/facebook/react)
3. run ```npm i```

**What is the expected behavior?**
React support node v7 for development

**Comment by gaearon** [comment]
Thanks for the fix.
