### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by wenpengfei** [facebook/react#8140]
`Uncaught Error: Attempted to update component`Connect(Connect(Connect(Connect(getContext(withHandlers(MemberPrepaidView))))))`that has already been unmounted (or failed to mount)`

Any idea why am I getting this?

**Comment by gaearon** [comment]
No, we would need a minimal example reproducing the problem to help troubleshoot it.

**Comment by wenpengfei** [comment]
@gaearon  thanks for your reply. it seems works.....
