### ISSUE TITLE
Hot Module Replacement has problem working with dropbox

### ISSUE THREAD

**Issue by wangzhen10** [facebook/react#8141]
I'm submitting a bug report

React version： **15.0.1**

Webpack version: 1.13.3

Current behaviour:
Hot Module Replacement does not work when my project is in my dropbox named "dropbox(person)". But after I change the name to "dropbox" without"()". It does work.

I spend 2 days to figure out this problem. I just want to share this with others. So they do not need to waste time on this.

**Comment by gaearon** [comment]
Thanks for the report! You should however file this with Webpack because React is just a user interface library and has no relation to hot module replacement. Cheers!
