### ISSUE TITLE
path attribute is removed in animateMotion tag

### ISSUE THREAD

**Issue by rchaser53** [facebook/react#8154]
**Do you want to request a _feature_ or report a _bug_?**
 bug

**What is the current behavior?**
React remove path in animateMotion tag and outputs a warning ''Warning: Unknown prop `path` on <animateMotion> tag. Remove this prop from the element."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/4f121otb/3/

**What is the expected behavior?**
I want to use path in animateMotion tag without using dangerouslySetInnerHTML.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.2, google chrome 56.0.2902.0 dev / Windows 10 version 1607

**Comment by ScottMunn** [comment]
Did you find a solution for this?

**Comment by Lyonsclay** [comment]
It looks like reactjs doesn't support the path attribute;

https://facebook.github.io/react/docs/dom-elements.html#all-supported-svg-attributes

**Comment by gaearon** [comment]
Works in React 16.
https://jsfiddle.net/kygz40ks/
