### ISSUE TITLE
htmlFor and api considerations

### ISSUE THREAD

**Issue by oelmekki** [facebook/react#8161]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Discussion**

Hi guys,

I've been using react daily since april 2015, and I still do the same mistake on a regular basis: using `for` instead of `htmlFor` on `<label>`s. "Oh, yeah, that again".

This makes me wonder: why can't we use `for` as a property in first place? I suppose it's related to the fact that `for` is a javascript keyword, but as far as I know, there's no public API allowing to use a `for` property as a loop instruction? Wouldn't it be a better API that applies the principle of least surprise here, instead of having us to remember specificity that has no actual impact on how we use the API? (actually, I realize the same could go with `class`/`className`).

**Comment by davecarlson** [comment]
I'd like to see some consistency on this point actually. In my mind, anything that should end up being a properties of a node (eg: class="" rel="" for="" etc... ) should have a consistent naming convention when creating components. 

With that in mind, something like: 
```
<div 
htmlFor=''
htmlClass=''
>
```

would make more sense than the current hap-hazard approach to different ones to avoid clashing with javascript keywords

**Comment by Aweary** [comment]
The attribute notes correspond to the property names used in JavaScript to access these values. https://jsfiddle.net/po7mtLhw/

So they are consistent and were not haphazardly chosen. While JSX makes it feel like you're dealing with the DOM directly React is still managing these elements in JavaScript so it makes more sense to be consistent with property names rather than HTML attribute names.

**Comment by davecarlson** [comment]
@Aweary , totally understand (Y). I was more referring to javascript's poor choice of prop names, rather than anything react specific.

I guess this is more of a question about how JSX should 'feel'. Should there be an additional level of abstraction, to make it more developer friendly ? (not saying there *should*, just throwing some thoughts out there :) )

**Comment by oelmekki** [comment]
@Aweary thanks, I did not realize `htmlFor` was the name for the actual DOM api.

I get the implementation now, and it's indeed coherent. But don't you think it's still a problem that it's not what users could expect? I'm pretty sure I'm far from the only one thinking in term of html when I write jsx for react-dom :)

**Comment by Aweary** [comment]
I totally agree that it can be confusing, no doubt about that. I do think the current warnings you get in dev are mostly sufficient, and it's a lesson you only need to learn once.

I just don't think that, at this point, it would be a change worth making. It would be a pretty huge breaking change (especially `className`) to change these attributes. You **could** support both, but that's even more confusing IMO.

**Comment by oelmekki** [comment]
Yeah, I was thinking about the dual attribute solution, so that people more at ease with thinking in DOM and those who prefer thinking as html both have a painless experience.

I'm sorry, I'm an example of the fact that "learning it once" is not enough :) (maybe it'll change now that I realize it's about DOM api attribute names).

Do you mind if I leave this issue open, so that we may see if it's an issue for other people too?

**Comment by zpao** [comment]
For a long time and in some browsers with considerable marketshare when React launched, it wouldn't have allowed the JSX transform to work consistently.

`<label for="foo" />` would get transformed to (at the time) `React.DOM.foo(null, {for: "foo"})`. Specifically the use of `for` as a key like that was not valid and would throw an error. Same for `class`. Now you could write that as {'for': ...}` to work around it. But you also had to access the property the same way - `this.props['for']`. We didn't like this inconsistency, not any of the other potential fixes (transforming the prop from `class` in JSX to `className` would have other issues with inconsistency and violate the principle of least surprise). This is the same reason that the DOM API is what it is - it wasn't valid to use keywords as property names without quotes.

The situation is better today so if we were to do it again, we'd use `class` and `for`. Perhaps we'll consider the idea of a migration but this is something that would be more invasive than a lot of the other changes we've made over the last few years so it would be harder. Supporting both would only exist as some intermediate state but it gets really tricky with composite components and their API when manipulating classname.

I'm going to close this out as we've talked about it ad nauseam over the last few years. It's not to say some change won't happen at some point but we don't need to keep more issues open on the topic.
