### ISSUE TITLE
onChange is not triggered for autocomplete in Chrome on iOS

### ISSUE THREAD

**Issue by maxcold** [facebook/react#8174]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In Chrom 54 on iOS onChange is not triggered on inputs after choosing an option from autocomplete suggestion

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
http://output.jsbin.com/sediruxaxo/6/ - you have to have smth in you autofill data in chrome. Try to fill in the form with suggested autocomplete option. In the first case onChange handler won't be triggered

**What is the expected behavior?**
onChange is triggered for autocomplete

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome 54 on iOS 10 at least

**Comment by patriciarealini** [comment]
https://github.com/facebook/react/issues/1159

**Comment by spicyj** [comment]
^ Closing in favor of #1159.
