### ISSUE TITLE
Search is broken on the docs page

### ISSUE THREAD

**Issue by cmswalker** [facebook/react#8178]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the search input for the docs page @ https://facebook.github.io/react/docs/hello-world.html does nothing. Seems to not be firing a click handler for the search icon/magnifying glass.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
just try to use the search bar https://facebook.github.io/react/docs/hello-world.html

**What is the expected behavior?**
It should search the docs. Does react index its docs through an internal search engine/service for search? Just curious

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
No versions of react, just the docs page.`Chrome v 53.0.2785.143 `. Likely worked before, never actually tried to use search until now.

**Comment by RobertKielty** [comment]
I tested this just now and it appears to work for me. I searched for "Events" and "JSX" For both search terms a drop-down appeared with relevant documentation suggestions.

Suggested doc pages could be selected via up and down keys; pressing enter navigates to the pages. Clicking on a suggested also navigates to the page.

You are correct in saying that clicking on the Magnifying Glass does not do anything, I suspect that this is working as expected.

**Comment by gaearon** [comment]
This is what I see when I type:

<img width="635" alt="screen shot 2016-11-03 at 14 16 53" src="https://cloud.githubusercontent.com/assets/810438/19969366/3258f14c-a1d0-11e6-959e-be2f8ac88b75.png">

Magnifying glass doesn't do anything. Maybe we could hide it when you're searching to make it clearer but it doesn't seem very important to me.

**Comment by cmswalker** [comment]
Interesting. So the reason why this was so confusing is that nothing was being populated in the dropdowns, seems like there was a small window where algolia's search wasn't firing on keydown, I checked the console and there were no errors either. The magnifying glass only seems important when there are no dropdowns, its really not the focus here.

Looks good now! Thanks

**Comment by gaearon** [comment]
Ah cool. Maybe some kind of a network or server issue. Glad it's resolved.
