### ISSUE TITLE
Warn when an invalid CSS property+value is stripped out by React

### ISSUE THREAD

**Issue by FezVrasta** [facebook/react#8182]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
React strips invalid CSS properties but doesn't throw any warning.

**What is the expected behavior?**
React should strip invalid CSS properties (for example: `color: rgb(255,255,255,1)`) and throw a warning to let the developer know that something is wrong with the passed values.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I guess all the versions.

**Comment by syranide** [comment]
React doesn't strip invalid values, the browser ignores invalid values for styles. It would also be rather counter-productive to throw a warning because a lot of code relies on gracefully degrading when the properties aren't supported by the browser, i.e. `border-radius`. It's infeasible for React to understand the full HTML5 specification (regardless of browser support) and actually validate values.

**Comment by FezVrasta** [comment]
I don't think I get it, if I do:

```
<div style={{ foo: 'bar' }} />
```

React will render:

```
<div></div>
```

If, instead, I create an HTML element manually and I define such properties, I get:

```
<div style="foo: bar"></div>
```

**Comment by FezVrasta** [comment]
Sorry, I got it. Using `innerHTML` you can define any property, but with `element.style.propName` the invalid ones are automatically stripped out.

Thanks for the clarification.

**Comment by davidrenne** [comment]
I guess the main difference with browsers is when you use a css class, Chrome may show and cross it out on the inspector but styles it just drops the entire style attribute that is invalid.  I think maybe the Dom should show the raw style applied in chrome but merely show it struck through like classes do so people know they made a mistake and it isn't the react or jsx library.  Maybe if someone wants to submit a bug to Chrome that is best.  I just know now that the browser just "ghosts" those bad css attributes and it'd not react!
