### ISSUE TITLE
PureComponent does not respond to context changes

### ISSUE THREAD

**Issue by cvoege** [facebook/react#8184]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**

If you extend from PureComponent, and the context of the component changes but not the props, a re-render will not be triggered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

You can see the bug reproduced here: 

https://jsfiddle.net/fcz8tx3z/16/

**What is the expected behavior?**

You expect that if you click on the increment context button, you would see it updated in the view, but that doens't happen. If you change props, you'll see context instantly update to it's actual value in the view.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 
React 15.3.2
Chrome 54

Fixing this should be reasonably simple I think. Just need to add shallow comparing for context. I have my own stand in for PureComponent in the meantime: 

```js
class Purified extends Component {
    shouldComponentUpdate(nextProps, nextState, nextContext) {
      return !(shallowEquals(this.props, nextProps) && shallowEquals(this.context, nextContext));
    }
  }
```

**Comment by gaearon** [comment]
While this would solve the case with immediate parent, as soon as you put one `PureComponent` into another it would break anyway: https://github.com/facebook/react/issues/2517.

For now, please don't rely on context updates. They're broken, and it's a known issue.

See:

https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076
https://facebook.github.io/react/docs/context.html#updating-context

>Don't do it.

**Comment by cvoege** [comment]
Good point. Would it be wise to simply start referring to context as an antipattern? It's definitely overused in a lot of libraries (for example react-router)

**Comment by gaearon** [comment]
It's a useful feature and projects that treat if as a static thing that doesn't change work well. React Router also uses it correctly in latest versions as far as I know.

It's not an "antipattern", it's just an experimental API that has known issues. Some libraries need it, but their authors should be familiar with its problems.
