### ISSUE TITLE
React Component sending wrong content type on multipart form

### ISSUE THREAD

**Issue by xhallix** [facebook/react#8197]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Form multipart sending `Content-Type:application/x-www-form-urlencoded`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
```
var PicturesTab = React.createClass({
    render() {
      return <div className="pictures">
        <form method="post" enctype="multipart/form-data" action="/upload">
            <input type="file" name="uploadFile" />
            <input type="submit" className="btn btn-primary" value="upload" />
        </form>
      </div>
    }
  });
```
Submit the form to any existing action url
**What is the expected behavior?**
Content Type sent `Content-Type:multipart/form-data; `
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest

**Comment by xhallix** [comment]
okay seems like the root cause is not to write `encType` in camelcase. this took me hours to figure it out 👎

**Comment by Aweary** [comment]
@xhallix for future reference, you should get a warning in the console when using the wrong casing for an attribute.

```console
Warning: Unknown DOM property enctype. Did you mean encType?
```

**Comment by xhallix** [comment]
Hm I did not get a Warnung here, that would have saved me :)
