### ISSUE TITLE
ReactCSSTransitionGroup is not work

### ISSUE THREAD

**Issue by yuda1124** [facebook/react#8203]
I want to fade in animation. my code is 

```
import React, { PropType } from 'react';
import { BrowserRouter as Router, Link, Match, Miss } from 'react-router'
import JsonData from './subtitle.json';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group'
import styles from './LetterBox.css'

export default class LetterBox extends Reac
```t.Component {
  constructor(props){
    super(props);
  }

  render(){
    var boxStyle = {
      background : 'black',
      padding : 10,
      borderWidth : 1,
      borderColor : 'white',
      borderStyle : 'solid',
      location : 'absolute'
    }
    var letterStyle = {
      fontFamily : "맑은 고딕",
      fontSize : 50,
      color : 'white',
      textAlign: 'center'
    }
    var buttonStyleRight = {
      float : 'right',
      background : 'white',
      marginRight: 10,
      fontSize : 20,
      borderColor : 'black'
    }
    var buttonStyleLeft = {
      background : 'white',
      float: 'right',
      fontSize : 20,
      borderColor : 'black'
    }

    return (
      <div>
        <ReactCSSTransitionGroup
          transitionName="example"
          transitionName="carousel"
          transitionAppear={true}
          transitionEnterTimeout={500}
          transitionAppearTimeout={500}
          transitionLeaveTimeout={300}>
          <h1>{this.props.script}</h1>
        </ReactCSSTransitionGroup>
        
      </div>
    );
  }
}
```
but there are no changes...
anyone help?

**Comment by gaearon** [comment]
Please provide a full project or a fiddle reproducing the problem. Thanks!

**Comment by yuda1124** [comment]
umm.. I change my code simply.. 
```
`import React from 'react';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';
import styles from './LetterBox.css';

class App extends React.Component {

    constructor(props) {
        super(props);
        this.state = {items: ['Hello','World','Iwill KILL YOU']};
        this.handleAdd = this.handleAdd.bind(this);
    }

    handleAdd() {
        var newItems = this.state.items.concat([
            prompt('Enter some text')
        ]);
        this.setState({items: newItems});
    }

    handleRemove(i) {
        var newItems = this.state.items.slice();
        newItems.splice(i, 1);
        this.setState({items: newItems});
    }

    render(){
        
        return (
            <ReactCSSTransitionGroup
            transitionName="example"
            transitionEnterTimeout={500}
            transitionLeaveTimeout={300}
            transitionAppear={true}
            transitionAppearTimeout={500}>
            <h1>Fading at Initial Mount</h1>
            </ReactCSSTransitionGroup>
        );
    }
}

export default App;`
```
it is just my first view of my project.
and my package.json is 

> ``
{
  "name": "react-tutorial",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --hot --host 0.0.0.0",
    "test": "eslint src/**"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.16.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "css-loader": "^0.25.0",
    "eslint": "^3.8.0",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.4.1",
    "json-loader": "^0.5.4",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.1"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-addons-css-transition-group": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-router": "^4.0.0-alpha.4"
  }
}

> 

and css file is
`
.example-enter {
  opacity: 0.01;
}

.example-enter.example-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}

.example-leave {
  opacity: 1;
}

.example-leave.example-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
}

.example-appear {
    opacity: 0.01;
}

.example-appear.example-appear-active {
  opacity: 1;
  transition: opacity .5s ease-in;
}
`
it doesn't work without any error, plz help!

**Comment by renarsvilnis** [comment]
Just noticed @yuda1124 , you have forgotten to provide a key for the  `<h1>` element.

> **Note:**
> You must provide the key attribute for all children of ReactCSSTransitionGroup, even when only rendering a single item. This is how React will determine which children have entered, left, or stayed.
> https://facebook.github.io/react/docs/animation.html

**Comment by mikedklein** [comment]
@yuda1124 even without the key your code seems to work http://codepen.io/mikedklein/pen/yVYBNr

**Comment by khovansky-al** [comment]
Well, here's a working example of animating dynamically added elements based on @mikedklein's pen: http://codepen.io/alx-khovansky/pen/zovYZP
It just loops over what you had in state.items.
So, like @renarsvilnis said, "key" prop is essential here, without it it will not work.
Also, we don't know what you were trying to achieve, but if you don't need to animate element removal I suggest you just use CSS keyframes.

**Comment by mikedklein** [comment]
@khovansky-al good point in demoing why the key is necessary I was just trying to get it at why it was failing for @yuda1124

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR
