### ISSUE TITLE
Documentation: Sample is still using string refs

### ISSUE THREAD

**Issue by snakajima** [facebook/react#8209]
Sample code "Step 5: Add Inverse Data Flow" in Quick Start/Thinking in React is still using old string refs. 

```
  handleChange() {
    this.props.onUserInput(
      this.refs.filterTextInput.value,
      this.refs.inStockOnlyInput.checked
    );
  }

  render() {
    return (
      <form>
        <input
          type="text"
          placeholder="Search..."
          value={this.props.filterText}
          ref="filterTextInput"
          onChange={this.handleChange}
        />
        <p>
          <input
            type="checkbox"
            checked={this.props.inStockOnly}
            ref="inStockOnlyInput"
            onChange={this.handleChange}
          />
          {' '}
          Only show products in stock
        </p>
      </form>
    );
  }
```

I think it's better (easier to understand) to use a new syntax.

```
  handleChange() {
    this.props.onUserInput(
      this.filterTextInput.value,
      this.inStockOnlyInput.checked
    );
  }

  ...
     ref={(input) => this.filterTextInput = input}
  ...
     ref={(input) => this.inStockOnlyInput = input}
```

**Comment by Aweary** [comment]
@snakajima good catch! /cc @lacker can the CodePen be updated?

**Comment by lacker** [comment]
This seems like a good idea. In general when we update the codepen we just fork and switch the link to a new one, so anyone can submit a new codepen, and just submit a PR that's linking to the new one. @snakajima @Aweary are either of you interested in fixing this?

**Comment by snakajima** [comment]
Just sent a pull request #8254 @lacker @Aweary

**Comment by breakpoint25** [comment]
I am new to reading the documents; I wish the documentation explained the use of the ref as it was never mentioned and I think it is a key part to how the application works. I think it may be best to add a quick paragraph about its use?

**Comment by gaearon** [comment]
I agree, refs aren’t introduced until later on.
Could we use controlled inputs there instead?

**Comment by gaearon** [comment]
I think we need to restructure it a little bit. We should have two separate change handlers. Then we wouldn’t need refs at all there.

**Comment by gaearon** [comment]
I probably won’t have time to work on this but it’s a good contribution opportunity.
If you’d like to help, please:

* Fork the relevant CodePen step
* Change it to have two change handlers that read `e.target.value` instead of using refs
* Change the text if necessary
* Send a PR!

The goal is to avoid using refs since we haven’t introduced them yet, and they’re not essential to this page.

**If you want to work on it please comment so that several people don’t work on this at the same time.**

**Comment by rohannair** [comment]
I can take this as my first PR.

**Comment by gaearon** [comment]
Sounds great!

**Comment by rohannair** [comment]
Just pushed PR #8815 

Didn't feel like the docs needed changing as `refs` vs `events` were not part of this earlier, and resisted the urge to make the function more complicated by adding in multiple arguments to bind to, as this is intended for beginners.
