### ISSUE TITLE
Closure Compiler (Advanced Mode) externs

### ISSUE THREAD

**Issue by jhiswin** [facebook/react#824]
este has already integrated into React into his Closure-centric framework.  Here's the externs for React that steida has already created:
https://github.com/steida/este-library/blob/master/externs/react.js
It was made for 0.5.0, so it is missing some exports.

It might be good to add a mentions in the docs.

It could also be possible to make a script to automatically generate externs for React.

**Comment by gaearon** [comment]
Closing as GCC advanced mode isn't really supported by React at this point.
It might have been supported if we set up any tests around this, but we didn't, and it regressed over time.
