### ISSUE TITLE
Awkward output on shallow rendering snapshots of components from node_modules

### ISSUE THREAD

**Issue by khankuan** [facebook/react#8253]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Experiencing awkward output from shallow rendering snapshots for components imported via node_modules.
```
exports[`<Test /> renders 1`] = `
<div>
    <ComponentFromNodeModules>
      <span />
    </function ComponentFromNodeModules() {_classCallCheck(this, ComponentFromNodeModules);return _possibleConstructorReturn(this, (ComponentFromNodeModules.__proto__ || Object.getPrototypeOf(ComponentFromNodeModules)).apply(this, arguments));}>
  <Connect(ComponentFromRepo) />
</div>
`;
```

**What is the expected behavior?**
Extra closing tag should contain only component name.

**Comment by gaearon** [comment]
This is not an issue with React. It's an issue with Jest, and, specifically, [pretty-format](https://github.com/thejameskyle/pretty-format).

It is fixed now: https://github.com/facebook/jest/issues/2037, https://github.com/thejameskyle/pretty-format/pull/46. Please make sure you're using the latest version of Jest.

**Comment by khankuan** [comment]
Nice thanks!
