### ISSUE TITLE
[Documentation] Examples on PureComponent Vs Component 

### ISSUE THREAD

**Issue by lucas-aragno** [facebook/react#8255]
In here https://facebook.github.io/react/docs/react-api.html#react.purecomponent I think it would be nice to have some examples comparing PureComponent against Component

**Comment by lacker** [comment]
Do you think the examples in https://facebook.github.io/react/docs/optimizing-performance.html are good enough? If so perhaps we could just link over there from the reference docs.

**Comment by lucas-aragno** [comment]
Yes! I wanted to show PureComponents to a co-worker and he found that hard to understand bc they weren't examples on that page and  I sent him that same link so I think it would be nice to have a link there from the pure component page

**Comment by mmdonaldson** [comment]
Is it discouraged to use Pure Component? Because I also agree that the documentation is a little scattered on it

**Comment by lacker** [comment]
@lucas-aragno OK - want to send a PR just adding a line linking to the examples?

@mmdonaldson It isn't discouraged, no.

**Comment by lucas-aragno** [comment]
@lacker sure will do

**Comment by laumair** [comment]
@lacker @lucas-aragno I think an example of the direct comparison should be added as well with the link. Would be helpful.

**Comment by lucas-aragno** [comment]
sent #8477

**Comment by lacker** [comment]
Cool, let me close this issue & we can continue the discussion on that PR. Thanks!
