### ISSUE TITLE
Make sure that jest tests fail if an error is thrown within a jsdom event handler

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#8260]
In a few situations in our unit tests, we use .dispatchEvent on a jsdom DOM node in order to use the jsdom event system:

https://github.com/facebook/react/blob/e612826650ff68e73bff4d71db01fea8147ee1fd/src/renderers/dom/shared/wrappers/__tests__/ReactDOMInput-test.js#L127

But it appears that if the event handler throws (ex: change the onChange handler in that test to throw), then the error is silently ignored and does not cause the test to fail.

jsdom does make some attempt to report an error:

https://github.com/tmpvar/jsdom/blob/9.8.3/lib/jsdom/living/events/EventTarget-impl.js#L235

We should hook into this in our jest config (scripts/jest/test-framework-setup.js) and see if we can fail any test that triggers this exception behavior. From the implementation of reportException it looks like we might be able to do an onerror handler; if that doesn't work then hooking into their "virtual console" may be possible.

**Comment by franciscofsales** [comment]
I tried playing around with this by catching the error event jsdom dispatches on window and it was kind of going fine but then I had conflicts with tests in here:

[https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactErrorBoundaries-test.js#L256
](https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactErrorBoundaries-test.js#L256
)

any ideas what I might be getting wrong?

**Comment by renderf0x** [comment]
Got this working using the onerror suggestion above; Added #8278 as a PR.

**Comment by franciscofsales** [comment]
@renderf0x that is exactly what I had done, apart from naming and comment. Not sure how to not trigger that issue.

**Comment by franciscofsales** [comment]
Got it. Added #8279. Thanks

**Comment by renderf0x** [comment]
@franciscofsales ah indeed. rad. we'd have to have FB confirm, but this probably just never was an issue because it wasn't being listened for (hence this issue). good stuff.

**Comment by franciscofsales** [comment]
@renderf0x yeah, I think so. I got the answer from your commit actually. I was spying on `error` turns out it's `onerror`. Thanks.

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR
