### ISSUE TITLE
Add #reactjs irc note to support page.

### ISSUE THREAD

**Issue by samsch** [facebook/react#8268]
**Do you want to request a *feature* or report a *bug*?**
Docs change

I think there used to be a pointer to the freenode #reactjs channel in the [support page](https://facebook.github.io/react/community/support.html), but now only Reactiflux is linked. Could the note be added back in? The channel still has 500+ users in it most hours of the day, with several of us who frequently answer questions, and a pretty good flow of conversation and questions throughout the day.

**Comment by lacker** [comment]
Seems like a fine idea to me. Want to send a pull request? Just tag me in it.
