### ISSUE TITLE
Future of refs

### ISSUE THREAD

**Issue by yormi** [facebook/react#8275]
Hi there !

I'm writting here because I use 'refs' to pilot my tests and I would love to be able to uniformise my tests. Right now, with this PR https://github.com/airbnb/enzyme/pull/672#issuecomment-259870776, I can achieve that pretty well with string refs.

Since string refs are considered legacy, and since there still seems to be problems with refs (https://github.com/facebook/react/issues/3234), I was wondering, what is the plan concerning refs.

Moreover, would it be possible to support them in shallow rendering ? I looked into it and I think it'll be possible if we return the `_instance` as with mount of the given element instead of the `_renderedComponent`. I'm aware it's a breaking change but if we can make

So, I'd like to understand the plan and/or the logic behind returning `_renderedComponent`. Maybe I could help. Oh and since I'm on it, if it's not to much trouble, I'd be interested in the reason why changing from string refs to callback refs.

Thank you for your help !

**Comment by gaearon** [comment]
Does `renderer.getMountedInstance()` help? It should give you the instance rather than the element.

**Comment by yormi** [comment]
@gaearon That was exactly what I needed. Thanks !

Ok now, let's say I have: 
```javascript
instance = {
  _constructComponent,
  _instantiateReactComponent,
  ...,
  refs = [], // containing elements with string-refs
  callbackRef1, // still the element. Assigned with the ref-callback (e) => { this.callBackRef1 = e }
  callbackRef2,
  callbackRef3
}
```

**Comment by yormi** [comment]
Ok another question guys ! Is it necessary to shallow render without owner and context ? If yes, a quick explaination would be nice :)

https://github.com/facebook/react/blob/master/src/test/ReactShallowRenderer.js#L61
https://github.com/facebook/react/blob/master/src/test/ReactShallowRenderer.js#L67

I don't get why and it would solve the problem I'm facing right now with the string refs. They currently throw when unmounting because they don't have an owner.

**Comment by yormi** [comment]
Nevermind that. Answer here: https://github.com/facebook/react/blob/master/src/test/__tests__/ReactTestUtils-test.js#L44

With an owner we can't assert the result with JSX

**Comment by yormi** [comment]
Took me a bit more time than expected...

Follow-up here:
https://github.com/facebook/react/pull/8311
