### ISSUE TITLE
[Feature Request] Add Error-shaped propType option?

### ISSUE THREAD

**Issue by fritx** [facebook/react#8286]
**Do you want to request a *feature* or report a *bug*?**

I request a feature.

**What is the current behavior?**

Currently, there is no Error-shaped propType option.
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**My minimal use case**

```js
class MyImage extends Component {
  async fetchUrl () {
    try {
      const src = await reqUrl(fid)
      this.setState({ src })
    } catch (error) {
      this.setState({ error })
      throw error
    }
  }

  render () {
    const { src, error } = this.state
    return <Image src={src} error={error}  />
  }
}

class Image extends Component {
  static propTypes = {
    src: PropTypes.string,
    error: PropTypes.error,   <--- my requested feature
  };

  render () {
    const { src, error } = this.props
    const _src = error ? errorSrc : src
    return <img src={_src} />
  }
}
```

**Comment by fritx** [comment]
I've changed to use `onError` prop to pass error bottom-up, instead of top-down,
and won't need this feature any more.  :joy:

**Comment by gaearon** [comment]
Please use PropTypes.instanceOf(Error).
