### ISSUE TITLE
Immutable HTML elements and react

### ISSUE THREAD

**Issue by ragebiswas** [facebook/react#8288]
Hi everyone! This is my first report here, please bear with me if I don't make much sense :-)

I am facing an issue with interoperability with web-components. I have to work with a proprietary library where the dom nodes (of the custom web-component element) are frozen (i.e. not extensible), and I get this error in console:

`ReactDOMComponentTree.js: Uncaught TypeError: Can't add property __reactInternalInstance$xxxx object is not extensible(…)`

Upon inspecting further, this seems to be thrown from the following snippet:

```javascript
/**
 * Populate `_hostNode` on the rendered host/text component with the given
 * DOM node. The passed `inst` can be a composite.
 */
function precacheNode(inst, node) {
  var hostInst = getRenderedHostOrTextFromComponent(inst);
  hostInst._hostNode = node;
  node[internalInstanceKey] = hostInst;
}
```

React seems to be adding a new property to a dom node (for precaching) - and that's where things fail. In case it helps, I've also pasted the entire stack trace below.

My question: is it valid for react to assume that a dom node is mutable? If not, can the precaching omit such nodes? I'm not able to attach a reproducible test case due to the proprietary nature of the custom webcomponent - and I don't seem to be able to reproduce the issue with my simple webcomponents. I can try again if that is really required, however!

Stacktrace:

```
precacheNode	@	ReactDOMComponentTree.js?1a2c:48
mountComponent	@	ReactDOMComponent.js?1302:517
mountComponent	@	ReactReconciler.js?6bfa:47
_updateRenderedComponent	@	ReactCompositeComponent.js?cd59:762
_performComponentUpdate	@	ReactCompositeComponent.js?cd59:721
updateComponent	@	ReactCompositeComponent.js?cd59:642
performUpdateIfNecessary	@	ReactCompositeComponent.js?cd59:558
performUpdateIfNecessary	@	ReactReconciler.js?6bfa:158
runBatchedUpdates	@	ReactUpdates.js?ce09:151
perform	@	Transaction.js?6dff:138
perform	@	Transaction.js?6dff:138
perform	@	ReactUpdates.js?ce09:90
flushBatchedUpdates	@	ReactUpdates.js?ce09:173
closeAll	@	Transaction.js?6dff:204
perform	@	Transaction.js?6dff:151
batchedUpdates	@	ReactDefaultBatchingStrategy.js?ef70:63
enqueueUpdate	@	ReactUpdates.js?ce09:201
enqueueUpdate	@	ReactUpdateQueue.js?fd2c:25
enqueueForceUpdate	@	ReactUpdateQueue.js?fd2c:158
ReactComponent.forceUpdate	@	ReactComponent.js?702a:85
forceUpdateIfPending	@	index.js?d5ed:28
traverseRenderedChildren	@	index.js?d5ed:6
(anonymous function)	@	index.js?d5ed:36
(anonymous function)	@	index.js?c80a:84
```

Do let me know if there's something obvious that I'm missing!

**Comment by Aweary** [comment]
I think it's generally a valid assumption that DOM nodes are both mutable and extensible, and React is certainly not alone when it comes to doing so. That said, extending nodes should be done with careful consideration and only when necessary. In this case, `internalInstanceKey` is used to associate DOM nodes with their internal instances. As far as I know this is required if we want to be able to get the closest instance for a given node.

**Comment by brigand** [comment]
It could fall back to using a Map if it's non-extensible, but that's more complexity and code. The performance cost would be negligible in the case where zero non-extensible dom elements exist.

**Comment by thecodejack** [comment]
Is there any workaround to handle this error?

**Comment by brigand** [comment]
@thecodejack it'd require changing react.

**Comment by ragebiswas** [comment]
Yeah we also ended up convincing the authors of the web-component to allow
mutability in this case.

**Comment by thecodejack** [comment]
ok. I also attached noop function to Object.freeze which was being used in web components. This handled the issue for now.

**Comment by gaearon** [comment]
I don’t think we’ll support immutable DOM nodes. Sometimes we just need to keep some state associated with them, and WeakMaps are not supported everywhere.
