### ISSUE TITLE
Expose renderSubtreeIntoContainer to React Native

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#8289]
We never built this for React Native but there are use cases for layers in React Native too.

Basically we need to port https://github.com/facebook/react/blob/ef99e7e096cb661de0e72f93a442fbfeaaa07b1c/src/renderers/dom/stack/client/ReactMount.js#L434-L543 to ReactNativeMount.

**Comment by spicyj** [comment]
I don't think we currently have a way to make a new container short of making a new root view in native land (which starts a new tree automatically).

**Comment by gaearon** [comment]
If there are specific use cases we can always expose `createPortal` there.
Just need to learn more about them.

**Comment by sebmarkbage** [comment]
I think we already expose Portals on React Native.

**Comment by gaearon** [comment]
Haha I didn’t realize. I wonder if anybody tried to use them yet.

**Comment by sophiebits** [comment]
I (still) don't think we currently have a way to make a new container short of making a new root view in native land (which starts a new tree automatically).

**Comment by sebmarkbage** [comment]
I think you can insert a root view manually and it register itself with the tag without it rendering into it. It does need to be in Native though. Which makes sense because you need to build some wrapper to manage where this gets inserted.
