### ISSUE TITLE
Negitive consequences of the licence

### ISSUE THREAD

**Issue by jhicken** [facebook/react#8307]
I have take this down I will re-post after some more chatter internally.

**Comment by gaearon** [comment]
>For some reason facebook decides that this companies product has infringed on there IP. The moment facebook decides to enter litigation with this company. The company no longer has a license to use react. 

I think this part is incorrect. The patent grant specifically mentions it doesn't terminate if Facebook sues for patents first:

https://code.facebook.com/pages/850928938376556

>Does the additional patent grant in the Facebook BSD+Patents license terminate if Facebook sues me for patent infringement first, and then I respond with a patent counterclaim against Facebook?

>No, unless your patent counterclaim is related to Facebook's software licensed under the Facebook BSD+Patents license.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
