### ISSUE TITLE
v15.4.0: ReactTestRenderer and ReactMount gone

### ISSUE THREAD

**Issue by alansouzati** [facebook/react#8312]
After updating to react 15.4.0 I'm facing issues with missing ReactTestRenderer and ReactMount.

I tried to look into the release notes, but I could not see anything regarding ReactTestRenderer being gone. I'm not calling `ReactMount` directly, I'm using `ReactDOM.render`.

Any ideas? If I don't change anything in my code and rollback to 15.3.2 everything works fine.

**Comment by RoccoC** [comment]
What version of `react-hot-loader` are you using (if at all)? I know v1.x called ReactMount directly, and updating to v ^3.0.0-beta fixed that issue for me.

**Comment by alansouzati** [comment]
Thanks @RoccoC I'm using v1.x. Let me test it out with v 3. 👍

**Comment by gaearon** [comment]
ReactTestRenderer is not gone. It's on npm as `react-test-renderer` package. Importing it from `react/lib` is not officially supported, that was just an implementation detail.

ReactMount has moved but it's internal module. It will be removed eventually. Don't rely on tools relying on internal modules. RHL 1.x has not been maintained or supported for a long time by now.

**Comment by alansouzati** [comment]
Thanks for clarifying. I got the `react/lib/react-test-renderer` from the Jest documentation. I just checked and the documentation is up to date now.

I will make sure to update it in my code as well.
