### ISSUE TITLE
react-addons-test-utils 15.4.0 now depends on react-dom instead of react

### ISSUE THREAD

**Issue by vvo** [facebook/react#8314]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
react-addons-test-utils 15.4.0 has a peer dependency on `react-dom` and uses it, 15.3.0 had a peer dependency on `react`.

In 15.3.0, react-addons-test-utils/index.js:
```js
module.exports = require('react/lib/ReactTestUtils');
```

In 15.4.0, react-addons-test-utils/index.js:
```js
module.exports = require('react-dom/lib/ReactTestUtils');
```

If your code contains:

```js
import {isElement} from 'react-addons-test-utils';
```

It will fail given your current dependencies.

So if you did not have react-dom in your dependencies, because previously it was not needed, now it is and it will break your code.

Is this a breaking change?

This leads to errors like:

`Module not found: Error: Can't resolve 'react-dom/lib/ReactTestUtils' ` or `Cannot find module 'react-dom/lib/ReactTestUtils'`

**Current workaround**

```sh
npm install react-dom --save[-dev]
```

**Comment by laughnan** [comment]
seeing this as well.

**Comment by matm** [comment]
Seriously, that's a breaking change that can take CI systems down. 

Is it documented somewhere?

**Comment by flaviusone** [comment]
> that can take CI systems down

It did. 💀

**Comment by vvo** [comment]
I think we have all various experiences with this bug, let's keep it constructive and see if we can do something about it so that we focus on positive not negative comments.

**Comment by gaearon** [comment]
That's indeed frustrating but this ship has sailed now. Sorry we screwed it up.

We released 15.4.0 RC a month ago and publicly asked for feedback:

* https://github.com/facebook/react/issues/7770#issuecomment-253899837
* https://twitter.com/sebmarkbage/status/794600168016384001
* https://twitter.com/dan_abramov/status/787014238405533696

Unfortunately nobody reported this issue even as it was discovered in https://github.com/algolia/react-element-to-jsx-string/issues/56 before the stable release.

Sorry for breaking your CIs, hopefully the fix wasn't too complex.

**Comment by junibrosas** [comment]
Im now experiencing while integrating Mocha + Typescript. :(

**Comment by gaearon** [comment]
All you need to do is to add the dependency on `react-dom`. Unless you have some new information about this issue I think further “me too” comments won’t be helpful. Again, sorry about this!

**Comment by chaintng** [comment]
A work around to make CI work,
make sure that your app contains follow dependencies all in the same version
- react-addons-test-utils
- react
- react-dom

**Comment by axelson** [comment]
I got bit by react-addons-test-utils 15.4.1 not being compatible with react 15.2.1.  Makes me wish that npm shrinkwrapped dev dependencies as well. Is backwards compatibility of major versions a goal for react-addons-test-utils?

**Comment by gaearon** [comment]
React does not currently support using different versions of its packages in one project. We are working to decouple them to the point it is possible but this will take us a while.

**Comment by zhoulujun** [comment]
https://www.zhoulujun.cn/html/tools/webpack/2016_0217_6459.html
  "react": "^16.7.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.7.0",
react-dom 16 根本就没有lib/ReactTestUtils 这玩意儿。
于是修改，react-addons-test-utils index 文件,坑还是未填好
//module.exports = require('react-dom/lib/ReactTestUtils');
module.exports = require('react-dom/test-utils');
最好还是降级到15.x ，期待官方修复！
