### ISSUE TITLE
React DOM Server shouldn't contain a separate copy of the reconciler

### ISSUE THREAD

**Issue by arendjr** [facebook/react#8316]
**Do you want to request a *feature* or report a *bug*?**

I don't know if it's technically a bug, but to me it's certainly a regression because it inflates the size of the react-dom-server package when used on the client.

**What is the current behavior?**

Might be best to just quote the release announcement for React 15.4:

> Another thing to watch out for is that React DOM Server is now about the same size as React DOM since it contains its own copy of the React reconciler. We don't recommend using React DOM Server on the client in most cases.

**What is the expected behavior?**

Just like React 15.3 and below, only one copy of the reconciler should be needed when using both React DOM and React DOM Server.

**What use case do you have for using React DOM Server on the client?**

For example, [Selectivity.js](https://arendjr.github.io/selectivity/) allows developers to specify custom templates to customize the rendering of the UI component. But because Selectivity is at its core a non-React library it accepts templates as either strings or functions returning strings that are manually inserted into the DOM. Now, Selectivity does have a React API which also includes a plugin that wraps the templates so they can be specified as functions returning React elements (see the source code for details: https://github.com/arendjr/selectivity/blob/master/src/plugins/react/templates.js). This plugin relies on react-dom-server to transform the React elements to a string understood by Selectivity core.

While the above example is rather specific to a single library, I do think the use case of specifying templates in non-React libraries through JSX might be more widely applicable.

**Comment by gaearon** [comment]
>the use case of specifying templates in non-React libraries through JSX might be more widely applicable

If those templates are known statically or on the server you could turn them to HTML there. 

If not, you could render DOM into an empty element and then read its inner HTML.

**Comment by jasondonnette** [comment]
I have a different use-case where I am using renderToString to save SVG's client-side.

But I suppose using inner HTML of the dom element would be sufficient as well.

**Comment by arendjr** [comment]
I guess I'll update Selectivity to also render into an out-of-DOM `<div>` then and use its `innerHTML`...

**Comment by gaearon** [comment]
For what it's worth even if this isn't technically the case now, we are thinking about separating DOM renderer from server renderer anyway in the future.

**Comment by arendjr** [comment]
So you're saying we shouldn't rely on DOM Server to be able to share code with React DOM anyway, right?

I will close this issue then, as I agree it seems using DOM Server on the client is a dead end anyway. At least Selectivity is patched now to no longer rely on it :)

**Comment by gaearon** [comment]
Yea, this is about right. Separating them is useful both for speeding up server rendering (so that it skips the unnecessary client-only code paths) and for making client rendering code thinner.
