### ISSUE TITLE
Change bin/jsx default file extension to .jsx

### ISSUE THREAD

**Issue by andrewdavey** [facebook/react#832]
Currently, bin/jsx defaults to looking for `.js` files to which contain jsx content to compile. Whilst it's possible to override this using `jsx -x jsx ...`, I think that since jsx content is not valid JavaScript, using the `.js` extension by default isn't ideal.

Could we change `bin/jsx` to look for `.jsx` files instead?

Another advantage to this is that the generated `.js` files can live the same directory as the source `.jsx`. This simplifies the generation of source maps files as well, because the path to the `.jsx` is trivially relative to the generated `.js`

For example, given `foo.jsx`, running `jsx . .` would result in:

```
$ ls
foo.jsx
foo.js
foo.js.map
```

**Comment by koistya** [comment]
As far as I understand, if you choose to use `.jsx` extension for your React components, you will be forced to explicitly specify this extension in every `require()` statement throughout your code base (e.g. `require('../TextEditor.jsx')` instead of just `require('../TextEditor')`) in order to be able to navigate between files with `CTR+Click`. That's the primary reason why `.js` is currently used by default in [React.js Starter Kit](https://github.com/kriasoft/react-starter-kit).

**Comment by gaearon** [comment]
@koistya This depends on the bundler you're using. In Webpack, extensions can be [configured explicitly in `resolve.extensions`](https://github.com/gaearon/react-hot-boilerplate/blob/master/webpack.config.js#L20); pretty sure Browserify allows something similar.

**Comment by koistya** [comment]
@gaearon regardless of which bunder you're using and its configuration, the `CTR+Click` feature won't work in your code editor or IDE if you omit `.jsx` extension in `require(..)` statements. Do you use an editor that picks up these settings from your bundler's configuration?

**Comment by gaearon** [comment]
Oh, I get your point now. I don't really use an IDE.

Regardless, I think such issues should be filed against IDEs themselves. If you use JSX, IDE already has to have some knowledge about it (e.g. how to parse it), so it's not too much to expect it to also follow JSX `require`s IMO.

**Comment by jokeyrhyme** [comment]
Feels suspiciously like the user agent string conundrum. JSX is distinctly not JavaScript, but we put it in `*.js` files anyway because the tools we use don't conveniently look at `*.jsx`. We propagate a lie for convenience.

**Comment by brigand** [comment]
>  though it'll break some people's current expectations

It could give an error when no files are found, and the extension isn't explicitly set.  I say error, as in non-zero exit code, so any CI servers that install the latest version implicitly will fail.

```
JSX found 0 .jsx files.

The default extension was changed from .jsx to .js.  To restore the old behavior add the following to your command: -x js
```

**Comment by rickbeerendonk** [comment]
Related: https://github.com/facebook/react/issues/2943

**Comment by sdiaz** [comment]
IDEs like Webstorm recognize JSX inside a `.js`, just configure `JSX Harmony` when the IDE detects JSX and prompt to use it instead of `ECMAScript 5.1`

**Comment by zpao** [comment]
We're deprecating react-tools so closing out.
