### ISSUE TITLE
Delete all examples except "fiber" & "basic-jsx"

### ISSUE THREAD

**Issue by yavorsky** [facebook/react#8321]
Many people to understand something new are reading docs/articles, but good practice is to explore examples in parallel.

Current examples' issues:
 - Depends on Babel 5.8.
 - `<script type="text/babel">` - deprecated.
 - `setInterval(render, 50)` - to wait dom.
 - Outdated libraries (like webcomponentsjs 0.7).
 - Generally, you must 'parse' in mind the whole `html` file to understand how small Component works.

For me, possible solution could be rewriting examples as separate modules with own `package.json`, README, etc., with simple `npm start`, `npm build` scripts.

If it can be useful, I could make a PR in a few days.

**Comment by gaearon** [comment]
I think the vast majority of the content in `examples` folder it either useless or outdated.
I'd replace it completely with something more useful but I don't have time to work on this.
Assigning to @lacker to figure this out.

**Comment by lacker** [comment]
Err yeah I did not realize this "examples" directory existed. We have a whole lot of examples inline in the documentation now. Like isn't every codepen basically an example? I looked through them but they basically all seem like they are not valuable, with the exception of the "fiber" example which seems to not be so much an example and more of a place where people can stash code for this small one-off tool, which is fine I suppose. So my proposal is to remove all of them except Fiber. Curious if anyone objects, perhaps for the jquery-specific or web-components-specific examples. IMO if there is a better example of something elsewhere on the internet, there's no value in us providing a worse one, and pretty much everything falls into that category now.

**Comment by gaearon** [comment]
I'm fine with removing all except basic-jsx and Fiber which are useful for our own testing. But they need to be renamed to "fixtures" or something so that people don't look there.

**Comment by yavorsky** [comment]
The only feature of keeping examples in project's directory is sandbox purposes. But for now, there are many different build setups (like create-react-app) to try React in the fastest way and the most comfortable environment.
Really reasonable idea to remove it.

**Comment by gaearon** [comment]
We got rid of them.
