### ISSUE TITLE
v15.4.0 hard dependency on React-hot-loader > v.1.3.0

### ISSUE THREAD

**Issue by bencripps** [facebook/react#8330]
We have tried to uprev our version of React with every major release, since they very often help us with perf or core issues that we should be addressing, so we updated to 15.4.0 yesterday.

However, it seems as though there is a breaking change in 15.4.0 when it comes to our development process. Although our apps build successfully, they break when we try to dev using our webpack/hot-reloading process. 

Wepback spits out the following error, for each file creating a React Component.

````
ERROR in ./packages/ux/src/field/date/components/date/picker/Month.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /Users/ben_cripps/Documents/Dev/mozu/mozu-adminui/packages/ux/src/field/date/components/date/picker
 @ ./packages/ux/src/field/date/components/date/picker/Month.js 1:332-363
````

I believe that upgrading to the newest [prerelease](https://github.com/gaearon/react-hot-loader/releases/tag/v3.0.0-beta.6) of react-hot-loader would completely fix this issue, but I'm not sure how we should proceed since the documentation points out that v3.0.0-beta.6 is fairly experimental.

As of now, I think we are going to stay on React v15.3.2 since it doesn't require us to update our hot-reloader, and how we've configured webpack/babel.

I assume this isn't an oversight, and the removal of many of the lib files is a the correct path, I'm just wondering if there is another work around other than switching to the prerelease for our hot-reloader.

Thanks!

**Comment by gaearon** [comment]
Please refer to this thread: https://github.com/gaearon/react-hot-loader/issues/417.
The 1.x branch has been unmaintained for many months so 3.x beta is more "stable" than it already.
