### ISSUE TITLE
Unable to find element with ID 'undefined'

### ISSUE THREAD

**Issue by artursgirons** [facebook/react#8338]
React@15.4.0 (on 15.3.2 all is well)
This invariant "Unable to find element with ID 'undefined'" error happens when specific (yet not special in any kind) component update is triggered from `callback` in `ReactDOM.render(<element>, <domElement>, <callback>)`. Using MobX for state management. and latest 2nd Webpack.
This I guess doesn't qualify as proper issue report, as I could localize issue to specific component, which when removed solves this. And there is completely nothing special about this component. All is working in 15.3.2.

Sidenote, app is rendered on server successfully and when crash happens on client then... when I move cursor over that particular component after this crash - error is being constantly console.log'ed. But when I move cursor outside, nothing gets logged. And I'm not attaching any listeners for cursor movements.

**Comment by Aweary** [comment]
@artursgirons can you share a test case reproducing the issue?

**Comment by artursgirons** [comment]
@Aweary, on a tight schedule.. But if no one else will experience this nor have some reproducible-sharable bits, I'll try to.. For time being I've moved back to v15.3.2.

**Comment by gaearon** [comment]
We would definitely need a reproducing example to investigate.

**Comment by artursgirons** [comment]
Sorry :( related to this - https://github.com/mobxjs/mobx-react/issues/96
