### ISSUE TITLE
Error: Cannot find module 'react/lib/ReactPerf'

### ISSUE THREAD

**Issue by joemckie** [facebook/react#8342]
Bug report:

**What is the current behavior?**

Importing `react-addons-perf` throws the following error:

```
Error: Cannot find module 'react/lib/ReactPerf'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../node_modules/react-addons-perf/index.js:1:18)
```

I checked, and the file doesn't exist in the `lib` directory.

**What is the expected behavior?**

It shouldn't throw an error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The latest version I was using was `15.2.1`. This is an issue for me after updating to `15.4.0`, but may have been introduced between the two.

**Comment by goto-bus-stop** [comment]
Did you update react-addons-perf to 15.4.0 as well? ReactPerf was moved from `react/lib/ReactPerf` to `react-dom/lib/ReactPerf` in 15.4.0.

**Comment by joemckie** [comment]
Weird. It's actually on an old version, but `yarn outdated` isn't showing it as needing a bump. I'll try that now!

**Comment by gaearon** [comment]
Please keep both version in sync, that's what's causing the issue.

**Comment by joemckie** [comment]
Thanks guys - just in case anyone else comes across this issue, it's because `react-native-mock` is specifically demanding `15.1.0` right now.

I've [raised an issue](https://github.com/RealOrangeOne/react-native-mock/issues/111) over in their repo.

**Comment by gaearon** [comment]
I'd recommend using Jest for testing React Native instead. That's what we use at FB, and we maintain it.

**Comment by joemckie** [comment]
@gaearon cheers! I personally dislike Jest but thanks for the advice. Thinking of moving to TAP at some point so I don't think Jest would be a step in the right direction for me.

**Comment by gaearon** [comment]
Just FYI, if you last tried Jest a year ago or more you should give it another try. It has changed a lot, and the only thing common with the previous project is its name.

**Comment by joemckie** [comment]
It was a while ago - maybe about six months I think? I'll try it out again soon, I'm trying to move away from tools that do too much as it can be really difficult to decouple the dependency later on down the line.

**Comment by vinnymac** [comment]
For anyone who comes across this trying to update. Some update tools such as `npm-check` and `yarn update` are reporting 15.4.1 as the latest version of `react-addons-perf`. This in fact does not exist right now.

```
├── react-addons-perf@15.4.1  invalid
```

Try explicitly installing `react-addons-perf@15.4.0` instead. It works fine with 15.4.1 versions of `react` and `react-dom`.

```
success Saved lockfile.
success Saved 1 new dependencies.
├─ react-addons-perf@15.4.0
```

**Comment by gaearon** [comment]
This is weird. Are you using a custom npm registry?

I checked, and it's there:

```
npm dist-tag ls react-addons-perf
latest: 15.4.1
```

**Comment by vinnymac** [comment]
@gaearon I am not using a custom npm registry. 

It may have something to do with the fact that my `react-addons-perf` package was installed with an exact version of `15.3.2`, when trying to update to the exact version of `15.4.1` the auto updater failed.

However by installing the latest version it used `^15.4.1` instead, and is now working just fine. I just did `yarn add react-addons-perf --dev` and everything is working now. I am not 100% certain why I had gotten the invalid package upon using the updater. Perhaps a false positive on a dependency conflict? I wish I had more information to share.

In any case, it was easy to resolve and others should be able to find this discussion if they really even need it. Future readers please ignore my comment above.
