### ISSUE TITLE
React unable to fully removing select in mobile browsers

### ISSUE THREAD

**Issue by wlingke** [facebook/react#8357]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Please refer to this fiddle: https://jsfiddle.net/qyc3e774/

The goal is that when the select does an "onChange" event, the select is removed. However an unexpected thing occurs in mobile (tested in latest iOS on latest mobile chrome and safari).

When you select a value, the select is replaced by a standard button that does nothing. But once you tap on the button, the browser brings up the select menu again even though there is no select element there. If you look into the DOM, there is no select element.

**What is the expected behavior?**
When the select is removed via onChange and the button shows up, tapping the button should do nothing.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.0.
Browsers: latest mobile chrome & safari
OS: latest iOS

**Comment by yaycmyk** [comment]
It works fine for me in latest iOS Safari.

**Comment by wlingke** [comment]
@yaycmyk did you select a value and then tap the button on a phone? It should bring back up the native browser's selector.

**Comment by wlingke** [comment]
@yaycmyk I ended up just figuring it out. It is because when the select is removed from the DOM, `focus` is still on it. Therefore when you tap on a button, it brings back up the menu.

Does it make sense to blur selects when they are removed from the DOM?

**Comment by yaycmyk** [comment]
@wlingke I'm not seeing that behavior. What I do see is when I tap one of the options, the select is switched with the button but the selection popover remains. I can tap back to the original option, but nothing happens. Looks more like a WebKit bug than something React should be concerned with, IMO.

**Comment by wlingke** [comment]
@yaycmyk Yea that is one manifestation of the behavior. It seems like its because the component still has focus. If you blur it in the `onChange` this removes the problem.

I am not sure if this is a webkit bug... it kind of feels like React should be cleaning this up by blurring the component if it is removing it from the dom?

**Comment by yaycmyk** [comment]
I don't believe it still has focus. See this: https://jsfiddle.net/qyc3e774/2/

It's a WebKit bug.

**Comment by wlingke** [comment]
Hmm..  look at this: https://jsfiddle.net/p96p1ng4/6/

It has focus directly after the render,

**Comment by yaycmyk** [comment]
The DOM replacement hasn't happened yet in your code. See this example: https://jsfiddle.net/p96p1ng4/7/

render() is where the VDOM is generated, there's no guarantee the replacement has actually happened yet. That's why it's important to use the React lifecycle methods to test at the appropriate times.

**Comment by wlingke** [comment]
Fair enough. Can't argue with that.

The only thing I know that solves the unexpected behavior is to "blur" the select before it unmounts. 
https://jsfiddle.net/p96p1ng4/8/ blurs it before unmount and has no unexpected behaviors
https://jsfiddle.net/p96p1ng4/9/ does nothing before unmount and has unexpected behaviors

That is why I think something related to the focus of the element is causing issues.

**Comment by gaearon** [comment]
I'm having a hard time convincing myself this has something to do with React. I would say it's likely a browser issue, and encourage you to recreate it in vanilla JS to test it. (If you still experience it.)

If you're convinced it's React-only, please file a new issue with both test cases so we can verify it.
