### ISSUE TITLE
Production mode results in ever-changing generated keys

### ISSUE THREAD

**Issue by jimkyndemeyer** [facebook/react#8367]
We're seeing a mysterious behaviour with regards to generated keys. But **only** in production mode.

Note the keys of the "RelayAdHocQuery" and "TabPanel" components at the bottom:

![react-keys-production](https://cloud.githubusercontent.com/assets/15837712/20484281/bd65c5ce-aff6-11e6-99a3-bd30c3424a0b.gif)

Also note that the parent hierarchy doesn't change. On each forced update of a parent, the keys in question simply append ".$", so we're loosing state. Everything works as expected in development mode, where the component instances are reused based on the re-use of keys.

Unfortunately, despite our best efforts, we've been unable to isolate exactly why this happens, ie. as a simply reproducible test case. Maybe someone with knowledge of the key generating algorithms can points us towards a solution.

React 15.3.2. Seeing this in all evergreen browsers.

**Comment by syranide** [comment]
> Also note that the parent hierarchy doesn't change. On each forced update of a parent, the keys in question simply append ".$", so we're loosing state.

It seems that on every update you are nesting your children one level deeper every time, with an empty string key. That's why you see the key increasing every time. I.e. you're doing the equivalent of `values = [values]`, so each time it gets deeper and deeper and thus increasing/changing the key. 

I doubt this is a problem with React. It seems far more likely that you're doing something unintentional or that it's a bug with Relay (or whatever else you're using).´

Anyway, debug and log the actual children value being provided to the highlighted div in your GIF and you'll probably find that there's something strange going on with it.

**Comment by jimkyndemeyer** [comment]
Thanks for the quick response.

Two things. We're only seeing this in production mode, so our React component code is exactly the same for prod/dev. We've specifically isolated this issue by only swapping out the React dev bundle with a production mode bundle.

Also, wouldn't the additional nesting be shown in the React dev tools?

**Comment by gaearon** [comment]
It it's nesting of arrays of elements it wouldn't be shown. For example `<div>Hi</div>`, `<div>{['Hi']}</div>`, `<div>{[['Hi']]}</div>` would look the same in DevTools.

**Comment by gaearon** [comment]
Please provide the reproducing code that behaves differently in development and production.

**Comment by jimkyndemeyer** [comment]
Thanks @gaearon 

We tried but couldn't isolate this in a test case. But I think the info about nesting as arrays is enough for us to investigate further.

I close this for now.

**Comment by jimkyndemeyer** [comment]
If others encounter this issue, it was indeed a "wrapping" issue that appears to be caused by https://github.com/gajus/react-css-modules/issues/112

The difference between dev and production mode is the use of Object.freeze on elements which affects the transformation that `@CSSModules`performs on the elements tree.

**Comment by syranide** [comment]
But I'm curious though, `Object.freeze` as part of React codebase or yours? Because React should have the same behavior in both dev and prod, and should freeze in both if it does at all.

**Comment by jimkyndemeyer** [comment]
I'm basing it on the top comment at https://github.com/gajus/react-css-modules/issues/112#issue-142115613

I'm not familiar with React internals, but It could make sense to skip Object.freeze in production due to improved performance.

**Comment by syranide** [comment]
Oh yeah, interesting. It seems React only uses freeze in DEV yes.

**Comment by gaearon** [comment]
I think that way that project operates on React elements is not a supported way of using React. React elements should be treated as immutable.

It is also rather inefficient. It seems to me that if you want to use CSS modules, you should either just embrace the fact that class names are generated and interpolate them, or write a *static* transform that will rewrite the class names during compilation.
