### ISSUE TITLE
ReactCSSTransitionsGroup doesn't execute enter animation properly in some cases

### ISSUE THREAD

**Issue by skhavari** [facebook/react#8369]
Trying to build a nifty animation for launching dialogs but running into a snag with ReactCSSTransitionsGroup. The goal is to ensure that the dialog looks like its zooming out of the button that launched it. [Here is a sample that shows the working demo and unexpected behavior](https://jsfiddle.net/bqbj2z24/20/).

The unexpected behavior exhibited is the following

1. Click on the first button (either one). Works perfectly.
1. Click on the second button, the enter animation does not play.
1. Doesn't matter how many buttons you add, only the first works as expected. All additional buttons won't show the enter animation properly.
1. The leave animation works for all buttons.

I've reproduced this with glamor and aphrodite so feels good to rule out the CSS library as the culprit.  

Trying to figure out if there's something wrong with the code, unintended usage of ReactCSSTransitionsGroup or a bug with it.

Thanks!

also posted on [SO](http://stackoverflow.com/questions/40728125/reactcsstransitionsgroup-with-dynamic-styles-doesnt-execute-enter-animation-pro)

**Comment by gaearon** [comment]
cc @jquense @taion

**Comment by skhavari** [comment]
feel free to close this one - its my bug.  For reference,  the confusion on my part is that both * & *-active styles are applied, not one or the other.  re-writing the css rules fixes things.
