### ISSUE TITLE
ResponderEventPlugin regression in React 15.4.0

### ISSUE THREAD

**Issue by necolas** [facebook/react#8370]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

The `ResponderEventPlugin` no longer recognizes start DOM events.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

The `EventPluginUtils.isStartish` helper only checks for mouse/touch start events. [In this section of code](https://github.com/facebook/react/blob/2f8d1689db30a769188f08b79480a1301b736d6f/src/renderers/shared/shared/event/eventPlugins/ResponderEventPlugin.js#L318-L325), the `topLevelType` used to be only `topMouseDown` or `topTouchStart` in React 15.3, but is now `topClick` in React 15.4.0. This means the event plugin can no longer recognize start events.

This PR exposes the issue in `react-native-web`, which uses the `ResponderEventPlugin`: https://github.com/necolas/react-native-web/pull/255

**What is the expected behavior?**

The same behaviour as exhibited with React 15.3.2.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Works in React 15.3.2. Doesn't work in React 15.4.0.

**Comment by spicyj** [comment]
If you add a React DOM node to your tree with `onMouseDown={function() {}}`, does that affect the behavior?

**Comment by necolas** [comment]
Yes it does! It appears that all the Touchable examples work (mouse and touch) if the page also includes:

```js
<div onMouseDown={()=>{}} onMouseUp={()=>{}} onTouchStart={()=>{}} onTouchEnd={()=>{}} />
```

**Comment by remon-georgy** [comment]
I'm wondering how can we move this forward. Any directions to help a capable developer try to submit a pull request?

**Comment by gaearon** [comment]
If you're looking for an intro to the event system, this might be helpful. https://www.youtube.com/watch?v=dRo_egw7tBc

**Comment by spicyj** [comment]
We need to add dependencies to these event types:

https://github.com/facebook/react/blob/0f34bdc622cc79835b599d2f1d8b0889b138e579/src/renderers/shared/shared/event/eventPlugins/ResponderEventPlugin.js#L59

It is tricky though because the plugin is shared between web and native and they have different event names. It may work to just always include the mouse events but I'm not sure if that causes problems in RN.

**Comment by necolas** [comment]
Which dependencies exactly? I've set mouse dependencies in RNW but that stopped working with React@15.4 - https://github.com/necolas/react-native-web/blob/f8f28980957ecb46393981d9b4bdfc820da06c26/src/modules/injectResponderEventPlugin.js

**Comment by spicyj** [comment]
Oh, I would have thought that works. This code should run for your responder event handler and cause those deps to be listened to:

https://github.com/facebook/react/blob/v15.4.0/src/renderers/dom/shared/ReactDOMComponent.js#L221

**Comment by necolas** [comment]
The problem was that the `EventConstants` module no longer exports a key mirror – all the event type values are now `null` after [this patch](https://github.com/facebook/react/commit/2f9a9dc4c56c1caee250626c54c587c5f233fcab). Resolved the issue in RNW here: https://github.com/necolas/react-native-web/commit/44ecbc072e9bb23151f33c56c021c8caaae1e227#diff-fecd5b3cfaeb4f62d70f4219e850f039
