### ISSUE TITLE
className named 'active' invaild when rerender

### ISSUE THREAD

**Issue by weishiji** [facebook/react#8376]
![my_favorites](https://cloud.githubusercontent.com/assets/3954134/20518802/6bd56c56-b0db-11e6-89cc-0418ffb87cd8.png)
![image](https://cloud.githubusercontent.com/assets/3954134/20518823/853879cc-b0db-11e6-816f-033989193147.png)

**Comment by ilanus** [comment]
What's the problem? can you attach your Component code?

**Comment by gaearon** [comment]
It's hard to tell something without an example.
