### ISSUE TITLE
document.caretPositionFromPoint / caretRangeFromPoint do not typecheck

### ISSUE THREAD

**Issue by meleyal** [facebook/react#8377]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Neither [`document.caretPositionFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint) (standards track) nor [`document.caretRangeFromPoint()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint) (old syntax) typecheck, producing the following flow error:

```
caretPos = document.caretPositionFromPoint(x, y)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `caretPositionFromPoint`. Function cannot be called on
caretPos = document.caretPositionFromPoint(x, y)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `caretPositionFromPoint` of unknown type
```

**Which versions of React, and which browser / OS are affected by this issue?**
React 15.4.0
Flow 0.33.0

**Comment by Aweary** [comment]
@meleyal thanks for the issue. React doesn't have any part in type checking your application. Flow maintains [type declarations for the DOM](https://github.com/facebook/flow/blob/master/lib/dom.js)   internally. You can either just re-declare the `Document` type with the method(s) you're using or see if the flow team are open to adding it to their DOM lib.
