### ISSUE TITLE
Documentation: missing mention to refs

### ISSUE THREAD

**Issue by samuele-artuso** [facebook/react#8382]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

The [Thinking in React document](https://facebook.github.io/react/docs/thinking-in-react.html) in the Quickstart section of the documentation contains some code that uses refs but refs are not mentioned in the text.

Refs are used in the JS code in [this pen](http://codepen.io/snakajima/pen/JbYQvL?editors=0010#0) at lines 71 and 78.

**What is the expected behavior?**

Refs should be explained in Thinking in React or in an earlier section of the Quickstart section of the documentation so that the reader is able to follow along.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v15.4.0. The issue is live at [this URL](https://facebook.github.io/react/docs/thinking-in-react.html).

**Comment by gaearon** [comment]
Good point.

**Comment by lacker** [comment]
Maybe just a link from right around the code that first uses refs, pointing to the document that explains them?

**Comment by hanumanthan** [comment]
I dont find this issue in the current docs. If this is still an issue, would like to work on it else can we close this ? @samuele-artuso @lacker

**Comment by gaearon** [comment]
This was fixed indeed.
