### ISSUE TITLE
FaceBook

### ISSUE THREAD

**Issue by am3crt** [facebook/react#8393]
I have notice on FaceBook services in nearest time that when you open you account on mobile phone from safari and I tried to see my message they transfer me to install messenger app. Also i notice sometime the messages did come in inbox message it come to different messages like filters request and archive message.

**Comment by gaearon** [comment]
Hi!

This is an issue tracker for React, a JavaScript library developed and used by Facebook.

Unfortunately we can't help you with Facebook products here so you should use the appropriate venues for reporting issues such as [this](https://facebook.com/help/326603310765065?helpref=faq_content).
