### ISSUE TITLE
React DevTools Download should not appear in chrome-extension://

### ISSUE THREAD

**Issue by alexlur** [facebook/react#8409]
This is a bug report.

**Expected Behavior**
React should not suggest me to download the DevTools extension in a `chrome-extension://` page, because the extension has no permission to inject the devtool.

**Actual Behavior**
`Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools`

**Reproducing**

1. Create a Chrome extension with an `option` or `popup` page that uses React
2. Load the extension to Chrome and open up that page.
3. Observe console.

**Version**
Google Chrome 56.0.2924.3
React 15.4.0

**Comment by gaearon** [comment]
How can we detect this?

**Comment by alexlur** [comment]
The intuitive way is to check `location.protocol`.

**Comment by gaearon** [comment]
Thanks for the suggestion. Will be fixed in https://github.com/facebook/react/pull/10359 for React 16.
