### ISSUE TITLE
className doesn't work with `is` attribute is present

### ISSUE THREAD

**Issue by yordis** [facebook/react#8419]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When I pass `is` attribute the `className` don't work. It's output `classname` instead of `class` in the DOM.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

Demo: https://jsfiddle.net/69z2wepo/63313/

**What is the expected behavior?**

Should render `class` instead of `classname`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"classnames": "^2.2.5",
"react": "^15.4.1",
"react-dom": "^15.4.1"
```

**Comment by gaearon** [comment]
`is` is a special DOM attribute opting you into using [web components](https://facebook.github.io/react/docs/web-components.html).

The documentation page mentions the issue:

>One common confusion is that Web Components use "class" instead of "className".

The issue is discussed in detail in #4933 so I will refer you to that discussion.
I hope this helps!
