### ISSUE TITLE
issue collaboration with react and react-dom

### ISSUE THREAD

**Issue by N4G1B4T0R** [facebook/react#8429]
**Do you want to request a *feature* or report a *bug*?**
Yes, i wanna report a bug.
**What is the current behavior?**

When u install in react and react-dom (last version) on intellij(window 10x64).
npm i react react-dom

In node_modules>react-dom>index.js we found file:

module.exports = require('react/lib/ReactDOM');

but in node_modules>react/lib/ReactDOM we havent got this file. There is only node_modules>react/lib/ReactDOMFactory

If we wont to use react-dom 

 import ReactDOM from 'react-dom';

 we will find this error

ERROR in ./~/react-dom/index.js
Module not found: Error: Cannot resolve 'file' or 'directory'

But if u install   "react": "^0.14.6",  "react-dom": "^0.14.6" we will havent got such problems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
You did not install the latest version of `react-dom`:

https://npmcdn.com/react-dom@15.4.1

As you can see the line is different there. Try setting both to `^15.4.1` and if the problem persists, try deleting node_modules and clearing npm cache.

**Comment by DanCiobanu** [comment]
@gaearon thank you, worked perfectly!
