### ISSUE TITLE
Consider exposing ReactElement factory function

### ISSUE THREAD

**Issue by thheller** [facebook/react#8431]
Currently React exposes `React.createElement(type, config, children)` [1] to the outside world and internally calls the `ReactElement(type, key, ref, self, source, owner, props)` [2] function to create the actual Element instance.

`React.createElement` performs a copy of `config` to create `props` and extract `key` and `ref`. 

In the ClojureScript world many libraries wrap React to provide a more cljs-idiomatic interface using CLJS persistent maps for props. The "hiccup"-syntax is very popular and convenient.

```clojure
[:div {:key "my-key" :ref my-ref-fn :other "props"}
  [:h1 "text]]
```

While this is far from ideal since we first allocate the CLJS data structures in addition to just `ReactElement`s it is particular inconvenient that we convert the props data once and React does again. It would safe a lot of overhead if you could just call `ReactElement` directly saving a whole lot of work.

`React.createElementRaw(type, key, ref, props)` would be nice (as the others would be `null` anyways) or maybe under a more obscure name (to discourage use). It is fine if this is marked experimental and not otherwise officially supported. 

Happy to create a matching PR if you folks agree to expose this somewhere.

[1] https://github.com/facebook/react/blob/6810627a91f2020caee7fecf21580187dc6ef0fc/src/isomorphic/classic/element/ReactElement.js#L183-L265
[2] https://github.com/facebook/react/blob/6810627a91f2020caee7fecf21580187dc6ef0fc/src/isomorphic/classic/element/ReactElement.js#L117

**Comment by gaearon** [comment]
If you're only optimizing it in production, would it make sense to skip React altogether and generate plain objects like Babel does [with this plugin](https://babeljs.io/docs/plugins/transform-react-inline-elements/)? See also #3228.

**Comment by thheller** [comment]
Oh and `ReactCurrentOwner.current` is not available when creating the element manually. Not sure how relevant that is, seems to be required for refs?

**Comment by gaearon** [comment]
It's only required for string refs, and those will eventually get deprecated anyway.

I encourage you to just generate those objects directly.
