### ISSUE TITLE
When developing packages with `npm link`, invalid "manually calling a React.PropTypes" warnings are logged

### ISSUE THREAD

**Issue by wesleytodd** [facebook/react#8445]
**Do you want to request a *feature* or report a *bug*?**

both?

**What is the current behavior?**

When developing a react component as a package, it is common practice to `npm link` your local copy into a project.  For this to work you need a copy of react installed in both directores, otherwise node and browserify (haven't tested with webkit) are not able to find it.  This results in a ton of warnings for "manually calling a React.PropTypes validation function".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

I am assuming it means "you have two copies of react on the page".  But preferably there should be first class support for developers working in the methodology.  Barring the ability to test for this condition directly, it would be nice to disable warnings in some fashion.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Currently testing with react 15.3.2

**Comment by gaearon** [comment]
I’m not sure why this would happen if versions match. However using multiple Reacts isn't supported anyway. Could you not `npm link` React back instead?

e.g.

```
cd my-app
npm link ../my-component

cd ../my-component
npm link ../my-app/node_modules/react
npm link ../my-app/node_modules/react-dom
```

This way you'll be using only one copy (the one in your app).

**Comment by wesleytodd** [comment]
The versions do match, I was VERY sure to check that before posting here :)

And I totally understand not supporting multiple reacts in a complete application or in production, but since this is just a development warning, it seems reasonable to do something in dev mode only.

I can try that, but I think it is rather unintuitive for your typical developer workflow.  So even if it works it might be better to think of a way to actually support this workflow.  

I believe a simple solution would be to suppress warning and just have one warning when multiple versions are loaded that are all the same version.  One simple way would be to set a global variable with the react version number, and flip a switch to turn off these messages.

For reference, the reason this warning is specifically being logged is the `manualPropTypeCallCache` inside `createChainableTypeChecker` which tracks calling calls to the proptypes methods, and is ONLY run in development mode.

**Comment by gaearon** [comment]
Even if we fix this particular warnings other (more important) things will likely break. For example string refs don't work across Reacts to the best of my knowledge. I understand it's just a developer warning, but I don't see the sense in fixing this if other things will still be broken in more fundamental ways. While the workaround may be unintuitive, it matches how React is supposed to be used (just one copy). When we fix other issues with multiple Reacts we could try to fix this as well but I don't see why this is valuable now given that the workaround exists and should fix other issues as well.

**Comment by wesleytodd** [comment]
I didn't know there were plans to fix the other issues related to multiple reacts.  As long as there is some longer term plans I am happy to close this issue.  Do you happen to have links to related issues on this that I can look through?

Thanks!!

**Comment by gaearon** [comment]
#6350 is one of these problems.
