### ISSUE TITLE
Expose root ref by default to allow automatic forwarding of setNativeProps

### ISSUE THREAD

**Issue by bitmage** [facebook/react#8447]
In React Native, [TouchableHighlight requires its children to forward 'setNativeProps'](https://github.com/facebook/react-native/issues/97).  This is implemented in built-in components, but must be manually implemented for all custom components.

This causes big incompatibilities with a library like [Native Base](https://github.com/GeekyAnts/NativeBase/issues/68), not to mention any custom components that the developer creates, [which is apparently a preferred pattern for theming](http://willowtreeapps.com/blog/react-native-tips-and-tricks-styling-in-js/):

> For our projects, we create a common directory inside the main js directory. This folder houses commonly-reused components throughout the app. For example, we can declare common Text and Header components...

It could be remedied by making available a default ref `root` which points to the root node.  This would allow generic forwarding to be written into a base class, which other components could inherit from:

```javascript
setNativeProps(props) {
  this.refs.root.setNativeProps(props)
}
```

This would essentially forward the props down the chain until we hit a "concrete" built-in component.  Any arguments against making a `root` ref available by default?

**Comment by gaearon** [comment]
Yes, refs are not free, and making them always available is going to hurt performance and memory usage.

Maybe in the future this could be solved by https://github.com/facebook/react/issues/4213.
