### ISSUE TITLE
Questions about unstable_createPortal

### ISSUE THREAD

**Issue by BinaryMuse** [facebook/react#8455]
I was talking to @vjeux about whether or not `unstable_renderSubtreeIntoContainer` will remain around, and he pointed me to the new/upcoming [`unstable_createPortal`](https://github.com/facebook/react/blob/7d2be2c9a7b4a976e20d2d7c312b43b1bee01a07/src/renderers/dom/fiber/ReactDOMFiber.js#L212) API. I've been using the former to render subtrees that I can move into Atom panes and panels (since I control the node I'm rendering the subtree into, I can move it around as I see fit).

So my two questions are:

1. Will I continue to be able to move this DOM node wherever I want it? (E.g. not just attached to the document like most people do for modals)
2. Will this continue to retain context into the subtree?

**Comment by gaearon** [comment]
>Will I continue to be able to move this DOM node wherever I want it? (E.g. not just attached to the document like most people do for modals)

It will stay mounted as long as node reference is the same. If node reference changes, old portal gets unmounted, and a new one gets mounted.

>Will this continue to retain context into the subtree?

Yes, that’s the primary purpose of this API (just like `renderSubtree`).

--

Note that `createPortal` is only available in Fiber so you won’t see it for a while.

**Comment by spicyj** [comment]
> Note that createPortal is only available in Fiber so you won’t see it for a while.

We're not gonna remove unstable_renderSubtreeIntoContainer until then though! We have need for this too. :)

**Comment by BinaryMuse** [comment]
> It will stay mounted as long as node reference is the same. If node reference changes, old portal gets unmounted, and a new one gets mounted.

@gaearon So do I understand correctly that the ReactDOM method will return a DOM node to put wherever I want? That's even better as it may eliminate an extra container node.

**Comment by spicyj** [comment]
No, you would still create and pass in a container. You would be able to move that container.

**Comment by spicyj** [comment]
I'll close this since it isn't actionable for us but I hope we answered your questions. :) If not, please comment and I'll do my best to clarify.
