### ISSUE TITLE
Full-screen and onMouseOut listener

### ISSUE THREAD

**Issue by NicolasSiver** [facebook/react#8456]
When a container is moved to a full-screen mode, `onMouseOut` listener isn't triggered for a children components, until you will move a mouse.

Example/Demo: https://jsfiddle.net/69z2wepo/63678/

How to use an example:

- Demo is for Chrome
- Open a console
- Click on a `FS` button, try to don't move a cursor
- When in a full-screen, move now a cursor

As an expected behavior, I assume, mouse listener should be triggered as mouse leaves a component.

**Comment by gaearon** [comment]
The browser does the same thing. I don‘t think it’s possible for us to detect this case without convoluted hacks.
