### ISSUE TITLE
[react-test-renderer] componentWillUnmount is not called for inner component instance

### ISSUE THREAD

**Issue by gre** [facebook/react#8459]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

componentWillUnmount for inner instances is never called.

Here are 2 (jest) tests, the first works, not the second.

```js
import React from "react";
import renderer from "react-test-renderer";

test("top level componentWillUnmount works", () => {
  let count = 0;
  class A extends React.Component {
    componentWillUnmount() {
      count ++;
    }
    render() {
      return <div />;
    }
  }
  const inst = renderer.create(<A />);
  inst.unmount();
  expect(count).toEqual(1);
});

test("inner componentWillUnmount works", () => {
  let count = 0;
  class A extends React.Component {
    componentWillUnmount() {
      count ++;
    }
    render() {
      return <div />;
    }
  }
  const inst = renderer.create(
    <div>
      <A />
    </div>
  );
  inst.unmount();
  expect(count).toEqual(1);
});
```

**What is the expected behavior?**

The two test above should pass. All component that are unmounted should have the proper lifecycle, whatever the nesting is.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.4.0

**Comment by spicyj** [comment]
Ah, unmountComponent in ReactTestRenderer needs to call this.unmountChildren.

**Comment by Aweary** [comment]
I can take a look at this

**Comment by gre** [comment]
[This PR](https://github.com/facebook/react/pull/8512) should fix it. I also added a test so there is no regression on this.
