### ISSUE TITLE
onPaste not triggered when using html + svg elements in Google Chrome

### ISSUE THREAD

**Issue by micnic** [facebook/react#8461]
I have the following React component classes:

``` js
const SomeSVG = React.createClass({
    displayName: 'SomeSVG',
    render() {
        return React.createElement('svg', null);
    }
});

const SomeDiv = React.createClass({
    displayName: 'SomeDiv',
    render() {
        return React.createElement('div', {
            tabIndex: '-1',
            style: {
                height: '300px'
            },
            onPaste: (event) => { // This event listener is not triggered in Google Chrome
                console.log(event.clipboardData.getData('text'));
            }
        }, React.createElement(SomeSVG));
    }
});
```
I am unable to listen for paste event in Google Chrome, in Firefox it works fine. The interesting thing is that if I add an HTML element with content (without content it does not paste!) as child the paste event is triggered. I checked the developer tools of the browser, the paste event is triggered always, but it is stopped somewhere in React code when there is only a svg child element or there are a svg child element + a html child element without any content.

Open following examples in Google Chrome (and Firefox for comparison)
Example with not working paste listener: https://jsfiddle.net/uxs90v6p/
Example with working paste listener: https://jsfiddle.net/uj6x0g8d/

Instructions to use the examples:
Copy something in the clipboard, click on the blue area to focus the div element, paste what you have in the clipboard using Ctrl+V and see the console if it is logged

**Comment by Aweary** [comment]
@micnic thanks for the report, I was able to verify the issue occurs in Chrome and does not occur in Firefox. It appears to be a bug in Chrome. Here's a case reproducing the issue using plain JavaScript: https://jsfiddle.net/etmo8rL5/

```js
var div = document.createElement('div');
var svg = document.createElementNS("http://www.w3.org/2000/svg","svg");
div.appendChild(svg);
div.tabIndex = -1;
div.style.backgroundColor = '#EEEEFF';
div.style.height = '200px';
div.addEventListener('paste', function(event) {
	console.log('paste: ', event.clipboardData.getData('text'));
});
document.body.appendChild(div);
```

The issue does not occur if the `svg` is removed.

**Comment by micnic** [comment]
Thanks for the investigation @Aweary , somehow in Chrome the developer tools stops when I put a breakpoint to the clipboard paste event in the React version and I did not try the plain DOM API example. Will report this bug to Webkit.

**Comment by micnic** [comment]
Just FYI, reported to WebKit ant Chromium issues trakers:
https://bugs.webkit.org/show_bug.cgi?id=165248
https://bugs.chromium.org/p/chromium/issues/detail?id=670215

**Comment by vovsemenv** [comment]
Any workarounds for this issue?

**Comment by micnic** [comment]
@vovsemenv, from what I reported to chromium bug tracker:
> This happens when there is a html element with a svg child element or when there is a html element with a svg child element + a html child element without any content (if it has content it works fine).
