### ISSUE TITLE
react-test-renderer does not install dependencies on npm v2

### ISSUE THREAD

**Issue by kweiberth** [facebook/react#8466]
I'm currently using react-test-renderer version `15.4.1` and npm version `2.15.9` and jest version `17.0.3`. When running tests that use react-test-renderer, I'm seeing this error:

```
Cannot find module 'object-assign' from 'ReactTestRenderer.js'

at Resolver.resolveModule (node_modules/jest/node_modules/jest-cli/node_modules/jest-resolve/build/index.js:151:17)
at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactTestRenderer.js:15:15)
at Object.<anonymous> (node_modules/react-test-renderer/index.js:3:18)
```

Is this an issue with npm v2?

**Comment by gaearon** [comment]
Good catch. I think we need to add `"object-assign": "^4.1.0",` to `dependencies` [here](https://github.com/facebook/react/blob/master/packages/react-test-renderer/package.json) (and add `dependencies` section itself). Wanna make a PR?

Technically [addon packages](https://github.com/facebook/react/blob/master/packages/react-addons/package.json) should also get it, I think.

**Comment by kweiberth** [comment]
Thanks for the response. Yes I will make a PR.

**Comment by pedrottimark** [comment]
Noticed while searching: it looks like this issue can be closed now :)

**Comment by aweary** [comment]
Thanks @pedrottimark!
