### ISSUE TITLE
Calling setState inside the onTouchStart event prevents all other touch events to occur

### ISSUE THREAD

**Issue by kevinzwhuang** [facebook/react#8469]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the callback supplied to onTouchStart calls `this.setState`, the subsequent touch events that should work normally do not fire. See this jsfiddle example of this behavior: https://jsfiddle.net/p9qckd3y/1/

```
// example
onTouchStart --- set state here

---- Touch events end here ----

onTouchEnd (Never happens) --- reset to initial state
```

**What is the expected behavior?**
onTouchStart should be able to set state, then allow other touch events to occur.

The following behavior should be expected
```
// example
onTouchStart --- set state here
onTouchEnd --- reset to initial state
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested on React v15.4.1 & React v15.3.2 in Chrome 54 on Linux + Android.

**Comment by Aweary** [comment]
Thanks for the issue @kevinzwhuang. The issue is that you're passing `getInitialState` as the `touchEnd` event handler, and `getInitialState` doesn't actually update the state.

React calls it internally when constructing the initial state, but calling it again does not update the state. If you want to revert back to the initial state you should call `setState` with the return value of `getInitialState`

```js
  onTouchEnd() {
   const state = this.getInitialState()
   this.setState(state)
  }
```
See this JSFiddle: https://jsfiddle.net/zjo0jv5h/

**Comment by kevinzwhuang** [comment]
Ah thanks for the quick response @Aweary. 

Just noticed my typo there in the jsfiddle, meant to write it as `this.setState(this.getInitialState())` 😞 . Nevertheless, this was not a bug with React! 

Turns out one of the higher order components I was wrapping over the child nodes was halting `touchEnd` events whenever `setState` changed the state being passed in as props. Probably some side effect in our HOC, I'll have to take a closer look another time. Got it working again with ordinary components. Thanks again!

**Comment by bandava** [comment]
Hi All, 
I am also facing same issue and touchend or touchmove is not calling after touchsmart. I am doing long press for child components. So in setrimemout I am setting the state of the child on which long pressed. Can you please sugget what's wrong with it
