### ISSUE TITLE
Try/cath render childrens

### ISSUE THREAD

**Issue by emirdeliz** [facebook/react#8473]
Hi, i have a problem in my application, this use a window with various childrens. 

![captura de tela 2016-12-01 as 09 32 35](https://cloud.githubusercontent.com/assets/6270495/20792503/42fb4fba-b7a9-11e6-9056-36e9aaba5820.png)

Each card is a children. The problem occurs when load data from server, and a runtime exception happens. Then others childrens not load. I believe the problem would be solved with try/catch in father component, 
but I did not figure out how to do it.

**Comment by abritinthebay** [comment]
This is a problem with how you're handling the data. Not with React.

**Comment by gaearon** [comment]
If your component throws, you need to find where it happens and fix the error in the component code. React will provide ways to recover from errors in the future but this is still a crash in your application which you should fix. I hope this helps!

**Comment by emirdeliz** [comment]
Hi @abritinthebay, same with various validations of data before render, when worked with complex data and ajax is possible occur errors of runtime.

**Comment by emirdeliz** [comment]
Hi @gaearon thanks for your response. This a problem today for me. My application consume data of a client outsourced. The data is a json large and complex  and validate all data of this is a problem

**Comment by abritinthebay** [comment]
It may be a problem, but it's not _React's_ problem.

If you're not validating that your data all bets are off. Fix your data. Check *why* it throws - then add those checks.

**Comment by emirdeliz** [comment]
@abritinthebay I understand, but in some cases other erros of runtime can occur and other components can not fail.

**Comment by gaearon** [comment]
@emirdeliz You can always put `try` / `catch` inside `render()` of your own components and handle any failures if the data may be corrupted. This won't catch failures of *child* components so if you're really worried you need a `try` / `catch` in every component that depends on unreliable data in its `render` method.
