### ISSUE TITLE
Strange caret behaviour in text inputs on Chrome desktop

### ISSUE THREAD

**Issue by hkeide** [facebook/react#8480]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce it**

If you go to Facebook Messenger (or any web app I've found with a React input field) in Chrome and type in the string "flflflflflflfl" and try to move the caret backwards using the arrow keys you will see the problem. The caret "ignores" every other keystroke, and then jumps two places every other keystroke. Backspacing in the middle of the string also produces strange behaviour.

Here is a video of the behaviour I get: 

https://youtu.be/XGBOCLczCy4

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The bug is present in Chrome 55.0.2883.75 on OS X 10.11.6.

The bug is also present on a fresh install of Chrome Dev Channel 57.0.2936.0 on Windows 10 from Sauce Labs

The bug is not present in Firefox or Safari on OS X.

The bug seems to be present in both controlled and uncontrolled fields (value vs defaultValue)

I'm on React 15.3.2 and react-dom 15.3.1

I don't know which version Facebook Messenger is on

**Comment by gaearon** [comment]
I can't reproduce this. Maybe it was some temporary issue that got solved.
If you can still repro, please provide an example.

**Comment by hkeide** [comment]
If you go to Facebook Messenger right now on Chrome on a Mac (I'm on 60.0.3112.113 and 10.11.6 (15G1611)) the same behaviour is still there. Input the string "flflflflf" in the message field and try to move the caret using the arrow keys from right to left.

**Comment by gaearon** [comment]
Oh wow, you're right. I tried it in a different place by mistake.

This does look like a bug.

Can you reproduce it with any isolated example?

**Comment by gaearon** [comment]
cc @flarnie in case it's a known issue with Draft

**Comment by hkeide** [comment]
I've tried some different apps that I have lying around, and the last one I can reproduce it in uses react and react-dom version 15.5.4. I just tried creating a new fresh app using https://github.com/coryhouse/react-slingshot which is on react and react-dom 16.0.0, and there I haven't been able to reproduce the problem yet. I'm assuming the inputs in the example app are controlled, although that didn't matter last time I was looking into this.

So maybe this is actually fixed in 16?

**Comment by gaearon** [comment]
If it's still happening on Messenger then not since it uses 16.

Could it be a Draft issue rather than a React issue?

**Comment by hkeide** [comment]
I didn't use Draft when I first encountered it, nor am I using it in my older apps that I can currently reproduce it in. I also remember making a really barebones app that still exhibited the strange behaviour. I just happened to check Facebook Messenger because I was trying to think of some high profile app that would use the latest React.

How can I help further? Any ideas for ways to get more information?

**Comment by hkeide** [comment]
Playing around some more with this in Facebook Messenger I've noticed it seems related to the handling of the "f" character (only lowercase). If you try the string "fffffff" then you get the same behaviour. No other lowercase English or Norwegian character produces the behaviour when simply repeated. When "f"s are inserted next to "l" characters you also get the strangeness. I haven't found any other pairing that reproduces the problem. Maybe this could be a clue?

**Comment by gaearon** [comment]
With that new knowledge, can you try reproducing it in vanilla React?

**Comment by gaearon** [comment]
I can't reproduce it anymore. Whether it was React, Draft, or a Chrome bug, seems like it got fixed.
