### ISSUE TITLE
Without an `onChange` handler and renderToStaticMarkup

### ISSUE THREAD

**Issue by kevinsimper** [facebook/react#8482]
I am using `ReactDOMServer.renderToStaticMarkup(Layout)` and I get this message, isn't that wrong?

Could not find any issue about it?

```
Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

**Comment by Intregrisist** [comment]
Seems like somewhere in your code you have something like:

```
<input value="hello" />
```

**Comment by kevinsimper** [comment]
Of course there is a chance it change, I am outputting pure HTML and if I put readOnly you can't edit it :)

**Comment by Aweary** [comment]
Yeah this warning should not be triggered for static markup. Right now its being triggered via [internal PropType validation](https://github.com/facebook/react/blob/751b76e3518883c31b6105736c2b13839863fdef/src/renderers/dom/shared/utils/ReactControlledValuePropTypes.js#L29-L43) when [an input is mounted](https://github.com/facebook/react/blob/751b76e3518883c31b6105736c2b13839863fdef/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L76-L80). If we had the transaction object we could check to see if we're using `makeStaticMarkup`, but `mountWrapper` doesn't have access to the transaction, so it may be non-trivial to suppress this warning.

**Comment by Intregrisist** [comment]
@kevinsimper, what I meant here is that there is no way for the input to change with user interacting directly with the input field because it's a controlled input field.  React is controlling the value, meaning it's "readOnly" because that input will only ever output what your code assigns to the `value` prop.

**Comment by kevinsimper** [comment]
@Intregrisist Yes, I no what you meant, but I am not using javascript in the front-end, I am using node.js to output pure html 😄 

@Aweary Okay, that is good to hear that it is not a error on my side, I could have been my mistake 😄 I will do what you suggest even though it is suboptimal :)

**Comment by gaearon** [comment]
I agree it’s a bit confusing but I actually don’t think we should fix this.

If you later want to make the site dynamic then every such field will become read-only and spam you with warnings.

Isn’t it better to use `defaultValue=` from the very beginning in this case? It also serializes to `value=` in the markup but completely avoids both the warning and the further problems.
