### ISSUE TITLE
dist files are built with process.env.NODE_ENV=development

### ISSUE THREAD

**Issue by popeindustries** [facebook/react#8492]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
It appears that the `dist/*`files have been built/bundled with the wrong `process.env.NODE_ENV`. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Open any of the `dist/*` files and search for `"development" !== 'production'`.

**What is the expected behavior?**
If `process.env.NODE_ENV` was correctly set at build time, the expectation would be `"production" !== 'production'`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Version 15.4.1 is affected, along with `react-dom`. Unknown if other versions were similarly affected.

**Comment by Aweary** [comment]
@popeindustries the unminified `dist` files are actually meant for development use only. If you check out the minified versions they are built for production.

This is mentioned in the [Using a CDN](https://facebook.github.io/react/docs/installation.html#using-a-cdn) section on the installation doc page:

> ```
> <script src="https://unpkg.com/react@15/dist/react.js"></script>
> <script src="https://unpkg.com/react-dom@15/dist/react-dom.js"></script>
> ```
> The versions above are only meant for development, and are not suitable for production. Minified and optimized production versions of React are available at:
> ```
> <script src="https://unpkg.com/react@15/dist/react.min.js"></script>
> <script src="https://unpkg.com/react-dom@15/dist/react-dom.min.js"></script>
> ```

Hope this helps!

**Comment by popeindustries** [comment]
Aha! Sorry for the erroneous issue.
