### ISSUE TITLE
Best way to add raw attribute values to elements

### ISSUE THREAD

**Issue by prasannavl** [facebook/react#8493]
I'm using a direct snippet from my personal website, that I can safely assume has it uses widely. 

Somewhere in the render function:
```
const emailAddress = "&#115;&#111;&#109;&#101;&#32;&#101;&#109;&#97;&#105;&#108;";
const mailToAddress = `mailto:${emailAddress}`;
```

And a part of the larger code to render:
```
<address className="icons">
        // Lots more stuff here..
        <a href={mailToAddress} className="icon-envelope"></a>
</address>
```

The above won't work. The problem here is the `href` with the mailTo. React re-encodes all of this. In order to avoid this, the well known way is to use `dangerouslySetInnerHtml`. However, it makes no sense to use it here, since it's a part of a much larger element. And you cannot just set attributes this way, you have to set the whole element. 

And this phenomenon is encountered quite often in many scenarios. Personally, I think the whole `dangerouslySetInnerHtml` is over-engineered. Real use cases scenarios, for protecting vital stuff, programmers generally use well known api to encode anyway - this is really pointless in real life practical scenarios - the only thing it gives you is headaches. This often just makes you jump through hoops to perform very simple stuff. 

Would greatly appreciate any suggestion of how to handle the above mentioned scenarios. Thanks.

PS: The entire address block above is cleanly abstracted into one component which can be found here:
https://github.com/prasannavl/prasannavl.com/blob/master/src/components/fragments/Address.tsx

**Comment by syranide** [comment]
Setting a property to an encoded string is impossible in HTMLDOM. Entity encoding exists only to allow plain string representation of html, it cannot be represented in the live DOM. So the feature you're suggesting would literally only make sense and work with server rendering/render to string. Whereas `dangerouslySetInnerHtml` has actual client-side uses.

> I'm using a direct snippet from my personal website, that I can safely assume has it uses widely.

AFAIK everyone stopped doing this ages ago, it's trivial to decode and doesn't really stop your email address getting harvested anymore.

**Comment by prasannavl** [comment]
> Setting a property to an encoded string is impossible in HTMLDOM. Entity encoding exists only to allow plain string representation of html, it cannot be represented in the live DOM.

I think you're being attached too specific case I've shown as an example. The issue is about being able to set raw attribute values. 

> AFAIK everyone stopped doing this ages ago, it's trivial to decode and doesn't really stop your email address getting harvested anymore.

I don't know where you're getting this from - but every decent website still does this. Take a look at GitHub's profile, perhaps.  Yup, it's easy to decode, but doesn't mean it has it's uses. Infact, I had my email un-encoded when I first moved to React and had drastic increase in my spam levels.

Please take a look at the code link to the React component I linked above. The problem is just to set a single attribute I had to encode the whole thing as string. It's very messy. This is fortunately a small module.

**Comment by syranide** [comment]
> I think you're being attached too specific case I've shown as an example. The issue is about being able to set raw attribute values.

You can't "set raw attribute values". HTMLDOM doesn't allow you to.

**Comment by prasannavl** [comment]
> You can't "set raw attribute values". HTMLDOM doesn't allow you to.

I probably wasn't clear enough. It shouldn't be relevant because React promotes agnostic development. I should be able to set raw attribute values that's parsed as it is by the browser. **There should be a way for React to just get out the way**. Not re-encode it by itself.

**Comment by syranide** [comment]
@prasannavl You're not getting my point I think, you literally cannot set raw attributes in HTMLDOM via JS. You just can't. React is not encoding attributes client-side, it only sets properties and calls `setAttribute`. React encodes attribute values (and other things) when rendering static markup server-side as part of the process to create a serialized representation of the DOM.

IMHO, the solution to what you're trying to do is to apply a post-process obfuscation step of mailto-addresses to html generated by React.

**Comment by prasannavl** [comment]
Thanks for making it clear as to what React does on the client-side. This makes it clear on where our mismatch comes from. I didn't look into the fact the React simply passes them through on the client side - I was trying to be agnostic about it. But that's good.

> React encodes attribute values (and other things) when rendering static markup server-side as part of the process to create a serialized representation of the DOM.

Yup. Here's where the problem lies. There's should be a option to simply bypass the attribute values here.

**Comment by deanbrophy** [comment]
Hey, @prasannavl,
This issue looks a bit stale. Do you think it should still be open?
