### ISSUE TITLE
thead.props.children should always be an array

### ISSUE THREAD

**Issue by swamikevala** [facebook/react#8494]
thead can contain one or more tr elements.
If it contains 1 then thead.props.children is an object, if it contains > 1 then it is an array.

Would make it much simpler to use if it always returned an array

**Comment by Aweary** [comment]
Thanks for the issue @swamikevala. This applies to all elements, not just `thead`. There are no current plans that I'm aware of to change this API, though that may change in the future.

Check out `React.Children`, a top-level API that makes it easier to deal with `this.props.children` by abstracting away the specific data structure being returned.

https://facebook.github.io/react/docs/react-api.html#react.children
