### ISSUE TITLE
Add component stack to the contentEditable warning

### ISSUE THREAD

**Issue by kevart** [facebook/react#8497]
*feature*

>Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

It would help heaps if I would know _which_ component is causing this.

**Comment by gaearon** [comment]
We should add component stack to it, just like other warnings have it.

**Comment by Ethan-Arrowood** [comment]
@gaearon I'd like to try this one out. I'm a first-time contributor for the React project so some more pointers would be appreciated!

**Comment by gaearon** [comment]
Here is an example of [a warning that includes component stack](https://github.com/facebook/react/blob/fa7461e25bb63188bc2a3d2eb5ea085dfc7c5f1a/src/renderers/shared/fiber/ReactChildFiber.js#L195-L201). Here is [how we test such warnings](https://github.com/facebook/react/blob/a947d3f92fba61ba9107861dde9e4ea89ad87442/src/renderers/__tests__/ReactComponent-test.js#L488-L493).

Here is the [contentEditable warning](https://github.com/facebook/react/blob/e932ad68bed656eed5295b61ba74e5d0857902ed/src/renderers/dom/shared/utils/assertValidProps.js#L64-L72). As you see, it doesn't include the stack. Add it there. Here is [the relevant test](https://github.com/facebook/react/blob/a947d3f92fba61ba9107861dde9e4ea89ad87442/src/renderers/dom/shared/__tests__/ReactDOMComponent-test.js#L1117-L1122). Change it to also test the warning message (not just a single word like now) and for the presence of the stack.

Hope this helps!

**Comment by Ethan-Arrowood** [comment]
👍 Thank you! I'll give it a shot later today

**Comment by Ethan-Arrowood** [comment]
@gaearon how can I interact with these errors? I have edited the proper file but my test is still failing. Is there a recommended way of debugging?
