### ISSUE TITLE
Performance monitoring does not record any behaviour on page reload

### ISSUE THREAD

**Issue by bokkibear** [facebook/react#8504]
Bug: Using `?react_perf` appears to correctly switch on performance monitoring, but no React measures show up in the timeline.

To reproduce:

1. In Chrome, go to any page with non-production React code and add the `?react_perf` query string as described in https://facebook.github.io/react/blog/#profiling-components-with-chrome-timeline. For example: https://jsfiddle.net/f9oc9Ldy/3/?react_perf

2. Open Chrome DevTools and click to the "Timeline" tab

3. Refresh the page

4. When the page has refreshed, look at the timeline and note that there aren't any react-specific marks.

5. In the console, do `performance.getEntriesByType("measure")` - you'll get an empty array, when you should get actual performance measures.

Tested with React 15.4.1 on Chrome. I'd expect to see React-specific events (e.g. `mount` events for the React components) in the timeline, and to be able to access performance measures from the console.

Looking in the code, it appears that all recorded performance measures are immediately deleted, which may be causing this issue. See https://github.com/facebook/react/blob/master/src/renderers/shared/ReactDebugTool.js

```
  const markEnd = function(debugID, markType) {
    if (!shouldMark(debugID)) {
      return;
    }

    var markName = `${debugID}::${markType}`;
    var displayName = ReactComponentTreeHook.getDisplayName(debugID) || 'Unknown';

    // Chrome has an issue of dropping markers recorded too fast:
    // https://bugs.chromium.org/p/chromium/issues/detail?id=640652
    // To work around this, we will not report very small measurements.
    // I determined the magic number by tweaking it back and forth.
    // 0.05ms was enough to prevent the issue, but I set it to 0.1ms to be safe.
    // When the bug is fixed, we can `measure()` unconditionally if we want to.
    var timeStamp = performanceNow();
    if (timeStamp - lastMarkTimeStamp > 0.1) {
      var measurementName = `${displayName} [${markType}]`;
      performance.measure(measurementName, markName);
    }

    performance.clearMarks(markName);
    performance.clearMeasures(measurementName);
  };
```

Immediately after every measurement, we instruct the browser to clear the same measure (by name) - so it seems like no measurements ever take place. Removing the final two lines of the function restores expected behaviour.

**Comment by gaearon** [comment]
Have you followed the exact steps in the blog post?
In particular I don't see you mentioning you pressed "Record".
This is required for measurements to be recorded.

**Comment by bokkibear** [comment]
That's not correct, for two reasons:
1) The Chrome timeline automatically starts recording when you reload the page
2) The steps above will record other events, just not React ones
3) The fix I described resolves the problem.

Feel free to try it yourself!

**Comment by gaearon** [comment]
I don’t remember this very well now. There is some overhead to the profiling mode, and keeping measurements will likely eat memory, especially in larger apps. I've often seen Chrome crash completely when the measurements are recorded for too long so I don't think it would be a very good default.

I'm not sure why "Record" button works differently from "record on page load" mode. Could this be a Chrome bug?
