### ISSUE TITLE
Components need key attribute?

### ISSUE THREAD

**Issue by bajalovic** [facebook/react#8516]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have created a `Dropdown` component that receives a value and an array of options as props. In `MyComponent` I render a multi step form (`currentStep` is saved in `state` object). When you switch between steps (and `MyComponent` is re rendered), `Dropdown` component keeps state from previous component instance. 
For example on one step `Dropdown` component is giving you options for Font Family, and on next step for Font Size. 
I fixed this bug with setting `key={1}`, `key={2}`, etc on each `Dropdown` component.

```javascript
export default class Dropdown extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      value: props.value,
      content: props.options.get(props.value)
    }

    this.onChange = this.onChange.bind(this);
  }
  onChange(e, value) {
    e.preventDefault();
    this.setState({value: value});
    if(this.props.onChange) {
      this.props.onChange(value);
    }
  }
  getOptions() {
    const items = [];
    this.props.options.forEach((content, value) => {
      items.push(<li key={value}><a href="#" onClick={(e) => {this.onChange(e, value)}}>{content}</a></li>);
    });
    return items;
  }

  render() {
    const options = this.getOptions();
    return <div>
      {this.props.options.get(this.state.value)}
      <i className="fa fa-caret-down"></i>
      <ul>
        {options}
      </ul>
    </div>
  }
```

```javascript
export default class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {step: 0, font_family: 'Arial', font_size: '10'};
    this.goToStep = (e, step) => {e.preventDefault(); this.setState({step: step}); };
    this.onFamilyChange = (value) => this.setState({font_family: value});
    this.onSizeChange = (value) => this.setState({font_size: value});

    this.fontFamilyOptions = new Map([['arial', 'Arial'], ['times', 'Times'], ['helvetica', 'Helvetica']]);
    this.fontSizeOptions = new Map([[10, '10 px'], [12, '12 px'], [14, '14 px']]);
  }

  getFirstStep() {
    return <div>
        <label>Choose Font Family</label> 
        <Dropdown value={this.state.font_family} options={this.fontFamilyOptions} onChange={(value) => this.onFamilyChange(value) } />
        </div>
  }

  getSecondStep() {
    return <div>
        <label>Choose Font Size</label> 
        <Dropdown value={this.state.font_size} options={this.fontSizeOptions} onChange={(value) => this.onSizeChange(value) } />
        </div>
  }

  render() {
    return <div>
      <a href="#" onClick={(e) => this.goToStep(e, 0)}>Step 0</a>
      <a href="#" onClick={(e) => this.goToStep(e, 1)}>Step 1</a>
      {this.state.step === 0 ? this.getFirstStep() : this.getSecondStep()} 
    </div>
  }
}
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 0.9.1
Chrome 54.0
Mac OS Sierra 10.12.1

I am not sure if I am doing something wrong here or is it a bug.

**Comment by bajalovic** [comment]
What I see that happens is that React does not initialize `Dropdown` component when steps switch, but re-use existing one and therefor `constructor` method is not called. I fixed this with adding `componentWillReceiveProps` method to `Dropdown` component.

```javascript
  componentWillReceiveProps(nextProps) {
    if(nextProps !== this.props) {
      this.setState({value: nextProps.value});
    }
  }
```

This way it will work without `key` attribute. Is this 'the right' way of doing it?

**Comment by brigand** [comment]
@bajalovic this is expected behavior. Your `componentWillReceiveProps` will setState on all updates since there's a new props object on each render, which isn't what you want. You could compare `nextProps.value` and `this.props.value`. I'd use `key` here.

**Comment by aweary** [comment]
@brigand's advice is good. Since there's been no update on this I'll assume you figured it out 😄 

For future reference, we try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
