### ISSUE TITLE
DX feature: more specific error when render returns Component instead of Element

### ISSUE THREAD

**Issue by slorber** [facebook/react#8517]
Version: 15.4.1

When the render function returns a React Component instead of a React Element, the error message might be quite cryptic, like:

> invariant.js:38 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

https://jsfiddle.net/69z2wepo/64457/

I think React could try to detect that the render function is returning a component instead of an element, and print something convenient (like its displayName).

Why is this useful? Because for example I'm using a lib where there was an API breaking change where a prop has been changed from component to element, and it was hard to find the cause of the problem, even by looking at invarient stack/variables in debugger. (see https://github.com/akiran/react-slick/issues/458)

Quite related but it seems that if React tries to put a component in the JSX (like `<span>{Component}</span>`, but also with `React.createElement`) this is simply swallowed, I think a warning would be useful too :) see https://jsfiddle.net/69z2wepo/64460/

**Comment by gaearon** [comment]
We now provide a better message:

<img width="449" alt="screen shot 2017-10-04 at 16 36 27" src="https://user-images.githubusercontent.com/810438/31184750-3370a926-a922-11e7-8176-eaf04b0a67e8.png">

>Quite related but it seems that if React tries to put a component in the JSX (like <span>{Component}</span>, but also with React.createElement) this is simply swallowed, I think a warning would be useful too :) see https://jsfiddle.net/69z2wepo/64460/

Also fixed.
