### ISSUE TITLE
some instances change a same state,

### ISSUE THREAD

**Issue by carly1987** [facebook/react#8530]
**Do you want to request a *feature* or report a *bug*?**
![image](https://cloud.githubusercontent.com/assets/4493524/21007368/87825fe2-bd77-11e6-8915-bca148403457.png)
```
<color visiable={false} name='a'/>
<color visiable={false} name='b'/>
```

click instanceA, the state of 'visiable' will be true.
but click instanceB, the instanceA's visiable always be true,
how to do that click A, it's visiable will be true, and then click B, B's visiable will be true and the A's visiable will be false.  

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Aweary** [comment]
@carly1987 it looks like you're using some third party component (like [react-colors](https://github.com/casesandberg/react-color)?) for your color picker. Please file an issue there, as React does not provide a color picker itself.

Also, it would help to provide a fiddle reproducing your issue. You can use [this JSFiddle](https://jsfiddle.net/reactjs/69z2wepo/) as a starting point.

**Comment by carly1987** [comment]
i don't use react-colors

**Comment by carly1987** [comment]
I got the way to control the "Multiple instances of same react component":
`class Btn extends Component {
	constructor(props) {
		super(props);
		this.state = {
			state: this.props.state
		}
	}
	changeState = () => {
		const state = this.state.state;
		this.props.closeAll();
		this.openIt();
		// if(state == 'off') {
		// 	this.openIt()
		// } else {
		// 	this.closeIt()
		// }

	}

	openIt = () => {
		this.setState({
			state: 'on'
		});
	}

	closeIt = () => {
		this.setState({
			state: 'off'
		});
	}

	render() {
		return (
			<div onClick={this.changeState}>{this.state.state}</div>
		)
	}
}
class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			state: 'off'
		}
	}
	componentDidMount() {

	}
	closeAll = () => {
		this.btn.map((btn) => {
			btn.closeIt()
		});
	}
	render() {
		this.btn = []
		return (
			<div>
				<Btn state={this.state.state} ref={(btn) => {this.btn.push(btn)}} closeAll={this.closeAll}></Btn>
				<Btn state={this.state.state} ref={(btn) => {this.btn.push(btn)}} closeAll={this.closeAll}></Btn>
				<Btn state={this.state.state} ref={(btn) => {this.btn.push(btn)}} closeAll={this.closeAll}></Btn>
			</div>
		);
	}
}`
