### ISSUE TITLE
War and Peace bug (Scrolling + Embed Font + Text with special characters)

### ISSUE THREAD

**Issue by tamtakoe** [facebook/react#8534]
If you use embed fonts for text like War and Peace with russian and french characters and you programmatically scroll bottom after component was rendered (componentDidMount) you will have excess gap in the bottom of scrolling.

![react_bug](https://cloud.githubusercontent.com/assets/2244675/21029933/1294fd8a-bdad-11e6-941c-99d1d7199b5c.png)
[Example](http://run.plnkr.co/ZJ5Dvh4frCYB9PfC), [code](http://plnkr.co/edit/aOKAp0En9QoELQPrPRib?p=preview) (use separate window mode in Plnker editor if example dosn't work)

Maybe it is because React rendering doesn't conform with fonts rendering

React .., 14, 15; Chrome, Firefox; Windows 10, Ubuntu 16

**Comment by gaearon** [comment]
Thanks for the report! Is there anything in particular that makes you think it is a React issue? Have you tried reproducing this without React?

**Comment by tamtakoe** [comment]
Yes. Bug doesn't repeat without React if I append element with text into container and scroll bottom after that. Unfortunately I don't know React so good to reproduce React live cycle by native JS

**Comment by tkh44** [comment]
@tamtakoe FWIW, this method works http://plnkr.co/edit/b9htnf6TE7TB7DNbqUG6?p=preview

**Comment by aweary** [comment]
Closing out as stale since there was no follow-up
