### ISSUE TITLE
react-test-renderer crashes re-rendering react-native TextInput

### ISSUE THREAD

**Issue by donataswix** [facebook/react#8539]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
react-test-renderer crashes rerendering component when props change.
```
  ● should not die

    TypeError: Cannot read property 'setNativeProps' of undefined
      
      at Component.componentDidUpdate (node_modules/react-native/Libraries/Components/TextInput/TextInput.js:799:15)
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:729:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-test-renderer/lib/ReactUpdates.js:89:32)
      at Object.flushBatchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:172:19)
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
```javascript
import ReactTestRenderer from 'react-test-renderer';
import React, {Component} from 'react';
import {TextInput, View} from 'react-native';

class Example extends Component {
  constructor(props) {
    super(props);
    this.state = {query: ''};
  }
  render() {
    const doSomething = () => this.setState({query: 'A'});
    return (
      <View>
        <View onPress={doSomething}/>
        <TextInput value={this.state.query}/>
      </View>
    );
  }
}

it('should not die', function () {
  const renderer = ReactTestRenderer.create(<Example/>);
  renderer.toJSON().children[0].props.onPress();
  renderer.toJSON();
});
```
**What is the expected behavior?**
No exception, TextInput value prop set to 'A'.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@15.4.1
react-native@0.39.1 
react-test-renderer@15.4.1
jest@17.0.3

**Comment by Aweary** [comment]
Thanks for the report @donataswix! The issue appears to be that the `TextInput` component is [expecting to receive a `ref`](https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L612-L614) from a native component (`AndroidTextInput` or `RTCTextField`) which it [calls `setNativeProps`](https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L761-L763) on. But it ends up being `undefined` and throws.

From what I can see, the `render` method for the native components is never being called, so the ref is never set. I'm entirely sure why that is, maybe @spicyj @cpojer have some insight?

**Comment by spicyj** [comment]
Hm, I don't think we support rendering RN components unless you mock the base ones. Not sure offhand though why you'd get this particular error.

**Comment by donataswix** [comment]
On a reread of [tutorial](https://facebook.github.io/jest/docs/tutorial-react-native.html), I found:
> However some react-native components or third party components rely on native code to be rendered.
I guess this invalidates my bug report. 

If anyone stumbles upon this, maybe this will be good enough for you too:
```javascript
jest.mock('TextInput', () => {
  return class extends Component {
    render () {
      return React.createElement('TextInput', this.props, this.props.children);
    }
  };
});
```

**Comment by spicyj** [comment]
Thanks for following up!
