### ISSUE TITLE
Attach ReactEventListener for ajax/dynamically loaded content

### ISSUE THREAD

**Issue by AngeIII** [facebook/react#8540]
Is there any way to attach onChange event listening like we do in Render function. HTML that loaded with AJAX and inserted via `dangerouslySetInnerHTML`

Example:
top:
```
import ChangeEventPlugin from 'react/lib/ChangeEventPlugin'
import EventConstants from 'react/lib/EventConstants'
```
on Render:
` <div ref="form" dangerouslySetInnerHTML={{ __html: this.state.formContent || '' }} />`

onDidMount:
```
ajax-> this.setState({
          formContent: response.html
        })
```

onDidUpdate:
```
this.refs.form.querySelectorAll('input, textarea, select').forEach((node) => {
      let topChange = EventConstants.topLevelTypes.topChange
      node._hostNode = node
      let event = ChangeEventPlugin.extractEvents(topChange, node, ???)
      console.log(event)
    })
```

But can't get it work with callback.

The issue is when `dispatchEvent` called `bookKeeping` variable refs to `div` not on dynamically loaded Nodes.

Any suggestion will be great.

EDIT:
Possibly looks like I want to trigger `enqueuePutListener` from React Dom manually

P.S.
I'm trying to work only with Native things. Do not suggest jQuery or document.addEventListener (I looking for multi-browser and multi-input types solutions like is done in React).

**Comment by Aweary** [comment]
Hey @AngeIII thanks for the issue!

> import ChangeEventPlugin from 'react/lib/ChangeEventPlugin'
import EventConstants from 'react/lib/EventConstants'

We do not recommend or support using internal modules in application code. These modules are meant for internal consumption only and are subject to change without notice.

> I'm trying to work only with Native things. Do not suggest jQuery or document.addEventListener (I looking for multi-browser and multi-input types solutions like is done in React).

`addEventListener` is available in all browsers that React supports. It's even [used internally to detect event support](https://github.com/facebook/react/blob/e3131c1d55d6695c2f0966379535f88b813f912b/src/renderers/dom/shared/utils/isEventSupported.js#L42), so there is nothing wrong with using that to attach event listeners yourself as well.

**Comment by AngeIII** [comment]
@Aweary, thanks for your reply. I'm understand your opinion and will do it with addEventListener.

Btw, it will be great if react-plugins in future can be a separated npm libraries that can be used standalone.
