### ISSUE TITLE
Requesting review/feedback for my blog "The Inner Workings Of Virtual DOM"

### ISSUE THREAD

**Issue by rajaraodv** [facebook/react#8547]
I wrote a blog post to make it easy for people to learn how Virtual DOM works. I'm using Preact(not react) to explain it. Wondering how much of it is similar to what React does? Appreciate any review/feedback. Thank you!

https://medium.com/@rajaraodv/the-inner-workings-of-virtual-dom-666ee7ad47cf

**Comment by gaearon** [comment]
I think a lot of this is very dependent on the implementation.
The observable part of how it works in React is described [here](https://facebook.github.io/react/docs/reconciliation.html).
The current implementation is described in detail [here](https://facebook.github.io/react/contributing/implementation-notes.html) although we're changing it a lot in Fiber.

I hope this helps!

**Comment by Aweary** [comment]
Looks like a great post @rajaraodv! We do try and reserve this issue tracker for actual issues or feature requests, so I'm going to close this out. Maybe try posting on a community-oriented platform like https://discuss.reactjs.org/ for feedback.

Have a great day!
