### ISSUE TITLE
Update renderToStaticMarkup documentation

### ISSUE THREAD

**Issue by abFx** [facebook/react#8553]
There are some inconsistencies regarding the use of **renderToStaticMarkup**

Current documentation says that  :

> Similar to renderToString, except this doesn't create extra DOM attributes such as data-reactid, that React uses internally. This is useful if you want to use React as a simple static page generator, as stripping away the extra attributes can save lots of bytes.

But on release 15.0 there is a statement that suggests : 

> **data-reactid** is no longer on every node. As a result of using document.createElement, we can prime the node cache as we create DOM nodes, allowing us to skip a potential lookup (which used the data-reactid attribute). Root nodes will have a data-reactroot attribute and **_server generated markup will still contain data-reactid_**.

I was looking to optimize the server render content by removing all that extra markup, and thought I was doing something wrong because there are still a lot of **data-reactid** everywhere, 
so, _**Is it still possible to render on the server without those extra dom attributes**_?

**Comment by kinop112365362** [comment]
in the source code, I look for the **renderToStaticMarkup**,but I don't find anything about data-reactId, this function only to control this DOM attributes **CHECKSUM_ATTR_NAME: 'data-react-checksum' ** if you calling it , in the page , I think you should see it , but it is not the other

**Comment by sugargreenbean** [comment]
I believe that renderToStaticMarkup has been deprecated: 

> Deprecated APIs removed from React, specifically findDOMNode, render, renderToString, renderToStaticMarkup, and unmountComponentAtNode

[Source ](https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/docs/_posts/2016-03-07-react-v15-rc1.md)

Quick test also shows that renderToStaticMarkup no longer suppresses data-reactid addition.

As such, I believe the documentation should remove references to renderToStaticMarkup, as well as the other deprecated APIs listed above.

**Comment by sugargreenbean** [comment]
@abFx I looked into this further and I found that you can still render on the server without those extra dom attributes, so the documentation does not need to be updated.

Try cloning this: https://github.com/mhart/react-server-example

And changing lines 41-48 in server.js to the following:

` var html = ReactDOMServer.renderToStaticMarkup(body(null, ... div({id: 'content', dangerouslySetInnerHTML: {__html: ReactDOMServer.renderToStaticMarkup(App(props)) }}),`

And you'll see that the items are server rendered without DOM attributes.

<img width="278" alt="screen shot 2017-03-27 at 3 02 10 am" src="https://cloud.githubusercontent.com/assets/1877368/24344511/d49693bc-1299-11e7-968d-6b659507d88b.png">

**Comment by sugargreenbean** [comment]
@zpao Can we close this issue? 

The original question was: _Is it still possible to render on the server without those extra dom attributes?_ And the answer is: yes, which means that documentation doesn't need to be updated.

**Comment by zpao** [comment]
Yes, we can close this - thanks @sugargreenbean for doing some triage!

`renderToStaticMarkup` will generate a string without the extra attributes.

`renderToString` will currently generate a string with `data-reactid` on every node. This used to be the behavior in the browser as well. However starting in v15, when we do the rendering in the browser we changed how things work so we can skip that (specifically we have a strong association to DOM nodes as they are created - we don't generate a string of markup). On the server we only have a string.

Keep in mind that if you plan on mounting the DOM made with server-side rendering, then you do actually want the one that has the `data-reactid` inline. This allows us to reuse the existing nodes. If you mount over something generated with `renderToStaticMarkup`, then that entire DOM tree will get thrown away (potentially dangerous for form elements).

(ps, I'm not actively involved with the project these days, so @gaearon is probably your best bet if you want a quick response from somebody with all the latest knowledge)

**Comment by abFx** [comment]
Thanks!
