### ISSUE TITLE
Click handler can get called twice in "non-prod" mode.

### ISSUE THREAD

**Issue by pllee** [facebook/react#8559]
I think this is a bug that only happens in "non-prod" mode.

I noticed this using the react-dropzone library but I think I found a simple use case to reproduce the problem.  If you check out the [fiddle](https://jsfiddle.net/69z2wepo/64978/) you can see that click handler is called twice even though the element is only clicked once.  Here is an example showing it ["working and not working"](https://jsfiddle.net/f2ntq2h6/1/)  

I believe it has something to do with the outer div's click listener and this chunk of code:

```js
if (true) {
  /**
   * To help development we can get better devtools integration by simulating a
   * real browser event.
   */
  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof document !== 'undefined' && typeof document.createEvent === 'function') {
    var fakeNode = document.createElement('react');
    ReactErrorUtils.invokeGuardedCallback = function (name, func, a) {
      var boundFunc = func.bind(null, a);
      var evtType = 'react-' + name;
      fakeNode.addEventListener(evtType, boundFunc, false);
      var evt = document.createEvent('Event');
      // $FlowFixMe https://github.com/facebook/flow/issues/2336
      evt.initEvent(evtType, false, false);
      fakeNode.dispatchEvent(evt);
      fakeNode.removeEventListener(evtType, boundFunc, false);
    };
  }
}
```

I tested this on Chrome/Mac I have also seen this behavior on React 14.8.

**Comment by edvinerikson** [comment]
changing `let clickCount = ++this.state.clickCount;` to `let clickCount = this.state.clickCount + 1` stops the counter incrementing by two each time.
also I think it might be event bubbling that is happening since you trigger a click in a child which should bubble up.

**Comment by Andarist** [comment]
Im not really aware of React internals, but from my short debug it seems that the culprit is this line - `this.refs.fileInput.open();` in your button's `onClick` handler.

Its synchronously calling `this.refs.inputEl.click();`, which in effect triggers top level dispatch of the click event. Your button's `onClick` handler at this moment is still not finished so probably in some internal queue and when this programatically induced click is being handled it calls both `onClick` handlers - button's and div's.

If the issue should be resolved, I would call a dibs on it. With some guidance about internals from somebody way more experience in react than I am should be quite easily fixable (I think ;) )

**Comment by pllee** [comment]
@edvinerikson changing click count does fix that but I just added that to make the issue of it being called twice more obvious.  If you look at the logs it is button click is called twice.  

Yeah it looks like an issue with the event bubbling you can see it working in my "working and not working" example by not invoking the click.

**Comment by Aweary** [comment]
I need to look at the example closer to say what's happening, but a quick note: `++this.state.clickCounter` will mutate `this.state` which isn't likely what you want.

**Comment by pllee** [comment]
@Aweary Just an fyi if I comment out the code that I mentioned I don't see the issue in my app which uses 14.8.

**Comment by Andarist** [comment]
<img width="1169" alt="screen shot 2016-12-13 at 16 53 35" src="https://cloud.githubusercontent.com/assets/9800850/21147291/c49cbe50-c154-11e6-81cc-10058a8a6278.png">

You can see here whats the stack trace for the second `dispatchEvent` which causes second `onClick` run.

**Comment by aweary** [comment]
For reference, this does not occur in the React 16 alpha: https://jsfiddle.net/6L9hgf2j/

**Comment by Andarist** [comment]
@aweary I think this issue can be closed then, right?

**Comment by Andarist** [comment]
For reference - while implementation has changed the simpler fix was introduced in https://github.com/facebook/react/pull/10296
