### ISSUE TITLE
Question / support - need a way to programmatically update field with defaultValue

### ISSUE THREAD

**Issue by ORESoftware** [facebook/react#8571]
Support question here - I am looking for a robust and performant way to update an input field's text programmatically, _where the input field has `defaultValue` instead of `value`_.

Something like this:

```js
render: function(){

  return (

      <input
        id="pickupField"
        tabIndex="1"
        placeholder=""
        className="order-form-input"
        onFocus={this.disableAddresses}
        onBlur={() => {
            this.enableAddresses();
            this.fieldChange('address');
        }}
        // we use defaultValue, not value
        defaultValue={(order.pickup || {}).address || ''}  
        ref="pickupAddress"
        hintText={(this.state.hideHintText) ? "" : "Enter the pickup address"}
        floatingLabelFixed={true}
        floatingLabelText="Pickup Address"
      />
   )
}

```

The problem I am having is that I want to sync with the database, upon the "onBlur" event of the input field. If I use `value` instead of `defaultValue`, _I can get this to work_, but there are two problems I see with using value instead of defaultvalue:

(a) much less performant => updating the react component state on every keystroke
(b) more importantly, it makes my database sync logic more complex, because I will update the React component state on every keystroke, but only sync with the database on every onBlur. I'd rather not have to write that logic, if possible.

I asked this question on SO:

https://stackoverflow.com/questions/41133182/react-uncontrolled-component-updating-the-input-fields-despite-presence-of-def

Please let me know if you have any ideas, thanks!

**Comment by gaearon** [comment]
Does this work?

```js
this.refs.pickupAddress.value = 'something';
```

It's a DOM node so you can do anything with it.

**Comment by ORESoftware** [comment]
It probably would :) but do I put that in the render method, or somewhere else?

**Comment by ORESoftware** [comment]
The major downside of that approach, is that I now have two different pieces of "rendering" logic. The method that updates all the this.refs and the render method. That's not good right? Ideally all the rendering logic would be in the render method. So this might work, but not super well, no?

**Comment by ORESoftware** [comment]
what I mean is:

```
const c = React.createClass({
  updateRefs: function(){
        Object.keys(input, item => {
            this.refs[item] = input[item]
        });
   },

  render: function(){
       return (

         )
  }

});
```


ideally, the render function could do what the updateRefs is doing without any separate code.

One way to achieve this might be to conditionally use either defaultValue or value in the elements, but that would also be tricky.

thanks for the idea, it will probably work

**Comment by ORESoftware** [comment]
Any idea if using placeholder instead of defaultValue might solve this kind of problem?

**Comment by gaearon** [comment]
Do you have any particular performance problem you're trying to avoid by using `defaultValue`?
Have you tried using state for this?

**Comment by ORESoftware** [comment]
it's kinda complicated, if you see the SO question at the top, I think it explains it well. basically, if I use value instead of defaultValue, I have to use onChange, if I use that, then I change my component state with every keystroke, which means that by default I would also be updating my DB with every keystroke, which is just unnecessary amount of requests.

One more question for the moment - after setting

```js
this.refs.x.value = 'y';
```

do I have to call` this.forceUpdate()`

because my React component with defaultValues did not update after calling the above line of code :(

**Comment by ORESoftware** [comment]
It seems like with defaultValue set, it will never update after the DOM element is first created*, that is bad news bears. *it will only update if the user types into the field.

**Comment by ORESoftware** [comment]
@gaearon as an example, if I do this for an <input> field:

                        ```js
                              ref="pickupAddress"
                           value={(order.pickup || {}).address || ''}
                            onChange={(e, value)=>{
                                this.refs.pickupAddress.value = value }
                            }
                            ```

it won't update the TextField, it will be stuck at whatever `value` is

**Comment by gaearon** [comment]
>I change my component state with every keystroke, which means that by default I would also be updating my DB with every keystroke, which is just unnecessary amount of requests.

This seems like the problem—can you just *not* update the DB every time local state changes? For example you could do so on blur.

>It seems like with defaultValue set, it will never update after the DOM element is first created

This might be possible—I don't actually know DOM nuances well. Worth looking at MDN.

**Comment by ORESoftware** [comment]
oh shit

> There is one exception to this behaviour – this.refs only points to a DOM node for refs on HTML elements. When you add a ref to a custom component, it’ll point to the component instance instead. So how do you access the DOM in this case?
> 
> ReactDOM.findDOMNode(componentInstance)

probably the problem with the DOM not updating, because actually this is not an <input> HTML tag but a React component

I will figure it out, thanks for your input!

**Comment by ORESoftware** [comment]
@gaearon 

just FYI I figured out a solution to this one. Use key={uniqueKey} in your components elements and update that when you want to unmount the component. when you rerender with new data your defaultValues will reflect the new data.

otherwise, you cannot programmatically change the defaultValue of a input field TMK

**Comment by gaearon** [comment]
Glad you found a solution that satisfies you. As I mentioned earlier I would recommend using state instead, and *not* sending data to DB on every state update.

**Comment by ORESoftware** [comment]
I toyed with this all day yesterday, and AFAICT, the React component key solution seems to be a good one for this use case. I don't think React unmounts the whole containing component, just the components with that key. We need to sync with the DB on some state change. When we change the child component state, we can do nothing. But when we change the parent component's state, that's the right time to sync with the DB. Perhaps in our case, we are changing the parent component's state too frequently, but I don't think so. I don't think there is a good "coarser grain" solution than onBlur for each text field / input field.
