### ISSUE TITLE
PropType validation fails when nesting validations

### ISSUE THREAD

**Issue by ssylvia** [facebook/react#8573]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
App does not properly validate against nest React.PropTypes testing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Demo: https://jsfiddle.net/yt22tzr7/

**What is the expected behavior?**
Should not fail proptype validation

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 15.4

**Comment by gaearon** [comment]
`key` has a reserved meaning in React and does not end up in `this.props`.
Therefore it fails the `propTypes` check.
You need to remove `key` from `propTypes` validations.

Additionally, you defined `handleClick` as a `string` but it should have been a `func`.
Here is a version that works: https://jsfiddle.net/jgmvq0tg/.
