### ISSUE TITLE
Top-level callback has different semantics from setState callbacks

### ISSUE THREAD

**Issue by acdlite** [facebook/react#8577]
When you call `setState` with a callback

```js
this.setState(partialState, callback);
```

the state update is [enqueued separately from the callback](https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/isomorphic/modern/class/ReactComponent.js#L68-L70). If the `setState` is called outside of `batchedUpdates` (or in Fiber parlance, with `Synchronous` priority), that leads to two separate flushes, because `enqueueSetState` triggers a synchronous render that is flushed before `enqueueCallback` is ever called.

We've replicated this behavior in Fiber as well.

However, the top-level callback that is passed to `ReactDOM.render` does not have the same semantics. Both the state update and callback are flushed at the end of the next render, even outside of `batchedUpdates`. See [this unit test](https://github.com/facebook/react/blob/master/src/renderers/shared/shared/__tests__/ReactCompositeComponentState-test.js#L180) for an example. The initial callback is called just after the initial mount, whereas if the callback had `setState` callback semantics, it would be flushed after the updates that are scheduled inside of `componentDidMount`.

We should fix this inconsistency so that all callbacks have the same semantics. In my opinion, it makes most sense if a callback is flushed right after the update/top-level render it corresponds to, and we should change `setState` callbacks to behave that way. One way to implement this would be to unify `enqueueSetState` and `enqueueCallback` so that `enqueueSetState` et al accept a callback.

Or we could change the top-level callback to behave the way `setState` callbacks do. Either way, it would require a breaking change to React.

The question is whether we want to make a change now (and possibly release it in a 16.0 version of Stack) or if we should make Fiber match the current, inconsistent behavior and fix it later.

@facebook/react-core

**Comment by gaearon** [comment]
We did something. I don't remember what it was but I'll close this. If somebody is curious I bet @acdlite can answer what we did.
