### ISSUE TITLE
Attempted to update component `t`: What is `t`?

### ISSUE THREAD

**Issue by kevart** [facebook/react#8578]
*feature request*

**What is the current behavior?**
`Attempted to update component `t` that has already been unmounted (or failed to mount).`

**What is the expected behavior?**
`Attempted to update component `<ProperComponentName>` that has already been unmounted (or failed to mount).`

We do not have a component `t`. It would help if the error message would tell which component.

**"react": "15.3.2"**

**Comment by syranide** [comment]
It makes sense that this would be from a minified build of your code, where names would be mangled.

**Comment by gaearon** [comment]
Just like https://github.com/facebook/react/issues/8579, this is likely an issue with your code swallowing the original error first. As a result internal state gets corrupted and you get a weird error later.

**Comment by kevart** [comment]
That makes sense. Sorry about that guys. I'll try to find out where it happens.
