### ISSUE TITLE
[Feature] New JSX attributes

### ISSUE THREAD

**Issue by donlion** [facebook/react#8603]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
At @tattoodo we are trying to build a rss feed for delivering Instant Articles to Facebook. We are rendering the feed through our React setup but we are unable to provide the needed attributes on the root `<rss>` tag.
```Unknown prop `xmlns:content` on <rss> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop```

**What is the expected behavior?**
Attribute `xmlnsContent` (and probably some other rss-familiar attributes) transpiles to `xmlns:content`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v. 15.3.2

**Comment by aweary** [comment]
Thanks for the issue @donlion! As far as I know React does not support rendering RSS XML documents. At some point in the future, we intend to remove the attribute whitelist all together which may allow you to render any XML documents, but I don't believe this is something we intend to explicitly support.

cc @spicyj

**Comment by nickdeis** [comment]
Have a look at [careless](https://github.com/HenriJ/careless).
The author has not responded to how the code is transpiled, so I took the liberty of looking into it and made [careless-loader](https://github.com/nickdeis/careless-loader) for webpack.
I use it mostly to generate enterprise fun time xmls during builds, but it might fit your use case.

**Comment by spicyj** [comment]
React DOM doesn't support XML, even if we change the attribute whitelist. It has lots of HTML-specific logic. In the future someone could perhaps make a "React XML" that is XML-specific.
