### ISSUE TITLE
findDOMNode does not work on StatelessComponent?

### ISSUE THREAD

**Issue by vifird** [facebook/react#8615]
**1. Report a `bug`**  

**2. `findDOMNode` does not work on `StatelessComponent`**

**3. Detail**
Hello, I need to hide a component in its parent `A`( `A` is parent, `B` is child), while `B` is writen by others and i can't rewrite any code in it.  
`findDOMNode` can resolve this problems , but it seems useless on `StatelessComponent`, so how can i resolve it?  
Here is my code, thanks a lot.
```
class A extends React.Component {

  componentDidMount() {
    findDOMNode(this.refs.b2).style.display = 'none'
  }

  render() {
    return (
      <div>
        <B ref='b1'/>
        <B ref='b2'/>
      </div>
    )
  }
}

const B = ()=> {
  return <div>Page B</div>
}
```

**Comment by gaearon** [comment]
Can you wrap it in your own div that you have control over?

**Comment by vifird** [comment]
In face, we are developing a React's library( we wirte `A` component, our users write `B`).
Wrapping is a solution, but we think we shouldnot change the structure of user's code. So we want to resolve it by `findDOMNode`.

**Comment by gaearon** [comment]
Can you provide a more realistic example? It is not clear *when* you want to hide that child. Is this something B would know about? It would help if you explained the use case in more detail.

**Comment by vifird** [comment]
@gaearon It's a router library, supports multiple pages mounting at a time, and we need to hide pages that not matched location instead of unmounting them(by using 'display:none'). 
Or, is there another way to change the style of stateless components?
By the way, does `React-Native` supports `display:none` to hide a component?

**Comment by nitin42** [comment]
@vifird  Just modified the code for component B with [react-functional](https://github.com/davidmarkclements/react-functional). Its working!

```javascript
import React from 'react';
import functional from 'react-functional';

let render = () => {
  return (
    <div>
      Hello
    </div>
  );
}

export default functional({render});
```

**Comment by vifird** [comment]
@nitin42 Yeah, it works, and it's really a wonderful library. Thank you so much!
