### ISSUE TITLE
PureComponent not working with setState inside interval

### ISSUE THREAD

**Issue by davegri** [facebook/react#8624]
**Do you want to request a *feature* or report a *bug*?**

Report a possible bug

**What is the current behavior?**

Calling `setState` (with new state) insider a `setInterval` callback does not cause a re-render when using `PureComponent`. I've tried logging the next and previous state inside `shouldComponentUpdate` and they show up as identical even though they shouldn't be.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

Component should update

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest version

**Comment by gaearon** [comment]
Thanks for the report. Unfortunately it is not very helpful without a code example.
This is why the issue template includes this line:

>If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).

It is likely that you're mutating the state somewhere. However without code it's impossible to tell.
If you don't provide an example we'll have to close the issue because it is not actionable.

**Comment by davegri** [comment]
So when trying to reproduce the bug I realized that we were doing `this.state.count++` which was causing the mutation. thanks for the hint! 

would it be possible to add warning for state mutations similar to `redux-immutable-state-invariant`? this was a pretty tough one for us to debug.

cheers

**Comment by gaearon** [comment]
There was an attempt in https://github.com/facebook/react/pull/8265 but the author didn't continue working on it.

**Comment by aweary** [comment]
Closing since `PureComponent` + `setState` seem to be working fine 👍 

>would it be possible to add warning for state mutations similar to redux-immutable-state-invariant? this was a pretty tough one for us to debug.

@davegri you can track https://github.com/facebook/react/issues/2272 for updates on that
