### ISSUE TITLE
Can't stopPropagation when render subcomponents in componentDidMount()

### ISSUE THREAD

**Issue by yujiaze** [facebook/react#8625]
Here's my JS Bin Demo:

https://jsbin.com/ronuhefito/edit?html,js,output

I render `Child` in `Parent` `componentDidMount`

but when I dragging child, the parent triggers dragstart too!

**The same problem with `click` event**

I tried e.stopPropagation() e.nativeEvent.stopPropagation() and e.nativeEvent.stopImmediatePropagation() but they all useless

So I can't stopPropagation when render subcomponents in componentDidMount(), but I have to render child when parent is mounted.

**Comment by aweary** [comment]
@yujiaze you are not technically rendering `Child` as a child of `Parent`, you're rendering `Child` as its own root by using `ReactDOM.render`. They are separate render trees and I don't think events will actually propagate from one root to other; you just get two separate trees with their own events

> So I can't stopPropagation when render subcomponents in componentDidMount(), but I have to render child when parent is mounted.

You should render `Child` as an actual child of `Parent` by returning it from the `Parent`'s render method. If you need to defer rendering until you are sure parent has mounted, use state to set a flag.

```js
var Parent = React.createClass({
  getInitialState() {
  return { mounted: false }
  },
  onDragStart(e){
  	console.log('parent');
  	e.dataTransfer.setData('Text','parent')
  },
  componentDidMount(){
    this.setState({ mounted: true })
  }
  render(){
  	return (
    <div draggable='true' id='parent' onDragStart={this.onDragStart}>
      {this.state.mounted && <Child />}
    </div>
    )
  }
})

```

[Here's a working example](https://jsfiddle.net/r3LL2eee/)
