### ISSUE TITLE
Strange performance problem in Google Chrome - putListener appears in the timeline

### ISSUE THREAD

**Issue by mstijak** [facebook/react#8626]
**Do you want to request a *feature* or report a *bug*?**

A performance problem in the latest Chrome on Windows 10. Firefox/Edge work fine.

**What is the current behavior?**
Chrome freezes for a few seconds on the second render. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Please open http://pink-wren.surge.sh/.

In the first input type 2. This will cause that all items to be redrawn.
Observe how browser freezes for a few seconds. 
Afterward, everything works fine.

Chrome Inspector timeline reveals strange React behavior.

![image](https://cloud.githubusercontent.com/assets/433394/21426157/84cdf686-c84d-11e6-9958-54ecb5747689.png)

**What is the expected behavior?**
This should not happen.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I tried React 15.4.1 and 15.3.1 on Windows 10.

**Comment by shortenda** [comment]
After looking into this issue myself, I believe this is a dupe of https://github.com/facebook/react/issues/7227 and should probably be closed.

**Comment by mstijak** [comment]
Is the patch for #7227 included in React 15.4.2? 
I just tried it and the problem is still there.
This is not a real problem for me, so feel free to close the issue. 
My intention was to report strange behavior.

**Comment by shortenda** [comment]
(I'm not a contributor, I was just looking into this issue because it was affecting my application)

It looks like [the commit that fixed this](https://github.com/facebook/react/commit/64e7602b3b9af9a43fd2f3495d3b13a398bb94d9) is tagged for one of the 16.0 alphas. I can confirm that upgrading to the alpha fixed the performance issues that I was seeing.

**Comment by mstijak** [comment]
@shortenda I just tried with the latest 16.0 alpha and the issue is gone. I'll close the issue. Thanks for the info.

**Comment by gaearon** [comment]
https://github.com/facebook/react/commit/64e7602b3b9af9a43fd2f3495d3b13a398bb94d9 was released in 15.3. GitHub's branch display for commits is messed up.

16 alpha is completely rewritten so maybe it doesn't hit some bad path, but it would be nice to learn what's causing this.

I'd like to reopen so that we can at least investigate some time in the future and confirm what was causing this.

**Comment by monkindey** [comment]
That is interesting. It will make more sense if @mstijak provide the React code you wrote.

**Comment by mstijak** [comment]
@monkindey Unfortunately, it's difficult to isolate a pure React example. I'm working on a framework that uses React for rendering and provides other features on top of it, e.g. two-way data binding. 

If you want to run the example on your machine, you should clone [Cx repo](https://github.com/codaxy/cx) and start the application using `yarn run litmus`.

**Comment by monkindey** [comment]
I think maybe because of [these line of the code](https://github.com/codaxy/cx/blob/master/packages/cx-core/src/widgets/List.js#L265-L268)

According to the documentation [mention](https://facebook.github.io/react/docs/handling-events.html) in the last

> The problem with this syntax is that a different callback is created each time the LoggingButton renders

**Comment by mstijak** [comment]
@monkindey If you read the original post, you'll find that strange behavior happens only if you type number 2 in the first input field and only for the first time. Creating event handlers in each render cycle is not optimal, but it doesn't explain 4s delay happening only once. Something else is going on here...

**Comment by gaearon** [comment]
Do you think you could try again with React 16 and report whether the issue still exists?

**Comment by mstijak** [comment]
It's gone.
