### ISSUE TITLE
Isomorphic app throws incorrect error when using legacy refs and unstable_handleError (React DOM tree root should always have a node reference)

### ISSUE THREAD

**Issue by taylorstine** [facebook/react#8630]
https://jsfiddle.net/taylorstine/7o3e6hkd/

I am building an application that renders a React component on the server and then sends the markup to the client, where the client side React rendering takes over.  I'm wrapping my root component in react hot loader's `<AppContainer/>` component.  The `<AppContainer/>` component uses the new `unstable_handleError()` method to catch errors that occur on the initial mount.  

Let's say I put some code in my components render method that's guarenteed to throw an error on the client but not on the server, maybe something like: 

```
/**Evil Component**/
render(){
   if (typeof window !== 'undefined') {
      throw new Error("GOTCHA!")
   }
   return <div>heyyyy</div>
}
```
Now, let's say along side that component I have another component that uses a legacy ref.  Something like this
```
/**Happy Component**/
render(){
   return <div ref="this-should-be-cool">Let me do me</div>
}
```

When my client calls `ReactDOM.render()`, the following error is thrown:
```
React DOM tree root should always have a node reference
```

Which is incorrect.  Note that if I was not using server side rendering, the correct error would be thrown, i.e.
```
GOTCHA
```

Clearly the solution is to not use legacy refs, but is this a bug? Or have string refs been deprecated?

**Comment by gaearon** [comment]
Please provide a project reproducing the problem.

**Comment by gaearon** [comment]
Oops never mind you did. I'll try to take a look!

**Comment by gaearon** [comment]
React 16 released official support for error boundaries (`unstable_handleError` is now `componentDidCatch`). It's fully supported on the client side, and not supported at all on the server side (since that would be incompatible with forward-only streaming). On the server side, just use `try` / `catch`.

There shouldn't be more obscure errors though.
