### ISSUE TITLE
[FeatureRequest]Custom PureComponent(compareLevel)

### ISSUE THREAD

**Issue by xialvjun** [facebook/react#8643]
I want a feature.
The now situation is just `class MyComponent extends PureComponent{}`, then `PureComponent` will do the shallow compare on `props and state` just one level for us.

But I found it's common that *In our redux store, we have a long array A, then we do a filter in the `mapStateToProps` and get an array B.  We may push/remove object to/from A, that may/maynot change B. Since B is always rebuilt, PureComponent will always rerender.*

I hope PureComponent to do the shallow compare more then one level.

So I came up this idea.
```js
class MyComponent extends PureComponent(2) {}

// and we can let this to not broke any old code
assert(PureComponent(1), PureComponent)

// Eh, if you like it, maybe we can
class MyComponent extends PureComponent(2, 1) {}
// in above, 2 is the level to compare at props, 1 is the level to compare at state.
```

Hope you consider it.

**Comment by yaycmyk** [comment]
This is pretty specific, you should just extend React.Component and implement the desired functionality in shouldComponentUpdate.

You can then extend your special version of Component as necessary.

**Comment by gaearon** [comment]
Yep, just implement custom `shouldComponentUpdate` if you need more control.
