### ISSUE TITLE
ReactDom.mount =  ReactDOM.render Flipped and curried

### ISSUE THREAD

**Issue by BLamy** [facebook/react#8654]
Would be a micro optimization to appease the functional gods but the order of `ReactDOM.render`'s arguments  has always felt backwards to me. 

I should say **were** I want the app to render and **then what** I want to render. 

Might sound kind of useless at first but I actually have built something where I was rendering different components into the same div based on something that was happening outside of react. 

```js
import { curry, flip } from 'ramda'
const mount = curry(flip(ReactDOM.render))
const render = mount(document.getElementById('content'))

...

if (otherFramework.tabIndex === 1) {
   render(<Home />)
} else if (otherFramework.tabIndex === 2) {
   render(<About />)
} else {
   render(<FourOhFour />)
}
```

**Comment by acdlite** [comment]
It's unlikely we'll do this given that what you're asking for can easily be implemented in user space.

However, in the future we'll likely have a separate API for mounting, updating, and unmounting the root of your application. Something like:

```js
const container = ReactDOM.createContainer(domEl);
container.render(<App />);
container.unmount();
```
