### ISSUE TITLE
WebComponents now requires class syntax

### ISSUE THREAD

**Issue by rektide** [facebook/react#8656]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Modern browsers no longer permit `Object.create(HTMLElement.prototype)` as a means of creating Web Components. See:

> It's not possible to use custom elements without ES6 classes.

- @domenic, https://github.com/w3c/webcomponents/issues/587#issuecomment-253993830

[WebComponent demo](https://github.com/facebook/react/blob/7dc5f91d886fcfd5bd9db40449370ce5d88ea188/examples/webcomponents/index.html#L39) uses this now-removed means of creating WebComponents.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Running the linked webcomponent demo will throw an Uncaught TypeError. 

**What is the expected behavior?**

The demo executes & renders.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I'm not sure when this change went into force in browsers. Chrome m55 that I'm on is broken. m54 was broken.

**Comment by gaearon** [comment]
Fixed in docs.
