### ISSUE TITLE
Facebook Engineers - Thank You For 2016

### ISSUE THREAD

**Issue by gabegreenberg** [facebook/react#8663]
To all the Facebook Engineers working on [open source](https://code.facebook.com/projects/),

We at [Reactiflux](http://www.reactiflux.com/) just wanted to take a moment to thank you for all your hard work in 2016. Your job isn’t easy. You have a million requests coming at you all the time from both your internal teams and the external community. Dan Abramov once compared managing issues and pull requests to [juggling chainsaws on fire](https://twitter.com/dan_abramov/status/804365646540709888). Yes, we know all of you get paid really well to do open source full time, and that your work meets Facebook’s needs, but we think that you have gone above and beyond in the way that you have treated the community.

The way that you guys respond to emails and Twitter mentions. The attention you give to each issue/PR. The time you give to different organizations doing podcasts and AMAs. The list goes on.

We’ve personally seen an amazing humility in each of you, and it’s a pleasure to be around you wonderful people. Thank you for what you do and the excellence you put into all your efforts.

We’d like to invite the React community to reply to this thread with your own “thank you” comments to the team at Facebook. Let’s show them how grateful we are! Feel free to include experiences with the team or just how the React ecosystem has helped you as a developer.

Sincerely,

On behalf of the Reactiflux community:
@gabegreenberg
@markerikson
@KyleAMathews 
@taion
@jquense
@vcarl
@benigeri 
@Phoenixmatrix

**Comment by antoligy** [comment]
Thanks! ☺️

**Comment by LordRobust** [comment]
Thank you! :)

**Comment by zwhitchcox** [comment]
Thank you!

**Comment by FlayaN** [comment]
Thanks, we really appreciate it! Keep it up :)

**Comment by superherointj** [comment]
Thanks! :)
Much Love. S2

**Comment by Jakehp** [comment]
Thanks for all the work 👍

**Comment by makenova** [comment]
Thank you! React Native helped me finally get into mobile development. RN had provided the motivation to level up my dev skills.

**Comment by gaearon** [comment]
Awwww. Thanks.

**Comment by miralize** [comment]
Just had my first brief experience with React Native and I'm just blown away with what I can do with it in just over 2 hours of playing around with it. Baby steps, but a step forward all the same. Sincerely appreciate the hard work from everyone who has contributed to React!

**Comment by AG-Systems** [comment]
Thank you!

**Comment by timarney** [comment]
Thank You for caring beyond the code.  Going over and above ... paying attention to what people are saying, thinking and understanding in the community.  Your efforts are truly appreciated.

**Comment by thejameskyle** [comment]
Aww... *suck-ups*

**Comment by caelon** [comment]
Thank you for writing a powerful, yet easy to work with, tool.

**Comment by bvaughn** [comment]
Nice way to end the year. Group hug :grin:

**Comment by introbig** [comment]
thanks!

**Comment by ryanflorence** [comment]
Thanks for being the cornerstone of the coolest job I've ever had :)

**Comment by joshmanders** [comment]
Seriously, I've never found a nicer, more helpful group of people in my life. You guys are the best. Thank you.

**Comment by g3r4n** [comment]
thanks!

**Comment by soorajvnair** [comment]
Absolutely agree. An amazing group of people. Thank you so much guys!. :)

**Comment by oksas** [comment]
Yall are great, React is 🔥 🔥

**Comment by augbog** [comment]
Thank you guys :) not only have you been super supportive in bringing changes the community has wanted in React, but you have also done a wonderful job in bringing changes that make development easier.

**Comment by Tueti** [comment]
Thanks guys! 😁👍

**Comment by QuantumInformation** [comment]
+1E100

**Comment by aymericbouzy** [comment]
Thank you so much ! React is the future no doubt about it, we owe so much of our own success to you, we couldn't be more grateful !

**Comment by nicolas-schmitt** [comment]
Thank you!

**Comment by FMCalisto** [comment]
Thank you!

**Comment by chandlervdw** [comment]
Thank you all!

**Comment by rricard** [comment]
Thank you for the awesome work!

**Comment by dominiceden** [comment]
Thank you! React has been a joy to work with since I picked it up this year and I can't wait to go further with it in the future. A huge part of it is the community, where I've seen core contributors take the time to discuss architecture decisions around React apps with developers and offer insight into why things work the way they do. I haven't ever seen a movement as strong as this before. Thanks again!

**Comment by vovanok1992** [comment]
React is awesome. Thank you !

**Comment by iraquitan** [comment]
Really thank you all for the amazing work!

**Comment by avanslaars** [comment]
Working with React is a pleasure, both because of the technology and the community. For both of those things, thank you!

**Comment by Faolain** [comment]
Thanks for everything, the impact your team has made cannot be overstated.

**Comment by inertum** [comment]
Thank you!

**Comment by aweary** [comment]
You guys are awesome, it's been an absolute pleasure working with you and learning from you ❤️

**Comment by persianturtle** [comment]
Thank you all for the wonderful work!  I've been working in AngularJS for over two years and am building my next big project with React for the simple reason that adding HTML to JS allows for more failures at compile time.  I can't wait to learn how to separate application state from its presentation with Redux.  It's brought me a new excitement and I'm incredibly thankful.

**Comment by droganov** [comment]
Thank you!

**Comment by mattferrin** [comment]
Thanks.

**Comment by quicksnap** [comment]
Thank you so, so much! Since I do engineering for a living, React actually makes my life better continually.

**Comment by acdlite** [comment]
The gushy positivity of this thread is almost too much to handle. Almost.

**Comment by dtschust** [comment]
Thanks!

**Comment by dmitriiabramov** [comment]
thank you! ❤️

**Comment by Daniel15** [comment]
Thanks for all the thanks! <3

**Comment by Daniel15** [comment]
Thanks for all the thanks! ❤️ 

And thanks to everyone I've worked with at Facebook for being so awesome :)

**Comment by jimmycarry** [comment]
thank you

**Comment by ShinyLeee** [comment]
Thank you! ❤️

**Comment by mattcolman** [comment]
👍

**Comment by Youmoo** [comment]
Thank you. :heart:

**Comment by FranciscoGileno** [comment]
I remember reading this issue "[Optional Sass Support](https://github.com/facebookincubator/create-react-app/issues/78)" on create-react-app and someone wrote:

> No Testing, No LESS or Sass support, No Hot reloading of components, So how is this project useful if you still have to add these things to ease your development?

Which Dan Abramov answered:

> We’re sorry if it’s not useful to you yet. We think that many people learning React would appreciate even the current feature set...

Which was replied:

> Sorry. Don't take my comments as being rude. I think this is a fantastic project.

That was a very important lesson for me.

Thanks.

**Comment by cylim** [comment]
Thanks. Facebook initialitive in Open Source helps a lot.

**Comment by jjanssen** [comment]
Much ❤️

**Comment by rafayepes** [comment]
Thank you all! ❤

**Comment by andreafalzetti** [comment]
👍

**Comment by steveluscher** [comment]
❤️

**Comment by nicerr** [comment]
Thanks 💐 Really fantastic support and treatment of the Open Source Community 👍🏻

**Comment by kstratis** [comment]
Thanks guys! You are doing an amazing job! Much love! ❤️ ❤️ ❤️

**Comment by lvtrvd** [comment]
You all are great and React is Awesome  :)

**Comment by saada** [comment]
Thank you for the best developer experience across all devices!!!
🤠🤠🤠

**Comment by den1k** [comment]
We wouldn't have been able to iterate that incredibly fast on vimsical.com without you guys. You're pushing the envelope. Thank you!

**Comment by akabiru** [comment]
Thanks for all your hard work! 👍

**Comment by themre** [comment]
Thanks and keep up an amazing work!

**Comment by urbanvikingr** [comment]
THANK YOU for leading with a good example for us to follow! Happy to say that HackerHours.org is just one of the places where your good work is being followed.

**Comment by raysmithdev** [comment]
Thanks guys. React & React Native have made developing fun again 🙂

**Comment by AnhHT** [comment]
Thanks for your awesome work.
From Vietnam with ❤️

**Comment by AbdoulayeKarimTraore** [comment]
Thanks for everything !! I use react-native and it's just awesome.

**Comment by schuchowsky** [comment]
Thank you! React for me went way beyond a great code - it's maintainers, community and ecosystem gave me a new perspective of work and a new way of life!

**Comment by idolize** [comment]
React has made web development so much fun! Can't thank you guys/gals enough 👍

**Comment by kabirbaidhya** [comment]
Thank you!! Keep doing good work. We need people like you guys in the community to grow and move ahead :+1:

**Comment by tomsapps** [comment]
+1 😝

**Comment by no0dly** [comment]
Thank you!

**Comment by rodrigopivi** [comment]
Thank you all!

**Comment by machycek** [comment]
Thanks to everyone! 👏🏼

You have helped our team to ship and maintain product in much reliable and faster way. Hard to describe how grateful I'm for your patience and decision you made to make our lifes easier.

Happy 2017 🎉 🍾

![image](https://cloud.githubusercontent.com/assets/8449312/21591538/6b9e3ec6-d105-11e6-98e6-cc685d9fec07.png)

**Comment by sanketsahusoft** [comment]
Thank you React community! You made our 2016 a year-to-remember!

-- Loads of love from The [NativeBase.io](http://NativeBase.io) team

**Comment by kastermester** [comment]
Cheers guys! :)

**Comment by jhgg** [comment]
Thank you React community & devs! Wouldn't have been as fun building Discord without this awesome framework!!

❤️ and ⚒ from the [Discord](https://discordapp.com/) team!

**Comment by rawrmaan** [comment]
THANK YOU beyond words for your continued work on React and React Native which have both allowed me to accomplish more in my one-man dev shop, and in a bigger team, than I ever thought possible. I'm so excited for what you have coming in 2017.

**Comment by ronal2do** [comment]
+1

**Comment by dmurawsky** [comment]
+1

**Comment by marceloogeda** [comment]
+1

**Comment by thomasgwatson** [comment]
Thank you, so sweet to see a community and contributors eco-system done right!

**Comment by madeinfree** [comment]
Thanks all :D

**Comment by aeleftheriadis** [comment]
Thanks for the great work. Bring more innovations this year.

**Comment by andela-Jaderibigbe** [comment]
Thanks for the great work and awesomeness!!! Bring more 🔥 this year!!!

**Comment by aitherios** [comment]
Thanks!! =D

**Comment by brentvatne** [comment]
❤️

**Comment by lvnr** [comment]
Thanks a lot! ❤️

**Comment by ColCh** [comment]
Thank you! ❤❤❤

**Comment by chagasaway** [comment]
thanks (:

**Comment by Onra** [comment]
Thank you ! 👍

**Comment by jvorcak** [comment]
Thanks a lot!!! ❤️  👍

**Comment by Satya5614** [comment]
Thank you React community!! :)

**Comment by chapati23** [comment]
React Native has literally saved our team _hundreds_ of hours (and thousands of $…) in our current project. Thanks for the great work :)

**Comment by lovio** [comment]
Thank you!

**Comment by maierson** [comment]
Wonderful indeed. Thank you !

**Comment by sorenjuul** [comment]
Awesome job. Thanks

**Comment by hunthunthunt** [comment]
Thanks team, I love working with React, it's an amazing library that exemplifies the spirt of open source

**Comment by vinaydate** [comment]
Thank you

**Comment by inframobliza** [comment]
You rock! Thanks

**Comment by diogoreus** [comment]
You rock! Thanks

**Comment by tsiiiboho** [comment]
❤️ - thanks guys.

**Comment by kdenz** [comment]
Thank you all very much!!!! React and React Native are simply brilliant!!!

**Comment by supernova23** [comment]
Thank you

**Comment by eriklharper** [comment]
React has been the best programming community I've ever been involved with and a lot of the credit  goes to Facebook and their extraordinary philosophy of contributing to open source.  Thank you, Thank you, Thank you :)

**Comment by RussMax783** [comment]
Thanks a ton!  You have all taken the development experience to a whole new level!

**Comment by jahe** [comment]
Awesome work. Thank you! :)

**Comment by RustyF** [comment]
Thanks for all your declarative lovelyness and here's to great new things in 2017!

**Comment by derekalia** [comment]
Thank you!

**Comment by ccruz2886** [comment]
Thanks you!!!... you guys has been doing an awesome Job.

**Comment by okbel** [comment]
Thank you

**Comment by cameronmaske** [comment]
Thank you!

**Comment by clementeghuerta** [comment]
Thank you!

**Comment by GramParallelo** [comment]
Obrigado!

**Comment by trejoramiro** [comment]
Thank you for the hard work you put into React!

**Comment by max-marcus** [comment]
Big thanks!

**Comment by alfonsoperez** [comment]
Thanks for all your hard work!, at my company and me on a personal level we are very grateful for all the amazing stuff you guys put out there on a daily basis. Keep it up!

**Comment by shek8034** [comment]
Thanks to all of you brilliant minds. You changed my 2016 and hence my life.

**Comment by gaearon** [comment]
Thanks again to all of you!
Most of us are from vacations by now and we’re working to ship some awesome stuff to you in 2017.

💜

**Comment by Trufinol** [comment]
Thanks!

**Comment by gregblass** [comment]
Thank you! You all have doubled my career opportunities and re-invigorated my love for coding and day-to-day enthusiasm with React Native!
