### ISSUE TITLE
jquery-bootstrap is not working

### ISSUE THREAD

**Issue by flik** [facebook/react#8664]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**Just run the example jquery-bootstrap is not working**

**What is the expected behavior?**
jquery-bootstrap is not working and showing blank page.

**version: 15.4.1 and OS Windows 7**

**Comment by mattvagni** [comment]
@flik This example (and most other examples) uses a build of babel to convert the example code on the fly to ES5. For this reason this example only works if you run a little http-server from the root of the react folder.

Easiest way (probably) to do is to install: https://www.npmjs.com/package/http-server globally:
```bash
npm install -g http-server
```

Then (from within the react folder) run: `http-server .`

You can then see the example on [http://127.0.0.1:8080/examples/jquery-bootstrap/](http://127.0.0.1:8080/examples/jquery-bootstrap/)

**Comment by sjmarshy** [comment]
@flik Is this still an issue?

**Comment by aweary** [comment]
It is not, since this example is no longer in the repo!
