### ISSUE TITLE
[Question] hostParent vs rootNodeID

### ISSUE THREAD

**Issue by aleclarson** [facebook/react#8666]
I'm curious what the `_hostParent` and `_rootNodeID` represent on the `_reactInternalInstance`.

Also, is there a method for getting a unique ID for a composite component, like `ReactNativeComponentTree.getNodeFromInstance` does with native components?

Or do composite components not have a unique ID?
Thus, I would need to create a unique ID manually.

**Comment by gaearon** [comment]
Curious what is your use case? Are you creating a renderer? Those are private APIs and will change significantly.

**Comment by aleclarson** [comment]
@gaearon I'm only traversing the mounted component tree. Is the `ReactNativeComponentTree` API going to change significantly? Or are you just referring to the internal properties I mentioned?

**Comment by gaearon** [comment]
ReactNativeComponentTree is a private API and can significantly change in any version. Please don't rely on it. All public APIs are documented on React and React Native websites. Everything else is internal.

**Comment by ajwhite** [comment]
@gaearon is there a good way to traverse the component tree? I've been walking it by following the `_owner` references. This is purely educational by building some personal dev tools as a learning process of React's internals; such as highlighting renders, visually outlining ancestry paths, etc.

**Comment by gaearon** [comment]
Not via official APIs. In Fiber, you can traverse parents on internal data structure, but in Stack, there is only a way to jump between owners.

**Comment by gaearon** [comment]
Closing as there isn't a specific issue here.
