### ISSUE TITLE
Document Profiling Components in Timeline

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8675]
Basically we need to move [this section](https://facebook.github.io/react/blog/#profiling-components-with-chrome-timeline) to some permanent place in the docs.
For example, [this page](https://facebook.github.io/react/docs/optimizing-performance.html) might be a good place for it.

**Comment by madeinfree** [comment]
I would like to help, have some recommend for this move ? or just move [section](https://facebook.github.io/react/blog/#profiling-components-with-chrome-timeline) into [page](https://facebook.github.io/react/docs/optimizing-performance.html) lowermost of article ?

**Comment by gaearon** [comment]
Fixed by #8680.
