### ISSUE TITLE
Docs look weird on small widths

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8676]
Note the accidental top bar:

<img width="401" alt="screen shot 2017-01-03 at 15 23 29" src="https://cloud.githubusercontent.com/assets/810438/21612335/a23b8808-d1c8-11e6-8006-17bd5fa9f07a.png">

Is this a misplaced tag? Also can see this when any doc page is loading.

**Comment by karthikchintapalli** [comment]
I would like to work on this. This is my first contribution to react, so help is welcome. :)

**Comment by gaearon** [comment]
@karthikchintapalli 

Cool! You can follow these instructions to get docs running locally:
https://github.com/facebook/react/blob/master/docs/README.md

Then you'll need to diagnose where the issue is coming from.

**Comment by karthikchintapalli** [comment]
@gaearon Thank you! Will get back in case of more questions.

**Comment by karthikchintapalli** [comment]
@gaearon This seems to be happening only for this particular blog post. Also, The extra text is present even on larger widths. It is just covered by the navbar. The page content starts noticeably lower when compared to the other posts. Further, the favicon is missing for this particular post when the page loads.

**Comment by karthikchintapalli** [comment]
@gaearon Ok, I think I get the issue. In the markdown, The first few words of the content, "Create React App" are a link. So, when the html file is generated, the `<meta property="og:description" content="" />` tag's content property has `<a>` tags within it. But, it's only supposed to take a string.

![screen shot 2017-01-04 at 12 18 39 pm](https://cloud.githubusercontent.com/assets/15844775/21633762/21c05658-d278-11e6-8596-0663041b73c7.png)

**Comment by karthikchintapalli** [comment]
@gaearon This is a fix I can think of. In docs/_layouts/default.html - 
```
{% if page.excerpt %}
{% assign type = 'article' %}
{% assign sectionTitle = 'React Blog' %}
{% assign description = page.excerpt | remove: '<p>' | remove: '</p>' %}
``` 

To

```
{% if page.excerpt %}
{% assign type = 'article' %}
{% assign sectionTitle = 'React Blog' %}
{% assign description = page.excerpt | remove: '<p>' | remove: '</p>' | remove: '<a>' | remove: '</a>' | remove: '<strong>' | remove: '</strong>'%}
``` 

I'm sure there would be a more general way to do this for all tags, though. Any suggestions?

**Comment by gaearon** [comment]
This makes sense! Wanna send a PR?

**Comment by karthikchintapalli** [comment]
Just sent a PR with the same changes :)
