### ISSUE TITLE
Shorthand CSS properties can cause style inconsistencies

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#8689]
I'm reporting a **bug**.

## What is the current behavior?

1. Render a host component with a `style` that contains both a [shorthand CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) and an over-writing longer form of the property (eg `overflow` and a conflicting `overflowX` and/or `overflowY` property).
2. Update the host component (re-render) with the same shorthand property (eg `overflow`) but remove the longer form property (eg `overflowX`).
3. The host component style is now invalid.

### Examples

This bug can be reproduced here: https://plnkr.co/edit/7O1xZUqbD13ST2BAxcm9?p=preview

*Update*: I have since updated the Plnkr to use `border` instead of `overflow` since it makes the problem more immediately obvious to spot.

#### Example
1. Render `style={{ overflow: 'hidden', overflowY: 'auto' }}`
1. Render `style={{ overflow: 'hidden' }}`
1. Expected: `<div style="overflow: hidden;" />`
1. Actual: `<div style="overflow-x: hidden;" />`

#### Alternate example
1. Render `style={{ overflow: 'auto', overflowX: 'hidden', overflowY: 'hidden' }}`
1. Render `style={{ overflow: 'auto' }}`
1. Expected: `<div style="overflow: auto" />`
1. Actual: `<div style="" />`

You can also reproduce this bug with properties like `margin`, `padding`, `border`, etc.

#### Caveats

Note that if the shorthand value changes between renders things work as expected (because React explicitly updates the shorthand style).

I know this is very edge-case behavior and so may not be worth fixing. I originally noticed it by way of issue bvaughn/react-virtualized/issues/525.

## Which versions of React / browser / OS are affected

This bug reproduces in Chrome, Firefox, and Safari using React 15.4.1 as well as the unreleased `ReactDOMFiber` renderer.

**Comment by bvaughn** [comment]
I think the underlying cause here is that `ReactDOM` only updates the `style` attributes that have changed (eg `overflowX`, `overflowY`). But removing one or both of these properties from a `CSSStyleDeclaration` impacts the `overflow` property as well, resulting in a `CSSStyleDeclaration` instance that doesn't _necessarily_ match the most recently specified `style` object..

I was not able to reproduce this issue in a unit test (using Jest) because Jsdom doesn't trickle down the effects like the major browser vendors seem to (eg updating `overflowX` doesn't impact `overflow`).

This issue is probably not worth fixing. It's probably too obscure.

**Comment by syranide** [comment]
Overlapping styles are not allowed. The solutions are very costly and it was (AFAIK) decided that it is not reasonable to support it. Warnings would be very helpful but that hasn't be done yet. There are a number of issues discussing it if you're interested in more information.

**Comment by bvaughn** [comment]
> Overlapping styles are not allowed

That's news to me. It may be the right decision but I don't think it's communicated clearly (at least not that I've seen). And it _works_ most of the time which may lead someone to assume it's supported.

> The solutions are very costly

Fair enough. I was curious how costly [`cssText`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssText) would be compared to [manually managing the updated properties](https://github.com/facebook/react/blob/df0d2a5106a225ae94ec978a99342443d57f83c2/src/renderers/dom/stack/client/ReactDOMComponent.js#L981-L998) as we are currently doing but I have not done any benchmarking.

**Comment by bvaughn** [comment]
Searching through React issues now I do see this mentioned a few other places (eg #5397). When I first observed this issue it was specific to `overflow`. I didn't immediately realize it affected all shorthand properties and so when I searched for pre-existing bugs- I failed to find them because my search was overly narrow.

**Comment by bvaughn** [comment]
I'll close this issue as a dup of #6348 and #5397.

Thanks @syranide!

**Comment by esr360** [comment]
Sorry to comment on an old and closed issue but is there no where currently open to discuss this issue? I'm facing it here https://codesandbox.io/s/elated-flower-zxvkf?file=/src/App.js and don't really like that "avoid using short-hand properties" is being pushed as an acceptable Developer Experience, especially for CSS enthusiasts. 

Border, for example, is an extremely common property. To avoid this issue I have to author my styles like this:

```js
borderWidth: '1px',
borderStyle: 'solid',
borderColor: 'blue'
``

Instead of 
```js
border: '1px solid blue'
``

Whilst I understand there are costly performance issues meaning a solution is not viable, I'd still like the issue to be considered valid, and open (as I believe it _is_ still valid, and it is _not_ yet solved). Thanks.
