### ISSUE TITLE
Expected onBeforeMountComponent() parent and onSetChildren() to be consistent

### ISSUE THREAD

**Issue by MicheleBertoli** [facebook/react#8692]
**Do you want to request a *feature* or report a *bug*?**
It looks like a bug.

**What is the current behavior?**
Setting the state before rendering a component with the test renderer, shows a warning in the console:

> Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).
Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).

In the following example, it weirdly happens consistently the third time you run it, while in other more complex scenarios it does it earlier.

The steps to reproduce the issue are the following:

1. first of all, create an app and install the renderer
  ```sh
  create-react-app my-app
  cd my-app
  yarn add react-test-renderer
  ```

2. then, add the following button to the `App`
  ```jsx
  import renderer from 'react-test-renderer'

  // ...

  <button
    onClick={() => {
      this.setState({})
      renderer.create(<div />).toJSON()
    }}
  >💥</button>
  ```

Here is a demo:

![renderer](https://cloud.githubusercontent.com/assets/1308971/21671313/759126dc-d312-11e6-9261-24ee3387b65a.gif)

⚠️ I understand this is not a common way of using React and the Test Renderer. 
I'm more interested in knowing the reasons behind the problem and eventually see if there are some workarounds to apply.
What I'm trying to do is to serialize components and send them to an endpoint (see [snapguidist](https://github.com/MicheleBertoli/snapguidist)).

**What is the expected behavior?**
Ideally, there should not be any warning.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`react v15.4.1`
`react-test-renderer v15.4.1`

I have been able to reproduce the issue on the latest versions of Chrome, Firefox and Safari on MacOS.

**Comment by etiennedi** [comment]
I'm having the same Issue wihtout using `react-test-renderer`. I'm getting the same error after randomly clicking inside a Modal component (I've tested with both `react-modal` and `react-responsive-modal`). Rendering the same content inline (instead of inside a modal) does not produce any errors.

I'm using `react@15.4.2` and `react-dom@15.4.2` The only scenario where I don't see the error above is when downgrading to 15.3.2.

**Comment by gaearon** [comment]
As for OP post, I don't think we explicitly support this use case. It's a bit unexpected but we probably won't be looking into it soon. Feel free to investigate a fix (I think it might have to do with needing to call `onBeforeMountComponent` and `onSetChildren` from the test renderer, just like ReactDOM renderer does it. You can search the code for these calls.)

@etiennedi 

Your case sounds more like a bug. However we can't investigate it without a minimal reproducing case.

**Comment by alvov** [comment]
@MicheleBertoli We're also having a similar issue (well, kind of). In our tests we render components both with `react-test-renderer` (`create()`) and `react-addons-test-utils` (`renderIntoDocument()`) which use different`_debugID` generators. Therefore we get the ids conflicts which are reported by `ReactComponentTreeHook.js`.

Funny thing is, we get a conflict even if we render the same component by these two utils as there's a difference in how `_debugID` is generated for text elements: `react-test-renderer` generates them incrementally ([getNextDebugID.js](https://github.com/facebook/react/blob/6eebed0535a5e28effb7200783cede7a4bdab7ec/src/shared/utils/getNextDebugID.js)) while `ReactDOMComponent.js` uses the parent id [with an opposite sign](https://github.com/facebook/react/blob/0585ee8b22069f20797d3c4d210d7e2d1f62a416/src/renderers/dom/stack/client/ReactDOMComponent.js#L178) (still not sure I got that whole thing right though).

Anyway, I have to agree that this case is pretty edgy.

**Comment by gaearon** [comment]
We’re probably not going to fix this in React 15.
React 16 won’t have the `onBeforeMount*` and similar hooks altogether so I’m closing this.
