### ISSUE TITLE
Warnings can be as clean as validateDOMNesting?

### ISSUE THREAD

**Issue by lomocc** [facebook/react#8701]
**We can see the *validateExplicitKey* warnings like this:**

![1](https://cloud.githubusercontent.com/assets/2075138/21709682/fbb1f794-d41d-11e6-8e2e-f722bdcf589f.png)
It hard to see the path of components.

**We can see the *validateDOMNesting* warnings like this:**

![2](https://cloud.githubusercontent.com/assets/2075138/21709683/fbe7d0bc-d41d-11e6-854e-c107154342e1.png)

**Warnings can be as clean as validateDOMNesting?**

**Thanks.**

**Comment by lomocc** [comment]
**I also think the words as ‘in ... ( create by ... )’ is unnecessary.**
**And the component name appeared 2 times.**

**Comment by gaearon** [comment]
We actually went the other way, and now show the stack in all cases.
The good thing about the stack is that if you enable [this Babel plugin](https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source) in development, you will see **filenames and line numbers** there.

We think it's valuable enough that all warnings should now show the component stack.

If you have specific suggestions on how to improve the stack format, please file an issue!
Thanks.
