### ISSUE TITLE
Is _instance pointing to _ReactInternalInstance & _ReactInternalInstance pointing to _instance, expected Structure ?

### ISSUE THREAD

**Issue by sanjay1909** [facebook/react#8708]
<img width="894" alt="screen shot 2017-01-07 at 09 26 55" src="https://cloud.githubusercontent.com/assets/755489/21743657/7e2c6ee6-d4bb-11e6-9964-9d2469e945e4.png">

I was playing with the examples understand the internal code flow of React's setState.
I noticed that **ReactCompositeComponentWrapper** Object had reference to **_instance** Object which in turn had reference to ReactCompositeComponentWrapper Object as **_ReactInternalInstance**. Is that an expected structure ?

**Comment by aweary** [comment]
Yes, it is intentionally a doubly linked structure. `ReactCompositeComponentWrapper` is an internal only and wraps user-defined composite components. It holds a reference to the instance of the user-defined component that is defined [when it is mounted](https://github.com/facebook/react/blob/eca5b1d48e71218800156ce474ec79b990b09fbd/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L263). Then `ReactInstanceMap` is used to [store a reference to the internal wrapper on the public instance](https://github.com/facebook/react/blob/eca5b1d48e71218800156ce474ec79b990b09fbd/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L265-L266).

If you look at [`ReactInstanceMap`](https://github.com/facebook/react/blob/master/src/renderers/shared/shared/ReactInstanceMap.js) it has some more information in the doc comments

> `ReactInstanceMap` maintains a mapping from a public facing stateful  instance (key) and the internal representation (value). This allows public methods to accept the user facing instance as an argument and map them back to internal methods.

**Comment by gaearon** [comment]
(Note these are private implementation details and will change in future versions.)

**Comment by sanjay1909** [comment]
Thanks for the clarification, it was really helpful
