### ISSUE TITLE
When children is Array, the error message of validateChildKeys not consistent.

### ISSUE THREAD

**Issue by lomocc** [facebook/react#8709]
**validateChildKeys results were inconsistent**
```js
// ReactElementValidator.createElement
    if (validType) {
      for (var i = 2; i < arguments.length; i++) {
        validateChildKeys(arguments[i], type);
      }
    }
```
```js
// ReactElement.createElement
  var childrenLength = arguments.length - 2;
  if (childrenLength === 1) {
    props.children = children;
  } else if (childrenLength > 1) {
    var childArray = Array(childrenLength);
    for (var i = 0; i < childrenLength; i++) {
      childArray[i] = arguments[i + 2];
    }
    if (process.env.NODE_ENV !== 'production') {
      if (Object.freeze) {
        Object.freeze(childArray);
      }
    }
    props.children = childArray;
  }
```

**When *childrenLength* equals 1, the result is different.**

**And try this for the result: [http://jsbin.com/nonucegozo/edit?html,output](http://jsbin.com/nonucegozo/edit?html,output)**

**sorry, My English is on the way, I use the google translate.**

**Thanks.**

**Comment by aghoneim92** [comment]
@lomocc the reason the behavior is different is because when childrenLength > 1 it means the React.createElement function was called with multiple children arguments and not with one array containing all the children. In this case, the key prop is not required. It's equivalent to this JSX:
```
<div>
  <p>1</p>
  <p>2</p>
  <p>3</p>
</div> // OK 
<div>
{
  [ <p>1</p>,
    <p>2</p>,
    <p>3</p>,
  ]
}
</div> //NOT OK without key prop

**Comment by lomocc** [comment]
@aghoneim92 
* Maybe I didn't make it clear?
* Try the demo please: [http://jsbin.com/juredi/edit?js,console,output](http://jsbin.com/juredi/edit?js,console,output)
* Many times our user interface comes from an array, (dataProvider in the jsbin). So we can\`t use the pure JSX:
```html
<div>
  <p>1</p>
  <p>2</p>
  <p>3</p>
</div>
```
* If we use ```{}``` in JSX, the key prop is required. Otherwise it will be reported to the wrong:
```html
// error, the key prop is required
<div>{children}</div>
```
* But it\`s ok, if we use the ```React.createElement```, and pass the ```...children```.

```js
// ok
React.createElement('div', null, ...children)
```
* Where is the difference?

**Comment by aghoneim92** [comment]
@lomocc the difference is that calling `React.createElement('div', null, ...children) is the same as calling `React.createElement('div', null, <p/>, <p/>, <p/>)` and not the same as calling `React.createElement('div', null, [<p/>, <p/>, <p/>])`, which is what you should be doing. You could then just type `React.createElement('div', null, children)` and it would work as expected.

**Comment by lomocc** [comment]
@aghoneim92 Thanks for the answer.
* But, I also think there is a problem with the API ```React.createElement```, Because:  
```js
// It works correctly, no error reporting
React.createElement('div', null, ...children);
React.createElement('div', {children});
```
```js
// Error reporting: Each child in an array or iterator should have a unique "key" prop
React.createElement('div', null, children);
<div>{children}</div>
```
* Isn't it the same way?

**Comment by aghoneim92** [comment]
@lomocc it's not the same way, because specifying children as an array should be done the second way. You should never pass children as a prop like this `React.createElement('div', {children})` because the API specifically states that you should provide children as the third argument, not within props. If you specify children in props it does not get validated either and no error gets thrown just like you have noticed.

**Comment by gaearon** [comment]
Yep, as explained above this is intentional and lets us differentiate “dynamic” children (where we need to ask you to specify keys) from “static” children (where we know the order never changes). JSX transform relies on this.
