### ISSUE TITLE
Delimit dynamic part of the warning messages with newlines

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8719]
As proposed in https://github.com/facebook/react/pull/8495#issuecomment-271311978, I think we should find the warnings where we add a dynamic part to the end (like `"Check the render method of <...>"`) and delimit it with two newlines. This way it’s much easier to recognize in the middle of a bunch of errors:

![](https://cloud.githubusercontent.com/assets/810438/21771524/9b3aeccc-d67f-11e6-8f5d-dfe0dd195d2f.png)

This is a good first issue to contribute. You would need to find `warning()` calls that include additional info like `Check the render method of` and add a couple of newlines. You'd also need to change the tests in case they fail.

**Comment by gaearon** [comment]
Assigning myself so I don’t forget about this issue. But this is a good place to get your feet wet with the React codebase.

**Comment by richiethomas** [comment]
I'd like to work on this issue. :)

**Comment by gaearon** [comment]
👍 Please send a PR and ping me!

**Comment by richiethomas** [comment]
@gaearon - while browsing through 'codebase-overview.md', I noticed a potential typo in the markdown.  On line 116, there appears to be one too many "`" marks, resulting in the rest of the file appearing as code, instead of regular text with code excerpts interspersed when relevant:

<img width="1389" alt="screen shot 2017-01-09 at 2 38 51 pm" src="https://cloud.githubusercontent.com/assets/3839713/21780459/a490b4ce-d679-11e6-8483-aedeb3c08939.png">

I'm happy to fix this as well, but should I create a separate issue for this and submit a PR, or just bundle the fix together with my work on issue #8719?

**Comment by gaearon** [comment]
Please create a separate PR.

**Comment by gaearon** [comment]
While unrelated, I generally recommend reading docs on the website:
https://facebook.github.io/react/contributing/codebase-overview.html

**Comment by richiethomas** [comment]
@gaearon I've got more questions, mostly just questions about how the codebase works.  But they aren't directly related to this issue so I'm unsure where to raise them.  I tried asking on the #reactjs IRC room as specified in the "How To Contribute" guidelines, but was told there is not much React development talk in that room.  I don't want to needlessly pollute this issue's comment space, but I don't know another venue to ask.  Any suggestions?

**Comment by AshikNesin** [comment]
@richiethomas You are working on this issue ?

**Comment by richiethomas** [comment]
@AshikNesin yes, I am. :)

@gaearon I'd like to make sure I have it right before submitting a PR.  As one example of the change being requested, on line 36 of ReactElementValidator.js, I would add 2 newlines at the start of the string that's returned from the 'getDeclarationErrorAddendum' function.  In other words, change:

' Check the render method of `' + name + '`.';

to this: 

'\n\n Check the render method of `' + name + '`.';

If I have it right, I'll submit a PR for this and related code snippets later today.

**Comment by gaearon** [comment]
Something like this. But there's a few more similar places you'd need to change.

**Comment by richiethomas** [comment]
Yep, that's what I understood.  Will submit a PR soon.  Cheers.

**Comment by richiethomas** [comment]
I got all the codebase's references to 'Check' which relate to dynamically-generated warnings, but I also found similar warnings with different verbage so I'm doing a more fine-grained search now.  If it's OK, I'll submit a follow-up PR if I find anything.

**Comment by gaearon** [comment]
Best to put them all in one PR I think.

**Comment by richiethomas** [comment]
For the sake of a code review only, can I submit a 2nd PR for the changes I'm less sure about?  After that I can incorporate the feedback I get and squash everything into one commit.

**Comment by richiethomas** [comment]
OK.  So that I understand, the spirit of this bugfix is to only address the dynamically-generated warnings with large blocks of text, right?  If a warning has dynamic content but is small, easily parseable, and clearly shows which file is problematic, there's no need for a newline, right?

**Comment by gaearon** [comment]
Yes. I want to fix those that are easy to miss and add info at the very end of a long message.

**Comment by richiethomas** [comment]
Can I ask a core contributor for feedback on this PR?  Thank you. :)
