### ISSUE TITLE
[Feature request] PropTypes: validate that no extra props has been passed

### ISSUE THREAD

**Issue by mqklin** [facebook/react#8721]
Here is a [stackoverflow question](http://stackoverflow.com/questions/33907154/react-validate-that-no-extra-props-has-been-passed) and sorta solution:

```
componentWillReceiveProps(nextProps) {
  const passedPropNames = Object.keys(nextProps);
  const expectedPropNames = Object.keys(MyComponent.propTypes);
  passedPropNames.forEach(propName => {
    if (!expectedPropNames.includes(propName)) {
      console.warn('Not expecting a property called', propName);
    }
  });
}
```

It's not working properly at least because there is no recursion, but I hope that the idea is clear.
It can be useful for example after refactoring and helps to eliminate death code, when some props are no longer needed.

**Comment by gaearon** [comment]
Thanks for the suggestion. This issue already exists: #1587.
Please feel free to contribute to the discussion there.
