### ISSUE TITLE
Potential typo in "code-overview.md"

### ISSUE THREAD

**Issue by richiethomas** [facebook/react#8724]
There appears to be a typo on line 116 of "codebase-overview.md".  Specifically, I see one "`" symbol too many, with no closing "`" symbol.  This results in all text after line 116 appearing as one large block of code.  See the screenshot below, with the markdown code on the left and the stylized code rendered on the right:

<img width="1389" alt="screen shot 2017-01-09 at 2 38 51 pm" src="https://cloud.githubusercontent.com/assets/3839713/21780669/7b5de9e0-d67a-11e6-9dfd-5615a00c00e7.png">

Based on the content of the subsequent text after line 116, I would expect it to appear as the following:

<img width="1436" alt="screen shot 2017-01-09 at 2 42 08 pm" src="https://cloud.githubusercontent.com/assets/3839713/21780706/9d68e9ea-d67a-11e6-8c89-b1de39f6b33d.png">

**If this is indeed something that should be fixed, I'd like to fix it, and can submit a PR immediately.**

**Comment by gaearon** [comment]
I think you're right, please do submit a PR.

**Comment by gaearon** [comment]
(For future reference, feel free to send PRs for small fixes like this without creating an issue.)
