### ISSUE TITLE
Any better way to get refs in ReactTransitionGroup?

### ISSUE THREAD

**Issue by techctu** [facebook/react#8734]
I've found I can get children's refs in ReactTransitionGroup. Just like

```
<TransitionGroup ref={(ref) => this._refs = ref}>
    <div>Hello</div>
</TransitionGroup>
```

Then I can get ```<div>Hello</div>``` by ```this._refs.refs['.$.0']```

It's quite ugly. 

Is there any better way?

**Comment by gaearon** [comment]
This is an implementation detail and is not officially supported. As far as I know there is currently no better way (you could also get a top-level ref and then use DOM API to get a child).

We could work around it by switching to callback refs internally. However we don't plan to change the TransitionGroup code anymore in this repository. We've been moving it to https://github.com/reactjs/react-transition-group so please file new feature requests and bug reports there. Thanks!
