### ISSUE TITLE
Cannot run tests correctly on Windows

### ISSUE THREAD

**Issue by jddxf** [facebook/react#8737]
There are some issues in test code failing the tests on Windows.

1. Invalid regular expression
https://github.com/facebook/react/blob/master/scripts/jest/ts-preprocessor.js#L30-L32
It would be an invalid regexp just like /\\(a)/.

2. Invalid arguments passed to `child_process.spawn`
https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js#L34-L45
This issue is similar to https://github.com/facebook/react/issues/8021

**Comment by aweary** [comment]
@jddxf do you want to submit a PR with fixes for these?

**Comment by jddxf** [comment]
Sure,I've already done this.Something is wrong with my git.I can't fetch or push.

**Comment by jddxf** [comment]
I wonder whether issues of this sort should be opened since they're not related to the functionality.Maybe a PR would be enough?

**Comment by gaearon** [comment]
If you can fix it, just send a PR, but when not sure or don’t have time, please file an issue so somebody else could do it. Thanks for jumping on this.

**Comment by jddxf** [comment]
got it.thanks.
