### ISSUE TITLE
Make sure findDOMNode works on test renderer

### ISSUE THREAD

**Issue by spicyj** [facebook/react#8753]
This injection is missing in the stack test renderer:

https://github.com/facebook/react/blob/2da35fcae888752948454dd04e9573cc7bdba8f5/src/renderers/dom/stack/client/ReactDOMStackInjection.js#L69-L72

Something similar should be added near here:

https://github.com/facebook/react/blob/master/src/renderers/testing/stack/ReactTestRendererStack.js#L136

Without that, you get a "Missing injection for stack findDOMNode" error when calling findDOMNode in files that use ReactTestRenderer (and don't use ReactDOM). Would be great to repro the error with a test and then fix it.

**Comment by spicyj** [comment]
Hm, not sure this makes sense actually.

**Comment by spicyj** [comment]
Gonna close this for now until I figure out what we actually want.

**Comment by aweary** [comment]
@spicyj there was some discussion in https://github.com/facebook/react/pull/8164 about why we weren't supporting `findDOMNode` in the test renderer

**Comment by spicyj** [comment]
Good memory, thanks. :)
