### ISSUE TITLE
No more checksum validation for server-side-rendered HTML markup string?

### ISSUE THREAD

**Issue by mocheng** [facebook/react#8758]
After upgrading to v15, my isomorphic rendering app whines on page load.
>warning.js:36Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="

It turns out that there is a [change in v15](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#document.createelement-is-in-and-data-reactid-is-out) removing `data-reactid` attributes in rendered HTML, but server side rendering method `renderToString` still generated `data-reactid`. As a result, `ReactDOM.render` and `ReactDOMServer.renderToString` never matches and it just keeps whining on error.

I tried to replace `renderToString` with `renderToStaticMarkup` and the error disappeared. However, there is no `data-react-checksum` attribute in generated HTML markup. In my memory, the `data-react-checksum` attribute is to check whether browser and server side generated HTML matches. Now, there is no such checksum, then every render just compare the whole generated DOM? Will that hurt performance?

**Comment by gaearon** [comment]
That's not what's happening. On the client we still generate the attribute *when comparing markup*, even in 15.

So your problem is due to something else. But it's hard to say what without seeing a minimal example reproducing it.

**Comment by mocheng** [comment]
@gaearon Good to know that. 
I figured out that my issue is due to dynamic route of react-router is leveraged in the upgrade. After I tweaked browser side code according to [this](https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md#async-routes), It works.
Thank you for clarification.

**Comment by lzr900515** [comment]
now i have the same problem. you link is 404 . can you give me a help? @gaearon
