### ISSUE TITLE
If didn't set {this.props.children}, the children still be evaluated. 

### ISSUE THREAD

**Issue by kunyan** [facebook/react#8759]
Hi, here's my code

```
class Spinner extends React.Component {
  render() {
    if(this.props.loading) {
      return <div className='spinner'></div>;
    } else {
      return (
        <div className="spinner-wrapper">
              { this.props.children }
          </div>
      );
    }
  }
}


class App extends React.Component {
  render() {
    return (
      <Spinner loading={!this.props.account}>
        <div>{this.props.account.name}</div>
      </Spinner>
    );
  }
}

const account = null;
            
ReactDOM.render(
  <App account={account}/>,
  document.getElementById('demo')
);
```

I thought it should be display a spinner, but got error

`Uncaught TypeError: Cannot read property 'name' of null`

How can I avoid it ?

**Comment by gaearon** [comment]
Nested JSX is just an expression that is evaluated immediately. It doesn’t get “delayed” by components. So even if you use a `Spinner`, you still try to read `account.name` from a null object which fails.

Commonly, when data is not available, people use early returns. For example:

```js
    if (!this.props.account) {
      return <Spinner />
    }
    return <div>{this.props.account.name}</div>;
```

**Comment by gaearon** [comment]
Think of it as function arguments. Even if function doesn't use an argument, it is evaluated before calling the function. So if evaluation fails, it happens early. Some programming languages are “lazy” and evaluate arguments only as needed, but JavaScript is not one of them.
