### ISSUE TITLE
onToggle Event name not recognized

### ISSUE THREAD

**Issue by CyrilWork** [facebook/react#8761]
**report a *bug*?**

**What is the current behavior?**

onToggle prop attached to a details html element does not attach the event handler , instead shows a warning "Warning: Unknown prop `onToggle` on `<details>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in details (created by Details) ...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

No time right now

**What is the expected behavior?**

-

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest

WorkAround:

Use onClick instead, (does not work fire event handler when details is opened with keyboard !)

**Comment by gaearon** [comment]
Would you like to send a PR to support this event?

**Comment by CyrilWork** [comment]
I don’t have time right now.

**Comment by gaearon** [comment]
Maybe somebody else could do it then. I’ll keep it open, thanks.

**Comment by trejoramiro** [comment]
I'd like to take a stab at this!

**Comment by gaearon** [comment]
Sure, please go ahead! You can search for older PRs that add events to get a sense for how it looks.

**Comment by fabiancook** [comment]
For reference https://jsfiddle.net/m4eg68uz/

**Comment by diegomura** [comment]
@trejoramiro are you still working on this? If not, I would like to work on this 😄

**Comment by trejoramiro** [comment]
Hey @diegomura, go ahead no problem!
