### ISSUE TITLE
Incorrect JSX with dynamic elements

### ISSUE THREAD

**Issue by Taakn** [facebook/react#8772]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When doing something like this:
```
<div>
{this.aFunction(this.state.param)}
</div>
```
And `{this.aFunction(this.state.param)} `returns some JSX that depends on `param` (with some logic or if/then clause) then the result is sometimes incorrect when `param` changes. Seems like the virtual DOM processing comparing before and after the changes is causing problems.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.2.1. Everything worked fine in previous versions of react. Everything works fine on iPhone 7 but not iPhone 6

**Comment by gaearon** [comment]
Did you get a chance to create a reproducing example, like we ask in the issue template that you filled? It’s right in your issue description:

>If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).

We won’t be able to help if you don’t provide a code example that fails. The three-line code snippet you provided looks fine so the problem is in something else.

**Comment by Taakn** [comment]
Sorry about that I understand. I've been trying to reproduce what I'm seeing in my app with a simple code sample like https://jsfiddle.net/4w3dby78/ but that works too. I'll do my best to get something reproducing the bug.

**Comment by aweary** [comment]
@Taakn any luck getting a reproducible example?

**Comment by Taakn** [comment]
I will close this as I don't have a simple, clean example to provide. Will reopen if I find something.
