### ISSUE TITLE
react-15.4.2.zip is missing from downloads section for 15.4.2

### ISSUE THREAD

**Issue by zowers** [facebook/react#8773]
*bug*

**What is the current behavior?**
there's no react-15.4.2.zip in "Downloads" section at https://github.com/facebook/react/releases/tag/v15.4.2

**What is the expected behavior?**
there's should be react-15.4.2.zip in "Downloads" the same way as react-15.4.1.zip was in section at https://github.com/facebook/react/releases/tag/v15.4.1

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
affected: 15.4.2
last-known-good: 15.4.1

**Comment by gaearon** [comment]
We stopped publishing the zips as you can get the same files from unpkg.
The unpkg CDN just serves the contents of our npm packages.
[We link to it from the docs:](https://facebook.github.io/react/docs/installation.html#using-a-cdn)

https://unpkg.com/react@15.4.2/dist/react.js
https://unpkg.com/react@15.4.2/dist/react.min.js
https://unpkg.com/react-dom@15.4.2/dist/react-dom.js
https://unpkg.com/react-dom@15.4.2/dist/react-dom.min.js

When a new version comes out, just replace the number in the URL to download it.
Or you could link to the newest available 15.x release:

https://unpkg.com/react@15/dist/react.js
https://unpkg.com/react@15/dist/react.min.js
https://unpkg.com/react-dom@15/dist/react-dom.js
https://unpkg.com/react-dom@15/dist/react-dom.min.js

Does this help?

**Comment by zowers** [comment]
ok, thanks
