### ISSUE TITLE
Differences between React and Rax?

### ISSUE THREAD

**Issue by MillyKirkland** [facebook/react#8783]
This says that React is much slower than React but has the same API, so why use React over Rax? [Link here](https://github.com/alibaba/rax)

**Comment by aweary** [comment]
@MillyKirkland thanks for the question, but we try to use this issue tracker solely for bugs and feature requests. You might be better served asking your question on a more discussion-oriented platform, such as [discuss.reactjs.org](https://discuss.reactjs.org/).
