### ISSUE TITLE
missing function 'emptyFunction'

### ISSUE THREAD

**Issue by acpower7** [facebook/react#8786]
Browsing through the react source, I'm trying to locate a file, 'emptyFunction.js'. I often see statements like var `emptyFunction = require('emptyFunction');`.

I've looked everywhere for this file but can't find it, where is it?

**Comment by voidsatisfaction** [comment]
It is on `node_modules/fbjs/lib/emptyFunction.js`

**Comment by decadef20** [comment]
To read the `preprocessor.js `file , you will get the detail.

**Comment by aweary** [comment]
@acpower7 we use a custom module system called "haste" that knows how to resolve these requires, check out [the codebase overview docs page](https://facebook.github.io/react/contributing/codebase-overview.html#custom-module-system) for more information!
