### ISSUE TITLE
Missing object-assign licence (please check others)

### ISSUE THREAD

**Issue by markalanrichards** [facebook/react#8789]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Missing copyright licence
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
See https://markssoftware.com/2017/01/14/npm-is-lying-to-you-and-facebook-is-stealing-copyright/
**What is the expected behavior?**
Not a lawyer, Facebook should know how to show MIT according to their policies.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Checked current version 15.4.2? All OSes and this is probably in previous versions.

**Comment by gaearon** [comment]
Thanks for flagging this!

For the context, the library author is well aware the library is being used by React (in fact we helped fix some issues in it). Claiming Facebook is “stealing copyright” and writing a blog post about it seems a bit premature since you could’ve reached out first.

It is a bug and not intentional.

cc @sindresorhus @zpao

**Comment by markalanrichards** [comment]
I hope you mean authors there are multiple contributors.

Displaying copyright should also be accurate regardless of any agreement,
as Facebook didn't create that element of source.

It is very dangerous to the community to get this kind of thing wrong in a
very popular project.

SCO vs UNIX showed the risk.

"Stealing" seems like an appropriately loud term, commonly used by
copyright enforcement campaigns to raise the significance of this problem.
Sorry this isn't a friendly term, but it is very important.

**Comment by gaearon** [comment]
I agree it’s important. Probably solveable by putting `@license` into the code of `object-assign` so that the license is preserved by the bundler.

Would you like to send a PR and verify this fix works?

**Comment by markalanrichards** [comment]
Great idea, except this is a complex legal thing. As I'm not a lawyer for
or an existing author in either project it doesn't seem right. It's one
thing to raise a concern, its another to get hands on and make my own copy
(branch for PR) that might be wrong and misrepresent the rights. Especially
as the repo owner has already suggested he might not care, which means I
have no idea what is appropriate to put in the license file.

**Comment by gaearon** [comment]
What I suggest is copying LISENSE file into the source of `object-assign` as a comment, and adding a `@license` directive to that comment so that it doesn't get stripped out.

There is nothing there you could misrepresent, it's a pretty manual operation, and you would use the existing license. Once you do that you could send a PR to `object-assign` so that the maintainers could verify the change is right.

Then you could rebuild React locally to verify if the change worked. This is not hard. It would take less time and be more helpful than writing a blog post.

**Comment by gaearon** [comment]
To be clear, we do care about this, but we also appreciate help. It is hard to get everything right, and sometimes we make mistakes. It is easy to write a post shaming a big company for making a mistake, but the reality is the React team is just a few people, and we have many other things we need to fix every day.

From your side, I think offering some help could be a tiny bit more productive. I would be happy to give you more details about the possible fix if you are willing to put in time not just to write a blog post about us making mistakes, but also to help us. That's the beauty of open source. 

In any case, I'll try to get to this before cutting the next release. Thank you again for flagging this. Cheers!

**Comment by markalanrichards** [comment]
My decision not to get involved in putting a copyright statement on someone else's work is because it's best the authors choose how they want to represent their copyright and getting it wrong on their work is a financial liability you should respect I may not want to take..

However, thank you for suggesting I try as I may have wanted to take the risk, but object-assign seems to have two positions on copyright (https://github.com/sindresorhus/object-assign/issues/44) I wouldn't know what to put in the @License statement now.

**Comment by markalanrichards** [comment]
Also why do you have this link in your source https://unpkg.com/react@15.4.2/dist/react-with-addons.js? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

**Comment by gaearon** [comment]
>Also why do you have this link in your source

Because that's where the polyfill code is coming from.
It [doesn't require licensing notice](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses):

>Code samples added on or after August 20, 2010 are in the public domain. **No licensing notice is necessary,** but if you need one, you can use: "Any copyright is dedicated to the Public Domain. http://creativecommons.org/publicdomain/zero/1.0/".

The link is provided so that it's more obvious where the source was.

**Comment by markalanrichards** [comment]
It would be good then, if instead of a link, the comments appropriately explained that the block of code is not owned by Facebook copyright and are an exception in the module. At least to ensure that Facebook doesn't try to assert ownership over that block in future. The Mozilla url may not work forever so the context can get lost when it isn't included directly.

**Comment by gaearon** [comment]
As I wrote above that snippet is in **public domain**. Which means the original authors have [dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law](https://creativecommons.org/publicdomain/zero/1.0/).

What does "Facebook doesn't try to assert ownership over that block in future" even mean for a work in public domain? The whole point of public domain is anyone can use, modify, or redistribute it, for any purposes, [with no requirements to give attribution](https://wiki.creativecommons.org/wiki/CC0_FAQ#Does_CC0_require_others_who_use_my_work_to_give_me_attribution.3F).

If you have any legal concerns please get in touch with `legal@fb.com`. I'm afraid I can't help you more in this thread.

**Comment by gaearon** [comment]
I'm going to lock this since the resolution seems straightforward and we’ll try to do this before the next release. The further discussion didn’t seem very productive and I’d like to avoid spamming people subscribed to the repo. If you find more problems, please file a new issue. Thanks!

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/8803 will fix this.
I’m waiting for lawyers’ reply on the CC0 bit.
