### ISSUE TITLE
IE11 triggers onChange event of file input when element.value is assigned

### ISSUE THREAD

**Issue by larsnystrom** [facebook/react#8793]
**Do you want to request a *feature* or report a *bug*?**
*bug* (possibly related to #7295)

**What is the current behavior?**
Here is a component for a file upload button:

	class UploadButton extends React.Component {
		render() {
			const { onUploadFile } = this.props;
			<input
			    type="file"
			    name="file"
			    ref={(c) => this.file = c}
			    onChange={() => {
			        onUploadFile(this.file.files[0]);
			        this.file.value = null;
			    }}
			/>
		}
	}

When a user selects a file to upload, `onUploadFile` is called. In this case, I want to call `onUploadFile` if a user selects the same file two times in a row, so we set `this.file.value` to null after the first selection so that the `onChange` handler is called the second time the user selects the file. So far so good.

The bug is that in IE11, setting `this.file.value` to null causes the `onChange` handler to be called. This is not the case in IE10, Chrome or Firefox. You can validate this by seeing that `onUploadFile` is called twice when selecting a file in IE11, but not in the other browsers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

https://jsfiddle.net/5b5y3yt0/
(Actually, in this fiddle the `onUploadFile` callback is called three times in IE11.)

**What is the expected behavior?**

The same behavior in IE10 and IE11 (and Chrome and Firefox).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.4.2 (react@latest in the fiddle).

**Comment by aodinok** [comment]
I think this issue has nothing to do with React at all,  it's IE11 default behaviour (or bug), you can check [this](https://jsfiddle.net/ovd40bfj/1/) simple example in IE11 and you should see 2 alerts, all other browsers will show only 1 alert... I think IE11 handling "this.value=null" like value change and calling onChange handler again...

**Comment by gaearon** [comment]
Seems like it's unrelated to React then? If it's React's fault let us know and we can reopen.

**Comment by larsnystrom** [comment]
Yeah, this is a bug in IE11, not react. Sorry for taking up your time.
