### ISSUE TITLE
the text is not shown on the text box

### ISSUE THREAD

**Issue by ChenLiZhan** [facebook/react#8801]
I am creating a HTML form to get input information from users via React v0.13.3 and working on MacOS with Google Chrome. My problem is when user types text on the text box, the words cannot be shown on the view (the text box). It looks like the listener in the store is not aware of the action has been triggered

 I separated `components`, `actions`, and `stores` into three files, which are `/components/AddProduct.js`, `/actions/AddProductActions.js` and `/stores/AddProductStore.js`.

1. Here is the code of `/components/AddProduct.js`:
```javascript
import React from 'react';
import AddProductStore from '../stores/AddProductStore';
import AddProductActions from '../actions/AddProductActions';

class AddProduct extends React.Component {
  constructor(props) {
    super(props);
    this.state = AddProductStore.getState();
    this.onChange = this.onChange.bind(this);
  }

  componentDidMount() {
    AddProductStore.listen(this.onChange);
  }

  componentWillUnmount() {
    AddProductStore.unlisten(this.onChange);
  }

  onChange(state) {
    this.setState(state);
  }

  handleSubmit(event) {
    // event.preventDefault();
    // var name = this.state.name.trim();
    // var price = this.state.price.trim();
    // var description = this.state.description.trim();

  }

  render() {
    return (
      <form onSubmit={this.handleSubmit.bind(this)}>
        <label className='control-label'>Description</label>
          <input type='text' className='form-control' ref='descriptionTextField' value={this.state.description}
                          onChange={AddProductActions.updateDescription} />
      </form>
    );
  }
}

export default AddProduct; 
```

2. Here is the code of `/actions/AddProductActions.js`:
```javascript
import alt from '../alt';

class AddProductActions {
  constructor() {
    this.generateActions(
      'updateDescription'
    );
  }
}

export default alt.createActions(AddProductActions);
```

3. The code of `/stores/AddProductStore.js`
```javascript
import alt from '../alt';
import AddProductActions from '../actions/AddProductActions';

class AddProductStore {
  constructor() {
    this.bindActions(AddProductActions);
    this.description = '';
  }

  onUpdateDescription(event) {
    this.description = event.target.value;
  }
}

export default alt.createStore(AddProductStore);
```

However, if I simply change the name of the function and the corresponding properties to a shorter name (i.e. `descriptio` instead of description), the problem is solved perfectly. As the result, I'm wondering is this a bug or a naming convention in React?

**Comment by gaearon** [comment]
React doesn't rely on naming conventions anywhere, its API is very explicit. Please try to reduce your test case to just React, without other libraries. Then please publish it somewhere so that we can reproduce it. Thanks!

**Comment by aweary** [comment]
Since there's been no response I'm going to go ahead and close this out. @ChenLiZhan if this is still an issue for you, please provide a reduced test case as that uses just React and we'd be happy to look at it and help out. Thanks!
