### ISSUE TITLE
Double click event emitted on wrong component

### ISSUE THREAD

**Issue by maxired** [facebook/react#8804]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When doubleclicking a component, if the initial click create a new component in overlay of the first one,
then a double click event is emitted on the new component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/69z2wepo/67536/ .

When double clicking on the button, an alert box is created. this should not happen, as the doubleClick handler is on the new component.

**What is the expected behavior?**
The doubleclick event should proably be emitted on the button, not on the new layer.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on Chromium 53/Firefox 50.1 on linux, Chrome 51/Edge/IE11 on Window 10
This is with 15.4.2. I haven't test it on another version.

**Comment by fabiancook** [comment]
Hi,

It appears you are wanting to propagate the event to the `Hello` component correct?
If so, pass a function as a prop, and then invoke pass that as the handler within Modal

In `Hello.prototype.render`:

`this.state.showModal && < Modal onDoubleClick={this.onDoubleClick}/ >`

In `Modal.prototype.render`:

`onDoubleClick = {this.props.onDoubleClick} >`

This will invoke the function passed as a property to `Modal` when double click is invoked.

![image](https://cloud.githubusercontent.com/assets/4337080/22013133/677fc74e-dcfc-11e6-9725-d5fcd3d4d2d8.png)

**Comment by maxired** [comment]
Hi @fabiancook ,

I think we have a misunderstanding.
My question is, why is the `onDoubleClick` handler called on the modal, while it was not there for the initial click ? It seems counter intuitive to me.

In fairness, after more time spending on it, this seems to match the current implementation of browsers.
Still, I am not sure to understand the [UIEvent spec for dblclick](https://www.w3.org/TR/uievents/#dblclick)

**Comment by fabiancook** [comment]
Sorry, are you referring to the quick succession of clicks? One event occurring on the `button`, then one on `Modal`

**Comment by fabiancook** [comment]
Currently, it does not meet this statement `except that the event target MUST be the same between mousedown, mouseup, and dblclick.`, you are correct sorry.

**Comment by maxired** [comment]
I am refering to the dblick event.

I have indeed two clicks, which in normal situation should trigger a dblclick, but here,
the two clicks events are not on the same dom element, so I am not sure why the dblclick event is emitted.

**Comment by syranide** [comment]
@maxired Probably just browser quirks, React does not interpolate dblclick (it's an OS feature).

**Comment by maxired** [comment]
@syranide thanks for the explanation. 
Yep you are right, it does not seems to be react related.
