### ISSUE TITLE
Misleading reconciliation behavior due to this.props.children

### ISSUE THREAD

**Issue by ishestakov** [facebook/react#8810]
**Do you want to request a *feature* or report a *bug*?**

*bug* ?

**What is the current behavior?**

Currently after component state change the input element loose focus (I think due to misleading reconciliation mechanism). Playing with `key` doesn't get it work as expected. If we'd remove `this.props.children` from `App` component everything will work as expected. 
Another way to fix this issue is to change `FormInput` component in slightly other way: https://jsfiddle.net/ishestakov/vyypqt60/1/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

https://jsfiddle.net/ishestakov/jdcL1bjn/
If you'd start typing in the input the focus would be lost due to DOM manipulations

**What is the expected behavior?**
The expected behavior is to only update HTML elements during reconciliation and thus not to loose the focus

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest, also this is reproducible on 0.14.7.

**Comment by syranide** [comment]
You're encountering #8731, the issue and workarounds are detailed there.

**Comment by syranide** [comment]
You're encountering #8731, it has details and workarounds.

**Comment by gaearon** [comment]
Yes, it’s the same issue—please don’t rely on children “lining up” when you return early.
Instead, use conditions inside JSX.

Here’s a fixed example:
https://jsfiddle.net/jpzLzrhc/
