### ISSUE TITLE
ReactDOM.render fails if react-dom was loaded before a DOM was available

### ISSUE THREAD

**Issue by ronami** [facebook/react#8812]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*

**What is the current behavior?**

ReactDOM.render fails if there was no global document when it was first loaded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

I'm not providing a jsfiddle example because the use case happens with Node.js and JSDom. Here's how to reproduce:

Define a component that has a state, and have it's render function render null for one of the cases (This happens pretty frequently using HOCs such as 3rd party translation tools, etc):
```js
class MyComponent extends React.Component {
  state = {
    display: false
  }

  componentDidMount() {
    this.setState({display: true});
  }

  render() {
    return this.state.display ? <div/> : null;
  }
}
```

Define a test, load jsdom global before every test and cleanup after you're done:
```js
const ReactDOM = require('react-dom');

describe('App', () => {
  let cleanup;

  beforeEach(() => cleanup = require('jsdom-global')());
  afterEach(() => cleanup());

  it('', () => {
    ReactDOM.render(
      <MyComponent/>,
      document.body
    );
  });
});
```

This would fail with the following error: `Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure 'window' and 'document' are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.`.

If you require react-dom after a dom was defined globally, the test will pass. Also, returning anything other than null (any React element) will make the test pass.

It looks like react-dom is using https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/ExecutionEnvironment.js#L14 to get if a DOM is available when it was first loaded and doesn't look again when ReactDOM.render() is called.

If any of this makes sense, I will be happy to give a PR to fix it, if you can throw me in the right direction.

**What is the expected behavior?**

ReactDOM.render should render correctly even if a global document was added after it was loaded, as it works for such a component that doesn't return null for a certain state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested with latest React and Node.js +7.0.0.

Thanks!

**Comment by gaearon** [comment]
This is not supported, sorry. Running checks for browser globals every time we perform a DOM operation is worse for performance so we would rather do it once during the boot.

>as it works for such a component that doesn't return null for a certain state.

It might be better to just crash early in `ReactDOM` if browser globals are unavailable. Not sure how many people rely on this, and it would be a breaking change, but we could do it.
