### ISSUE TITLE
Wondering if react support for `babel-preset-env`?

### ISSUE THREAD

**Issue by dickeylth** [facebook/react#8824]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

- Currently react's size (v15.4.2: react.min.js 20.7KB compressed, react-dom.min.js 121KB compressed) is about 140KB after compression, which is still a pain point for mobile web situation.

**What is the expected behavior?**

- I've heard that [React implement its own event dispatching and bubbling, it normalizes common events across browsers so that you don't need to worry as much about it.](http://stackoverflow.com/questions/19807946/why-is-reacts-filesize-so-big-given-its-small-api), which maybe make a huge contribution to react's size. So I'm wondering if it's possible or already enabled for react to combine with [babel-preset-env](https://github.com/babel/babel-preset-env) to provide ability for smaller production bundle size?
- For example in our team in China, we mainly focus on iOS Safari & Android Browser & Hybrid WebViews in iOS & Android, which of those are based on webkit kernel, so any polyfill for IE/Edge, Opera, Firefox or other desktop browsers is unnecessary for our production codes. If those polyfills could be stripped out, that should make our final production codes much smaller.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

- React@15.4.2

**Comment by pedi** [comment]
any proof that `React Event normalize`?
> make a huge contribution to react's size

From what I read from the source code, there should be no single pain point that makes the React bundle size so large

**Comment by gaearon** [comment]
>is about 140KB after compression

This is incorrect, it is about 45 kB gzipped (after compression). The number you are quoting is *before* compression. The uncompressed size still has impact on parse and compile time though.

We will be looking into removing the polyfills and normalization that are unnecessary in modern browsers. We will not be using flags for this because it is too difficult to reliably do this as a build step, and to maintain many different configurations.

I hope this helps!

**Comment by dickeylth** [comment]
@gaearon Sorry my description is not accurate, I mean after uglified instead of compression.
Looking forward to seed "removing the polyfills and normalization that are unnecessary in modern browsers"😘
