### ISSUE TITLE
Small error in tutorial

### ISSUE THREAD

**Issue by yellowmoneybank** [facebook/react#8825]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
In the tutorial are functional components explained with the following code-snippet
```
function Square(props) {
  return (
    <button className="square" onClick={() => props.onClick()}>
      {props.value}
    </button>
  );
}
```

**What is the expected behavior?**

To work correctly when you follow the tutorial it should be
```
function Square(props) {
  return (
    <button className="square" onClick={() => props.handleClick()}>
      {props.value}
    </button>
  );
}
```
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v15.4.2

**Comment by aweary** [comment]
Thanks for the issue @yellowmoneybank!

The current example is actually correct. The function itself may be called `handleClick`, but its passed to the `<Square />` component as `onClick`:

```jsx
return <Square value={this.state.squares[i]} onClick={() => this.handleClick(i)} />;
```

Hope that clears it up!

**Comment by gaearon** [comment]
@brigand and I rewrote some parts of the tutorial in https://github.com/facebook/react/issues/9454, and following along should be easier now. Let us know if you're still struggling! We’re happy to look at remaining issues in case we missed anything.

https://facebook.github.io/react/tutorial/tutorial.html
