### ISSUE TITLE
Click handlers triggered on disabled buttons containing elements (Chrome)

### ISSUE THREAD

**Issue by troch** [facebook/react#8827]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On current version of React (15.4.0), in Chrome and Opera, buttons with a click handler and an element inside them (i.e. not only a text node) get their click handler triggered on click when disabled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

http://codepen.io/anon/pen/MJJNpj

**What is the expected behavior?**

Both buttons should not react to click events.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React (15.4.0), Chrome (v55). Was working in React 15.3.x.

**Comment by aweary** [comment]
Hey @troch, this issue was actually just filed (with the same Codepen) in https://github.com/facebook/react/issues/8826. See my comment there https://github.com/facebook/react/issues/8826#issuecomment-273817794. In summary, it was resolved in 15.4.1. Hope that helps!

**Comment by troch** [comment]
Oops sorry, that's my coworker. Misunderstanding.

**Comment by aweary** [comment]
I figured, no worries 😄
