### ISSUE TITLE
PropTypes.shape should throw if the object have more properties than specified

### ISSUE THREAD

**Issue by ghanjra** [facebook/react#8832]
if i have setup like:

```
MyComponent.propTypes={
  compProps:React.PropTypes.shape({
      propA: React.PropTypes.string.isRequired,
      propB: React.PropTypes.string.isRequired
  }).isRequired
};
```

when i call it like:
```
const propsObj = {
   propA:'',
   propB:'',
  unwantedProp: ''
};
<MyComponent compProps={propsObj}/>
```

i expect it to show warning, as the passed object does not have the exact shape as required.

Please advice

**Comment by aweary** [comment]
Thanks for the issue @ghanjra! We have an existing issue open about this https://github.com/facebook/react/issues/1587. I'm going to close this out in favor of https://github.com/facebook/react/issues/1587 so the discussion doesn't get fragmented, feel free to add any input you have there!
