### ISSUE TITLE
DOM element rendered with same props is not detected as wasted

### ISSUE THREAD

**Issue by mocheng** [facebook/react#8847]
I found this issue when  #trying to demo React Perf in Chrome which basically utilizing `react-addons-perf`. When `input` DOM element is rendered with same `checked={true}` or `checked="checked"` prop, it is not detected as wasted.

Code below cannot not be detected as wasted even onClick is new function for every render.
```
const DumbCompnent = ({onClick, text, completed}) => {
  return (
    <div>
      <input type="checkbox" checked={completed} readOnly onClick={onClick} /><label>{text}</label>
    </div>
  );
}
```

Interestingly, if the code just exempt `checked` prop if the value is false, it can detect it as wasted properly. Code as below
```
const DumbCompnent = ({onClick, text, completed}) => {
  const checkedProp = completed ? {checked: true} : {};
  return (
    <div>
      <input type="checkbox" {...checkedProp} readOnly onClick={onClick} /><label>{text}</label>
    </div>
  );
}
```

I have created minimal TODO-like project to reproduce this issue https://github.com/mocheng/sample-wasted

Repro Steps:
1. Click "Start" on Perf Tab;
2. Check one item in web page;
3. Click "Stop" on Perf Tab;

Expected Result: It should detect wasted render .

Actual Result: No wasted is detected.

This can be reproduced In React v15.4.2.

**Comment by gaearon** [comment]
React Perf does not work in React 16. We might resurrect it at some point, but for now it's not very clear how it should work with the new algorithm. In any case, we can close this now.
