### ISSUE TITLE
Remove React.createMixin

### ISSUE THREAD

**Issue by aweary** [facebook/react#8852]
Since mixins are no longer a part of the future React API plan, and the [current React.createMixin implementation](https://github.com/facebook/react/blob/master/src/isomorphic/React.js#L78-L81) is just a no-op, I think we can consider removing it.

Since it was part of the public API I believe it would need to happen in the next major release. Should we add a deprecation warning before then? There are [a number of projects](https://github.com/search?utf8=%E2%9C%93&q=%22React.createMixin%22&type=Code&ref=searchresults) that use the API.

cc @spicyj @gaearon

**Comment by gaearon** [comment]
Yes let's get rid of it. Want to send a PR to add a deprecation warning?

**Comment by aweary** [comment]
On it!

**Comment by kaushik94** [comment]
@aweary can I work on this one? Since I am new to the community, I might need a bit of direction as to where to start.

**Comment by gaearon** [comment]
@kaushik94 It’s already been done as part of #8853, I just forgot to close the issue. Sorry!
