### ISSUE TITLE
Feature test during start-up instead?

### ISSUE THREAD

**Issue by syranide** [facebook/react#886]
https://github.com/facebook/react/blob/master/src/dom/getTextContentAccessor.js

Could for instance be simplified to the below code, and even if many of these tests were to be done during start-up the effect should be immeasureable (by comparison, even IE8 can manage to create ~250.000 elements a second) and it seems like we could simplify the code slightly by doing it like this.

Since we still use `ExecutionEnvironment.canUseDOM` it should be safe to use in all environments, right?

```
"use strict";

var ExecutionEnvironment = require('ExecutionEnvironment');

/**
 * Gets the key used to access text content on a DOM node.
 */
if (ExecutionEnvironment.canUseDOM) {
  module.exports = 'innerText' in document.createElement('div') ?
    'innerText' :
    'textContent';
}
```

**Comment by aweary** [comment]
@spicyj do you think this still makes sense? Is it worth changing?

**Comment by aweary** [comment]
I'm going to close this since there's been no recent movement or interest, it introduces a potential problem with existing test suites, and the performance improvement would likely be minimal.
