### ISSUE TITLE
onSubmit handler has Proxy object as first argument

### ISSUE THREAD

**Issue by gsingh93** [facebook/react#8869]
**Do you want to request a *feature* or report a *bug*?**
I believe this is a bug, since I can't find any documentation on this behavior changing.

**What is the current behavior?**
When calling a submit handler like `onSubmit`, the first argument is a `Proxy` object and the second argument is an `Event` object.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://codepen.io/anon/pen/zNEGpw?editors=0010

(see the console to see both objects)

**What is the expected behavior?**
The first argument should be an `Event` object, not a `Proxy` object.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is happening in react 15.4.1 and 15.4.2. It is not happening on 15.3.1.

**Comment by gaearon** [comment]
You should use the first argument to the event handler, just like in the docs.
The fact that it appears as "Proxy" shouldn't worry you—that's implementation detail.

I’m not sure why the second one exists: it’s likely a bug (and maybe even fixed in master, @aweary might remember).

**Comment by aweary** [comment]
The second event was just the result of an internal implementation detail with `invokeGaurdedCallback`. This was resolved in https://github.com/facebook/react/pull/8363 and should likely be released in the next minor version.
