### ISSUE TITLE
Maintaining ref prop through React.cloneElement()

### ISSUE THREAD

**Issue by pvienneau** [facebook/react#8873]
React's [0.13 RC](https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html) suggests that `ref` prop on components pushed through `React.cloneElement()` will allow for two parents to maintain `ref` props to the same child.

I've tried to replicate this behaviour in a [CodePen](http://codepen.io/pvienneau/pen/PWJjKq), but I am not able to maintain two `ref` references to the same child (ie the ancestor component's `ref` gets nulled).

Here is the jist of the code, working code found [here](http://codepen.io/pvienneau/pen/PWJjKq):

```
class ChildComponent extends React.Component{
  constructor(props){
    super(props);   
  
    this.onClick = this.onClick.bind(this);
    this.extendsChildren = this.extendChildren(this);
  }
  
  onClick(e) {
    e.preventDefault();
    
    try{
      alert(this._input.value);
    }catch(e){
      alert('ref broken :(');
    }
  }
  
  extendChildren(){
    return React.Children.map(this.props.children, child => {
      return React.cloneElement(
        child,
        {
          ref: ref => this._input = ref
        }
      );
    });
  }
  
  render() {
    return(
      <div>
      <button onClick={this.onClick}>
        ChildComponent ref check
      </button>
      {this.extendChildren()}
    </div>
    );
  }
}


class AncestorComponent extends React.Component{
  constructor(props){
    super(props);
    
    this.onClick = this.onClick.bind(this);
  }
  
  onClick(e) {
    e.preventDefault();
    
    try{
      alert(this._input.value);
    }catch(e){
      alert('ref broken :(');
    }
    
  }
  
  render() {
    return (
    <div>
        <p>
          The expected behaviour is that I should be able to click on both Application and ChildComponent check buttons and have a reference to the input (poping an alert with the input's value).
        </p>
      <button onClick={this.onClick}>
        Ancestor ref check
      </button>
      <ChildComponent>
        <input ref={ref => this._input = ref} defaultValue="Hello World"/>
      </ChildComponent>
    </div>
    );
  }
}
```

Has this behaviour been dropped/never implemented since the above RC? Or am I doing something wrong?

**Comment by gaearon** [comment]
>I've tried to replicate this behaviour in a CodePen, but I am not able to maintain two ref references to the same child (ie the ancestor component's ref gets nulled).

I think you might have missed this paragraph:

>Note: `React.cloneElement(child, { ref: 'newRef' })` DOES override the ref so it is still not possible for two parents to have a ref to the same child, unless you use callback-refs.

It's unfortunately not very clear, but the point was that **if you override `ref` it still gets overwritten**. The change in RC was related to the case where **you just clone but don't override `ref`**.

However, indeed, it is possible to keep both refs with callbacks. You just need to do it manually.
Based on your example:

```js
  extendChildren(){
    return React.Children.map(this.props.children, child => {
      return React.cloneElement(
        child,
        {
          ref: (node) => {
            this._input = node;
            if (typeof child.ref === 'function') {
              child.ref(node);
            }
          }
        }
      );
    });
  }
```

**Comment by pvienneau** [comment]
Ah great. Yes, I misunderstood the meaning behind `callback-refs` in the docs, but thanks for walking me through a solution. I appreciate it.

**Comment by arnemahl** [comment]
@gaearon Don't you need to bind the `ref(node)` function, or turn it into an arrow function, to make it access the correct `this`?

**Comment by gaearon** [comment]
Yea I think you're right. You need to.

**Comment by gaearon** [comment]
Or maybe not. :P

I don't remember whether React takes care to call it with the right instance or not. You can try and let me know.

**Comment by arnemahl** [comment]
Tested it to make sure :) `this` was undefined.

Apart from that it works perfectly. Below is the fixed snippet (also added a missing `}`).

```javascript
return React.Children.map(this.props.children, child =>
  React.cloneElement(child, {
    ref: (node) => {
      // Keep your own reference
      this._input = node;
      // Call the original ref, if any
      const {ref} = child;
      if (typeof ref === 'function') {
        ref(node);
      }
    }
  })
);
```

**Comment by gaearon** [comment]
Thanks! I fixed it up in my comment so that people don't get confused.

**Comment by d07RiV** [comment]
Surely you meant `const {ref} = child.props;`?

**Comment by gaearon** [comment]
>How does this work - why is ref a property of child itself, and not of its props?

Because it doesn't behave like a prop. A component can't read its own ref (by design). Just like `key`, it's a React-specific property and doesn't become a part of the props.

>Can we rely on it?

Yes.

**Comment by bananatranada** [comment]
@gaearon Please forgive me if I'm wrong (I have a hard time understanding the code), but that keeps references of the original children (not rendered) and the cloned version, right? The old children is closed over, yes? `child.ref()` makes a call to the non rendered, original children's `ref`.

**Comment by craigkovatch** [comment]
@gaearon has this advice changed in 16.3+?

Also, latest React typings do not expose a 'ref' property on a `ReactElement<P>`, despite the property being readable at runtime. Am I doing something bad? 🙃

**Comment by eps1lon** [comment]
The TypeScript typings are maintained by the community over at DefinitelyTyped. If you're missing a property feel free to submit a patch.

**Comment by eemeli** [comment]
Here's a small update to @gaearon's manual method that also handles `createRef()` refs:

```js
return React.Children.map(this.props.children, child =>
  React.cloneElement(child, {
    ref: (node) => {
      // Keep your own reference
      this._input = node;
      // Call the original ref, if any
      const {ref} = child;
      if (typeof ref === 'function') {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    }
  })
);
```

That's based on what the [React internals](https://github.com/facebook/react/blob/2e5d1a8b9e2c29418a27b24306e4c8d5f8681f4f/packages/react-reconciler/src/ReactFiberCommitWork.js#L693) appear to do: just set the value of `ref.current`.

**Comment by discrete-projects** [comment]
Can you provide an example of how the ref is applied to the child DOM element in the above scenario?

**Comment by eemeli** [comment]
@discrete-projects Something like this? When `Thing` props change, both `doSomething()` and `doSomethingElse()` should be called with the `#dom-thing` element. Fair warning, I've not tested this code.

```js
class Wrapper extends React.Component {
  _input = null

  componentDidUpdate() {
    doSomething(this._input)
  }

  render() {
    return React.Children.map(this.props.children, child =>
      React.cloneElement(child, {
        ref: node => {
          this._input = node
          const { ref } = child
          if (typeof ref === 'function') ref(node)
          else if (ref) ref.current = node
        }
      })
    )
  }
}

export class Thing extends React.Component {
  _ref = React.createRef()

  componentDidUpdate() {
    doSomethingElse(this._ref.current)
  }

  render() {
    return <Wrapper {...this.props}>
      <div id="dom-thing" ref={this._ref} />
    </Wrapper>
  }
}
```

**Comment by Attrash-Islam** [comment]
Interesting how we can do such a solution that you suggested @gaearon but also works for both: _ref functions_ and _useRef_ 🙂 Child can pass ref as a function and pass the useRef object and it works as expected with the parent being use _useRef_.

**Comment by vctormb** [comment]
> Here's a small update to @gaearon's manual method that also handles `createRef()` refs:
> 
> ```js
> return React.Children.map(this.props.children, child =>
>   React.cloneElement(child, {
>     ref: (node) => {
>       // Keep your own reference
>       this._input = node;
>       // Call the original ref, if any
>       const {ref} = child;
>       if (typeof ref === 'function') {
>         ref(node);
>       } else if (ref !== null) {
>         ref.current = node;
>       }
>     }
>   })
> );
> ```
> 
> That's based on what the [React internals](https://github.com/facebook/react/blob/2e5d1a8b9e2c29418a27b24306e4c8d5f8681f4f/packages/react-reconciler/src/ReactFiberCommitWork.js#L693) appear to do: just set the value of `ref.current`.

For me it's not working.. I'm receiving the warning `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by d07RiV** [comment]
This creates big issues when trying to only use useRef, since in this case you're forced to use ref functions, and the rest of the code must also now expect ref's to be functions sometimes. I.e. all forwardRef components can't just set `current` value, they need to check if the ref is a function first.
