### ISSUE TITLE
your website page not working properly in ie10

### ISSUE THREAD

**Issue by flik** [facebook/react#8875]
**Do you want to request a *feature* or report a *bug*?**
I have attached a screen short. check please. 80% people in the world use ie built in browser. 
![ie10 b](https://cloud.githubusercontent.com/assets/900323/22358839/4ae459dc-e464-11e6-9b86-9ff58626b885.png)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by nhunzaker** [comment]
This is the footer of the site. Looks like it's happening because it uses flex-box without the -ms- prefixes for legacy compatibility.

**Comment by gaearon** [comment]
Good catch, do you want to send a PR?

**Comment by nhunzaker** [comment]
Yeah, I'd be happy to, but I can't get to it until this afternoon if @flik you wanna get on that contributor list :)

**Comment by flik** [comment]
:) sure.
