### ISSUE TITLE
React onClick doesn't fire on IE 11

### ISSUE THREAD

**Issue by WebTerminator** [facebook/react#8877]
There seems to be an issue the the onClick not working correctly. 

I was previously using react v.15.4.0, I than changed to 15.3.0, than to 15.2.0 and now to 0.14.8 with no luck. It seems like it's just the onClick as there is an action triggered onChange (on the text input) which works fine.

The jsx component I am talking about is the following (- onClick={this.handleSubmit.bind(this) -), however I assume that the issue will be related to any "onClick" across the application

```
class FirstName extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
	  		submitted: false,
	  		firstNameError: false
		};

		this.setFirstNameErrorOn = this.setFirstNameErrorOn.bind(this);
	}

	setFirstNameErrorOn (v) {
		this.setState({ firstNameError: v })
	}
	getName () {
		var name = this.refs.firstName.value;
        this.setState(function() {
        	this.props.action(name);
        });
        if(name.slice(-1) != 's') {
        	this.props.setHideS(false);
        }
	}
	goNext () {
		this.setState({ submitted: true }, function() {
			this.props.actionID(2);
			this.props.activeNav('case-1');
			this.props.setNavA(true);
			this.setFirstNameErrorOn(false);
		});	
	}
	handleSubmit (e) {
		e.preventDefault();
		window.scrollTo(0, 0);
		if(this.props.currentState.name.slice(-1) === 's'){
			this.props.setHideS(true);
			var url = '/validate-name/' + this.props.name;
			axios.get(url)
		    	.then(res => {
		    		if(res.status == 200){
						this.goNext();
		    		}
		    	},
		    	(error) => { 
		    		this.setFirstNameErrorOn(true);
		    	}
		    );
		}

		else if(this.props.currentState.name != '') {
			this.props.setHideS(false);
			var url = '/validate-name/' + this.props.name;
			axios.get(url)
		    	.then(res => {
		    		if(res.status == 200){
						this.goNext();
		    		}
		    	},
		    	(error) => { 
		    		this.setFirstNameErrorOn(true);
		    	}
		    );
		}
		else {
			this.props.setHideS(false);
		}
	}
	componentDidMount(){
		this.refs.firstName.focus();
	}
	getActiveForm () {
		if (this.props.show === 1) {
			return "show-form";
		}
		else {
			return "";
		}	
	}
	render () {
		var activeForm = this.getActiveForm(this.props.show);
		return (
			<div className={"form " + activeForm + " first-name"}>
				<h2>tell us your<br /> first name</h2>
				<form>
					<input 
						type="text"
						ref="firstName"
						onChange={this.getName.bind(this)}
						placeholder="First Name"
						maxLength="10"
						className={this.state.firstNameError ? 'invalid': ''}
					/>
					<span>Oops! Try again!</span>
					<div className="buttons-wrapper">
						<a href="/" className="back">
							<span>
								back
							</span>
						</a>
						<button className="next" onClick={this.handleSubmit.bind(this)}>
							<span>
								continue
							</span>
						</button>
					</div>
				</form>
			</div>	
		);
	}
};
```

**Comment by aweary** [comment]
Hey @WebTerminator! I'm not able to reproduce your issue. I ran the code you shared in a [JSFiddle](https://jsfiddle.net/m0c6njcc/) and simplified the `handleSubmit` method to just show an alert and it runs as expected in IE11.

Can you share a small example reproducing your issue? You can use the fiddle I linked above (or [the one we link to in the PR template](https://jsfiddle.net/reactjs/69z2wepo/)) as a starting point.

**Comment by WebTerminator** [comment]
Hi @aweary  here is the link (please keep it private): https://tshirt-builder.stage.aiareview.co.uk/builder. Thanks

**Comment by aweary** [comment]
Thanks @WebTerminator, but I mean something more along the lines of the JSFiddle I linked. It's difficult for us to help if we don't have a minimal case reproducing the issue, so we can verify its an issue with React and not your own components.

**Comment by WebTerminator** [comment]
I am really but it was my mistake, I didn't include "npm install --save-dev babel-polyfill". What threw me off was the fact that there was no error in the console. Thanks

**Comment by aweary** [comment]
Glad to hear you figured it out, thanks for the follow up!

**Comment by ShovalLev** [comment]
Im dealing with the same problem and cant find any solution! Did you fixed it??
