### ISSUE TITLE
react tutorial const history

### ISSUE THREAD

**Issue by hermit8888** [facebook/react#8878]
When I copied the code from the code examples on the react tutorial page, into a forked codepen, and followed the tutorial, the time travel in the code didn't work. The following tweak made it work.

Under the "**Storing a History**" section: 

In the fourth code example the line:  **const history = this.state.history;**
was changed to: **const history = this.state.history.slice(0, this.state.stepNumber + 1);**

**Comment by lacker** [comment]
I can't repro this - it seems like it's working for me. Check https://codepen.io/ericnakagawa/pen/ALxakj for a codepen with the final, working code - I just accepted a PR to update the tutorial to link to that, so hopefully this will be clearer to people in the future. My suspicion is that you missed something that was not explicitly laid out in code, but rather just described in text.

**Comment by gaearon** [comment]
@brigand and I rewrote some parts of the tutorial in https://github.com/facebook/react/issues/9454, and following along should be easier now. Let us know if you're still struggling! We’re happy to look at remaining issues in case we missed anything.

https://facebook.github.io/react/tutorial/tutorial.html
