### ISSUE TITLE
JSX is inconsistently in rendering SVG text-anchor attribute between React DOM and ReactTestRenderer

### ISSUE THREAD

**Issue by digiguru** [facebook/react#8880]
I think there is a bug in the behaviour of outputting the following text between ReactDOM and ReactTestRenderer.

```
<svg>
            <circle r="20%" cx="50%" cy="50%"></circle>
            <text textAnchor="middle" x="40%" y="50%">no hyphen</text>
            <text text-anchor="middle" x="60%" y="50%">with hyphen</text>
 </svg>
```

**What is the current behavior?**

It seems that when rendering the component using a jest Snapshot (which uses ReactTestRenderer) produces the following is output.

![Jest HTML output](https://www.evernote.com/shard/s399/sh/ddf1cb51-723e-418f-b504-7d1670629331/787d136f056134af/res/9ffbd86b-a61a-46b2-9dd2-ac967e8488b2/skitch.png?resizeSmall&width=832)
```
<svg
  height="400"
  width="400">
  <circle
    cx="50%"
    cy="50%"
    fill="#bada55"
    r="200" />
  <text
    textAnchor="middle"
    x="50%"
    y="25%">
    no hyphen
  </text>
  <text
    text-anchor="middle"
    x="50%"
    y="75%">
    with hyphen
  </text>
</svg>
```
When I run the same code in the browser using JSX compiled to javascript and put through ReactJS, I get the following output - see [example](https://jsfiddle.net/zfst39e0/)

![Rendered HTML output](https://www.evernote.com/shard/s399/sh/02ca80cc-9249-4606-90de-e144555676e6/001782857fa5964b/res/06d4ba40-c37d-4ccc-9340-a7d1c2eb1a57/skitch.png?resizeSmall&width=832)

```
<svg data-reactroot="" width="400" height="400">
  <circle fill="#bada55" r="200" cx="50%" cy="50%"></circle>
  <text text-anchor="middle" x="50%" y="25%">no hyphen</text>
  <text x="50%" y="75%">with hyphen</text>
</svg>
```

Clearly the Test renderer is leaving unknown attributes as is, whereas the DOM renderer is altering the camelCase to make them hyphenated.

I'm not sure if I can change my JSX to allow this example to work in both scenarios - a jest-snapshot and ReactJS? If not does the bug lie in the jest snapshot renderer or the ReactJS renderer?

**What is the expected behavior?**

ReactTestRenderer behaves the same as ReactJS.

Of note: here are the version numbers I have been using in my code...

```
"devDependencies": {
    "@types/jest": "^16.0.4",
    "@types/react": "^15.0.1",
    "@types/react-dom": "^0.14.20",
    "@types/react-test-renderer": "^15.4.1",
    "jest": "^18.1.0",
    "jest-cli": "^18.1.0",
    "jest-html": "^1.3.3",
    "react": "^15.4.2",
    "react-test-renderer": "^15.4.2",
    "tslint": "^4.3.1",
    "typescript": "^2.1.5"
  },
```

A brief look through the source code yeilds this line for the reactRenderer...

https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/renderers/dom/shared/SVGDOMPropertyConfig.js

I can't find a similar line for the test renderer.

**Comment by niole** [comment]
Maybe this is happening because you are using `text-anchor` instead of `textAnchor` and this attribute is therefore being ignored in your application, which is the correct behavior.

**Comment by gaearon** [comment]
The test renderer is agnostic of the rendering target (DOM/Native) so I don’t think we’ll be treating DOM attributes specially in it. The test renderer verifies what your components intend to render, but not necessarily what appears in the browser.

If you’re *rendering* results of test renderer somewhere (and thus noticing the inconsistency), you can solve this by taking test renderer JSON output, converting it to React elements, and then actually using ReactDOM to render them to HTML or DOM. This way it would go through the same DOM-specific code path.

I hope this helps!
