### ISSUE TITLE
Bump fbjs to 0.9.x

### ISSUE THREAD

**Issue by dmnd** [facebook/react#8898]
Probably lots of React apps depend on babel-runtime, perhaps directly or maybe indirectly. This can problematic, though, because it can cause such apps to depend on two versions of core-js:

1. Your babel using React app -> babel-runtime ^6.22.0 -> [core-js ^2.4.0](https://github.com/babel/babel/blob/2104ab6c44e807e50a799f010ba3e896f0c2e54d/packages/babel-runtime/package.json#L9)
2. React -> [fbjs ^0.8.4](https://github.com/facebook/react/blob/59aac010dd049719394c9cc4b70417302ce73c14/packages/react/package.json#L26) -> [core-js ^1.0.0](https://github.com/facebook/fbjs/blob/e13bb5721844bee2afa065321f260355d080bc3f/package.json#L63)

These two versions aren't semver compatible, so it means a project that depends on babel-runtime and also React will have two copies of core-js in use. A concrete example of this is a React app that [also depends on Relay](https://github.com/facebook/relay/blob/7d5e9165ede146c91b3f0b6583f28f6687289eeb/package.json#L32). There are probably many other such examples, though. It'd be nice to collapse this dependency into a single version of core-js.

React could bump its dependency to the latest fbjs which is [fbjs 0.9.0-alpha.1](https://github.com/facebook/fbjs/blob/master/packages/fbjs/package.json#L61). That's alpha right now, but it's been alpha for 7 months and probably you guys can arrange a stable release if you want to.

See also:

* https://github.com/facebook/fbjs/issues/217
* https://github.com/facebook/relay/issues/1421

**Comment by gaearon** [comment]
Can you try to send a PR that updates it? I’m not sure what changed in fbjs.

**Comment by zpao** [comment]
Not worth doing yet. Follow along in the fbjs issue before anything is done. I'll update the changelog there as I've done in the past so it's easy to determine what has changed.

**Comment by gaearon** [comment]
@zpao Still not a good time?

**Comment by zpao** [comment]
Was chatting with @sophiebits about this a couple weeks ago, were planning on getting to it after 16 launched… so I guess that's now 😀 Let's try to knock that out next week.

**Comment by gaearon** [comment]
@zpao Still wanna do it?

**Comment by adamnoakes** [comment]
any update on this?

**Comment by billyjanitsch** [comment]
@adamnoakes the fbjs dependency was removed entirely in #13069.

**Comment by nhunzaker** [comment]
Ah. It has! I believe this can be closed. Thanks for the ping!
