### ISSUE TITLE
pasteOnCapture triggers when the DOM event is in the bubbling phase

### ISSUE THREAD

**Issue by AnilRedshift** [facebook/react#8909]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When setting up an `onPaste` handler, react provides two choices: `onPaste`, or `onPasteCapture`. In both cases, the DOM event.currentTarget is the #document (which is reasonable given how react's delegate behavior works), but the `eventPhase` is `3` (aka bubbling) in BOTH cases.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar 
http://jsbin.com/dacolavipe/edit?js,console,output

**What is the expected behavior?**
Expected is that `onPasteCapture` fires when the DOM event is in the capture phase. This is needed to be able to manipulate the paste handler properly when playing focus games on Edge

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest version of React, affects at least Chrome and Edge, but I suspect it is browser/OS independent.

**Comment by mikekreeki** [comment]
Looks like React juts copies native event's `eventPhase` onto `SyntheticEvent`. It gathers all the handlers into `event._dispatchListeners` simulating capture/bubble phases to get them. Those events will be later run in event queue which does not know at this point in which phrase the handler was gathered. This works the same for other events too.

It seems to me that it's always `3` as React's uses one global event handler which is called in bubbling phase. When reimplementing event system, it does not change this value accordingly when calling provided callbacks.

**Comment by aweary** [comment]
We do listen for some events during the capture phase, so it should be possible to handle the event during the correct phase. I'll have to look into it more 🤔

**Comment by mikekreeki** [comment]
I checked the code and edited my comment to clarify but you were faster 👍

**Comment by gaearon** [comment]
Let's track this in https://github.com/facebook/react/issues/9783.
