### ISSUE TITLE
Docs: Tutorial should not mention getDOMNode

### ISSUE THREAD

**Issue by jaredbeck** [facebook/react#8935]
The current live docs at https://chenglou.github.io/react/docs/tutorial.html contain the following incorrect example:

```
// tutorial16.js
this.refs.author.getDOMNode().value.trim();
```

According to https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html, 

> The other big change we’re making in this release is exposing refs to DOM components as the DOM node itself. That means: we looked at what you can do with a ref to a React DOM component and realized that the only useful thing you can do with it is call this.refs.giraffe.getDOMNode() to get the underlying DOM node. Starting with this release, this.refs.giraffe is the actual DOM node.

so, perhaps the example should be changed to

```
// tutorial16.js
this.refs.author.value.trim();
```

I tried to click on the "Edit on GitHub" link at the top of the tutorial, but got a 404. So, the only thing I could think to do was to open an issue. Hope it helps.

Thanks. :heart:

**Comment by gaearon** [comment]
These are not the current docs, it's just @chenglou’s old fork :-)

The docs are here: https://facebook.github.io/react/docs/tutorial.html
The tutorial itself has been rewritten with a different example, too.

Hope this helps!

**Comment by chenglou** [comment]
Crap, why is my page ranked so high on google?

**Comment by gaearon** [comment]
Must be all your thoughtleadering!

**Comment by jaredbeck** [comment]
Thanks. Cheng, maybe you could take down your old pages so they don't confuse other beginners like me?

**Comment by gaearon** [comment]
Unfortunately this would still be an issue for any of 10K forks of React. Maybe we can add some detection code that adds a banner to the top of the doc page?

**Comment by chenglou** [comment]
@jaredbeck through which link did you access my fork?

**Comment by jaredbeck** [comment]
> Maybe we can add some detection code that adds a banner to the top of the doc page?

That would be better than nothing. I'm worried that I just spent a few hours learning some outdated techniques. :(

> @jaredbeck through which link did you access my fork?

I don't remember, sorry.

**Comment by chenglou** [comment]
For whatever reason you got linked to my fork; It doesn't make sense for me to delete mine, or Dan's, or whoever else's.

I can't disable my gh-pages; but I've updated it to the latest react#gh-pages. This way if anyone stumbles upon my fork they'll at least see up-to-date info.
