### ISSUE TITLE
Dynamic rendering of react component

### ISSUE THREAD

**Issue by praveeni2it** [facebook/react#8944]
In my case, i have a list of component names in left side of the window with a "+" sign. Once I click the "+" sign, the component should get displayed.

If the list is like,
* component-1
* component-2
* component-3
* component-4
* component-5

If my click order is 3,2,5,4,1,
the component should render in the following order,

--Component-3--
--Component-2--
--Component-5--
--Component-4--
--Component-1--
How should i do it?

**Comment by aweary** [comment]
Hey @praveeni2it, we use this issue tracker exclusively for feature requests and bug reports. Support and usage questions should be directed elsewhere like StackOverflow, [discuss.reactjs.org](https://discuss.reactjs.org), or [Reactiflux](https://www.reactiflux.com/).

Hope that helps!
