### ISSUE TITLE
Improve PropType warning and mention received prop type

### ISSUE THREAD

**Issue by pke** [facebook/react#8955]
The warning `Failed prop type: Invalid prop "children" supplied to "Div", expected a ReactNode.` should include the actual type that was detected as invalid. Something like

`Failed prop type: Invalid prop "children" supplied to "Div", expected a ReactNode but got String`.

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.

I've opened a corresponding issue at https://github.com/reactjs/prop-types/issues/12 for anyone looking to continue discussing this.
