### ISSUE TITLE
onChange does the same as onInput, unlike DOM

### ISSUE THREAD

**Issue by caub** [facebook/react#8969]
This is confusing, normally 'change' event is called only with enter key (when the field was changed), 'input' is used for all changes https://jsfiddle.net/crl/8uyr4m0j/

Why did you put the 2 events for the same thing? it's not practical

**Comment by leoasis** [comment]
This is explained in the docs here: https://facebook.github.io/react/docs/dom-elements.html#onchange. It is intentional. The reason why is explained in the docs link as well

**Comment by aweary** [comment]
@leoasis is absolutely correct! This is intentional, as `onChange` behavior is not consistent between all browsers and most users expect it to fire when the input's value has actually changed.

The linked documentation should make it more clear. Hope that helps!

**Comment by caub** [comment]
Thanks for the answers

Still redundant and not helpful to have at least 2 events doing the same thing

**Comment by aweary** [comment]
We recommend using `onChange` over `onInput` as it provides similar semantics but is also more consistent across input types and browsers. Sorry if it caused any confusion! We try to be very explicit about it in our documentation.

We think `onChange` provides a better user experience this way.

**Comment by caub** [comment]
Could you provide another onEventName for the authentic 'change' event on text/email/password.. inputs, instead of discarding it? it's useful for simple updates, because they get fired on blur, or enter
