### ISSUE TITLE
React error reporting with Bugsnag

### ISSUE THREAD

**Issue by refaelos** [facebook/react#8972]
Is there any good guide on connecting React with Bugsnag (or any other solution) for error reporting ?

Will appreciate a good example for this one.

Thanks!

**Comment by aweary** [comment]
Hey @refaelos! I'd recommend checking with Bugsnag or asking in one of the many community driven platforms for discussing React like [https://discuss.reactjs.org/](https://discuss.reactjs.org/) or [Reactiflux](https://www.reactiflux.com/). We use this issue tracker for bug reports and feature requests only.

Sorry we couldn't answer the question!
