### ISSUE TITLE
setState errors

### ISSUE THREAD

**Issue by nicolaselmir** [facebook/react#8980]
Hey Guys, Im new to react and I wanted to know why the setState always gives me this: bundle.js:53089 Uncaught (in promise) TypeError: Cannot read property 'setState' of undefined

this is my code:

```
firebase.auth().onAuthStateChanged(function(user) {
     if (user) {
       axios.get('http://api-goes-here).then(function(res){
         this.setState({facebook : 11111}, function(){
           console.log(this.state.facebook);
         });
       })
     }
   }.bind(this));
```

**Comment by syranide** [comment]
You're not binding `this` correctly.

```
firebase.auth().onAuthStateChanged(function(user) {
     if (user) {
       axios.get('http://api-goes-here).then(function(res){
         this.setState({facebook : 11111}, function(){
           console.log(this.state.facebook);
         }.bind(this));  // <---- this
       }.bind(this))  // <---- and this
     }
   }.bind(this));
```

**Comment by gaearon** [comment]
Yup. You could also use arrow functions.

Here's a good article on how `this` works in JavaScript: https://yehudakatz.com/2011/08/11/understanding-javascript-function-invocation-and-this/amp/

I hope this helps!
