### ISSUE TITLE
React seems to skip rendering semicolon in inline styles.

### ISSUE THREAD

**Issue by moimael** [facebook/react#8986]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With SSR we get this warning using inline styles :

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ound-position:center;" data-reactid="2">
 (server) ound-position:center" data-reactid="2"><
```

I'm not sure if the browser is adding the semicolon or if react is skipping it on the server.

**What is the expected behavior?**
We should not get any warning, markup from client and server should match.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.4.2
Chrome / Linux
Firefox / Linux

**Comment by gaearon** [comment]
Can you provide the code reproducing this?

**Comment by moimael** [comment]
Since it is using SSR it seems hard to provide a fiddle. I can try to extract the code, but it's basic SSR using  renderToString and renderToStaticMarkup.

**Comment by moimael** [comment]
To give more precision, looking at the output of server rendering, React seems to never add a semicolon after the last item in the style attribute.

**Comment by gaearon** [comment]
Maybe you have an HTML minifier that strips the `;` on the server?

**Comment by moimael** [comment]
Oh yeah you're right, we have html-minifier on the server side. It seems to remove the semicolon. Thanks for your help !
