### ISSUE TITLE
ReactCSSTransitionGroup - Animated component not removed from DOM

### ISSUE THREAD

**Issue by ladz** [facebook/react#9001]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When ReactTransitionGroup is used like this (also compare http://codepen.io/ladz/pen/bgzYZG?editors=0010)
```
<CSSTransitionGroup
  transitionName="animatedFullscreenOverlay__anim"
  transitionEnterTimeout={0}
  transitionLeaveTimeout={0}
>...
```
(setting `transitionEnterTimeout` and `transitionLeaveTimeout` to zero) the children of `<CSSTransitionGroup/>` are not removed when the `leave`-animation completed. However, it can be fixed by settings both values to `1`.

**Which versions of React, and which browser / OS are affected by this issue?**
- React 15.4.2
- Safari on iOS 7.1.2 and native Android browser (Android 4.4.2)

CodePen: http://codepen.io/ladz/pen/bgzYZG?editors=0010

**Comment by gaearon** [comment]
Thanks for filing the issue, but I would like to ask you to file it in https://github.com/reactjs/react-transition-group instead. We intend to deprecate TransitionGroup in favor of that repository because we are not maintaining it. Cheers!
