### ISSUE TITLE
Bug: Cannot read property 'remove' of undefined in SimpleEventPlugin.js

### ISSUE THREAD

**Issue by tarun-dugar** [facebook/react#9007]
Sorry if this has been reported before but I could not find it in the issues section. I am getting a`Cannot read property 'remove' of undefined` error in `SimpleEventPlugin.js` but unable to replicate it. Here's where the error is occuring:

```
willDeleteListener: function (id, registrationName) {
     if (registrationName === ON_CLICK_KEY) {
       onClickListeners[id].remove(); // here
       delete onClickListeners[id];
    }
```

Also, here's a StackOverflow link with the same issue: http://stackoverflow.com/questions/33961443/unable-to-get-property-remove-of-undefined-or-null-reference

Also, I am using `React 0.14`. Let me know if you need any more details. Thanks.

**Comment by aweary** [comment]
Hey @tarun-dugar, thanks for the report. In order for us to help you we'd really need a small test case that reproduces the issue, so we can investigate it. `v0.14` is also a pretty old release, it's possible there were bugs that have been resolved in newer releases. Can you test with the latest release and see if you can reproduce the issue?

**Comment by tarun-dugar** [comment]
@aweary I was able to replicate the issue and did solve it. The issue was, as mentioned in the StackOverflow link in the question, that I was trying to access a `prop` passed by a parent component which was undefined, in the render function. Here's the hierarchy:

```
ParentComponent:
    render() {
        <ChildComponent
            data={this.props.sharedBy} // sharedBy is undefined
        />
    }

ChildComponent:
    render() {
        this.props.data.get('something') // this leads to the error I stated in the question
    }
```
Let me know if you need more details. Thanks.

**Comment by aweary** [comment]
Thanks for the update @tarun-dugar. In that case, it doesn't seem to be a bug with React, so I'll go ahead and close this out.
