### ISSUE TITLE
The Perf Doc printOperations image not update

### ISSUE THREAD

**Issue by monkindey** [facebook/react#9008]
> ### If I misunderstood, please let me know, and to apologize if I no clear to describe.

### Do you want to request a *feature* or report a *bug*?

Maybe Bug

### What is the current behavior?

When I look into the [Perf Doc](https://facebook.github.io/react/docs/perf.html#printoperations) and I saw the field print By printOperations function different with the Doc Image.

**The Image is**
![image](https://cloud.githubusercontent.com/assets/6913898/22968487/8b9b7078-f3a5-11e6-9e6a-c992c746e4c6.png)

and the printOperations print is 

![image](https://cloud.githubusercontent.com/assets/6913898/22968527/b3f6d896-f3a5-11e6-9bf6-a9cd2302854f.png)

* Owner > Node
* Operation
* Payload
* Flush index
* Owner Component ID
* DOM Component ID

### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).

NO, just the Doc

### What is the expected behavior?

would be awesome if change the image to sync the printOperation print and explain the new fields of it.

### Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?

NO, just the Doc

Thanks

**Comment by gaearon** [comment]
Thanks for reporting!
There’s just more details now, and they may change later again.

Feel free to send a PR with more accurate picture.

**Comment by monkindey** [comment]
Thanks @gaearon , I am glad to take a stab, Do I just replace `/docs/img/docs/perf-dom.png` with [this picture](https://cloud.githubusercontent.com/assets/6913898/22968527/b3f6d896-f3a5-11e6-9bf6-a9cd2302854f.png) ?

**Comment by gaearon** [comment]
To be honest I’m not entirely sure it’s worth doing. Others are outdated too. And as I said, they will change again.

**Comment by monkindey** [comment]
As you said, will release the new [Perf Doc](https://facebook.github.io/react/docs/perf.html) soon ?

**Comment by gaearon** [comment]
Perf addon has been removed from React 16. We might revive it at some point, but for now it's not relevant anymore.
