### ISSUE TITLE
Question | forceUpdate

### ISSUE THREAD

**Issue by viorelrj** [facebook/react#9012]
**Hello, I am a new user of React. I use it to make a web-app of creating css-based animations, so I have a div which shows the preview of animation, by adding div with certain classes in this node. The problem is that all the animations must be timed correctly, but they are out of sync when adding new div (because of React's feature of smart dom update). I found a way that I must update all the node containing animated divs. I tried to use forceUpdate, but it seems that I don't use it in correct way... I didn't find enough information about this method so I would be glad if someone could help me out.**

**Comment by ihtml5** [comment]
@viorelrj you can view [forceUpdate](https://facebook.github.io/react/docs/react-component.html#forceupdate) and [skip shouldComponentUpdate](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) at [react offical docs](https://facebook.github.io/react)

**Comment by aweary** [comment]
Hey @viorelrj! Welcome to the community. The issue tracker is meant only for bug reports and feature requests. I recommend asking in one of the various other community platforms oriented around support, such as [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

Hope that helps!
