### ISSUE TITLE
Feature - Best error tracking for React Special Props errors

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/react#9016]
I'm currently using React v15.4.1 and this error is displayed in the console:
```

Warning: li: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. 

printWarning @ warning.js:36
warning @ warning.js:60
warnAboutAccessingKey @ ReactElement.js:60
dehydrate @ backend.js:7956
dehydrate @ backend.js:7956
(anonymous) @ backend.js:7187
flushBufferSlice @ backend.js:7182
flushBufferWhileIdle @ backend.js:7170
```

I can't track easily what component trigger this error. I have to do a "binary search" in my code to find it.

**Comment by gaearon** [comment]
This is not coming from your components. It's an accidental mistake I introduced into React DevTools. Update React DevTools to the latest version, and it'll disappear.

**Comment by BrunoQuaresma** [comment]
I updated the extension to 2.0.12 and it works. Thanks @gaearon

**Comment by gaearon** [comment]
Sorry for the disruption 😊
