### ISSUE TITLE
Can I load data in the constructor?

### ISSUE THREAD

**Issue by HopeLyn** [facebook/react#9021]
After reading the docs [componentDidMount()](https://facebook.github.io/react/docs/react-component.html#componentdidmount), I was recommended to load data in the `componentDidMount()` method and I did it.It runs well.

But I still has a question: can we load data earlier than `componentDidMount()`?(like `constructor()` or `componentWillMount()`)

PS: Maybe it's my fault that not search too much. If there is any related docs or issues, plz point to me.I will appreciate it.

**Comment by TryingToImprove** [comment]
Take a look at http://stackoverflow.com/a/27139507/1514875

**Comment by aweary** [comment]
Hey @HopeLyn! You technically could load data in `constructor` and `componentWillMount`, but as the docs say, we recommend using `componentDidMount`. You likely won't see any noticeable difference loading it in an earlier lifecylce method, and it complicates things if you ever do server-side rendering.

Also, we use this issue tracker for bug reports and feature requests only. If you have a support or usage question we recommend using one of the many communities oriented around that, such as StackOverflow, [Reactiflux](https://www.reactiflux.com/), or [discuss.reactjs.org](https://discuss.reactjs.org/).

Hope that helps!

**Comment by HopeLyn** [comment]
@TryingToImprove @aweary Thanks a lot.
