### ISSUE TITLE
Unexpected behavior with wrapped `input` and `onChange` handlers

### ISSUE THREAD

**Issue by rangerscience** [facebook/react#9024]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

This is a code snippet to make one input "follow" a React expression until the user changes the field manually. This is accomplished by wrapping `input` with a Reach component, `Input`. Ideally, any property for `input` will work for `Input` - including `onChange` handlers.

Specifically, it's intended to let an `Input` follow the value of a regular `input` element.

When the `input` element wrapped by the `Input` component is changed, a React synthetic event is (as expected and desired) created and sent to the handlers.

However! When the "followed" `input` element is changed, the `Input` component `onChange` is triggered, with (AFAIK) a regular, non-synthetic `event` object.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

https://jsfiddle.net/4o6ypzg4/
(events are written to the console; open it up and take a look)

**What is the expected behavior?**

The `Input` component's `onChange` handler receives a React synthetic event.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.0, 15.4.2; Chrome 55.0.2883.95 (64-bit) on MacOS

**Comment by monkindey** [comment]
> If I misunderstood, please let me know, and to apologize if I no clear to describe.

It's not a **bug**. Maybe it's the closure which has the event variable in the React Component lifecycle.

First, How the React Event work is no clear to me. I just speculate.

When I take a look you code, I saw that 

```javascript
  componentWillReceiveProps(nextProps) {
    if(this.state.do_follow) {
      this.setState({value: nextProps.follow})
    }

    if(this.props.onChange) {    
      this.props.onChange(event)
    }
  }
```

you try to deliver the `event` to the App Component handleChange function. But if the scope have the event variable, the `this.props.onChange` call will throw the error. So I think, Does every hook in the React Component lifecycle also have the `event` variable. I try the `componentWillMount` in your demo, `console.log(event)` also print the native DOM Event.

Thanks.

**Comment by jddxf** [comment]
Actually `event` here is `window.event`, which is only available while a DOM event handler is being called.
See https://developer.mozilla.org/en-US/docs/Web/API/Window/event.

**Comment by gaearon** [comment]
Yes, it's not a bug but a misunderstanding. Indeed, you're passing `window.event` that's set by the browser.
