### ISSUE TITLE
Provide a mechanism for marking the React type so that it can be identified in HTML

### ISSUE THREAD

**Issue by velohomme** [facebook/react#9029]
It would be very helpful during analysis and debugging (especially when unfamiliar with code base) to be able to identify components by looking at the HTML.   For instance <Foo reactType="Foo" .... that would yield <div blah, blah data-react-type="Foo".  I realize I can do this with **data-react-type="Foo"** but it might be nice for formalize this.

**Comment by faurehu** [comment]
Have you tried the Chrome React devtools extension?

**Comment by aweary** [comment]
Yupp, we recommend using [`react-devtools`](https://github.com/facebook/react-devtools) for inspecting and debugging React applications.
