### ISSUE TITLE
Licence Clarification

### ISSUE THREAD

**Issue by sialcasa** [facebook/react#9030]
I've a question regarding the Licence FAQs (https://code.facebook.com/pages/850928938376556)

> Does the additional patent grant in the Facebook BSD+Patents license terminate if I sue Facebook for something other than patent infringement?

Am I right that if facebook infringes a patent of mine and I sue Facebook, I lose the right to use react? That would mean, that I have to move all of my applications to another technology.

**Comment by gaearon** [comment]
It says that if you choose to sue FB for infringing your patents first, then FB may choose to sue back for infringing its patents in return. Whether you “lose the right to use React” as a result can only be determined by the court.

I am not a lawyer and can’t give you legal advice though. If you need more help with this, please contact `jpearce@fb.com` with your concerns. Cheers!

**Comment by Cat-sushi** [comment]
This is my understanding.
[Too Broad Non-assertion Obligations of React License --PATENTS-- - Qiita](http://qiita.com/Cat_sushi/items/d52332bb10073e5fadfb "Too Broad Non-assertion Obligations of React License --PATENTS-- - Qiita")

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
