### ISSUE TITLE
Plans for a release build package react-15.4.2.zip?

### ISSUE THREAD

**Issue by KoenT-IM** [facebook/react#9036]
Hi,
are there plans to release a react-15.4.2.zip release build package for the latest release (as was done for the previous releases)? Couldn't see it on the Releases page: https://github.com/facebook/react/releases
Thanks,
K

**Comment by boxofrox** [comment]
I found the CDN links worked well for retrieving the distributed files in the absence  of the release zip.

https://unpkg.com/react@15.4.2
https://unpkg.com/react-dom@15.4.2

In the event this issue fell through the cracks, pinging @gaearon.

**Comment by gaearon** [comment]
Is there some particular reason you find the zip useful?
Those files are always available on npm and unpkg.

**Comment by gaearon** [comment]
In particular:

https://unpkg.com/react@15.4.2/dist/react.js
https://unpkg.com/react@15.4.2/dist/react.min.js

https://unpkg.com/react-dom@15.4.2/dist/react-dom.js
https://unpkg.com/react-dom@15.4.2/dist/react-dom.min.js

**Comment by gaearon** [comment]
I added them manually to the release, and will be adding those to the future releases too.

**Comment by boxofrox** [comment]
> Is there some particular reason you find the zip useful?

For me, no reason.  I used the zip before I noticed I could use unpkg instead.

Thanks for taking a look.

**Comment by gaearon** [comment]
Got it, thanks.
I added a note to our release process so that we'll attach them the next time.

**Comment by KoenT-IM** [comment]
Sorry for my late answer:
Using the .zip files was just because that's what I've been using to update to newer versions.
I didn't know about unpkg.com, so I learned that now.
Thanks for adding the files to the release.
Koen
