### ISSUE TITLE
Make uncontrolled inputs more user friendly?

### ISSUE THREAD

**Issue by syranide** [facebook/react#905]
`input` is simple enough, it's a bit verbose but there's nothing wrong with `this.getDOMNode().value`.

`select` also has `value`, but it's not supported on IE8 at the very least. Meaning, uncontrolled `select` is not fun at all to work with. If you use `multiple` on top of that, it becomes even worse as `value` seizes to be useful, the nice arrays in React no longer work.

Considering that it should be very little actual code, is it perhaps an idea to consider having `.getValue()`, `.setValue()`, `.focus()`, etc helpers on inputs? It would make reasonable common use-cases a lot less low-level to work with, at the cost of just a few bytes.

**Comment by jimfb** [comment]
I think we ended up going in a different direction here, right?  We no longer have wrappers (we just return the DOM nodes), and I don't think we want to expando DOM nodes.

**Comment by spicyj** [comment]
Yeah.
