### ISSUE TITLE
is it possible to remove ref /key /children from Props ? 

### ISSUE THREAD

**Issue by chandu0101** [facebook/react#9052]
Currently `React.createElement(ctor,props,children)`  extracting ref/key from props (props.key/props.ref) ,because of this compiled to js lanuages([scala.js](http://www.scala-js.org/),[bukclescript/reasonml](https://github.com/bloomberg/bucklescript),..) can't use their native classes as props (currently they wrapping inside js literal).

With Inline elements `{ type: Baz, props: { }, key: 'baz', ref: null } ` they can use native classes as props but it fails when component have children/ref 

From my point of view props should be Component Props and ref,key,children should be placed in different location!

**Comment by sebmarkbage** [comment]
[Inline elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements) can have refs too. You just have to make the compiler add it an ensure that it is consistently the correct types (e.g. not `undefined` or anything like that).

Children is just converted into a property after having been validated for keys. If you can guarantee that keys are correctly applied, you can just compile it to a children property on the native class.

**Comment by chandu0101** [comment]
@sebmarkbage  thanks for info. 

Regarding children : 

```scala
  var a$1 = $i_react.createElement(x$31, x$32, "man");
  var x1 = [{
    "$$typeof": jsx$1,
    "type": constructor,
    "props": props,
    "key": "1",
    "ref": null
  }, {
    "$$typeof": $g.REACT_ELEMENT_TYPE,
    "type": constructor$1,
    "props": props$1,
    "key": "2",
    "ref": null
  }];
  var constructor$2 = $a_app_components_Hello2();
  x$1.children = [a$1, x1];

```

even though i have valid keys inner array(x1) , I am still getting warning for `a$1`  `Each child....` do  i need to ignore this warning ?

**Comment by gaearon** [comment]
@chandu0101 Can you provide a complete example?

If you pass an array of children to `createElement` as third argument, and they lack the keys, you will get a warning. You can avoid it by doing the same thing JSX does: passing each child as variadic arguments. In this case we consider content to be “static” (like `<div><X /><Y /></div>` can never change child order) and thus don’t ask for keys.

Hope this helps.
