### ISSUE TITLE
Documentation - Epub format

### ISSUE THREAD

**Issue by benoitmaudet** [facebook/react#9065]
Hello,

Is there a way to get React documentation in epub format ?

Thanks,

**Comment by NeekSandhu** [comment]
Adobe has [extension ](https://chrome.google.com/webstore/detail/adobe-acrobat/efaidnbmnnnibpcajpcglclefindmkaj?hl=en)for chrome that lets you convert web page to pdf (then you can do pdf -> epub).

But unless some writes a script/bot that'll do that job instead, which I highly doubt, you are likely to be reading not so up to date docs.

**Comment by DanielIzquierdo** [comment]
@benoitmaudet there is an [extension](https://dotepub.com) to do so :shipit: :wink:

**Comment by DanielIzquierdo** [comment]
[here](https://epub.press/) you have another extension that do the same.

**Comment by aweary** [comment]
Thanks for the suggestions @NeekSandhu @DanielIzquierdo! We recommend reading the docs on the website, since they are partially interactive. If you need them in EPUB/PDF/MOBI/whatever then you can take the markdown source and convert them. Hope that helps!
