### ISSUE TITLE
React.PropTypes doesn't handle undefined very well.

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9068]
The [example](http://codepen.io/anon/pen/WpvdYO?editors=0010) shows:

![](http://p1.bpimg.com/567571/133ae6bcb53a47f7.jpg)

Sometimes we will make a typo mistake,e.g., enter `PropTypes.boolean` not `PropTypes.bool`,`PropTypes.fun` not `PropTypes.func`,and then the result are the same with the pic above.This will make us very confused.

And sometimes will spend us 2 or more minutes to find the typo,because at first we will check the code when we first see the error,"oh,god,I don't use `PropTypes.func`,why the error says it should be a func?",and then check it again and again,and finally find that it's just a typo and react will treat the `undefined` as a `func` to check.

I think this is not very friendly and the doc does not mention.Maybe it could be improved?

**Comment by AbsoluteZero273** [comment]
If it's really not intended, can I work on this to throw a warning?

**Comment by NE-SmallTown** [comment]
Is there any body could explain this?

**Comment by NE-SmallTown** [comment]
@gaearon Sorry to bother you dan,but there is no explanation so far,could you clarify my doubt?Thanks a lot!

**Comment by augusto-moura** [comment]
I think it's clear enough. It shows on console that the property type `v` is invalid, so you start from there. The prop type can be any function, from PropTypes object or not.

**Comment by NE-SmallTown** [comment]
@augusto-moura You are right.But the point is that if you don't know **react will treat the undefined as a func to check**,then you will be very confused,it maybe will spend your a lot of time to figure it out especially for new people.And the doc doesn't mention this.

So I agree that if you already know this,it will be easy to realize what the error means.But for new people,it's not very friendly.

**Comment by NE-SmallTown** [comment]
Who can explain this,thank you guys so much :sob:

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.

**Comment by darkkase** [comment]
in python we have somthing called deprecation warning ¬¬

**Comment by lxm7** [comment]
import * as PropTypes from "prop-types";

**Comment by gaearon** [comment]
>in python we have somthing called deprecation warning ¬¬

So do we, and PropTypes have been warning since April.
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

And there's automated codemod that will change the code for you (it's in the link).
