### ISSUE TITLE
split the doc from React repository

### ISSUE THREAD

**Issue by monkindey** [facebook/react#9079]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**

  __documentation__ is tightly coupled with the **React** repository

* **What is the expected behavior?**

   There are many pros to keep the doc in the repo. But, when I git clone react, I discovered the project is so HUGE lead to much slower when I cloned and forked.

   ![image](https://cloud.githubusercontent.com/assets/6913898/23400759/0a320174-fde0-11e6-9c4a-e4026ac6946b.png)

  The docs folder have the 50M size, and the **.git** folder have the 113M because of the docs i think. And I just want the **src** folder which only have the 3.5M.

  There also are some project like vue, webpack to split the doc from repository itself.

**Comment by monkindey** [comment]
Try the `--depth 1` arguments when you clone the React repository. and it will reduce about 60M.

![image](https://cloud.githubusercontent.com/assets/6913898/25138996/99f1150a-248e-11e7-9ebc-4bb694c6e467.png)
But it only got the last commit.

**Comment by gaearon** [comment]
I would prefer to split it too (not all team members agree though 😃). 
I don't think it would help with git history though—even if we delete the folder, the history is still there.

**Comment by monkindey** [comment]
hahaha, Thanks for your reply. I try to clone the repository but doc folder with the git's [sparse checkout](http://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository). But, unfortunately, it can't work. Maybe I use the wrong way. I will take a look into it and  update this issue when I have any new discovery of it.

**Comment by monkindey** [comment]
**Conclusion**: Using the `--depth 1` and git sparse checkout to reduce about **100M**

1. config sparse checkout
   * mkdir sparsed & cd sparsed
   * git init
   * git config core.sparseCheckout true
   * add config which means exclude the docs into .git/info/sparse-checkout file
       ```shell
        !docs/*  
        /*
       ```
   * git remote add origin https://github.com/facebook/react.git
2.  git pull origin master --depth 1

**Result as follows**

![image](https://cloud.githubusercontent.com/assets/6913898/25186956/45c7b80a-2554-11e7-81af-0f7eb3633382.png)

**Comment by gaearon** [comment]
I’ll close since moving docs out wouldn’t solve the issue with git history (unless I misunderstand how Git works).
