### ISSUE TITLE
react how to instance many child compenent on same parent ?

### ISSUE THREAD

**Issue by lafimostafa1990** [facebook/react#9081]
Hi guys,
i would like to call child(child has form) two times on the same parents like this : 
return(
<Child />
<Child />
)
but the problem is there many select on Child so when i'm changing the select i can't get the value from the second select where having second child.

**Comment by aweary** [comment]
Hey @lafimostafa1990, thanks for the question. Unfortunately I'm not entirely sure what you're asking, so I can't provide any clear answer 😢 

Also, we use this issue tracker for bug reports and feature requests only. If you have a support or usage question we recommend using one of the many communities oriented around that, such as StackOverflow, [Reactiflux](https://www.reactiflux.com/), or [discuss.reactjs.org](https://discuss.reactjs.org/).

Hope that helps, have a good one!
