### ISSUE TITLE
Mobile browser support docs

### ISSUE THREAD

**Issue by plievone** [facebook/react#909]
Currently only IE8 is mentioned as a legacy browser in http://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills . In your experience, should docs warn / suggest shimming some iOS or Android versions too? There might be quite many WP7.5 (IE9 mobile) and WP8 (IE10 mobile) users too (Lumias), where pointer/touch events etc won't work yet.

For example `Function.prototype.bind` is missing before Safari 5.1.4 (old iPads etc?) and I usually include even json2.js for old mobile browsers.

**Comment by gaearon** [comment]
Closing as outdated. If you think this is still relevant, please submit a pull request to new documentation. Thank you!
