### ISSUE TITLE
[Fiber] Make TreeHook DEV-only

### ISSUE THREAD

**Issue by gaearon** [facebook/react#9090]
We recently started pulling TreeHook in production bundle for the sake of the Fiber stacks in error boundaries, but as @trueadm observed, [this breaks the UMD bundle](https://github.com/facebook/react/blob/c8f14c26b05d84ac6f5d1fd93e9572d589b837f2/src/umd/ReactUMDEntry.js#L27).

We could remove the `__DEV__` gate there, but it's still bad to pull the whole hook into the prod bundle when we only use a [small part of it](https://github.com/facebook/react/blob/c8f14c26b05d84ac6f5d1fd93e9572d589b837f2/src/isomorphic/hooks/ReactComponentTreeHook.js#L379-L388) in Fiber.

I think we should separate what we need in dev and prod, and not pull extra code into the prod bundle.

Linked: #9096

**Comment by bvaughn** [comment]
I'll look at this 😄
