### ISSUE TITLE
Getting rid of String Refs in ReactTransitionGroup

### ISSUE THREAD

**Issue by juangl** [facebook/react#9093]
Is [this line](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L218) making use of String Refs? Can I make a PR to fix that?

**Comment by gaearon** [comment]
We don't plan to further make changes to TransitionGroup in this repository.
Please contribute to https://github.com/reactjs/react-transition-group instead!
Thanks.
