### ISSUE TITLE
How to locate the corresponding src code of react

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9094]
I notice that sometimes I want to find the implement details of some functions or features(e.g,`React.createElement, React.createClass, PureComponent,Reconciliation...`).

But every time I should add `debugger` in the code,and step over and over to enter the method I want to look,or in the ide to press `ctrl` and click the identifier to enter the file,but the code is promiscuous and nested,so it is diffcult to read.

So I want to know that is there a good way to solve this?I guess there maybe is a internal system to work fine on this?

**Comment by gaearon** [comment]
[Codebase Overview](https://facebook.github.io/react/contributing/codebase-overview.html) and [Implementation Notes](https://facebook.github.io/react/contributing/implementation-notes.html) should give you some initial context.

We are currently rewriting the core from scratch, so that’s one of the reasons why there’s so much code. We’ll be removing quite a lot of it soon.

Hope this helps!

**Comment by NE-SmallTown** [comment]
@gaearon Thank you dan,I have read the Codebase Overview and Implementation Notes.Before I just image that in your internal there is a way like just enter the key according to some rules(e.g.,enter `PureComponent : implement&file:[a-z].js` or  `createClass: definition&file:[a-z].js&date:xxx`) or even convenient we can do this by some visual operations.

But from your answer,there is not :rofl: ?

 And another question,I want to read or contribute to react fiber,I have read your "How to contribute" and watch the youtube video.Later I will read the [react fiber architecture](https://github.com/acdlite/react-fiber-architecture) and [Umbrella for remaining features](https://github.com/facebook/react/issues/7925) and [more details](https://github.com/facebook/react/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%5BFiber%5D).

But I notice that there are also many content about [old architecture](https://github.com/reactjs/react-future) or Reconciliation,so I want to know is it necessary to learn these?Or just go to learn fiber.

**Comment by gaearon** [comment]
No, there’s no such system, usually if you want to find something, you just search the project for the matching name.

I think it’s beneficial to learn how both work. Fiber is more complicated.

**Comment by NE-SmallTown** [comment]
@gaearon Thanks.Ye,I usually just search on the github or ide,but I find that the results are too much,and to filter them to find the only result that I want is a little difficult and waste some time.But from your answer,I believe if I know more about the codebase architecture as time goes on,I will be familiar with this,thanks again.
