### ISSUE TITLE
Pasting text in text box does not fire change event on IE11.

### ISSUE THREAD

**Issue by mashimonator** [facebook/react#9100]
I found a bug in IE11.
React version is 15.4.0.

Pasting text in text box does not fire change event on IE11.

https://jsfiddle.net/mashimonator/uh699v8d/6/

**Comment by gilbertKaradja** [comment]
Could not reproduce it(using your fiddle) in IE 11. Ver: 11.162.10586.0

**Comment by mashimonator** [comment]
I use ver 11.0.9600.18538
![untitled2](https://cloud.githubusercontent.com/assets/2460942/23583533/a5e2f65c-018a-11e7-9645-8fbda1bb1308.gif)

**Comment by Krizzu** [comment]
IE 11, ver. 11.0.9600.18537
 I was able to reproduce that.

The thing is - If you use a keyboard shortcut (CTRL+V), it will update. However, using Right Click -> Paste does not trigger updating. 

Also noticed that, If you press that small X at the end of input box, it won't trigger the update either.

**Comment by jitendra091** [comment]
Working on version  IE-11.0.9600.16428. And facing the same issue but in case of shortcut (CTRL+V).

**Comment by gaearon** [comment]
We've dropped IE from supported browsers in React 18 so this is unlikely to get fixed.
Sorry.
