### ISSUE TITLE
Getting `Cannot read property 'onBeginFlush' of undefined`

### ISSUE THREAD

**Issue by pnkapadia6** [facebook/react#9104]
Getting this bug `Cannot read property 'onBeginFlush' of undefined` from
`react-dom/lib/ReactServerRenderingTransaction.js` file on loading the react app.

react and react-dom are of version 15.4.2

The issue isn't browser specific. And have tried a couple of older versions of react/react-dom too.

**Comment by gaearon** [comment]
Can you check if you're using a minified version of `react.min.js` with a non-minified version of `react-dom.js`? Also I'm a bit confused about why you're seeing something from `ReactServerRenderingTransaction` in a client side app. Are you using server rendering?

**Comment by pnkapadia6** [comment]
@gaearon This is the project I'm working on https://github.com/pnkapadia6/math-redux

**Comment by gaearon** [comment]
So far I'm unable to run your project:

<img width="467" alt="screen shot 2017-03-03 at 8 11 19 pm" src="https://cloud.githubusercontent.com/assets/810438/23567376/e8a9ded0-004d-11e7-8c44-36bc359ccd79.png">

For some reason there are two Webpack modules with ID = 10:

<img width="695" alt="screen shot 2017-03-03 at 8 14 01 pm" src="https://cloud.githubusercontent.com/assets/810438/23567393/f581974c-004d-11e7-955a-e16913f5cbf5.png">

Have you tried using something official like [Create React App](https://github.com/facebookincubator/create-react-app) instead of configuring Webpack by hand? It's hard for me to help you because there seems to be something wrong with how Webpack is configured in your project, but I don't know what.

**Comment by pnkapadia6** [comment]
I wanted to setup myself and was working on this last year. Not sure what I changed down the lane, probably related to some module's version, that's breaking it.
Thank you for looking into it.

**Comment by gaearon** [comment]
I removed the `scss` files that were causing troubles (not sure why—could be a Webpack bug), and the game appears to run fine:

<img width="671" alt="screen shot 2017-03-03 at 8 20 13 pm" src="https://cloud.githubusercontent.com/assets/810438/23567589/dee13a3c-004e-11e7-8bf6-f361749ad81c.png">

<img width="268" alt="screen shot 2017-03-03 at 8 19 29 pm" src="https://cloud.githubusercontent.com/assets/810438/23567559/be1cf9f8-004e-11e7-8ff4-53d3d39d679d.png">

So I'm going to assume something in your build toolchain is causing the issue, and it's not a problem with React. Please use Create React App for a more supported experience.

**Comment by pnkapadia6** [comment]
Oh ok. Will fix that or shift to Create React App. Thank you!

**Comment by gaearon** [comment]
Can I ask you to reupload the project? Some Webpack folks are interested in digging into why it broke.

**Comment by TheLarkInn** [comment]
Also if convenient in the meantime I'm interested in seeing what stats look like with --verbose flag. @gaearon if you still have locally could you share a screen cap?

**Comment by gaearon** [comment]
@TheLarkInn 

I forgot I have the local copy still 😄 . There you go:

[Archive.zip](https://github.com/facebook/react/files/818154/Archive.zip)

**Comment by TheLarkInn** [comment]
Awesome I'll make some bandwidth for this tonight.

**Comment by alexrussell** [comment]
@gaearon FWIW your archive builds and runs fine for me (albeit looking like your screenshot), so I have a feeling your uploaded archive may be the version without those SCSS files that were causing the issues, and thus not overly helpful to @TheLarkInn. I may be wrong of course, but thought I'd better say something in case.

**Comment by gaearon** [comment]
Oops, you're right. Here's the version before my changes.
[Archive.zip](https://github.com/facebook/react/files/818747/Archive.zip)
