### ISSUE TITLE
Question/Bug report in higher-order-components.md

### ISSUE THREAD

**Issue by benjamingr** [facebook/react#9112]
Hey, at the moment the docs at https://github.com/facebook/react/blob/master/docs/docs/higher-order-components.md (and in https://facebook.github.io/react/docs/higher-order-components.html#static-methods-must-be-copied-over) say that static methods need to be copied over.

However, class inheritance in JavaScript also works for static properties.

```js
class Base {
  static get x() { return 5; }
}
class Sub extends Base {}
console.log(Sub.x); // 5
```

Looking at the recommended `hoist-non-react-statics` it looks like it just [copies the properties over](https://github.com/mridgway/hoist-non-react-statics/blob/master/index.js#L41) but `extends` is supposed to do that (with prototypical inheritance) anyway.

Is this an error in the docs (from a time ES2015 classes were not used, in ES5 `Function.prototype` extension this doesn't work - only with classes)?

**Comment by aweary** [comment]
Hey, @benjamingr! While static properties from base classes may work when using inheritance, most higher-order components use composition instead, and it's what we recommend doing as well. See our [doc page on Composition vs Inheritence](https://facebook.github.io/react/docs/composition-vs-inheritance.html) and the ["Mixins are Harmful"](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html) blog post for more details on why we recommend that.

If you look at the examples on the doc page, you'll see that the HOC never actually `extend`s the base class, it just wraps it in a new a class that renders base class.

I hope that helps!
