### ISSUE TITLE
Programmatically trigger onChange for IE

### ISSUE THREAD

**Issue by franz-see** [facebook/react#9116]
I am trying to test my script by programatically triggering onChange on my class. But it doesnt seem to work on IE8. Kindly advice how to proceed.

I created this jsfiddle to show that : https://jsfiddle.net/9gzej3u5/4/

The top part shows a typical reactjs code wherein values typed in an input field automatically appears in a separate DOM element.

The bottom part is the code wherein I try to programatically set the value on the reactjs's input field and trigger a change event. 

If the jsfiddle above is execute in a Chrome, Firefox, or Safari, the code works. If it is executed on an IE8 (for example), it fails.

Kindly advice how to programmatically an onChange event.

Thanks,
Franz

**Comment by aweary** [comment]
Hey, @franz-see! React uses a synthetic event system which does a lot of behind-the-scene work to normalize events across browsers. It's likely that you'll run into strange issues if you try to trigger native events manually like that.

Is there a specific use case you need to support? 

Also, I tested in IE10 and it appears to work. Are you trying to get this working with IE8 specifically? If so, it's worth nothing that React no longer supports IE8.

**Comment by vitalyq** [comment]
@aweary while the part that changes the element's value works, onChange handler is not invoked here. Actually it doesn't work in any IE at all.

The solution depends on what you are trying to achieve. Please check my [answer](https://github.com/facebook/react/issues/3249#issuecomment-292919084) in #3249.

**Comment by gaearon** [comment]
We don't support IE8 so I'll close this.

If you're experiencing problems in other versions please file a new bug with full instructions to reproduce and an example.
