### ISSUE TITLE
ReactCSSTransitionGroup nested transitions

### ISSUE THREAD

**Issue by radencode** [facebook/react#9118]
I am having an issue where I apply an animation to the parent route and the children inherit the same animations. I want different animations for the parent route from the the children routes. Can any one help with that. Here is what I am doing:

render() method:
```
const path = this.props.location.pathname;
const segment = path.split('/')[1] || 'root';
```
return() method:
```
<ReactCSSTransitionGroup
          transitionName = "fade"
          transitionEnterTimeout = {750}
          transitionLeaveTimeout = {250}>
          {React.cloneElement(this.props.children, {key: segment})}
</ReactCSSTransitionGroup>
```

And then in my children component:
```
<ReactCSSTransitionGroup
          transitionName = "slide"
          transitionEnterTimeout = {1000}
          transitionLeaveTimeout = {1000}>
          {React.cloneElement(this.props.children, {key: this.props.location.pathname})}
</ReactCSSTransitionGroup>
```

The children routes get `fade` instead of `slide` animation?

**Comment by gaearon** [comment]
Hi! This is a bug tracker rather than a support forum. I encourage you to check out [suggested support channels](https://facebook.github.io/react/community/support.html) for help with issues like this. Cheers!
