### ISSUE TITLE
Missing /> in tic tac toe tutorial throws errors on codepen

### ISSUE THREAD

**Issue by karlpokus** [facebook/react#9122]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

This line -> `<button className="square" onClick={() => alert('click')}>` located [here](https://facebook.github.io/react/tutorial/tutorial.html#an-interactive-component) throws errors in codepen as it's missing a closing tag `/>`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using the [starter code](https://codepen.io/ericnakagawa/pen/vXpjwZ?editors=0010) so using

- `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js`
- `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js`

**Comment by gaearon** [comment]
The tutorial says:

>Try **changing the opening tag** returned in the render() function of the Square class to:

It doesn’t ask you to change the whole expression. Just the opening tag.

**Comment by gaearon** [comment]
cc @lacker, this came up many times before. Do you think we can rephrase this?

**Comment by karlpokus** [comment]
@gaearon Oh! You're right. My bad.

**Comment by gaearon** [comment]
No worries, this part is confusing. I think people attempted to fix it at least three times.

**Comment by karlpokus** [comment]
> I think people attempted to fix it at least three times.

That's rather impressive :sunglasses: FWIW I got it right from your comment. Maybe all that is needed is something like *not the whole expression*?

**Comment by gaearon** [comment]
#9441 fixes it, and there’s further fixes on the way. Closing.

**Comment by gaearon** [comment]
@brigand and I rewrote some parts of the tutorial in https://github.com/facebook/react/issues/9454, and following along should be easier now. Let us know if you're still struggling! We’re happy to look at remaining issues in case we missed anything.

https://facebook.github.io/react/tutorial/tutorial.html
