### ISSUE TITLE
Mapping a function returning JSX to a list containing 0 returns a weird element in debugger.

### ISSUE THREAD

**Issue by szhongren** [facebook/react#9123]
Not sure what this is, have only confirmed it in the React Debug extension on Firefox. I'm using webpack 2.2.1 and babel-core 6.23.1.

Code [here](https://jsfiddle.net/p16qux88/5/). HTML of the actual page is fine, but in the debugger the 

    nums.map(
        (number) =>
            <li key={number.toString()}>
                {number}
            </li>)

turns into

    <li key="-1">-1</li>
    <li key="0"/>0
    <li key="1">1</li>

I'm not too familiar with JS so if this is expected behavior I apologize.

**Comment by aweary** [comment]
Hey @szhongren, thanks for the report. I tested your component out in Firefox using React Devtools 2.0.12 (assuming that's what you mean by React Debug?) and it appears to be displaying the elements just fine

![screen shot 2017-03-06 at 11 14 13 am](https://cloud.githubusercontent.com/assets/6886061/23620901/460106a0-025e-11e7-854f-b1b27e8917d6.png)

I would make sure you have the latest version of React Devtools installed. Also, the devtools is a separate project with its own issue tracker at [facebook/react-devtools](https://github.com/facebook/react-devtools/), so I would recommend you post there instead if you can provide a reproducible test case for them to look into!

**Comment by szhongren** [comment]
Ah ok, thanks! I'll work on reproducing it and post it there.
