### ISSUE TITLE
how to use react-native

### ISSUE THREAD

**Issue by KonishiLee** [facebook/react#9129]
I'm create a application use react-native, repository is [MoviePlate](https://github.com/KonishiLee/MoviePlate),  i don't use the redux or flux,  so i want to kown this app whether to use correct.

**Comment by gaearon** [comment]
For support questions, please [visit the appropriate venues](http://facebook.github.io/react-native/support.html). We use the issue tracker for bugs in React core. It is also not clear what exactly you are asking.

**Comment by KonishiLee** [comment]
I'm so sorry to create this issue, thank u for answer the question very much.

**Comment by gaearon** [comment]
No worries! Discord is a good place to get help: #react-native.

**Comment by KonishiLee** [comment]
Thank u very much, I got it.
