### ISSUE TITLE
Dynamically rendering a React component

### ISSUE THREAD

**Issue by anault** [facebook/react#9131]
Using React 15.1.0 and Node 4.6.2

**When assigning a Component passed by props to a var, and then trying to render this var, it renders nothing.**

In this example, `ParentComponent1` properly renders `ChildComponent`, but `ParentComponent2` does not:

```javascript
class ParentComponent1 extends React.Component {
  render() {
    return (
      <this.props.dynamicComponent />
    );
  }
}

class ParentComponent2 extends React.Component {
  render() {
    const dynamicComponent = this.props.dynamicComponent;
    return (
      <dynamicComponent />
    );
  }
}

class ChildComponent extends React.Component {
  render() {
    return (
      <div>Hey!</div>
    );
  }
}

ReactDOM.render(<ParentComponent1 dynamicComponent={ ChildComponent } />, ...);
ReactDOM.render(<ParentComponent2 dynamicComponent={ ChildComponent } />, ...);
```

Here's what `console.log(<this.props.dynamicComponent />);`
![alt text](https://dl.dropboxusercontent.com/s/5aakdbxfbegcn74/2017-03-07%20at%2011.44%20AM.png)
As opposed to `console.log(<dynamicComponent />);`
![alt text](https://dl.dropboxusercontent.com/s/spg38a277mezi9r/2017-03-07%20at%2011.43%20AM%20%281%29.png)

**Comment by gaearon** [comment]
This is just how JSX works.
If you change it to

```js
var DynamicComponent = this.props.dynamicComponent;
return <DynamicComponent />;
```

it will work fine.

Explanation:

https://facebook.github.io/react/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized
