### ISSUE TITLE
Impure state allocation / JSX shortcoming? List cannot interface with Item's props?

### ISSUE THREAD

**Issue by neaumusic** [facebook/react#9132]
I seem to have found an edgecase with impure state allocation. I believe that ListComponent should be able to interface with ListItemComponent's props
```
Parent
  ListComponent
    ListItemComponent
    ListItemComponent
    ListItemComponent
```

* The parent knows which items it wants to display in a list
* **A list **item** expects open / closed / selected and displays it's title / content appropriately**
* The parent should not have to manage the list selection mechanic, but the list cannot directly interface with it's embedded list items

```
render () {
  return (
    <div id='parent'>
      <List onComponentSelected={this.forgetAllThatMicro}>
        <Component1/>
        <Component2/>
        <Component3/>
      </List>
    </div>
  );
}
```

---

I was thinking about sending the class names as props, and having List instantiate them, but there doesn't seem to be a way to do this with a dynamic JSX class  -- `<{this.props.classes[0]}/>` ??

---

I saw that `cloneElement` is promoted, but I cannot seem to update a cloned element's props after the initial construction. I'm updating the child styles 60 times per second, and don't want to clone an object for no reason, but this may be the cost of React

**Comment by gaearon** [comment]
Can you create a tiny example demonstrating the problem? It is not exactly clear what you are struggling with.

If you want to pass additional props to received children, yes, `cloneElement()` is how you’d do that. Another option is to pass a function like `renderItem` to prop as a list so that it can call it back with any data. But until we have seen how you tried to solve this, it is hard to help you fix the issues.

**Comment by neaumusic** [comment]
Thanks for the reply man, I will work on an example; essentially -- List cannot communicate through ListItem `props` (&`callbacks`) without going all the way back through Parent, which I think is an anti-pattern because Parent has nothing to do with their interaction

**Comment by neaumusic** [comment]
This does seem to be accounted for, both with cloneElement and JSX.

```
return this.props.children.map((child, index) => {
  return React.cloneElement(
    child, {
      ...child.props,
    }
  );
});
```

```
return this.props.children.map((child, index) => {
  return ( <child.type {...child.props}></child.type> );
});
```

I can interface with the element by adding props the same way I do with any rendered element

**Comment by gaearon** [comment]
Yea. As I noted render callbacks are another way to do this:

https://facebook.github.io/react/docs/jsx-in-depth.html#functions-as-children

This way you could pass additional data to a function that would use that data to return elements.
