### ISSUE TITLE
autoCompleteType attribute unknown prop warning

### ISSUE THREAD

**Issue by toddgeist** [facebook/react#9135]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If you add an autoCompleteType attribute to an input react will warn with this.

`Warning: Unknown prop 'autoCompleteType' on <input> tag. Remove this prop from the element.`

here is a fiddle that shows the issue
https://jsfiddle.net/wjvfxq6r/2/

**What is the expected behavior?**
autoCompleteType does seem to be a standard, there for it should not warn.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested version is 15.4.2.  All browsers

**Comment by toddgeist** [comment]
add autoCompleteType, right after this line.

https://github.com/facebook/react/blob/346d50e2ba0cccf25605791e9739ddb0cf5ddd04/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L42

Also add it to the list of supported props
https://github.com/facebook/react/blob/b59fb796ea2c05c8609858fc28b707d13245fd9c/docs/docs/reference-dom-elements.md#L105

**Comment by gaearon** [comment]
>does seem to be a standard

Can you point me to this standard?

**Comment by simonkberg** [comment]
AFAIK `autocompletetype` was a proposal and never became standard (Chroem implemented this as `x-autocompletetype`). It has been replaced by [autofill](https://html.spec.whatwg.org/multipage/forms.html#autofill) (which uses the `autocomplete` attribute that React already whitelists).

**Comment by gaearon** [comment]
That's my findings as well.

**Comment by toddgeist** [comment]
ok - I get it. I was working off the payment.js repo which recommends this approach. But I see now where I got confused
