### ISSUE TITLE
Learning error, find module error

### ISSUE THREAD

**Issue by pedropcruz** [facebook/react#9137]
Hello, this is my first time on react, and i have this issue:

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" content="text/html" http-equiv="content-type">
    <title>Title</title>
</head>
<body>
    <div id="container"></div>

    <script type="text/javascript" src="../node_modules/react/react.js"></script>
    <script type="text/jsx">
        /** @jsx React.DOM */
        var Hello = React.createClass({
            render: function () {
                return <div>
                            <h1>Hello at {this.props.now}</h1>
                        </div>
            }
        });

        React.renderComponent(<Hello now={new Date().toString()}/>,
            document.getElementById('container'));
    </script>
</body>
</html>`

On browser:
`Uncaught ReferenceError: module is not defined`

What i am doing wrong?

EDIT: More details from the error, it's on the print: http://prntscr.com/ehnj98

**Comment by gaearon** [comment]
`/node_modules/react/react.js` is not React.
You probably want:

* `/node_modules/react/dist/react.js` in development
* `/node_modules/react/dist/react.min.js` in production

That said I recommend trying [Create React App](https://github.com/facebookincubator/create-react-app) for a cohesive and supported learning experience.
