### ISSUE TITLE
Misleading wording in Documentation

### ISSUE THREAD

**Issue by al3x-huang** [facebook/react#9141]
Under "[Lifting State Up](https://facebook.github.io/react/tutorial/tutorial.html#lifting-state-up)": 

> The `onClick` doesn't have any special meaning here, but it's popular to name handler props starting with `on` and their implementations with `handle`.

is misleading because it is special and references the SyntheticEvent handlers. Instead, the documentation should give a brief description of why `onClick` was used and reference the section on [SyntheticEvent](https://facebook.github.io/react/docs/events.html) to allow the users to see available handlers other than `onClick`.

**Comment by gaearon** [comment]
Agreed. Want to fix it? I think the intended meaning is that `onClick` inside `div` matters, but how you call a custom prop on your own component doesn’t.

**Comment by kkemple** [comment]
i can pick this up if no one else is jumping on it

**Comment by gaearon** [comment]
Fixed by #9427.
