### ISSUE TITLE
CSSPropertyOperations.js Failing during Setup

### ISSUE THREAD

**Issue by hmarcelodn** [facebook/react#9150]
Uncaught SyntaxError: Unexpected token : CSSPropertyOperations.js:60.

I am getting this error when loading my page. I am using React with the following web-pack configuration:

```
                {
                    test: (/.jsx$/),
                      loader: 'babel-loader',
                      exclude: /node_modules/,
                      query: {
                          presets: ['es2015', 'react', 'stage-0']
                      }
                }
```

Does anyone understands whats the issue?

Thanks.

**Comment by gaearon** [comment]
What is on line 60 of `CSSPropertyOperations.js` for you locally?

**Comment by hmarcelodn** [comment]
`    process.env.NODE_ENV !== 'production' ? warning(false, 'Unsupported style property %s. Did you mean %s?%s', name, camelizeStyleName(name), checkRenderMessage(owner)) : void 0;  
 `
thats line 60 for my CSSPropertyOperations.js.

**Comment by gaearon** [comment]
Looks normal. It's hard to say what's breaking, but it's most likely unrelated to React.
To tell more we'd need to see your build setup.

Have you tried to use a supported build environment like [Create React App](https://github.com/facebookincubator/create-react-app)?

**Comment by hmarcelodn** [comment]
We are experimenting using "some" React Components to benefit Aurelia Framework which does not support virtualization well as react does. So it's an experimental try of using Aurelia+React+Webpack. In a try to create virtualized-lists components we decided to install the following packages:

- react
- react-dom
- babel-loader
- babel-preset-es2015
- babel-preset-react
- lodash

I just added the following configuration to my webpack file. Anyways I will paste the whole code.

`
        module: {
            loaders: [
                {
                    test: /\.scss$/,
                    loader: ExtractTextPlugin.extract({
                        fallbackLoader: "style-loader",
                        loader: "css-loader?sourceMap!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true",
                        publicPath: "./"
                    })
                },
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader',
                    query: {
                        plugins: ['transform-decorators-legacy'],
                        presets: [['es2015', {loose: true, modules: false}], 'stage-1'],
                        cacheDirectory: true
                    }
                },
                {
                    test: (/.jsx$/),
                      loader: 'babel-loader',
                      exclude: /node_modules/,
                      query: {
                          presets: ['es2015', 'react', 'stage-0']
                      }
                },
                {
                    test: /\.json$/,
                    loader: 'json-loader'
                },
                {
                    test: /\.css$/, loader: ExtractTextPlugin.extract({
                        fallbackLoader: "style-loader",
                        loader: "css-loader",
                        publicPath: ""
                    })
                },
                {
                    test: /\.html$/,
                    loader: 'html-loader',
                    exclude: path.join(METADATA.root, 'index.html')
                },
                { 
                    test: /\.(png|gif|svg|jpg)$/, 
                    loader: 'url',
                    query: { limit: 10000, name: 'images/[hash].[ext]'}
                }
}

`

My babel.rc as following:

`
{
  "presets": [
    [ "stage-1" ],
    [
      "es2015",
      {
        "loose": true,
        "modules": false
      }
    ],
    [ "react" ]
  ],
  "plugins": ["transform-decorators-legacy"]
}
`

**Comment by gaearon** [comment]
I can take a look at a *project* reproducing this, but copy and pasting configs and trying to make it work in hopes of reproducing the issue (which is unlikely in my experience) will take too much time, so I’m not ready to do it.

**Comment by aweary** [comment]
Since there's been no response yet and no there's no reproduction of the issue for us to check out, I'm going to go ahead and close this.

@hmarcelodn as mentioned, it's very likely this is a build tooling issue and not an issue with React itself. If you can put together a small test case reproducing the issue we can help determine where the issue stems from.
