### ISSUE TITLE
Serializing to "HTML with only as much JS as necessary"

### ISSUE THREAD

**Issue by Pomax** [facebook/react#9154]
This is sort of a feature request, mostly because I haven't been able to make the current react tooling do what I need it to do.

I have a massively huge article up on https://pomax.github.io/bezierinfo that consists of a single page of React-managed content, of which the bulk is "passive" HTML content. Paragraphs, headings, that kind of stuff. However, there are also active components with JS interaction bindings, and so I was trying to figure out a way to turn this article into a "react-managed by the client" into a "thin ui managed by the client, react-built offline" solution. 

I had a look at ReactDOMServer.renderToStaticMarkup, but while this generates all the HTML nicely, it also loses any and all JS bindings that are necessary to keep the UI working. As this is an ~800kb article not counting static assets (there's some 1.6MB of images on top of that), the notion of first loading the plain markup content and then loading the react bundle on top of that, to hook into the preloaded markup would be a terrible experience for people in the slightly-less-wealthy parts of the world.

Is there some way to, or would there be a sense in developing a way to render React content to HTML "as much as possible" while preserving React's management of interactive UI components? Essentially, a solution in between `renderToString` and `renderToStaticMarkup`, to prevent as much data duplication between the pregenerated HTML and the react application itself? It seems that the heavy payload (in bytes, but certainly in client-side processing as well) incurred by using a fully react-managed bundle could be relieved significantly if "content that is guaranteed passive, regular HTML" could be serialized out as HTML with React hooking back into that code only for elements that require active management.

(I have no idea how much work that would be, but I'm pretty sure it would help bring down the average page size down again, which on a global scale would save quite a lot of time and money, while allowing content to be loaded by people for whom parts of the internet are currently inaccessible due to load time and byte cost)

**Comment by syranide** [comment]
If I understand you correctly what you want is basically for the server-side to have all the textual content, whereas the client-side would essentially have all passive textual content replaced with NULL and have React re-use whatever textual content is already in the DOM instead.

This is problematic for many reasons, one is that if there is a markup-mismatch and the DOM needs to be regenerated then the necessary textual content doesn't actually exist to do that. The textual content may also have been modified (translated, enhanced, etc) by the server/browser which can make it tricky to correctly resume. If you strip the textual content from your components then it also assumes that there is no client logic requiring that textual knowledge (say a word counter or a word lookup tool).

In my opinion, this feature doesn't really make practical sense for React as it is only really useful for massively passive pages, that is not the intended use-case for React. It also requires a build-tool to somehow be able to identify this passive textual content inside your React components (but not strip active content) and substitute that, React cannot do this for you, I'm not sure how this would even work, it seems intuitively near impossible to accomplish in any meaningful way.

IMHO the solution in your case is to write your page as a regular HTML-page and render React into the interactive areas/examples only. This way the overlap is minimal and only where necessary. React is not designed for progressive enhancement, it's designed for rich interfaces, there's nothing wrong with breaking out of React for "documents" and render parts of it as raw HTML or using something else. If you want you can also render your passive content with `renderToStaticMarkup` if you prefer that over raw HTML.

**Comment by Pomax** [comment]
While I'm sure there might be instances where those problematic cases apply, this is not one of them. The only interaction is on canvas surfaces, manipulation of which do not modify the DOM. As for translation: there is no way I'm letting the client run a translation of 70+ print pages of content, each locale has its own dedicated page, with content appropriate for that particular locale. No after-the-fact modification.

As for "that is not the intended use-case for React": the last thing you want to judge sites against is the *intended* use, what you want to judge against is how the world *actually* uses React in 2017, and that's for far more than pure UI management =)

As for why I can't write it as regular HTML pages: I briefly considered that, but had to very quickly conclude that would be completely unmanageable. [There is a ton of processing that needs to be done on the content](http://pomax.github.io/1489108158510/localization-is-hard), so the only option is to structure this as a build system that ultimately yields a webpage, but in reality is written as components that are easily managed in isolation. And in 2017, the reality is that if someone needs a build framework for web content, the internet tells to use React with Babel and Webpack. 

While I'll absolutely grant you that this is not "the most common use for React", I also highly doubt I'm the only one who needs this functionality - I'm just the first one who filed an issue on it. Having a function that works at a level "in between" `renderToStaticMarkup` (which creates pure HTML without any way to hook React back in) and `renderToString` (which creates *massively* overly verbose markup here, increasing the page size by some 50%), tapping into some React class property that indicates whether a component is passive or not would be extremely useful. Then I (and others) could for instance mark my `<Graphics>` component as "active", and mark most of my other components as "passive", and get a mix of the output that `renderToStaticMarkup` and `renderToString` generate, with the React-hooking attributes applied *only* to the markup associated with active components, for the React bundle to hook into, without React also trying to hook into any of the DOM that isn't going to change.

**Comment by syranide** [comment]
> While I'm sure there might be instances where those problematic cases apply, this is not one of them. The only interaction is on canvas surfaces, manipulation of which do not modify the DOM. As for translation: there is no way I'm letting the client run a translation of 70+ print pages of content, each locale has its own dedicated page, with content appropriate for that particular locale. No after-the-fact modification.

Google Chrome does language translation this way automatically in many cases. There are also extensions that modify the page content in invasive ways. This is why React tags the nodes with IDs, so that it can consistently overcome some invasive modifications to the page content without breaking.

> As for "that is not the intended use-case for React": the last thing you want to judge sites against is the intended use, what you want to judge against is how the world actually uses React in 2017, and that's for far more than pure UI management =)

If people use it outside of its intended purpose then it's on them to be aware of the limitations. Exactly what this is is debatable, but scope/feature creep is not a feature.

> Having a function that works at a level "in between" renderToStaticMarkup (which creates pure HTML without any way to hook React back in) and renderToString (which creates massively overly verbose markup here, increasing the page size by some 50%),

I was under the impression that you wanted to get rid of textual content being submitted twice, first as pre-rendered HTML and later in the JS bundle as well. If what you're concerned about is the react nodeids in the markup then I suggest you measure the size after compression. They compress very well.

IMHO the problem with what you're requesting is that for all ReactDOM apps the number of passive components will always approach 0 over time. You're also making an implementation detail into a user responsibility, if they make even a single mistake and mark a non-passive element as passive then the UI will break, which is horrible. With the upcoming Fiber-renderer for React this MIGHT mean that it will gracefully recover by silently discarding and just re-render that tree instead, but if that's the case then it's may be reasonable for React to drop the nodeids as well as they're no longer critical.

**Comment by Pomax** [comment]
>Google Chrome does language translation this way automatically in many cases. There are also extensions that modify the page content in invasive ways. This is why React tags the nodes with IDs, so that it can consistently overcome some invasive modifications to the page content without breaking.

If a person runs extensions that break websites, then that's on them. If React can't overcome their DOM manipulation to a React-incompatible form, that is not React's failing. I would be more than happy to supply users a website that is doesn't transfer twice if it means React won't try to overcome external content manipulation. 

> I was under the impression that you wanted to get rid of textual content being submitted twice, first as pre-rendered HTML and later in the JS bundle as well. If what you're concerned about is the react nodeids in the markup then I suggest you measure the size after compression. They compress very well.

That is correct, but we're not talking "a few kb" here, we're talking a difference between a 310kb document before gzip and a 220kb document before gzip. Even after compression, the difference is an appreciable 20+kb. At least for the users I'm targeting.

I'm basically trying to support people in less well connected, or expensively connected, parts of the world, so I'm trying to find ways that will reduce both transfer size, and operational activity: if the text gets rendered to html (either static markup or react string, and ideally something in between) then the React app that is served in addition to that html should ideally no longer have the already sent text "in it". In an ideal setup, React is smart enough to see React HTML (in the case of react strings) and be able to recreate what it needs in order to do its job without needing to transfer a bundle that's 180kb (before gzip) heavier due to content duplication.

(Of course I'll happily take a "React doesn't do this on its own, use a specialized Webpack loader like ..." but I know of no such loaders, and certainly don't have the expertise on React or time available to dedicate to writing that loader myself)

**Comment by syranide** [comment]
> If a person runs extensions that break websites, then that's on them. If React can't overcome their DOM manipulation to a React-incompatible form, that is not React's failing. I would be more than happy to supply users a website that is doesn't transfer twice if it means React won't try to overcome external content manipulation.

It's your site that is broken in their eyes.

> That is correct, but we're not talking "a few kb" here, we're talking a difference between a 310kb document before gzip and a 220kb document before gzip. Even after compression, the difference is an appreciable 20+kb. At least for the users I'm targeting.

IMHO 10% overhead doesn't seem like that big of a deal, but obviously not perfect.

> In an ideal setup, React is smart enough to see React HTML (in the case of react strings) and be able to recreate what it needs in order to do its job without needing to transfer a bundle that's 180kb (before gzip) heavier due to content duplication.

Like I said in the previous post, this is more or less impossible. React is a run-time renderer, it knows nothing of your code and even doing this kind of processing of the JS-files would be a truly daunting task. Taking a bunch of JS-files and figuring out which strings inside your components is static would be enormously complicated and reading these strings back from the DOM is hugely fragile.

React is simply not the tool for low-interaction large-document pages with payload size concerns, but jQuery for instance would be a perfect tool. So again, like I wrote, you can design your base page with React and render it with `renderToStaticMarkup` and then separately render all the interactive widgets on-top, but that's really as far as React can go. What you have in mind is simply not feasible and even if it was the use-cases so few that few would be interested in spending the effort to develop the tooling for it.

> (Of course I'll happily take a "React doesn't do this on its own, use a specialized Webpack loader like ..." but I know of no such loaders, and certainly don't have the expertise on React or time available to dedicate to writing that loader myself)

ReactDOM is just one React frontend and (at least with Fiber) can easily be forked and you can have your own implementation; either with passive tagging or simply one that does not tag nodes at all by virtue of being more fragile. But like above, this seems like the smaller concern, content duplication should be far more important to avoid.

**Comment by gaearon** [comment]
Somewhat related discussion: https://github.com/facebook/react/issues/6622.

**Comment by necolas** [comment]
We're working on something related to this feature

**Comment by gaearon** [comment]
We've recently introduced our research on [Server Components](https://reactjs.org/server-components). Server Components let you avoid sending JS code for things that are mostly static.

Server Components still need to encode the render output in the payload for hydration so it doesn't by itself solve the duplication. However, we do plan to add some deduplication when you use Server Components so that it can "reuse" text and attributes from the initial HTML. I think that would be a significant improvement on the use case in this thread. Closing because this issue is more general, and that feature will be a part of the work.

**Comment by Pomax** [comment]
It'd be fantastic if there was still a path to "develop using React, but _generate_ vanilla html + browser-model-obeying js" but it's a hard problem, and not enough people are demanding a path towards having an excellent dev experience with "webby" deployment.

At this point I've moved my own site off of React, with a dev experience that's primarily markdown, and a build system that basically pregenerates _everything_, from HTML to latex-as-SVG files, and even running canvas code on an offline canvas so that the initial frame can be captured as PNG so it can be put on the page as fallback image. This approach means that if the user has JS disabled (I sincerely hope no one still runs a browser without noscript etc. in 2021 =) 100 pages of online book still work perfectly fine, and if they have JS enabled, the page bundle loads and doesn't really "rehydrate" do much as just "attach" to all elements that need interactivity.

As a bonus, this obviates any need for server components; while the dev experience is a watch-based continuous build task, the _result_ is something that can be thrown at any serverless host (gh-pages, aws s3, what have you).

**Comment by gaearon** [comment]
I think there is a bit of a misunderstanding here. Server Components don't really require a _server_, you can run them at the build time. They're just a way to not ship code to the client.

**Comment by gaearon** [comment]
In other words, what I'm saying is that we're working on a first-class way to express something as React components without having to run all of them on the client. Instead, only stateful/effectful components would need to be in the JS bundle.

This mechanism would be compatible both with a server environment (where you run non-client parts on demand) and with a ahead-of-time build environment (where you run non-client parts during the build).

**Comment by Pomax** [comment]
Ah, looking forward to reading the docs on that mechanism.

**Comment by gaearon** [comment]
There's still some difference from what you're looking for because we can't entirely avoid some duplication. I.e. we don't load the _code_ for the components, but we do need to embed their _rendered tree_ as JSON into the HTML at the end. It wouldn't block the initial HTML render but it'd be needed for hydration. It's basically like a pre-rendered React tree. Without this, it wouldn't be possible to mix and match Client Components at arbitrary points in the otherwise static tree. **However**, we have ideas on how to make that embedded representation minimal in terms of its footprint. E.g. it wouldn't duplicate text content and would just reuse it from the initial HTML. Another difference in capability is that for further _navigations_, while you could just let the browser load new HTML, we'll also have a way to load _just_ those rendered trees (assuming their output is written to files parallel to HTML). So that you can navigate from an already loaded page without blowing away all the client state.
