### ISSUE TITLE
Tutorial.md and its tic-tac-toe example.

### ISSUE THREAD

**Issue by agamemnus** [facebook/react#9162]
I think that the [React tutorial](https://facebook.github.io/react/tutorial/tutorial.html) has some significant problems and my question to maintainers is whether there is an appetite to overhaul it. If there is, I will take the effort to do so.

I think that one big problem is that it does not separate the tic-tac-toe example from overall conceptual discussion. Adding disparate non-runnable examples muddles the focus of the tutorial. It should be split up, in my opinion.

As for tic-tac-toe example itself, there are many structural design issues. Probably the most glaring of these is the repetition in the render function of the Board class: `{this.renderSquare(0)}`, `{this.renderSquare(1)}`, etc. There is no hint of how one could use a more programmatic approach. Another issue is the use of `this` everywhere, which very often makes things harder to interpret and introduces bugs -- `this` is not always the same, etc..

I think there should be both an ES5 and an ES6 version (with fewer arrow functions), (and/or something in between?), as this is meant to be a React tutorial example, not an ES6 tutorial. Many people are not familiar with a lot of ES6 syntax, but for those who are, there is also a bit of a tendency to, er, "overuse" arrow functions in the tic-tac-toe example. While ES6 is useful to know, one cannot teach by flooding the student with too many concepts at once.

Here is the current example on the site:
https://codepen.io/ericnakagawa/pen/ALxakj

Here are my current versions: (with a Connect 4 option...):
https://codepen.io/Agamemnus/pen/MppMby -- ES6 (plus JSX).
https://codepen.io/Agamemnus/pen/LWyaLz -- ES5, I think (plus JSX).

**Comment by kasiriveni** [comment]
👍

**Comment by gaearon** [comment]
@lacker Can you please provide direction here?

**Comment by agamemnus** [comment]
Also: if setState is async, don't we need to worry about whether the last
setState finished running before running the click event handler, or is it
queued up already in a clever manner?

**Comment by lacker** [comment]
I think basically we do not have the appetite for an overhaul. A soup-to-nuts tutorial is fundamentally something that involves some stylistic decisions. This one is designed to match how we teach React internally at Facebook, and a lot of those stylistic decisions are aligned that way. Focusing on ES6 is one of those, for example. Each of your points of feedback seem reasonable to me, but they are also somewhat of a matter of opinion. If we take all the differently-opinionated feedback, we will end up with something that feels inconsistent, and that the React team can't maintain.

Overall, I would suggest that if you have a different way you would prefer to have a React tutorial work, write up your own and put it on your site! You can use this exact tic-tac-toe example if you like. We like to have a React tutorial on here to explain React in the way that the React team thinks about it, but there are many React tutorials in the world, that adhere to different principles, and that is a good thing.

**Comment by agamemnus** [comment]
Thanks. I might.

I would suggest making that grid template in the render() at least programatically generated instead of typing it out `{this.renderSquare(1)}` 1 by 1.

**Comment by lacker** [comment]
I dunno, that part seems ok to me. It's just not that big of a grid, and you don't really need your tic tac toe app to be extensible to n x n, so this keeps it simple and comprehensible.

But like I said this is so stylistic. GitHub pull requests aren't even the ideal tool for working on writing, it's like trying to produce a great novel via crowdsourcing. So I encourage you to get out there and write your own tutorial that's way better than this one!

**Comment by agamemnus** [comment]
"But like I said this is so stylistic." Yes, I guess so.

"I dunno, that part seems ok to me. It's just not that big of a grid, and you don't really need your tic tac toe app to be extensible to n x n, so this keeps it simple and comprehensible."
Yes, from your perspective, but I must not be the only one to look at the tutorial and not immediately know that you can put an array of elements into those curly braces... it's not really about making it more flexible, but more about showing that that can be done.
