### ISSUE TITLE
Warn about overwriting React component's instance property `updater`

### ISSUE THREAD

**Issue by roman01la** [facebook/react#9164]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
React component silently overwrites instance property `updater`.

```js
/**
 * Base class helpers for the updating state of a component.
 */
function ReactComponent(props, context, updater) {
  this.props = props;
  this.context = context;
  this.refs = emptyObject;
  // We initialize the default updater but the real one gets injected by the
  // renderer.
  this.updater = updater || ReactNoopUpdateQueue;
}
```

**What is the expected behavior?**
It would be very useful to raise a warning in DEV mode for such a case.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v15.4.2

**Did this work in previous versions of React?** Yes

**Comment by acdlite** [comment]
Good idea. This would be a good first PR!

**Comment by rogeliog** [comment]
I'm happy to help out with this issue

**Comment by tomaszlakomygp** [comment]
Opening a PR, wish me luck!

**Comment by tomaszlakomygp** [comment]
@acdlite PR opened, I'm awaiting your feedback.

@rogeliog Hope you don't mind "stealing" that issue, I had a bit of extra time in front of a screen this evening :)

**Comment by rogeliog** [comment]
@tomaszlakomygp sure!

**Comment by jwilso48** [comment]
Since it's been almost two months since the last update on this issue, I'm gonna give this issue a go.

**Comment by acdlite** [comment]
@jwilso48 We're going to merge @rogeliog's PR, just haven't gotten to it. Been pretty busy here, sorry!

Going to close this issue out in favor of https://github.com/facebook/react/issues/9236
