### ISSUE TITLE
Concatenated prefixed css properties doesn't work in React 15.

### ISSUE THREAD

**Issue by furagi** [facebook/react#9166]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
React doesn't set property display to string ";display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex". It just omit properties, which contains concatenated strings like "-webkit-linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%);background:-moz-linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%);background:linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)" or this I've mentioned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/z5r53tdh/4/
**What is the expected behavior?**
Expected: root div has property display == ";display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex", like it was in React 0.13: https://jsfiddle.net/z5r53tdh/2/
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React@15
Cromium 50.0.2661.102 (64-bit)
Calculate Linux 3.15.5-calculate

Yes, it worked in previous versions of React (0.13)

**Comment by pmacmillan** [comment]
seems to be known: #2020.

It looks like React used to concatenate together a string and then convert that to dom (which allows the invalid CSS), but that in converting to use createElement and setting the style property, the invalid style gets ignored by the DOM.

**Comment by syranide** [comment]
Yep, this is intentional and was never officially supported.
