### ISSUE TITLE
Coffeescript and React 16 (Fiber)

### ISSUE THREAD

**Issue by berkaey** [facebook/react#9167]
This could be a little bit early but I got confused about ```React.createClass``` and  ```React.createFactory``` usage with coffeescript and React 16 (Fiber).

I read some comment (and watching React Conf 17) about moving ```React.createClass``` to another package and removing ```React.createFactory```

So I wonder, can I be able to wrote this below after React 16 released? (and what is the best approach to use coffeescript with react? )

```
React = require "react"

{div} = React.DOM

View = React.createClass
 displayName: "Hello"
 render:()->
  div {className:"hello"}, "Hello React 16"

module.exports = React.createFactory View

```

Thanks.

**Comment by gaearon** [comment]
We’ll likely keep `createFactory` but move `createClass` and `DOM` to another package.
You can still import them from that package (we haven’t settled on the name yet).

It could look like:

```
React = require "react"

createClass = require "react-create-class" // hypothetical name
{div} = require "react-dom-factories" // hypothetical name

View = React.createClass
 displayName: "Hello"
 render:()->
  div {className:"hello"}, "Hello React 16"

module.exports = React.createFactory View
```

There are two problems however:

1) You **should not** export the result of calling `React.createFactory`. This is a bad pattern in today’s React too. Just export the component itself (`View`) in your example, and call `createFactory` when importing it.

2) You don’t need `createClass` for declaring components. CoffeeScript already supports classes. So you should inherit from `React.Component` just like you’d do in ES6.

With my suggested changes your code would look like this:

```js
React = require "react"
div = React.createFactory "div"
// or {div} = React.DOM // works today
// or {div} = require "react-dom-factories" // hypothetical name in React 16

class View extends React.Component
 render: ->
  div {className:"hello"}, "Hello React 16"

module.exports = View
```

Hope this helps!

**Comment by berkaey** [comment]
Thanks! 👍

**Comment by molszanski** [comment]
@berkaey, you might be interested in looking at an official [coffescript 2](http://coffeescript.org/v2/#coffeescript-2)

**Comment by berkaey** [comment]
thanks @molszanski ;)
