### ISSUE TITLE
Possible issue with the warning when the element doesn't have an explicit key assigned to it

### ISSUE THREAD

**Issue by superKalo** [facebook/react#9168]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

I think there might be an issue with the [warning if the element doesn't have an explicit key assigned to it](https://github.com/facebook/react/blob/v15.4.2/src/isomorphic/classic/element/ReactElementValidator.js#L72).

I have the following component:

```javascript
const data = ['first', <br />, 'second', <br />, 'third', <br />];

const MyComponent = () => <div>{ data }</div>;

ReactDOM.render(<MyComponent />, document.getElementById('root'));
```

In dev mode, this triggers the console warning (expected behavior, of course):
> Warning: Each child in an array or iterator should have a unique "key" prop.

However, if I have a nested array of `data`, the warning is gone:

```javascript
const data = [['first', <br />], ['second', <br />], ['third', <br />]];

const MyComponent = () => <div>{ data }</div>;

ReactDOM.render(<MyComponent />, document.getElementById('root'));
```

There is no warning. But why?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Demo: https://jsfiddle.net/superKalo/jdqe74uv/

**What is the expected behavior?**

If I understand well how [the way keys work](https://facebook.github.io/react/docs/lists-and-keys.html#keys), I would expect to get the same warning with the nested array of `data`, just like the one with the flat array of `data`, since in both cases there are no `key` attributes set.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Spot on React 15.4.2.

Tested on Chrome 57.0.2987.98, Firefox 52.0 and Safari 10.0.3 on macOS Sierra.

**Comment by syranide** [comment]
Hmm, I'm actually not sure whether this is intended or not. The sub-arrays themselves will by definition always lack keys and shouldn't warn, that seems like it makes sense. However, the nested elements lacking keys should intuitively emit warnings, but it can also make sense to not emit warnings as not having keys isn't necessarily wrong and you're nesting so you're already doing non-obvious stuff.

Again not entirely sure, some dev hopefully knows :)

**Comment by gaearon** [comment]
I do see the warning for nested case in React 16: https://jsfiddle.net/qrt54cb2/

I don't know what we fixed but it's good to know that we did 😛
