### ISSUE TITLE
componentConstructed() - Life cycle step

### ISSUE THREAD

**Issue by borela** [facebook/react#9169]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The life cycle of the component creation is:
* constructor()
* componentWillMount()
* render()
* componentDidMount()

**What is the expected behavior?**
A new method `componentConstructed` like so:
* constructor()
* componentConstructed()
* componentWillMount()
* render()
* componentDidMount()

In some cases, a high order component needs to prepare the child after its instance gets created, replacing the child's constructor is not trivial and using `componentWillMount` will work but it needs extra logic to prevent multiple initialization as it is called on updates too.

The name suggested for the method is not important and it was just an idea, but there might be better options.

**Comment by gaearon** [comment]
>In some cases, a high order component needs to prepare the child after its instance gets created

Can you describe this in more detail? It’s not very clear what practical scenario you are describing.

**Comment by borela** [comment]
Short answer: 
Generally this is useful when the outer component needs a reference to the child instance before it gets rendered and the change needs to happen only once either because it is too heavy or it makes no sense to do it over and over.

Long answer:
I have a [high order component](https://github.com/ctrine/react-ui/blob/master/src/rind/index.js) that adds support to callback chains, theming and even mouse/keyboard state tracking which is later passed to the template to [trigger animations using react motion](https://github.com/ctrine/react-ui/blob/master/src/checkbox/template.js). 

To make these additions not too heavy, the rind prepares some properties like [lists of handlers](https://github.com/ctrine/react-ui/blob/master/src/rind/index.js#L363), event proxies(used to raise the handlers' chain), etc...

**Comment by borela** [comment]
In the end I made a anonymous class extending from the child, it was a simpler solution.
