### ISSUE TITLE
setState can only update a mounted component warning

### ISSUE THREAD

**Issue by timurtu** [facebook/react#9171]
I'm getting the following warning in the console

<img width="1231" alt="screen shot 2017-03-13 at 8 16 36 pm" src="https://cloud.githubusercontent.com/assets/4442012/23880620/2e9f7b72-082b-11e7-834d-34fc6401b2ad.png">

Here's the Snippet component causing the warning. I'm setting state in `componentDidMount`.

<img width="598" alt="screen shot 2017-03-13 at 8 20 13 pm" src="https://cloud.githubusercontent.com/assets/4442012/23880646/4d7cd986-082b-11e7-826a-2da4c31c140a.png">

I tried making a jsfiddle but there's too many dependencies. The error logged will increment on resize but it doesn't always happen.

**Comment by milesj** [comment]
It's because `checkClearFix` is being called when a `resize` occurs and the component is not mounted in the DOM.

**Comment by timurtu** [comment]
Hmm I just thought of that and removed it on componentWillUnmount

```javascript
componentWillUnmount() {
    if (!this.props.splitTheGrid) {
      window.removeEventListener('resize', false)
    }
  }
```

but it's still happening

**Comment by aweary** [comment]
@timurtu  you have to pass the listener to `removeEventListener`, just like you do with `addEventListener`. You should just bind `checkClearFix` in the constructor and pass it directly to `addEventListener` instead of wrapping it in an arrow function that just calls it. Then you could pass `this.checkClearFix` to both `addEventListener` and `removeEventListener`

**Comment by timurtu** [comment]
Oh okay. Like this? It now says setState is not a function.

<img width="1280" alt="screen shot 2017-03-13 at 9 18 46 pm" src="https://cloud.githubusercontent.com/assets/4442012/23881726/bb0f7b46-0832-11e7-9d87-deb06a520906.png">

**Comment by timurtu** [comment]
I also tried binding it here and now it gives the error from before

<img width="1280" alt="screen shot 2017-03-13 at 9 37 20 pm" src="https://cloud.githubusercontent.com/assets/4442012/23882194/5ff60704-0835-11e7-9b62-7409fe35f855.png">

**Comment by milesj** [comment]
You would need to set the bind: `this.checkClearFix = this.checkClearFix.bind(this);`.

**Comment by timurtu** [comment]
that worked ty
