### ISSUE TITLE
PropTypes.oneOf relies upon stringification when using Symbols

### ISSUE THREAD

**Issue by ZebraFlesh** [facebook/react#9181]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`React.PropTypes.oneOf` prints a less than helpful error message when passed a Symbol which is not in the target value set: `Failed prop type: Cannot convert a symbol to a string`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

http://codepen.io/anon/pen/BWdEKb?editors=1011#0

**What is the expected behavior?**
`oneOf` prints the same or similar helpful error message that other primitive types get: 
```Failed prop type: Invalid prop `symbolSize` of value `Symbol(medium)` supplied to `Thing`, expected one of [Symbol(small),Symbol(large)].```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.4.2
macOS 10.12.3 / Safari 10.0.3 and Chrome 57.0.2987.98
Never worked

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.

**Comment by ljharb** [comment]
Fixed in https://github.com/facebook/prop-types/pull/224.
