### ISSUE TITLE
Finding whether an event is a true synthetic event for html element

### ISSUE THREAD

**Issue by prasanna1211** [facebook/react#9182]
**Do you want to request a *feature* or report a *bug*?**
Requesting a feature. As far as my knowledge (Sorry if I am wrong), currently I can't able to find whether an event is a valid synthetic event for a html DOM element. For example onChange is a valid event for <input type="text" />. It would be helpful if we have an API to check whether given method is a valid synthetic event for the html element.
**Use case:**
  Lets say I write a component which has <input /> as child, I would like to pass in synthetic event as props to the parent component. In the child component I would loop to see if a prop is a valid synthetic element and attach as props to the child element. If not don't attach to the HTML element.

In parent component 
`<Child onEnter = ... onClick = .... All synthetic events ... />`
 
In child component I will render this
`<input  {...validSyntheticEventsCallback}  name="name"  ... /> `                                                     

validSyntheticEventsCallback will include all the props that are valid synthetic events. This will help in making parent components more generic to write. Also all those logic can be included in the parent component itself.

**What is the current behavior?**
Currently we need to manually assign every event with the DOM.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

It is not related to browser / OS / version issue.

**Comment by syranide** [comment]
@prasanna1211 I'd say that if your intention is to create a wrapper component then your best course of action is to just extract and remove "your new magic properties" from the props-object and then pass the rest along to the DOM element. That's how I do it in https://github.com/syranide/react-swf

**Comment by prasanna1211** [comment]
@syranide I do agree which is basically the base of forming HOC which cuts out the synthetic events. But still we would still be comparing props and check if it is a valid event for that particular element. In that how will we know whether it is a valid event for that particular element. In other words onChange() is a valid event for <input type="text" />. Is there any API to check this ? Or we need to just populate the list of all valid events and check against it ?

**Comment by aweary** [comment]
There is no API currently for checking if a prop is a valid property for a DOM element. We do warn if we find an unknown property being rendered on a DOM element but that's about the extent of it, and it's likely to go away in the future.

I agree with @syranide, you should "extract" your custom props from `this.props` and pass the rest of them down to the element.

```jsx
const { onCustomEvent, ...rest } = this.props;
return <div {...rest}>Some Content</div>
```

**Comment by prasanna1211** [comment]
@aweary Thanks for your comment. I agree with that point. I did the same with what both of you had said. But I had warnings for now. Since it won't be in the future I think it would make sense to ignore the warning for now.

**Comment by syranide** [comment]
@prasanna1211 It shouldn't be emitting any warnings if you did it as @aweary showed.
