### ISSUE TITLE
Not working on IEMobile/9.0

### ISSUE THREAD

**Issue by svipben** [facebook/react#9183]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
React doesn't work on `IEMobile/9.0`, but in documentation it says 

> React supports all popular browsers, including Internet Explorer 9 and above.

but it  shows blank page...

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 15.4.2
Phone: Nokia Lumia 800 (IEMobile/9.0)

P.S. Instagram also doesn't works for my phone, it just shows blank page as I know Instagram also uses React.

**Comment by syranide** [comment]
`IEMobile/9.0` is not really IE9. Anyway, you probably need to provide some relevant errors/stack traces so that it can be determined whether this is a problem with React at all, it could just as likely be unsupported third-party libraries or your own code that breaks it.

**Comment by svipben** [comment]
@syranide Seems you're right, right now tested with `create-react-app` and it was fine. It's so hard to configure correctly babel and webpack, especially webpack, damn :D
