### ISSUE TITLE
[Feature Request] New PropType to check if a prop is a valid React Component (Can be fed to createElement)

### ISSUE THREAD

**Issue by Nimelrian** [facebook/react#9186]
There is no PropType to check whether a prop is a valid React Component (As in, the prop could be supplied as the first argument to `React.createElement`). 

This would be a nice feature for a composable component where the user could supply different components to a man-in-the-middle component which creates elements of the supplied component and feeds props to them. Example:

https://jsfiddle.net/tm26xsnf/

Edit: For clarification: `instanceOf(Component/PureComponent)` does not work.

**Comment by Ethan-Arrowood** [comment]
I agree this would be a nice addition. I'd love to try and solve this issue if you don't want to.

**Comment by Nimelrian** [comment]
I'm currently a little busy with other projects, so if you want to make this work, go ahead 👍

**Comment by brigand** [comment]
For anyone stumbling upon this issue, it can currently be implemented like this:

const hasPrototype = (f, p) => {
  for (let proto = Object.getPrototypeOf(f.prototype); proto; proto = Object.getPrototypeOf(proto)) {
    if (proto === p) return true;
  }
  return false;
};

```js
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.func,
]);
```

Or maybe this:

```js
PropTypes.oneOfType([
  PropTypes.string,
  (props, propName, componentName)  => {
    const f = props[propName];
    if (
      // stateless function component
      Object.getPrototypeOf(f) === Function
      // es6 class
      || f instanceof React.Component
      // es5 class
      || hasPrototype(f, React.Component.prototype)) {
      return;
    }
    return new Error(`Expected prop ${propName} of ${componentName} to be a React component`);
  }
]);
```

(Untested).

**Comment by gaearon** [comment]
Either a string or a function are valid. There is no way to tell if a function is a valid component until you call it though so this is as specific as it gets. For this reason I think we can close this.
