### ISSUE TITLE
[Fiber] Infinite loop caused by a rendering error

### ISSUE THREAD

**Issue by rthor** [facebook/react#9193]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a component returns something other than a valid React element, or `null`, it throws and does so infinitely. This is render-blocking and freezes the window.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
This happened to me when creating a Provider-type component that rendered its children directly. More specifically, when they were `undefined`. Eg

```js
class Provider extends React.Component {
  render() {
    return this.props.children // should throw once.
  }
}

// Elsewhere
<div>
  <Provider>this works correctly</Provider>

  // This freaks out
  <Provider />
</div>
```

<img width="1375" alt="screen shot 2017-03-16 at 15 29 54" src="https://cloud.githubusercontent.com/assets/1608329/24016088/b7dbcac2-0a82-11e7-9493-a9e5d3877e40.png">

Is there a [CodePen, Fiddle, etc] of `@next` somewhere, that I can use to demonstrate this?

**What is the expected behavior?**
It should throw, but only once and not freeze the browser.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.0.0-alpha.4
Yes, see http://codepen.io/rthor/pen/bqYBap?editors=0010#0

---
PS I know it's an alpha version 😄

**Comment by gaearon** [comment]
Random hypothesis: maybe this happens if an error is rethrown in a later tick (like React Redux does).

**Comment by rthor** [comment]
@gaearon It does reach that point, with `depth = 1` and `event.error = null`.

**Comment by jaredpalmer** [comment]
I am experiencing this too. Happens whenever **anything** is undefined.

**Comment by acdlite** [comment]
I believe I've identified the issue and have a fix.

@jaredpalmer Would you mind posting a jsfiddle with the exact code that triggers the bug for you? It's ok if the fiddle isn't running Fiber; I will paste it into my environment.

**Comment by rthor** [comment]
@acdlite It happens whenever anything throws.

**Comment by eugene1g** [comment]
@acdlite This is the only problem with Fiber in our app so far (but... a major one...)

I have a simple test case to crash the browser. With Chrome, you probably should open the "Task Manager" so you can kill the tab after testing :D 
<img width="672" alt="screen shot 2017-06-01 at 3 13 37 pm" src="https://cloud.githubusercontent.com/assets/147496/26696567/fdb5af4a-46dc-11e7-9eff-0af656640dbb.png">


Test case: https://codesandbox.io/s/Q1ygERY2Y

**Comment by acdlite** [comment]
@eugene1g Thanks for the test case. We're aware of the issue and will fix before 16 stable goes out :)

**Comment by acdlite** [comment]
Will be fixed by https://github.com/facebook/react/pull/10213
