### ISSUE TITLE
Old props and state in the render function

### ISSUE THREAD

**Issue by borela** [facebook/react#9198]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The render function returns what would be the result of the current state and properties only.

**What is the expected behavior?**
Having the old properties and state from the previous render as a parameter, for example:

```js
class extends Component {
  render(oldProps, oldState) {
  }
}
```

This would be useful to trigger animations with [react-motion](https://github.com/chenglou/react-motion). Currently I am doing something [similar for checkboxes](https://github.com/ctrine/react-ui/blob/master/src/checkbox/template.js), when the "checked" state changes, a ripple animation is started.

**Comment by brigand** [comment]
I feel like this is niche enough that you should implement it yourself. Example:

```js
const withPreviousParams = (inst) => {
  const componentWillUpdate = inst.componentWillUpdate;
  const render = inst.render;
  let prevProps = inst.props;
  let prevState = inst.state;
  inst.componentWillUpdate = (...args) => {
    prevProps = inst.props;
    let prevState = inst.state;
    if (componentWillUpdate) return componentWillUpdate.apply(inst, args);
  };
  inst.render = (...args) => {
    render.call(inst, prevProps, prevState, ..args);
  };
};
```

Usage:

```js
  constructor(props) {
    super(props);
    this.state = {};
    withPreviousParams(this);
  }
```

**Comment by gaearon** [comment]
I don't think we'll be doing this. It’s a relatively rare use case. Most people will also expect `render` arguments to be the current props and state, and this is guaranteed to generate confusion.

The canonical way to implement it is to keep track of them yourself, which is already possible with the current API, and maybe build a helper if you often need it.

**Comment by borela** [comment]
@brigand I am already implementing it in a decorator and using it in [here](https://github.com/ctrine/react-ui/blob/master/src/checkbox/template.js#L54), but I agree it is too niche specific.
