### ISSUE TITLE
How to use React Component Lifecycle in ES6 ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [facebook/react#9203]
```
//ES5
getInitialState: function() {
    return {liked: false};
  }
```
### /* is this equal ???*/

```
//ES6
constructor(props) {
  super(props);
  this.state= {
    liked:false
  }
}
```

## or

```
//ES6

getInitialState() {
    return {liked: false};
 }
```

**Comment by xgqfrms-GitHub** [comment]
https://github.com/Binaryify/react-demos#state
https://github.com/ruanyf/react-demos#demo08-thisstate

**Comment by techyrajeev** [comment]
In react's context they are equal but not otherwise. When using es6 class it is okay to intialize the state in constructor like 

```
constructor(props) {
  super(props);
  this.state= {
    liked:false
  }
}
```

**Comment by xgqfrms-GitHub** [comment]
How to rewrite this `pen` in ES6, can you do me  a favor?
http://codepen.io/xgqfrms/pen/ryYKKJ

**Comment by techyrajeev** [comment]
If you are using CRA ( Create React App ) you can also use  es2016 property initializer syntax and don't need the constructor at all.
e.g 

```
class App extends Component {
  state = {
    liked:false
  }
}
```

**Comment by techyrajeev** [comment]
Updated http://codepen.io/xgqfrms/pen/ryYKKJ Please check.

**Comment by xgqfrms-GitHub** [comment]
![react-es6-error](https://cloud.githubusercontent.com/assets/18028768/24040867/00fce178-0b46-11e7-9a62-7e24095ded42.png)

it does't work?

**Comment by techyrajeev** [comment]
Can you check now? There was incorrect import order of React-Dom and React.

**Comment by gaearon** [comment]
Closing. https://github.com/facebook/react/issues/9203#issuecomment-287319766 is correct answer.

**Comment by xgqfrms-GitHub** [comment]
Thanks a lot!
