### ISSUE TITLE
Need UI Automation help for React UI application

### ISSUE THREAD

**Issue by TarunVarian** [facebook/react#9205]
Hi Guys,

We are developing a UI application for our project using React and I read https://www.npmjs.com/package/react-style that CSS selectors are not supported. Earlier I was doing UI Automation using Coded UI C# + CSS Selectors. Can anyone please guide the right approach for Continuous Integration testing for UI application?

Thanks,
Tarun Babbar
Varian Medical Systems Pune.

**Comment by aweary** [comment]
Hey @TarunVarian!

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

You may find our [doc page on `ReactTestUtils`](https://facebook.github.io/react/docs/test-utils.html) helpful. [Enzyme](airbnb.io/enzyme/) is also a popular option for testing React applications. If you need more specific recommendations definitely checkout the support channels I mentioned.

Hope that helps!
