### ISSUE TITLE
Chrome: "Not optimized: optimized too many times" for _updateDOMProperties and unmountChildren

### ISSUE THREAD

**Issue by lencioni** [facebook/react#9208]
React 15.4.2, Chrome 56.0.2924.87 and 57.0.2987.110

I have been doing some profiling in Chrome of the render performance of some of our components and noticed a couple of deoptimizations in React.

![screen shot 2017-03-17 at 9 21 37 am](https://cloud.githubusercontent.com/assets/195534/24052580/3a5b71e4-0af3-11e7-8ac4-e92f734bd1b8.png)
![screen shot 2017-03-17 at 9 22 00 am](https://cloud.githubusercontent.com/assets/195534/24052581/3a65d666-0af3-11e7-916e-e8872b8cfdbd.png)

The message Chrome reports is "Not optimized: optimized too many times", which apparently happens when V8 optimizes a function but when running it found a reason to deopt it, and this happened more than `max_opt_count` setting (currently set to 10). More information: https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-145192013

Clicking through the profile, it looks like most of the time is perhaps spent on this line, but I'm not sure if that is a clue as to what the deopt might be in this case.

```js
nextProp = this._previousStyleCopy = _assign({}, nextProp);
```

![screen shot 2017-03-17 at 9 26 57 am](https://cloud.githubusercontent.com/assets/195534/24052784/f77c5072-0af3-11e7-9d11-b5fffa0d2e60.png)

It might be worth spending some time digging into this, but I'm not sure if it will still be relevant after React 16.

**Comment by gaearon** [comment]
I don't think this line exists in [React Fiber implementation](https://github.com/facebook/react/blob/ad2b6545fee4c24ea2d7fa162fee012909920192/src/renderers/dom/fiber/ReactDOMFiberComponent.js).

Please feel free to experiment with `react@next` and `react-dom@next` and file any issues about them though!

**Comment by aweary** [comment]
For reference, that line was removed in https://github.com/facebook/react/commit/447e0a12b55f4570f62872e6ce50439704416ee, but time spent is not a direct indicator of why a function might deopt, so a profile of `react-dom@next` would be a great idea!

**Comment by thysultan** [comment]
Just came across this deopt as well, it's deopting because a named argument `nextProps` is being reassigned.

```js
function (lastProps, nextProps, transation) {
    ...
    nextProp = this._previousStyleCopy = _assign({}, nextProp);
```

**Comment by gaearon** [comment]
I think you might be confusing `nextProps` and `nextProp`. Also AFAIK it was deopting because `lastProps` is sometimes `null` but we're using a `for in` loop. In either case, I don't think fixing that gave any meaningful effect in my testing a while ago, and Fiber code is structured a bit differently. You're welcome to check it for deopts though (we have alphas published).
