### ISSUE TITLE
Very bad debugging for spread errors

### ISSUE THREAD

**Issue by cdubois-mh** [facebook/react#9211]
*bug*

When the spread operator is miss-used, the compiler goes crazy and doesn't give the developper any hint on why something went wrong. 

Inside a react es6 class, I was trying to render an array of jsx elements as follow:

```
class Modal extends Component {
[...]
    render() {
        let actions = [];
        for( let [ label, action ] in this.props.actions ) {
            actions.push(
                <input
                    key={ label }
                    type="button"
                    value={ label }
                    onClick={ this.onActionClicked( action ) }
                />
            );
        }

        return (
[...]
            <div className="alert-actions">
                { ...actions }
            </div>
        );
    }
}
```

I already know that I should've written `{ actions }` and not `{ ...actions }`.

I got an incredible load of errors that filled my terminal from babel compiler, the first error message being
> did not recognize object of type "JSXSpreadChild"
> at Object.getFieldNames

I would expect some error message telling me that I miss-used the spread operator.

I'm using React 15.2.0 ( npm ) and babel-runtime 6.23.0
in meteor.

**Comment by gaearon** [comment]
Please file an issue against Babel (which parses JSX). This is not actionable in React repository since we don't maintain a JSX compiler. Thanks!
