### ISSUE TITLE
Inconsistent behavior with keyed select options and value

### ISSUE THREAD

**Issue by ajainarayanan** [facebook/react#9212]
**Current behavior**:
  I have a component that is composed of multiple select elements each tied to different variables in the state. I have a setTimeout that changes only one of the select value. This causes other select values to be changed

**Steps to reproduce**:
  https://www.webpackbin.com/bins/-KfSVw3Ww4ZGFSaJ5_WY

The above webpack bin instance works as expected in chrome and safari but not in firefox.

**Issue**:
  In Firefox the value of select elements (the ones not set inside a `setTimeout`) reverts back to the first value instead of the previously set one.

**React version**: 15.4.2
**OS**: Mac
**Browser affected by this change**: Firefox 

Please feel free to close the issue if this is not a bug (or a known bug in firefox) and that I am doing something wrong. I tried searching for issues related to firefox and select elements and couldn't find any that looked similar.

**Comment by aweary** [comment]
Thanks for the issue @ajainarayanan! I looked at your example and was able to pinpoint where things are going wrong. The problem stems from the fact that you're using `shortid.generate` for the `key` of the `option

```jsx
<option  key={shortid.generate()} value={o}>
```

The problem with that is that `shortid.generate()` will just return a random number every time you render, so React will see that the key changed (event though the element really hasn't changed at all) and it will assume that it needs to recreate the `option` element. 

To resolve this, use a key that has semantic meaning, like the `option`'s `value`

```jsx
<option key={o} value={o} >
```

That way React knows that it only needs to consider re-creating the `option` element if its value has changed at all. Here's a working version of your example: https://www.webpackbin.com/bins/-KfSdIKRBDh-pmZoDIW0

It does seem concerning that this behavior is inconsistent between browsers, so I'll keep this open while we investigate if we can normalize that. Hope that helps!

**Comment by ajainarayanan** [comment]
@aweary Thanks for the quick response! That resolves it.

**Comment by aweary** [comment]
@ajainarayanan glad to hear it! The [doc page on Lists and Keys](https://facebook.github.io/react/docs/lists-and-keys.html) is a great reference for this.

**Comment by gaearon** [comment]
Unfortunately webpackbin appears down so I can't reproduce this. Regardless, it seems like a niche bug. If more people report it we can take a look.
