### ISSUE TITLE
[Feature request] PropTypes.element()

### ISSUE THREAD

**Issue by Sharlaan** [facebook/react#9213]
Currently, checking for required prop(s) within passed children need to be implemented with the props validator function, or with less than ideal `PropTypes.shape({ prop: PropTypes.XXX.isRequired })`

I would suggest the following :
```js
PropTypes.element(   
    prop1: PropTypes.AnyValidType,   
    prop2: PropTypes.AnyValidType.isRequired   
)
```

Another idea in same vein would be to extend current PropTypes.instanceOf() :
```js
PropTypes.instanceOf(
    MyCustomClass,
    [
        prop1: PropTypes.AnyValidType,   
        prop2: PropTypes.AnyValidType.isRequired  
    ]
)
```

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.
