### ISSUE TITLE
[Documentation][Add-Ons] Incorrect Prev Next links

### ISSUE THREAD

**Issue by romamatusevich** [facebook/react#9216]
Articles in Add-Ons have incorrect Prev Next links. For example the first `Performance Tools` has Prev link to the `Keyed Fragments` which is actually the fourth. `Immutability Helpers` does not have Prev Next links at all. I think the easiest way is just to remove the Prev Next links from Add-Ons articles. It will allow to add/update/remove articles without need to update Prev/Next links. What do you think?

**Comment by gaearon** [comment]
Would you like to send a PR fixing them?

**Comment by romamatusevich** [comment]
Sure, I will create pull request.

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/9226.
