### ISSUE TITLE
[Feature] granular forceUpdate 

### ISSUE THREAD

**Issue by thysultan** [facebook/react#9218]
When `forceUpdate` is called on a long list at the very least the whole list must be traversed. For example with the following list `arr = [1, 2, 3, 4, 5, 6]` and if we where to push 7 `arr.push(7)` the reconciler will go through elements 1 - 6 and then add a 7 at the end of that list. The suggestion to add support for the following forceUpdate signature.

```js
forceUpdate(a: {function|number}, b: number?)
```
Where when passed as an integer `a` is the start index and `b` the number of items to traverse similar to how `str.substr()` works.

When the function encounters a number as the `a` argument it changes the start index of where to start when reconciling the components children and when the `b` argument is set it changes the end index of where to end the traversal of the components children. So with the above mentioned example if i wanted to optimize the reconciliation process for append updates i could do the following.

```js
this.forceUpdate(arr.length);
```
and to target an update in the middle of the list of up to 3 items.

```js
this.forceUpdate(arr.length/2, 3);
```

This will allow for very precise O(1) updates when you know ahead of time how the data will change. 

Possible `setState` counter-part.

```js
setState(a: {function|Object}, b: (function|number)?, c: {number})

// usage
setState({arr: [...]}, this.state.arr.length);
```

**Comment by gaearon** [comment]
Why not call it on the child?

**Comment by thysultan** [comment]
When `[1, 2, 3]` changes -> `[1, 2, 3, 4]` 4 does not exist. The examples above are small. The use case is when the array of children is large. The idea is to allow an opt-in optimization of append/prepend/insert or pinpoint(startIndex -> endIndex) operation to be O(1) with large lists instead of O(n).

**Comment by gaearon** [comment]
Ah, I see.
Generally we solve this with two techniques:

* `shouldComponentUpdate()` (or `PureComponent`) on children. This short-circuits rendering if child has not changed, so it’s still O(n) but most items bail out super quickly.
* Windowing. If you have many items, rendering all of them is bad anyway. On the web, you can use [react-virtualized](https://github.com/bvaughn/react-virtualized). On native, you can use [new list views with recycling](http://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html).

Does this help?

**Comment by thysultan** [comment]
This is meant to avoid a O(n) internal operation altogether. For example if i wanted to lazy load components(an infinite scroll), as the list grows so will the subsequent operations to append to the list since it's O(n), by allowing a way to pin point a specific granular update(in this case the end of the list) the operation is reduced to O(1), `forceUpdate(arr.length)`.

Now say someone wanted to just prepend one item to the top of the list that was lazy loaded. This could then be done with a O(1) operation as `forceUpdate(0,1)` of which is known ahead of time that the update should not go past the first item of the list, at which point the list could have grown to multiple of its initial size.

**Comment by aweary** [comment]
While it may be an O(n) operation, using `shouldComponentUpdate` / `PureComponent` should reduce the total work required significantly, making the performance difference for a reasonable number of items negligible.

If you are rendering enough items that you are having performance issues, windowing is the way to go. Virtualizing the list will give you better beyond just append runtime, since it's only rendering the required number of items.

There's also the abstract cost of expanding the public API. Changing the signature of `setState` and `forceUpdate` should be done carefully and for very good reasons. I'm not sure this would be enough justification since the performance improvements aren't likely that substantial and windowing is a better, more familiar approach for large lists.

**Comment by thysultan** [comment]
@aweary I meant it as way to expose a lower level interface for isolated updates that high-level constructs like windowing can use to reduce the operational complexity of an update.

**Comment by thysultan** [comment]
> This API would also make it possible for users to introduce inconsistent render state, as it would defer the reconciliation path to the user who may get it wrong.

The target use is when you know what child(ren) need to be updated it's like a much lower level version of `shouldComponentUpdate`, sure you can shoot yourself in the foot with both of them but it's an explicit opt-in.

**Comment by gaearon** [comment]
>I meant it as a way to expose a lower level interface for isolated updates that high-level constructs like windowing can use to reduce the operational complexity of an update.

We will likely do this in some form, but it is unlikely we’ll do this at `forceUpdate` level. Maybe @bvaughn can provide additional insight on this.

**Comment by bvaughn** [comment]
Thanks for the ping, Dan.

> This API would also make it possible for users to introduce inconsistent render state, as it would defer the reconciliation path to the user who may get it wrong.

:+1: for this concern. For example, above you mentioned...

> This is meant to avoid a O(n) internal operation altogether. For example if i wanted to lazy load components(an infinite scroll), as the list grows so will the subsequent operations to append to the list since it's O(n), by allowing a way to pin point a specific granular update(in this case the end of the list) the operation is reduced to O(1), forceUpdate(arr.length).
> Now say someone wanted to just prepend one item to the top of the list that was lazy loaded. This could then be done with a O(1) operation as forceUpdate(0,1) of which is known ahead of time that the update should not go past the first item of the list, at which point the list could have grown to multiple of its initial size.

The expected behavior in this case is unclear to me. If you called `forceUpdate(0,1)`, how would React know that you _appended_ a child vs _replacing_ the previous first child?

> We will likely do this in some form, but it is unlikely we’ll do this at `forceUpdate` level. Maybe @bvaughn can provide additional insight on this.

I think it's too early for me to speculate on what approach we'll take. Sebastian and I have chatted a bit at a high level about things like DOM-element recycling, restoring transient state for list items the were unmounted and remounted, etc. But I haven't thought much about what API changes might be made on React side. I think we'll have some kind of virtualization component that abstracts away this concern from userland.

**Comment by thysultan** [comment]
> If you called forceUpdate(0,1), how would React know that you appended a child vs replacing the previous first child?

@bvaughn Insert cases will probably need more fine tuning but the way i see it is that given a list, old `[2, 3, 4, 5]` -> new `[0, 1, 2, A, 4, 5]`

```js
forceUpdate(-1)    // prepends `0`, short circuits.
forceUpdate(-2)   // prepends `0` and `1`, short circuits.

forceUpdate(0,1)  // diff's `[2] -> [0]` replaces  `2` with `0`, short circuits.
```
Append/Update updates work just like `string.substr(start, length)`

with `[2, 3, 4, 5]` -> `[2, 3, 4, 5, 6, 7]`

```js
forceUpdate(4)     // appends `6` and `7`  short circuits
forceUpdate(4, 1) // appends only `6` short circuits
```

with `[2, 3, 4, 5]` -> `[2, 3, A, 5]`

```js
forceUpdate(2, 1) // replaces `4` with `A` short circuits.
```
It's low level so you'd have to know what you're doing to avoid shooting yourself in the foot but if you do it right you could reduce the cost of updates to `O(1)`

**Comment by gaearon** [comment]
It's not clear to me why this is a good solution to the problem, and which other solutions you compared it to.

If other elements haven't changed, and you're trying to short circuit their rendering, you can force skipping over them by maintaining a cache of elements. React will bail out of reconciling constant elements.

On the other hand, if you really want to `forceUpdate` a particular child, you might as well wrap them into your own class components, get refs to them, and then `forceUpdate()` a particular one by index. So React already lets you do that in a way.

I hope this helps!

**Comment by thysultan** [comment]
>If other elements haven't changed, and you're trying to short circuit their rendering, you can force skipping over them by maintaining a cache of elements. React will bail out of reconciling constant elements.

How does this handle constant hoisted elements that have nested components as children that might return different snapshots? If you bail at the point of the hoisted element wouldn't this un-internationally also short circuit the child components that could update what they render or is this heuristic intentional in that regard?

**Comment by gaearon** [comment]
Yes, this is intentional. It won't work if something in the child tree depends on prop mutation above "descending down" to it without an actual new element being created.
