### ISSUE TITLE
Document how React treats different attributes

### ISSUE THREAD

**Issue by MMeent** [facebook/react#9220]
As of #9106 there are quite a lot of tests for HTML's boolean properties on tags. According to these tests HTML properties should get rendered into empty strings or not set, e.g. `<div hidden={true} />` should render to `<div hidden="" />` and `<div hidden={false} />` should render to `<div />`. 

But when I look further, there are other tests which do similar things: `<a href={true} />` should render to `<a href="true" />`. This means that if I take `true` as my property value, I will not know what the result will be. 

The issue being: React currently does not have a clearly-defined and documented way with which they handle their props. Could the docs be updated to specify which type of prop will result in what? e.g. "any number gets parsed to a string (using Number.toString()), an object gets stringified by using `arg => Object.entries(arg).map(([key, val]) => `${key}: ${val};`).join()`, and booleans toggle the property."

In short, these are the bugs/undocumented features/contradictions that the tests expect to happen, plus my expectations:

- `prop={true}` gets parsed to [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L222) or [`prop="true"`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L209) for select properties  
    expected: either `prop=""` or `prop="prop"`, not both // as per checked=checked HTML standard
- `prop=""` gets parsed as [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L303) or [` `](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L239)  
    expected: `prop=""`
- `prop="prop"` might get parsed as either [`prop="prop"`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L286), [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L231) or even [` `](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L376)  
    expected: `prop="prop"`
- `prop="foo"` => [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L245) or [`prop="foo"`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L286)  
    expected: `prop="foo"`
- `prop={false}` => [` `](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L282) or [`prop="false"`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L316)  
    expected: ` `
- `prop={['foo', 'bar']}` => [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L252) or `prop="foo,bar"` (hand-tested, no automatic test available)  
    expected: `prop="foo bar"`
- `prop={{foo: 'bar', baz: 5}}` => [`prop=""`](https://github.com/facebook/react/blob/78761c387f7ab24b0dbbb63e9085b26b808e5330/src/renderers/dom/shared/__tests__/ReactDOMServerIntegration-test.js#L257) or [`prop="foo: bar; baz: 5;"`](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/__tests__/ReactDOMComponent-test.js#L1180) or `prop="[object Object]"` (hand-tested, no automatic test available)  
    expected: `prop="foo: bar; baz: 5"` // as per style object transform

Hacky showcase: https://jsfiddle.net/ox8a7vfe/3/

Are these features or are these bugs?

If they are bugs, and work is going to be done on the props value parsing, then the following might be a nice addition:

- `prop={{foo: true, bar: true, baz: false}}` => `prop="foo bar"` // render all `true` keys, disregard `false` keys, like classNames.

**Comment by syranide** [comment]
Boolean HTML properties are treated separately from regular string properties. I.e. `'' + (true) === 'true'` so that's why boolean true ends up being `"true"` in the DOM for string properties, but HTMLDOM dictates that boolean properties should look a certain way and cannot have *any* value. React has an internal property config reflecting this, but if you use JS `node.property = x` then you will see the same behavior. So this is simply how HTMLDOM works. This is really a quirk of HTMLDOM, but having it further explained would certainly be a good thing as it can be hard to know where to draw the line between HTML and React, but IMHO this is a case of HTML being HTML and React just doing what needs to be done.

**Comment by MMeent** [comment]
> a case of HTML being HTML and React just doing what needs to be done.

React does both more than what needs to be done and the bare minimum, for different props, resulting in inconsistent behaviour. It also filters and drops custom attributes (like `<div customAttr="" />`, which is part of HTML spec) which makes it even more difficult to predict the behaviour of React in combination of css styling, etc. If React specified "propType [Aalways renders this way", it'd save quite a bit of debugging.

**Comment by syranide** [comment]
> React does both more than what needs to be done and the bare minimum, for different props, resulting in inconsistent behaviour.

@MMeent `node.hidden = 'foobar'; node.hidden === true`, that's how it works in the browser.

> If React specified "propType [Aalways renders this way", it'd save quite a bit of debugging.

This page lists all the special-case properties (https://facebook.github.io/react/docs/dom-elements.html). Other than that React is not doing anything funny that you shouldn't expect. If you provide valid DOM-values then React will work exactly as you would expect. If you provide a non-boolean value to a boolean prop both React and HTMLDOM will turn it into a boolean for you.

**Comment by MMeent** [comment]
> If you provide a non-boolean value to a boolean prop both React and HTMLDOM will turn it into a boolean for you.

if I `.setAttribute()` my props into the dom node, then `.getAttribute`, it returns the corresponding value (either string, null or function). As I'm writing jsx, which is basically html with curly braces for js-extensions*, I want my values to be interpreted as consistently, meaning `selected=""` results in `getAttribute('selected')===""`. That `element.property` is read differently is something else entirely, and not React's but the programmers' problem.

\* I know it's not exactly that, but for neigh all intents and purposes it is.

**Comment by aweary** [comment]
You shouldn't consider the actual attribute as the source of truth for element properties. In React it's consistent with the HTMLDOM standards for DOM properties. The property names reflect those of the JavaScript API for accessing DOM properties (`className` instead of `class`, `htmlFor` instead of `for`, etc.), so you can conceptualize it as an interface to that API instead.

There are [a number of internal property config options](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/DOMProperty.js#L25-L29) that determine how React sets properties/attributes so that it remains consistent with HTMLDOM.

**Comment by MMeent** [comment]
OK. That should then be documented, as the implementation notes say React uses `.setAttribute` in the code, and doesn't mention props in any other way. 

Also note that most, if not all, other vdom-libraries use get/setAttribute for their property/attribute diffing: [Preact](https://github.com/developit/preact/blob/b3845c17a00997f73c8e4530074dbb4efdf522e8/src/dom/index.js#L71), [Vue.js](https://github.com/vuejs/vue/blob/68abdc3c3c86e01089c32b434e662dc15a3a9eda/src/platforms/web/runtime/modules/attrs.js#L30) and [inferno](https://github.com/infernojs/inferno/blob/927f437b4c1c4903ea2cfd005317527defb8916b/packages/inferno/src/DOM/patching.ts#L816) to name a few, which might indicate a preference for html-like behaviour over DOMElement-like behaviour.

**Comment by aweary** [comment]
I totally agree that this should be clearer in the docs, and PRs are welcome!

>  the implementation notes say React uses .setAttribute in the code, and doesn't mention props in any other way.

We do use `setAttribute`, but not without qualification. There are cases where we also set the property on the node, or normalize boolean values.

> Also note that most, if not all, other vdom-libraries use get/setAttribute for their property/attribute diffing: Preact, Vue.js and inferno to name a few, which might indicate a preference for html-like behaviour over DOMElement-like behaviour.

[Here's](https://jsfiddle.net/vnva0jzq/) an example showing Inferno rendering `<div hidden="hidden"></div>` as `<div hidden></div>` and [here's](https://jsfiddle.net/69cc69r1/) one showing Preact doing the same. Conforming to the HTMLDOM spec is rather important for library that manages the DOM, so I think it's pretty consistent behavior.

**Comment by nhunzaker** [comment]
@arindampradhan Sorry for the delay. Please do :)

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#80

Let's continue the discussion there! Sorry for the inconvenience.
