### ISSUE TITLE
Create a new JSFiddle for issue template

### ISSUE THREAD

**Issue by aweary** [facebook/react#9224]
Right now the current JSFiddle (https://jsfiddle.net/reactjs/69z2wepo/) can be a pain to use. It doesn't have any syntax highlighting and defaults to using `React.createClass` which in almost every case is not what people are going to be reproducing issues with.

**Comment by gaearon** [comment]
I'm thinking maybe we should suggest CodePen instead?

**Comment by viankakrisna** [comment]
how about https://www.webpackbin.com/?

**Comment by aweary** [comment]
@gaearon here's a CodePen we could use: https://codepen.io/anon/pen/jBxEOw 

One thing I don't like about CodePen is that it prompts to create an account every time you fork a pen. It's totally understandable advertising, but it might annoy some people.

> how about https://www.webpackbin.com/?

I like WebpackBin! It probably has my favorite UI among our options. We want to be sure we use something most people will be familiar with, how popular is WebpackBin? 

We also need to verify that whatever we choose works in all supported browsers (IE9+). I've tried testing JSFiddles in IE9 and it doesn't work which makes debugging IE9 issues a big pain.

**Comment by viankakrisna** [comment]
Not sure how popular it is, maybe @christianalfoni can chime in :)

**Comment by christianalfoni** [comment]
Hi guys :)

When Wepbackbin 2 was launched 120.000 bins was created with previous version... over a period of about 6-7 months. When opening the main menu on the left of webpackbin.com now you see stats of created and viewed bins.

Webpackbin 2 is about a week old now. It is not nearly as popular as the others of course, but yeah... marketing and stuff is not my thing ;-)

I have not focused on supporting IE9 cause it makes me so angry... need Webpackbin to be a fun project, but happy to receive PRs on it. Probably just needs some polyfills and style fixes.

**Comment by jacobjuul** [comment]
Regarding the syntax highlighting, a simple solution would be to change from the `Javascript 1.7` setting to the `Babel` setting

**Comment by aweary** [comment]
I think JSfiddle is the safest solution at the moment. Codepen feels like the better product, but it does prompt you to setup an account everytime you go to fork the pen and for this specific situation that doesn't make a lot of sense.

I've got an updated JSFiddel using the `Babel` language that works well: https://jsfiddle.net/84v837e9/
