### ISSUE TITLE
React app triggers apphangb1 in IE 10 and 11

### ISSUE THREAD

**Issue by Bashif** [facebook/react#9228]
Hi,

The react based product we developed works fine with other browsers. But when it comes to IE most of the times the Apphangb1 error occurs with not responsive page. The page is already loaded but whole page (buttons, text field, etc) is hung.

The error occurs more frequently for https connections. For http and direct connections (when connected to local host machine using ip) the error frequency is very low. There is no any error output in the console at this time. However since the browser's dev tool also hangs there is no way to dig deep into the problem.

Is there any possibility that this kind of a condition can occur due to the way react is implemented? If so is there any workaround to overcome it?

**Comment by syranide** [comment]
Yeah React will "hang" if you make certain errors or throw in the wrong locations at the moment. But it will always emit an error, you're almost certainly swallowing errors somewhere, enable "pause on exceptions" and you should be able to find your way to it.

**Comment by aweary** [comment]
Unfortunately, we can't help much without a clear reproduction of the issue, and as mentioned it's likely an issue with your application code and not React.

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

If you can provide a reproduction that demonstrates an issue in React, let us know!

**Comment by Bashif** [comment]
Thank you very much for the quick response and for support forum links.

We used Google Tag Manager in our application. The error occurs when downloading http://www.googleadservices.com/pagead/conversion.js which is sometimes used by GTM. Anyway still trying to find out why the app crashes in IE for that process. 

Thanks again!
