### ISSUE TITLE
react-dom v15.4.2  fails to load for latest nodejs v7.7.3 (missing dependencies from clean install on travis-ci)

### ISSUE THREAD

**Issue by kaizhu256** [facebook/react#9229]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
react-dom@15.4.2 cannot successfully be required by node v7.73

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

reproduction here @ this travis-ci build
https://travis-ci.org/npmdoc/node-npmdoc-react-dom/builds/213432945#L330
```
testCase testCase_buildApidoc_default failed
Cannot find module 'react/lib/ReactComponentTreeHook'
Error: Cannot find module 'react/lib/ReactComponentTreeHook'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/npmdoc/node-npmdoc-react-dom/node_modules/react-dom/lib/ReactDebugTool.js:16:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[node test-case 1 of 1 failed] - testCase_buildApidoc_default
```

**What is the expected behavior?**
react-dom@15.4.2 should successfully be required by node v7.73

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
don't know only install latest version of react on latest version of nodejs on travis-ci

**Comment by gaearon** [comment]
It looks like you didn't install `react` package. Please make sure you installed both `react` and `react-dom`, and their versions match.

**Comment by kaizhu256** [comment]
thx, it works now.  fyi was using it to auto-generate api-docs for react-dom at https://www.npmjs.com/package/npmdoc-react-dom

![image](https://cloud.githubusercontent.com/assets/280571/24185651/47b1f758-0f0f-11e7-863f-42ae22e38eb7.png)
