### ISSUE TITLE
Odd behavior after i installed React through Bower. 

### ISSUE THREAD

**Issue by AKippins** [facebook/react#9237]
Reporting what seems to be a bug. I installed React into my project using Bower inside of Sails.js which sits on top of Node.js. More so wanted to bring this to your attention than it effecting me. I hadn't tried to use React in anyway yet. 

<img width="1440" alt="screen shot 2017-03-22 at 2 56 46 pm" src="https://cloud.githubusercontent.com/assets/2333708/24215898/a82e8a28-0f10-11e7-8993-b736fa69cc3c.png">

I'm using the most current version of React and Safari. 

<img width="262" alt="screen shot 2017-03-22 at 3 14 29 pm" src="https://cloud.githubusercontent.com/assets/2333708/24216364/4d31410e-0f12-11e7-8b6a-1953ef513221.png">

These are the other things that i'm using in conjunction. 

Mostly just an FYI for you.

**Comment by gaearon** [comment]
You didn't include `react.min.js` on the page. `react-dom.min.js` doesn’t work without it. Try with both of them (`react.min.js` should go first).

Note that `.min.js` should be used in production, and just `.js` files should be used in development.

Hope this helps!
