### ISSUE TITLE
Warn in dev if shouldComponentUpdate is defined on PureComponent

### ISSUE THREAD

**Issue by aweary** [facebook/react#9239]
Currently, if you define `shouldComponentUpdate` on `React.PureComponent` nothing bad happens and it acts like `React.Component` https://jsfiddle.net/jekmdfva/

We should probably warn in dev since it defaults the point of `PureComponent`

**Comment by gaearon** [comment]
Unrelated, but I also wanted to suggest warning for setting `defaultProps` and `propTypes` on instances (I've seen people do this with class properties syntax). Maybe somebody could do all three warnings together?

**Comment by aweary** [comment]
That's a great idea, happy to help anyone who wants to give this a shot

**Comment by misoguy** [comment]
I'd like to give this a shot :)

**Comment by misoguy** [comment]
What kind of warning message should it be? I'm trying to write a test first :)

**Comment by misoguy** [comment]
After writing a simple test code, I realized that there is a test code to ensure ```shouldComponentUpdate``` can be overridden.
What is the expected behavior when it is overridden?

**Comment by aweary** [comment]
@misoguy I responded to your question [in your PR](https://github.com/facebook/react/pull/9240#issuecomment-288746281)!

**Comment by abhaynikam** [comment]
@aweary : Issue is open since 23 days. Would like to contribute for same.

**Comment by abhaynikam** [comment]
```
Unrelated, but I also wanted to suggest warning for setting defaultProps and propTypes on instances (I've seen people do this with class properties syntax). Maybe somebody could do all three warnings together?
```
@gaearon : can you help me understand what is expected behavior here?
