### ISSUE TITLE
Unable to render images on android device

### ISSUE THREAD

**Issue by zeegeek** [facebook/react#9243]
We are using react with cordova to build a hybrid mobile application. All the images are rendering on inspect browser but not on the actual device.

We have tried the following approach to render image -

1.
import redcar from './RedCar.png'
`<image src={redcar} />`
2.
var redcar = require('./RedCar.png')
`<image src={redcar} />`
3.
`<img src="./RedCar.png" />
`4.
Copied image into android\assets folder and tried
`<image src='/android_asset/www/RedCar.png' responsive />`
5.
index.html
`<meta http-equiv="Content-Security-Policy" content="default-src *; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'; media-src *; img-src * filesystem: data:">`

6. Only way it's rendering the image son device is by giving a background image to <div> in css file.
But we need to read the image paths from JSON so we can't use this approach.
background-image: url("./RedCar.png");

7. 
Also I tried changing the webpack output->publicpath to "\" or "assets" and making use of url-loader / file-loader but couldn't get it right .

The images are supposed to render on device.

React version - 15.3.1

**Comment by viankakrisna** [comment]
is it 404ing? I think this is mostly issue with webpack config / cordova. If you can share a reproducible repo maybe i can help

**Comment by aweary** [comment]
Hey @zeegeek, sorry to hear you're having trouble. From what you've said I would agree with @viankakrisna, it's likely an issue with your build tooling.

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow. You may also want to reach out to any support channels Cordova offers.

If you can provide a test case reproducing the issue, demonstrating it's a React issue we can definitely look into it for you.

Hope that helps!
