### ISSUE TITLE
A flat badge for facebook

### ISSUE THREAD

**Issue by aleen42** [facebook/react#9250]
Here is [a repository](https://github.com/aleen42/badges) for making badges more acceptable in documenting, and I hope that the flat badge can be used in such an awesome project. 

[![facebook](https://rawgit.com/aleen42/badges/master/src/facebook.svg)](https://rawgit.com/aleen42/badges/master/src/facebook.svg)

**Comment by gaearon** [comment]
Hey, thanks for the suggestion. I don’t think we’ll be adding more badges as we have quite a few already 😉

**Comment by aleen42** [comment]
@gaearon You're welcome.
