### ISSUE TITLE
Stop masking context

### ISSUE THREAD

**Issue by gingur** [facebook/react#9266]
*Feature*

Return all contextProps available via a wildcard prop, this would be helpful for those who want to do `shouldComponentUpdate` comparisons with props, state, **and** context.

Possible solutions
```
static contextTypes = true;
// or
static contextTypes = /.*/;
// or
static contextTypes = {
  __all: true
}
```

**Comment by brigand** [comment]
This could also be used in the case where you ReactDOM.render inside a component and want to preserve things like the redux store and react-router.

**Comment by gingur** [comment]
That's a great point @brigand! Passing, cloning, or even serializing the context data could benefit from this feature.

**Comment by gaearon** [comment]
We'll be changing how context works, and I don't think properly exposing it in `shouldComponentUpdate` in the current form is a goal.

That said we'll probably get rid of masking so I'll hijack this issue to track it.

**Comment by gingur** [comment]
I don't know what that means, but as long as I can prevent wasted renders based on props, state *and* context I'm a happy camper.  If this is something that can automatically be handled by `PureComponent` even better :)

**Comment by gaearon** [comment]
The proposed context API solves this (https://github.com/reactjs/rfcs/pull/2) and we don't plan changes to the existing one so I think this is not relevant anymore.
