### ISSUE TITLE
can't I use 'this' in async function?

### ISSUE THREAD

**Issue by GravityMsc** [facebook/react#9286]
```
export default class Mytest extends React.Component {
    ...
    test = () => {
        console.log('test');
    }
    fetch = async () => {
        const response = await fetch(url).catch((err) => {
            console.log('Fetch failed!', err);
        });
        this.test();
    }
    render() {
        ...
    }
}
```
It shows  
> Uncaught (in promise) ReferenceError: _this5 is not defined

So,what should I do? avoid using async?

**Comment by OlegLustenko** [comment]
what about to use a non-arrow function?

**Comment by pietrasiak** [comment]
Can you try something like:

```
export default class Mytest extends React.Component {
    test() {
        console.log('test');
    }
    async fetch() {
        const response = await fetch(url).catch((err) => {
            console.log('Fetch failed!', err);
        });
        this.test();
    }
    render() {
        return (<div />);
    }
}
```

Arrow functions main + is that they're not changing context of `this` - at the same time this means you're not able to use `this` context in arrow function when you're not in some context already.

**Comment by gaearon** [comment]
>Uncaught (in promise) ReferenceError: _this5 is not defined

This sounds like a Babel bug. Please report it to Babel.
Unfortunately there is nothing we can do in this repo to help so closing.

**Comment by GravityMsc** [comment]
@pietrasiak @OlegLustenko  Thank you at all.,I'll try it some time and now I don't use async and await. This is just a try.

**Comment by Ai01** [comment]
@GravityMsc does babel fix this problem?

**Comment by adeelibr** [comment]
Any updates?
