### ISSUE TITLE
Maybe could use more accurate description of componentWillMount

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9304]
[Current doc about componentWillMount](https://facebook.github.io/react/docs/react-component.html#componentwillmount) says that:

> It is called before render(), therefore setting state in this method **will not trigger a re-rendering**.

I thinks it would be better if we say:

> It is called before render(), therefore setting state directly in this method **will not trigger a re-rendering** because we batch it.(but setting state indirectly/asynchronous will trigger a re-rendering,such as `setTimeout(() => {this.setState(...)})`).

**Comment by nehero** [comment]
Assuming the asynchronous action finishes by the time component mounts, sure.

But if you're needing to set the state, why not instead direct people to do these actions when the component mounts with `componentDidMount`?

**Comment by NE-SmallTown** [comment]
> Assuming the asynchronous action finishes by the time component mounts, sure.

Yea,we can add this tip.

> But if you're needing to set the state, why not instead direct people to do these actions when the component mounts with componentDidMount?

Except SSR,Yes.I just mean that we can make the doc with more accurate description

**Comment by probablyup** [comment]
"Synchronous code will be run before the first render occurs" might be more clear

**Comment by aweary** [comment]
Happy to review a PR making it clearer that _synchronous_ `setState` class in `componentWillMount` will not trigger a re-render. We should avoid mentioning batching as that's an implementation detail and we should focus on usage instead.
