### ISSUE TITLE
this.props undefined 

### ISSUE THREAD

**Issue by sughanpandita** [facebook/react#9305]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
We need more information to help you.
