### ISSUE TITLE
this.props undefined

### ISSUE THREAD

**Issue by sughanpandita** [facebook/react#9307]
SideBarDemo:
class SidebarDemo extends React.Component {

constructor(props, context) {
    super(props, context);

    this.state = {
        isVisible: false,
        layout:"Hierarchial",

    };
}
render(){

return(
<div><App layout={this.state.layout}/></div>

);
}
App:
static createDefaultGraph() {

if(this.props.layout==="Hierarchial"){
//do something
}

render(){
console.log(this.props.layout);
return(

);

}

}

"when I use console.log(this.props.layout) in App I able to get value of layout but when calling this.props.layout in createDefaultGraph method it gives "TypeError: Cannot read property 'layout' of undefined" "

**Comment by nehero** [comment]
Could you provide more code for `App`?

**Comment by sughanpandita** [comment]
1. **SidebarDemo:**
2. class SidebarDemo extends React.Component {
3. constructor(props, context) {
4.         super(props, context);
5. 
6.         this.state = {
7.             layout:"Hierarchial",
8. 
9.         };
10.     }
11. return (
12.             <div>
13.                 <div><App layout={this.state.layout}/></div>
14.                 <div className='Sidebar-demo'>
15.               
16.                 <Sidebar side='left' isVisible={ this.state.isVisible } onHide={ () => this.updateModal(false) }>
17.                     <Nav>
18.                         <NavItem href='#'>
19.                             <p>Layout</p>
20.                    <select id="layoutdrop" style={dropDown}  onChange=  {this.updateLayout.bind(this)} >
21.                                  <option value="Hierarchial">Hierarchial</option>
22.                                 <option value="Organic">Organic </option>
23.                                 <option value="Circular">Circular</option>
24.                                 <option value="BusEdgeRouter">BusEdgeRouter</option>
25. 
26.                             </select>
27.                         </NavItem>
28.                     </Nav>
29.                 </Sidebar>
30.                 </div>
31.                 
32.             </div>
33. 
34.         );
35. ReactDOM.render(
36.     <SidebarDemo/>,document.getElementById('container')
37. );
38. 
39. 
40. **App:**
41. class App extends React.Component {
42.   static createDefaultGraph() {
43. 
44. var h1
45.  if(this.props.layout=="Hierarchial"){
46. 
47.            
48.            h1=new HierarchicLayout();
49. 
50.         }
51.    return graph;
52. }
53. 
54.  render() {
55.      console.log(this.state.layout);
56.         return (
57.             <div>
58. 
59.                 <GraphComponent graph={this.state.graph} editable={this.state.editable} />
60.             </div>
61.         );
62. 
63. 
64.     }
65. }

**Comment by nehero** [comment]
You don't have access to react props in a `static` method. You'll need to either make the component non-static or pass the necessary fields as arguments to the function when you're calling it

**Comment by aweary** [comment]
Hey @sughanpandita, sorry to hear you're having trouble. I think @nehero is right.

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

**Comment by sughanpandita** [comment]
Thanks @nehero @aweary it's now working 👍
