### ISSUE TITLE
Lookup translate 

### ISSUE THREAD

**Issue by saadaouad** [facebook/react#9310]
Please any recommendation about using a lookup translate in react app, and any type of file should be use it (`.po`, `.mo` or `.js`) ?

**Comment by aweary** [comment]
Hey @saadaouad! Sorry, I'm not entirely sure what you're asking but it sounds like it's related to translations (internalization) with React?

If so, we try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow. Thanks!

**Comment by saadaouad** [comment]
Sure, thanks for help @aweary.
