### ISSUE TITLE
react-addons-create-fragment destructuring assignment remains in distributed code

### ISSUE THREAD

**Issue by tmacdonald** [facebook/react#9315]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When running `npm run build`, I get the following error:
```
Creating an optimized production build...
Failed to compile.

static/js/main.6a1ea184.js from UglifyJs
SyntaxError: Name expected [./~/react-addons-create-fragment/index.js:343,0]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The react-addons-create-fragment/index.js:343 is a line with destructuring assignment. I think code in the distributable should be es5.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
* using create-react-app, create an app
* add material-ui (`npm install --save material-ui`)
* import Drawer (`import Drawer from 'material-ui/Drawer'`)

**What is the expected behavior?**
This will build properly with `npm run build`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
unknown

**Comment by gaearon** [comment]
This is a bug. It indeed appears untranspiled.

That said can I ask why you're using `15.5.0-alpha.0` version of the package? As it says, this is an alpha. The latest stable version is `15.4.2`.

**Comment by tmacdonald** [comment]
It's unintentional. Where did you see the reference to `15.5.0-alpha.0`?

**Comment by bvaughn** [comment]
Inferred from the line number in your error message (which seem to reference [this file](https://unpkg.com/react-addons-create-fragment@15.5.0/index.js)). As Dan says though, this version of `react-addons-create-fragment` shouldn't be installed by default. You should only be using it if you specified the "dev" tag when installing (eg `npm i react-addons-create-fragment@dev`).

**Comment by tmacdonald** [comment]
It appears to be coming from the material-ui dependencies.

```
    "react-addons-create-fragment": "^15.0.0",
    "react-addons-transition-group": "^15.0.0",
```

I'll create an issue on that project asking why they are targeting an alpha release.

**Comment by bvaughn** [comment]
No need. This is my fault. On Friday I pre-released 15.5.0 add-ons, tagged as `dev`, as part of the upcoming 15.5.0 react release. I didn't consider that their tag wouldn't prevent semver dependencies from pulling them in. In hindsight, pretty silly.

I'll do a quick fix of this one in particular.

**Comment by bvaughn** [comment]
@tmacdonald: Try `npm i` again. Should pull in `react-addons-create-fragment@15.5.1` which should hopefully work for you. Let me know!

**Comment by tmacdonald** [comment]
Build successful 👍 . Thanks @bvaughn

**Comment by bvaughn** [comment]
Just did a quick audit of the other 15.5.0 add-ons and I think the destructuring statement in create-fragment was the only non-ES5 thing that slipped through.

Thanks for reporting it @tmacdonald! Sorry for the inconvenience. 😄

**Comment by gaearon** [comment]
We'll skip 15.5.0 then?

**Comment by gaearon** [comment]
I suggest running `npm deprecate` for 15.5.0 then so that people are aware of issues.

**Comment by bvaughn** [comment]
The bad release (15.5.0) is deprecated:

<img width="1047" alt="screen shot 2017-04-02 at 3 43 04 pm" src="https://cloud.githubusercontent.com/assets/29597/24591621/2075b4fe-17bb-11e7-8ca9-1f69601a86c8.png">
