### ISSUE TITLE
Async event handlder can't use preventDefault very well

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9319]
I create a [jsfiddle demo](https://jsfiddle.net/heaven_xz/mc312ej9/15/):

```
class APP extends React.Component {
  constructor(props) {
    super(props);
    
    this.handleClick = this.handleClick.bind(this);
  }
  
  // work fine
  handleClick (event) {
    event.preventDefault();
  
    setTimeout(function() {
    	console.log('async event callback fired!');
    }, 500);
  }
  
  // work bad,it will still trigger page refresh which means the default
  // behaviour doesn't be prevented
  /* handleClick (event) {
       event.persist(); // make sure we can get event.* in the async function below
  
       setTimeout(function() {
     	 event.preventDefault();
          console.log('async event callback fired!');
       }, 500);
     } */

  render() {
    return (
      <div>
        <form>
          <button onClick={this.handleClick}>click me</button>
        </form>
      </div>
    );
  }
}
```

I mean that maybe sometimes we need encapsulate the handler and the encapsulation is transparent,so `preventDefault` is **user's responsibility**,we can't  in advance of adding it just like the first way above.But the second way above can't work apparently.Of course we can add some options such as `needPreventDefault` in the encapsulation and provide it to user,but this looks like not a perfect way.

So,I want to ask that is there any good way to solve this?Thanks.

**Comment by jwbay** [comment]
preventDefault needs to be called synchronously to have any effect at all. This is true even without React in the picture. It's browser/DOM-level behavior.

**Comment by aweary** [comment]
@jwbay is correct, the event system is synchronous and `preventDefault` must be called synchronously, even outside React. Hope that helps!

**Comment by NE-SmallTown** [comment]
Thank you guys.I know this is browser/DOM-level behavior.The reason why I file this issue is that I want to discuss/explore more convenient/magic ways to solve this.Maybe someday I will digging in because I am busy these days.

**Comment by gaearon** [comment]
It is not very clear what exactly you are proposing. There is no way React DOM could do something a browser can’t. The browsers don’t let us “prevent” something that already happened.
