### ISSUE TITLE
Filtering out valid mathml properties

### ISSUE THREAD

**Issue by findlay-hannam** [facebook/react#9320]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
React is filtering out some attributes that are valid in mathml elements

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
Open https://jsfiddle.net/x8ct91f9/1/ (On firefox for full mathml support). You'll see the attributes are all filtered out, although they're valid as mathml.

**What is the expected behavior?**
The html is rendered with mathvariant, notation and linebreak

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Firefox is supposed to support mathml. Websites running MathJax will also be affected.

**Comment by nhunzaker** [comment]
This should be fixed by #7311. Tagging it here for followup.

**Comment by aweary** [comment]
This is resolved as of React 16 https://jsfiddle.net/un56cfks/ 🎉
