### ISSUE TITLE
change state of one component affect the other component

### ISSUE THREAD

**Issue by Serboy** [facebook/react#9326]
Hi, I'm having a problem using multiple component with one reducer and action. What I'm trying to do is to reuse data grid on modal.

 Here's the sample 
![sample](https://cloud.githubusercontent.com/assets/8003174/24644309/77b981d8-1945-11e7-88a9-210385d3191d.PNG)

Originally the data grid behind has no record and when I showed the modal with data grid and pass a data the data grid behind, it has now a data and also when select/check the item in data grid on modal it will also select/check on the other one. 

I am using react and react-redux.

Please help!.. 
Thanks a lot

**Comment by aweary** [comment]
Hey @Serboy! We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
