### ISSUE TITLE
Post form as proper JSON?

### ISSUE THREAD

**Issue by dbol55** [facebook/react#9343]
Is it possible to automatically transform a html form, to a proper JSON document with react? 

In contrast to old fashion form encoded data it would be wishful to get the whole JSON document such as unchecked booleans (false) etc. Finally if files could be included aswell as base 64 string it would be a great bonus.

**Comment by aweary** [comment]
Hey @dbol55! If you're using controlled components you could potentially just serialize your state using `JSON.stringify` and submit a POST request with `fetch` or a library like `axios`.

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
