### ISSUE TITLE
Build Error: not found the fbjs\lib\warning

### ISSUE THREAD

**Issue by teemosauce** [facebook/react#9350]
$ npm run build

> react-build@16.0.0-alpha.6 build D:\github\react
> npm run version-check && node scripts/rollup/build.js

> react-build@16.0.0-alpha.6 version-check D:\github\react
> node ./scripts/tasks/version-check.js

 STARTING  react.development.js (umd_dev)
Error: Could not load D:\github\react\node_modules\fbjs\lib\warning (imported by D:\github\react\src\isomorphic\modern\class\ReactNoopUpdateQueue.js): ENOENT: no such file or directory, open 'D:\github\react\node_modules\fbjs\lib\warning'
    at D:\github\react\node_modules\rollup\dist\rollup.js:9461:10

But I can found the package in the node_modules.(win10 64)

**Comment by gaearon** [comment]
It is quite possible that the build process is broken on Windows as we just rewrote it. Would you like to help fix it?

**Comment by ccsang** [comment]
It seems like that warning.js is resolved to 'D:\github\react\node_modules\fbjs\lib\warning', it's lack of a extension like '.js'

**Comment by ccsang** [comment]
It't due to "rollup-plugin-alias", isFilePath is not work on windows.
See this [issue](https://github.com/rollup/rollup-plugin-alias/issues/3)

**Comment by JeffWong16** [comment]
Has this problem been solved? I still have the same problem

**Comment by aweary** [comment]
@JeffWong16 would you like to test this out again and see if it's still broken?

**Comment by gaearon** [comment]
Let's track this in https://github.com/facebook/react/issues/9540.
