### ISSUE TITLE
404 Link in Web Components docs

### ISSUE THREAD

**Issue by timurtu** [facebook/react#9357]
At the bottom of the Web components docs [https://facebook.github.io/react/docs/web-components.html](https://facebook.github.io/react/docs/web-components.html) page there's a link to a 404.

[https://github.com/facebook/react/tree/master/examples/webcomponents](https://github.com/facebook/react/tree/master/examples/webcomponents)

**Comment by gaearon** [comment]
Yep, thanks. We actually deleted the link content but haven’t synced the docs yet 😞 
If you’re curious, there was nothing very interesting there—just an HTML file with the same content as in the doc.

**Comment by timurtu** [comment]
No problem

**Comment by aweary** [comment]
This link no longer appears in the docs

https://reactjs.org/docs/web-components.html
