### ISSUE TITLE
onclick handler default parameter value set to proxy

### ISSUE THREAD

**Issue by jeffbergman** [facebook/react#9367]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
This is expected behavior in dev, it's a proxy to the synthetic event ☺️

**Comment by jeffbergman** [comment]
You guys may know this already...

**I'm calling an onclick handler like this**:

<button className="btn-new-acct" onClick={this.props.showCreateAcct}>Create your account</button>

**The passed function is written with a default parameter like this:**

showCreateAcctFormOne(caOneDisplayMsg = '') {

**The compiled code is this:**

 key: 'showCreateAcctFormOne',
    value: function showCreateAcctFormOne() {
      var caOneDisplayMsg = arguments.length <= 0 || arguments[0] === undefined ? '' : arguments[0];

Which is where the proxy is assigned instead of the default

**Comment by jeffbergman** [comment]
Just saw you closed it, glad you know, yes I'm in dev, yes the workaround was obvious...
