### ISSUE TITLE
`prop-types` package does not declare `react` as a dep or peer dep.

### ISSUE THREAD

**Issue by ljharb** [facebook/react#9371]
Per https://unpkg.com/prop-types@15.5.1/index.js, `react` is a dependency of `prop-types`.

However, http://npmcdn.com/prop-types/package.json does not list it as either a `dependency` or a `peerDependency`. That makes it both an implicit dependency, and one whose version compatibility is unchecked.

Could you add `react` as a peer dependency, ideally over the entire range of React versions that `prop-types` works with? I'm particularly interested in if it works on 0.13 and 0.14, I'd want the React peer dep to be `^0.13 || ^0.14 || ^15`, for example.

(@acdlite @kentcdodds)

**Comment by sebmarkbage** [comment]
We should just inline isValidElement so we don't have to.

**Comment by ljharb** [comment]
That would be SO much better,

The only remaining reason airbnb-prop-types depends on React is isValidElement :-)

**Comment by acdlite** [comment]
Done!

**Comment by acdlite** [comment]
Btw prop-types lives here now: https://github.com/reactjs/prop-types

**Comment by ljharb** [comment]
omg separate repo, yay‼ you may want to update the repo field on https://www.npmjs.com/package/prop-types; it still points to this one.
