### ISSUE TITLE
Cannot find module './ReactReconcileTransaction' from 'ReactShallowRenderer.js' in `react-test-renderer`

### ISSUE THREAD

**Issue by wyze** [facebook/react#9372]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
Cannot find module './ReactReconcileTransaction' from 'ReactShallowRenderer.js'
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

```
$ yarn add --dev react-test-renderer
```

```js
// Component.test.js

const ReactShallowRenderer = require('react-test-renderer/shallow') // Cannot find module error
```

**What is the expected behavior?**

That `ReactReconcileTransaction` module is included in `react-test-renderer` package.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.5.1

---

If this is something relatively simple, I wouldn't mind making my first PR to React if given a nudge in the right direction. I looked already in the grunt tasks for building the packages, but nothing stood out.

**Comment by gaearon** [comment]
It does seem like something went wrong with packaging. Will need to take a closer look at this.

**Comment by bvaughn** [comment]
Should be fixed by #9375 based on my initial testing. We're making another release now~

**Comment by bvaughn** [comment]
react-test-renderer@15.5.3 just released with the fix!

**Comment by wyze** [comment]
Thank you both for a quick fix!
