### ISSUE TITLE
If ReactDOM.render is asynchronous, how to catch exceptions?

### ISSUE THREAD

**Issue by StephanBijzitter** [facebook/react#9378]
**Do you want to request a *feature* or report a *bug*?**
I want to request a feature.

**What is the current behavior?**
The callback is called, but doesn't pass an error if one occurred.
https://facebook.github.io/react/docs/react-dom.html#render

**What is the expected behavior?**
If an error occurs during rendering, I would want to handle the error in the callback.

Right now, I'm using this:
```jsx
    return new Promise(resolve => {
        const routerProps = {
            routes,
            history,
            onUpdate
        };

        try {
            render((
                <Provider store={_store}>
                    <Router {...routerProps}/>
                </Provider>
            ), document.getElementById('...-editor'), () => {
                resolve();
            });
        } catch (error) {
            reject(error);
        }
    });
```

But I would like to use this:
```jsx
    return new Promise(resolve => {
        const routerProps = {
            routes,
            history,
            onUpdate
        };

        render((
            <Provider store={_store}>
                <Router {...routerProps}/>
            </Provider>
        ), document.getElementById('...-editor'), error => {
            if (error) {
                reject(error);
            } else {
                resolve();
            }
        });
    });
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I'm using the major version 15 and have not checked any other versions.

**Comment by SavePointSam** [comment]
I would imagine having a promise chain returned from render may even be more elegant. Something to the effect of:

```
render((<span />)).then(
  value => dealWithValue(value),
  error => dealWithError(error)
)
```

**Comment by StephanBijzitter** [comment]
well yeah, that'd be even better, but then a decision needs to be made whether to let the returned promise completely replace the callback (breaking change), or wrap the callback (non-breaking change).

**Comment by SavePointSam** [comment]
I don't think the callback to promise chain would need to be a breaking change. It could just give deprecation warning when it's used and then break later.

**Comment by gsouf** [comment]
ok guys, silent from developers here! I had to put my pickiness apart and create a super dirty workaround...hope it can help someone until (maybe some day?) we have a native way to catch error from ReactDOM.render.

```
async function renderSomethingSomewhere(Something, somewhere) {
    let hasError = false;
    class ErrorBoundary extends Component {
        componentDidCatch(error, errorInfo) {
            hasError = true;
        }

        render() {
            return this.props.children;
        }
    }

    await new Promise(res => {
        ReactDOM.render(<ErrorBoundary><Something/></ErrorBoundary>, somewhere, res);
    });

    if (hasError) {
        // did not render properly
    } else {
        // works
    }
}

renderSomethingSomewhere(<MyComponent/>, someElement);
```

**Comment by gsouf** [comment]
@gaearon because error boundary class that we create here manipulates an outside variable during a render process, it does not follow any standard and it's hard to understand what's going on, especially if it's given to an unexperienced react developer. Even for me, reading again  after 6 months later, I  took some time to understand what is going on there.

**Comment by gaearon** [comment]
What I'm saying is, I don't feel like I understand why the code is structured this way at all. Why does `renderSomethingSomewhere` needs to return a Promise? What do you do with rejections?

Imagine your component throws a second _after_ it mounts, in response to some `setState`. Even if there was some convenient API for listening to errors in `ReactDOM.render`, it wouldn’t catch that, so your Promise would resolve successfully, despite the tree showing an error. Why do you try to distinguish initial errors from other errors?

**Comment by gaearon** [comment]
In other words, my point is that the whole premise of an API like `renderSomethingSomewhere` that needs to reject on errors seems mistaken to me.

**Comment by gsouf** [comment]
@gaearon I needed to render various components in an isolated way. If one of the component fails to render, I need to fail the whole process.

an over simplified example of what I needed to do, if we suppose that ReactDOM.render is synchronous and throws an exception when it fails:

```js
try {
    ReactDOM.render(....);
    ReactDOM.render(....);
    ReactDOM.render(....);
} catch (e) {
    // one of the render has failed, abort and show an error
} 
```

**Comment by gsouf** [comment]
@gaearon In my use case it's just simple components that have no state, they only take props and display something depending on the props. We do a screenshot of the component and we move to the next one.

It's not a typical react app workflow you would say, and I'm aware of that, but we have other constraints that makes it to be the simplest solution

**Comment by gaearon** [comment]
Can you describe the use case in just a bit more detail? There might be some more idiomatic solution.

**Comment by gsouf** [comment]
@gaearon I appreciate your help, but I think it's out of the scope of this ticket and as you mentioned anything else can fail after the component has initialy rendered. So we are not expecting a change on the react api here.
The solution we have atm works well for us and are not willing to change it for now

**Comment by gaearon** [comment]
Sure, sounds good. I’m just saying there might be something that’s simpler that neither of us thought of yet. For example maybe you don’t need many render calls and instead could have a single tree with a single error boundary at the top, but with multiple Portals to different DOM containers below it. Then the error boundary would catch errors from all of them even if they’re in different parts of the DOM. But I can’t say more without understanding your use case properly.
