### ISSUE TITLE
[Question] PropType deprecation warning.

### ISSUE THREAD

**Issue by rockchalkwushock** [facebook/react#9379]
**Do you want to request a *feature* or report a *bug*?**
I saw the package for propTypes in my newsfeed this morning. 

https://github.com/reactjs/prop-types

Is this a package that will be **required** to shut this warning off or is their a way to disable it if I'm not using propTypes? On the initial render with a component designed with `glamorous` I received the following warning:

**What is the current behavior?**
![screen shot 2017-04-08 at 12 04 32 pm](https://cloud.githubusercontent.com/assets/19720404/24830869/b77c7dfa-1c53-11e7-9b02-865f56ae42b2.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```json
"react": "^15.5.2",
"react-dom": "^15.5.2",
```

**Comment by kutsan** [comment]
Same issue, I don't even use propTypes and even `DefinePlugin` not working.

**Comment by gaearon** [comment]
You only see this warning if some component you are using (yours or a third party one) accesses `React.PropTypes`. Please look at the stack trace to find which component is causing it, and file an issue with the relevant library (or send a PR to them). The warning will disappear when all packages you use have updated to not rely on `React.PropTypes` (which will be gone in React 16), and will use the standalone package instead. I hope this helps!

**Comment by rockchalkwushock** [comment]
@gaearon will do appreciate the quick response!

**Comment by kutsan** [comment]
@gaearon Thanks Dan. I understand the situation but isn't there any way to disable this warning for our production builds? Obviously, other libraries can't migrate that fast.

**Comment by gaearon** [comment]
Warnings are always disabled in production builds. Am I missing something?

**Comment by kutsan** [comment]
@gaearon I am sorry this is totally my fault. There was a bug in our app.
