### ISSUE TITLE
Bug: render() before componentDidMount() 

### ISSUE THREAD

**Issue by comerc** [facebook/react#9380]
How to reproduce?

```bash
$ git clone git@github.com:comerc/cra-render-bug.git
$ cd cra-render-bug
$ yarn
$ yarn start
```

Chrome:

![2017-04-08 21 00 48](https://cloud.githubusercontent.com/assets/1025241/24831218/83daf15c-1c9e-11e7-8b55-7f487003fd9f.png)

Source:
```jsx
class App extends Component {
  componentDidMount() {
    console.log('componentDidMount')
  }
  render() {
    console.log('render')
    return (
      <div className="App">
      </div>
    );
  }
}
```

Ubuntu: 14.04
Chrome: 57
React: 15.5.3

**Comment by bvaughn** [comment]
Am I misreading something? The console screenshot you attached shows "render" being logged before "componentDidMount"
