### ISSUE TITLE
Incorrect export from react-addons-create-fragment package

### ISSUE THREAD

**Issue by lscspirit** [facebook/react#9381]
The react-addons-create-fragment npm package (v15.5.2) is not exporting the `createReactFragment()` function as intended. Instead it is exporting a function that returns the `createReactFragment()`.

To reproduce:

```javascript
var createFragment = require('react-addons-create-fragment');
var Hello = React.createClass({
  var fragment = createFragment({
    hello: <span>Hello</span>,
    world: <span>World</span>
  };
  render: function() {
    return <div>{ fragment }</div>;
  }
});

ReactDOM.render(
  <Hello/>,
  document.getElementById('container')
);

// Actual render: <div></div>
// Expected render: <div><span>Hello</span><span>World</span></div>
```
Note that the `React.addons.createFragment` that comes with `react-with-addons.js` is working as expected. This bug only affects the npm package.

**Comment by gaearon** [comment]
Should be fixed in react-addons-create-fragment@15.5.3.
Thanks!
