### ISSUE TITLE
15.5 addon bugs

### ISSUE THREAD

**Issue by gaearon** [facebook/react#9384]
This release has been a bit rocky. 😛 
I'm keeping track of known issues to fix them up together in the next patch.

- [x] Expose `unstable_batchedUpdates` on shallow renderer (https://github.com/facebook/react/pull/9382), needed for Enzyme (https://github.com/airbnb/enzyme/pull/876#issuecomment-292747996)
- [x] Create Fragment CommonJS entry point is messed up (https://github.com/facebook/react/pull/9383, https://github.com/facebook/react/issues/9381)
- [x] CRC package misses dependency on `object-assign`
- [x] Some CommonJS addons inline fbjs unnecessary
- [x] UMD files contain `process` shim
- [x] UMD files aren't envified
- [x] LinkedInput UMD is broken
- [x] Release `linked-input`
- [x] prop-types is missing LICENSE and PATENT file
- [x] Fix and release `create-react-class` (tagging @acdlite for this and add the rest of us)

Regarding `create-react-class`:
* Add docs link to the main docs. Currently just says "_Documentation is WIP_".
* Add peer deps for React 15.5+ (15.5+ because of `replaceState` callback issue). Currently there are no peer deps at all, only dev deps.
* Release update to NPM

**Comment by bvaughn** [comment]
> Packages miss dependency on `object-assign`

Just the `create-react-class package, right?

**Comment by gaearon** [comment]
yep

**Comment by bvaughn** [comment]
FWIW the prop-types `package.json` does list "BSD-3-Clause" license which is, I think, the same as the one we have in the `LICENSE` files.

Going to tag @acdlite to do this too since it looks like he's made changes to prop-types that weren't pushed to 15.5-dev or 15-stable branches.

**Comment by gaearon** [comment]
>Going to tag @acdlite to do this too since it looks like he's made changes to prop-types that weren't pushed to 15.5-dev or 15-stable branches.

Did the source of truth move to `reactjs/prop-types`? Maybe we should delete folder in the branches.

**Comment by bvaughn** [comment]
Oh! You're right. Andrew mentioned that at one point but I forgot.

I'd add the license and patents file and do a point release of prop-types then.

**Comment by bvaughn** [comment]
I think there are a couple of additional things we need to do for create-react-class:
* Add docs (at least a link to the main docs). Currently just says "_Documentation is WIP_".
* Add peer deps for React 15.5+ (15.5+ because of `replaceState` callback issue). Currently there are no peer deps at all.
* Release with peer deps and recently-added `object-assign` dep

**Comment by J-Dickson** [comment]
Formerly, `React.createClass` would set the `displayName` by default. This seems to have been omitted in `create-react-class`. Is this intentional? Thanks.

**Comment by bvaughn** [comment]
[create-react-class](https://unpkg.com/create-react-class@15.5.1/factory.js) still does this for DEV mode, no?

```js
// Add verbose displayName to the function, which helps when looking
// at profiling tools.
if (typeof property === 'function' && spec.displayName) {
  proto[name].displayName = spec.displayName + '_' + name;
}
```

I believe the problem is that `process.env.NODE_ENV` shouldn't be in the file.

**Comment by gaearon** [comment]
I think @J-Dickson is referring to Babel inferring `displayName` automatically (which is the case with `React.createClass` call). AFAIK we're waiting for a Babel release that does it. (@acdlite can clarify.)

But until it's not there, the codemod we're providing (see the blog post) adds a `displayName` manually to your existing classes.

**Comment by bvaughn** [comment]
Oh! So this: babel/babel/pull/5554
