### ISSUE TITLE
Infinite loop when dispatching event in event listener

### ISSUE THREAD

**Issue by kirazbaysal** [facebook/react#9400]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Normally when an event is dispatched, there's a place where a fakeNode is created, then the event is attached to that node, the event is dispatched then it's removed. Because these all happen synchronously, it goes into the event listener before the eventlistener is removed from fakenode. So when the second event is dispatched within the event listener, you get stuck in an infinite loop, because each time dispatch is called, both event listeners get called, then the first one dispatches the second event, so it goes on and on.... Specifically when bubbles=true. Though wasn't fully able to understand why.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
https://jsfiddle.net/6n79t4zp/ click on Hello world, look at the console.

**What is the expected behavior?**
Should not infinite loop. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not sure about previous versions. The version I use is 15.4.1 and it does repro in the JSfiddle so 15.5.3 has the problem as well.

**Comment by forgetaboutme** [comment]
see issue #5482

**Comment by jddxf** [comment]
This should only happen in development environment where we're simulating a real browser event to execute an event listener and when another event of **same** type is dispatched in the event listener.

As shown in [ReactErrorUtils#L59-L63](https://github.com/facebook/react/blob/master/src/renderers/shared/utils/ReactErrorUtils.js#L59-L63), there's a race condition between execution and removal of the event listener. 

Maybe we can avoid reuse of `fakeNode` or generate a different event type every time. I also tried removing event listener on `fakeNode` before the real event listener is executed but it didn't work in IE.

**Comment by thamaranth** [comment]
What's the status on this issue?

**Comment by aweary** [comment]
This is no longer an issue in React 16 https://jsfiddle.net/899d0bu2/
