### ISSUE TITLE
Comments Reactjs 

### ISSUE THREAD

**Issue by DaoHuyTuan** [facebook/react#9405]
i was use so many way to comments my code in js file it not run the comment code 
but in website i still see my comments code , it just show code like text 
can i not see my comment in website ?? 

![captbture](https://cloud.githubusercontent.com/assets/26370399/24922624/30104be4-1f19-11e7-912e-9268b81f9e75.PNG)

![capture](https://cloud.githubusercontent.com/assets/26370399/24922623/300f020c-1f19-11e7-90a2-68a71f2c3485.PNG)

**Comment by DaoHuyTuan** [comment]
i try other way but still like this 
{/**/} 
or 
it's error if i use type of comments

**Comment by forgetaboutme** [comment]
When using JSX, you need to wrap comments around curly braces:  ```{/* This is a comment */}```

**Comment by aweary** [comment]
@forgetaboutme is exactly right, using `{/* */}` should work fine. [Here's an example](https://jsfiddle.net/rzacbaur/). Hope that helps!

**Comment by DaoHuyTuan** [comment]
thank guys last day i use {/**/} too but it say "not define {/* "

**Comment by gaearon** [comment]
Please provide full code example if you have issues.
