### ISSUE TITLE
Event plugins names are mungled in Closure Compiler under advanced optimizations

### ISSUE THREAD

**Issue by roman01la** [facebook/react#9417]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
When React is compiled by Closure Compiler with advanced optimizations, names of injected event plugins are being mungled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
Compile React with Closure Compiler directly from NPM.

**What is the expected behavior?**
The names of injected event plugins should not be mungled.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v15.5.4
It didn't work in previous versions of React

Closure Compiler renames object properties, unless they are strings explicitly.
It happens because of the way how event plugins are injected [here](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/shared/ReactDOMInjection.js#L56-L60)
```js
  EventPluginHub.injection.injectEventPluginsByName({
    SimpleEventPlugin: SimpleEventPlugin,
    EnterLeaveEventPlugin: EnterLeaveEventPlugin,
    ChangeEventPlugin: ChangeEventPlugin,
    SelectEventPlugin: SelectEventPlugin,
    BeforeInputEventPlugin: BeforeInputEventPlugin,
  });
```

And later used [here](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/shared/shared/event/EventPluginRegistry.js#L45)
```js
  for (var pluginName in namesToPlugins) {
    var pluginModule = namesToPlugins[pluginName];
    var pluginIndex = eventPluginOrder.indexOf(pluginName);
```

**Comment by gaearon** [comment]
Yea. We're not really compatible with GCC right now and there are also a few places where we went for more clear code rather than GCC compat. I don't think it makes sense to fix GCC compat with one-offs because we'll just keep breaking it. Instead we should probably investigate enabling it by default in *our* build process now that we're switching to flat bundles. @trueadm is interested in this.

**Comment by roman01la** [comment]
@gaearon Makes sense. Just want to note that since ClojureScript now allows to build JS deps directly from NPM it means that potentially this issue blocks transition to a new build pipeline.

@trueadm If I can help somehow with this, please let me know.

Thanks!

**Comment by anmonteiro** [comment]
While it is an issue that React injects those properties dynamically, I've actually been down this road before and you're probably just using stale externs. Here's the commit where I fixed what you're seeing: https://github.com/cljsjs/packages/commit/149363fb9496a391d8cba74432395905160902f8

**Comment by roman01la** [comment]
@anmonteiro I'm compiling directly from NPM, so no externs. But I guess this would help, thanks!

**Comment by HiroAgustin** [comment]
@roman01la were you able to find a work around for it? I'm running into the same problem using [webpack-closure-compiler](https://www.npmjs.com/package/webpack-closure-compiler).

**Comment by roman01la** [comment]
@HiroAgustin you have to use externs file for React https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js

**Comment by gaearon** [comment]
I'll close this as we don't have a goal of being GCC compatible yet. Rather, we'd like to GCC compile ourselves: https://github.com/facebook/react/issues/11092. We'd need to fix up all those issues as part of that work, but I'd prefer to track them there in that issue.
