### ISSUE TITLE
A beginner's guide to exploring the source code

### ISSUE THREAD

**Issue by abhisheksoni27** [facebook/react#9430]
I have been using React for a while now, and I want to be able to contribute to the project. But I can't seem to figure out where to start, or which file to read first, etc,.

It'd be great if you could incorporate a beginner's guide right in this issue, which could be later sent to the docs, or as a special section in the docs.

**Comment by pavelsuraba** [comment]
Hi, this link to react's documentation might help you.
https://facebook.github.io/react/contributing/how-to-contribute.html

I think it's really helpful and provides a lot of informations and resources that will help you to start.

**Comment by gaearon** [comment]
Yea I think this is exactly the doc you're looking for. There's also an "Implementation Notes" doc next to it.

We are rewriting React right now so it's a bit confusing. Both implementations are checked in. We will soon delete the old one.

**Comment by abhisheksoni27** [comment]
@pavelsuraba Thanks for responding, and citing that link. 

@gaearon Should I wait for React 16 to land, then?

**Comment by gaearon** [comment]
Up to you!

**Comment by abhisheksoni27** [comment]
All right. :tada:
