### ISSUE TITLE
Tag 15.5.{1,2,3,4}, update docs

### ISSUE THREAD

**Issue by zpao** [facebook/react#9443]
Looks like the git tags were missed in the followup 15.5.x releases and the website still says 15.5.0 is the latest.

(I'd do it myself but just in case there are other things that happen these days, I'll let you all handle it)

**Comment by gaearon** [comment]
15.5.x was a really rocky release and IIRC anything other than 15.5.4 is flawed or broken in some way. 😞  Do we ever "skip" bad versions in the changelogs? I don't want to give people the impression that updating to, e.g. 15.5.3, is safe. How would you handle this?

Additionally different addons had different breakages in different patch versions, and they’re not lined up even now. Not sure if it matters or not, but we used to sync them up to the main version but can’t anymore.

**Comment by zpao** [comment]
I would still ensure the git tags are there. I would probably add them to the changelog and just include that those version are broken. I'd even go a step further and make sure that we `npm deprecate` those versions. Personally, I say embrace the brokenness and just be open that it happened and you fixed it 😀

As for the out-of-sync-ness… yea, that's why I avoided getting out of sync as much as possible for so long. It'll happen more as we move to out-of-sync monorepos though so no time like the present to figure it out 😉. What I started doing for fbjs is make the tags `project-version`. Not sure it's the best thing 🤷‍♂️

**Comment by flarnie** [comment]
I want to add them and note them as "Yanked". See http://keepachangelog.com/en/0.3.0/:
![screen shot 2017-04-26 at 8 02 29 am](https://cloud.githubusercontent.com/assets/1114467/25441344/cb26926c-2a56-11e7-9f69-c7264329b93b.png)

**Comment by stof** [comment]
I think it is OK if broken releases are not tagged on github. But if 15.5.4 is the working one, we should have a 15.5.4 release on github too. Otherwise, people using the download will get 15.5.0

**Comment by flarnie** [comment]
I'll have a draft of the changelogs up soon!

@stof You are right that we could probably skip broken versions. I am imagining that for anyone who, for whatever reason, ended up downloading the broken versions, it could be useful to see more info about that version and where it falls in the timeline. So while it would be ok for us to skip annotating those versions, I'd like to add notes about them just in case someone finds it helpful.

**Comment by flarnie** [comment]
Changelog and git tags are updated - please reopen and comment if I missed anything.

**Comment by zpao** [comment]
Thanks! The website still said 15.5.0 is the latest, probably want to update https://github.com/facebook/react/blob/15-stable/docs/_config.yml#L63 so the site will rebuild.

**Comment by gaearon** [comment]
Bumped the website version.
