### ISSUE TITLE
Show a warning when value is provided to a checkbox input

### ISSUE THREAD

**Issue by srph** [facebook/react#9446]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

A checkbox input can have a `value` prop which is most likely ignored (it should be `checked`).

**What is the expected behavior?**

I think we should throw a warning if a user provides a `value` instead of `checked` to a `<input type="checkbox" />`.

**Comment by aweary** [comment]
Thanks for the request @srph! I think this is a good idea. Currently, if you use `value` instead of `checked` with a controlled checkbox it _looks_ like its working but it's not. The input just remains uncontrolled and if its value is updated in state elsewhere it won't update in the DOM.

Would you like to submit a PR for this?

**Comment by Hypnosphi** [comment]
The `value` prop is helpful when you use a native form for sending data to server. It is responsible for the actual value that gets sent to the server when the checkbox is checked and the for is being submitted. So, for example, `<input type="checkbox" name="foo" value="on"/>` would get submitted as `foo=on` when checked, which could be exactly whot your server expects.

Of course, using native forms for submitting data isn't really common in single-page apps, but as far as I know React doesn't enforce the apps using it to be single-page.

I understand the issue with pseudo-controlled checkboxes though. Maybe the warning should arise when there is an `onChange` handler attached but no `checked` prop provided, regardless of the presence of `value`?

**Comment by aweary** [comment]
> I understand the issue with pseudo-controlled checkboxes though. Maybe the warning should arise when there is an onChange handler attached but no checked prop provided, regardless of the presence of value?

I think this is exactly what the warning should do 👍

**Comment by Hypnosphi** [comment]
Ok, I think I'll make a PR then

**Comment by Hypnosphi** [comment]
But I'm not really sure that having a handler on an uncontrolled component is an anti-pattern. Why should it be one?

**Comment by Hypnosphi** [comment]
Oh, I didn't notice there's already an open PR on that issue. The questions above are still to be discussed though

**Comment by athomann** [comment]
Okay, I'll adjust #9490 with that warning.

**Comment by jackysatpal** [comment]
Hello,

I like to solve this issue and I'm  beginner to React. 
If there is any slack channel or IRC channel then I would be happy to join it.

**Comment by sahilsharma011** [comment]
You can get in touch by going [here](https://facebook.github.io/react/contributing/how-to-contribute.html#how-to-get-in-touch)

**Comment by morajabi** [comment]
If it's not done yet, I can take it.

**Comment by nhunzaker** [comment]
Circling back to this, we have two outstanding PRs to resolve this: https://github.com/facebook/react/pull/10666, https://github.com/facebook/react/pull/9490 however, I'm still not sure that this is viable. There are still false warning cases. Working from [@aweary's direction](https://github.com/facebook/react/issues/9446#issuecomment-296494855):

> I understand the issue with pseudo-controlled checkboxes though. Maybe the warning should arise when there is an onChange handler attached but no checked prop provided, regardless of the presence of value?

When I updated https://github.com/facebook/react/pull/9490 (locally, don't want to force-push @athomann's master), I noticed that we hit a failure here:

https://github.com/facebook/react/blob/9d483dcfd6aad53ce082d249845436a56eb39248/packages/react-dom/src/__tests__/ReactDOMInput-test.js#L331-L342

`onChange` actually isn't necessary for this test. I think this is a relic of an older set of warnings that ran incorrectly for checkbox/radio inputs that was meant for text input types.

_But_, it is an existing use case, and there is probably code in the wild that listens to changes on checkbox/radios while relying on implicitly setting an uncontrolled checkbox to `unchecked` when `defaultChecked` or `checked` aren't specified. 

Unless we are absolutely sure this is an anti-pattern, I don't think we should have a warning.
