### ISSUE TITLE
Unit testing react + backbone without phantom.js

### ISSUE THREAD

**Issue by yoshuawuyts** [facebook/react#945]
This is closely related to #455, but not entirely the same.

I'm curious how one'd go around to testing browserified backbone + react apps. It appears that [react doesn't play well with phantomjs](https://github.com/facebook/react/pull/347), so I'm looking for alternatives. [Jsdom](https://github.com/tmpvar/jsdom) is next on the list, and I'm looking for suggestions how to properly handle this.

An issue that arises when using `browserify` and not loading the app through an html template is that you're not actually testing against the DOM and can't do things such as `<script src='vendor/react.js'></script>` to load packages into the global scope.

Do you have any ideas, theorems or suggestions on how to approach unit testing without phantomjs?

**Comment by loretoparisi** [comment]
I have tried to inject the shim script through ```page.injectJS```, but it didn't work, I guess since ```page.injectJS``` does not support closures:

```Javascript
page.open(url, function(status) {
          if (status === "success") {

            if (page.injectJs('phantom-react-shim.js')) {
              page.render(pageCaptureFileName, {
                format: Settings.pageCaptureFileType,
                quality: Settings.pageCaptureQuality
              })
            }

          }
        });
```

http://phantomjs.org/api/webpage/method/inject-js.html

**Comment by neb42** [comment]
@spicyj That link is 404'ing. Do you have another copy of the code?

**Comment by spicyj** [comment]
Edited my comment to work again.
