### ISSUE TITLE
Default Props not set through multiple inheritance

### ISSUE THREAD

**Issue by nehero** [facebook/react#9460]
*If this belongs somewhere else like babel's issues then I will close and repost there*.

**Do you want to request a *feature* or report a *bug*?**
Possible bug?

**What is the current behavior?**
When extending a class that extends `React.Component`, default props are not set in IE 9 or 10 causing some 3rd party components to throw errors. In this case, `Select` is made using `React.createClass`. 

The specific issue with this one is that the props `inputProps` on `Select` are not being set default to an object so the error `cannot read property "X" of undefined` is being thrown. Setting the prop manually to an empty object on the `<TetherSelect>` fixes this error.

Link to line where default props are set: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L140

```javascript
import React from 'react';
import Select from 'react-select';
import TetherComponent from 'react-tether';

/** from https://github.com/JedWatson/react-select/issues/810#issuecomment-250274937 **/
/*
  Select is an es5 component created with "React.createClass"
*/
export class TetherSelect extends Select {

    constructor(props) {
        super(props);

        this.renderOuter = this._renderOuter;
    }

    _renderOuter() {
        const menu = super.renderOuter.apply(this, arguments);

        // Don't return an updated menu render if we don't have one
        if (!menu) {
            return;
        }

        /** this.wrapper comes from the ref of the main Select component (super.render()) **/
        let width = this.wrapper ? this.wrapper.offsetWidth : null;

        return (
            <TetherComponent
                renderElementTo="body"
                ref="tethered-component"
                attachment="top left"
                targetAttachment="top left"
                constraints={[{
                    to: 'window',
                    attachment: 'together',
                    pin: ['top']
                }]}
            >
                {/* Apply position:static to our menu so that it's parent will get the correct dimensions and we can tether the parent */}
                <div></div>
                {React.cloneElement(menu, {style: {position: 'static', width: width}})}
            </TetherComponent>
        );
    }

}
```

Here is my `.babelrc`. I've also tried without the `transform-es2015-classes` and `transform-es2016-object-super`.

```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["ie >= 9"]
      },
	  "loose": true
    }],
    "react"
  ],
  "plugins": [
	  "transform-object-rest-spread",
      "transform-class-properties",
	  ["transform-es2015-classes", {
		"loose": true
	  }],
	  ["transform-es2015-object-super", {
		"loose": true
	  }]
  ]
}
```

**What is the expected behavior?**
The default props should be set. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested with React `15.4.2`. This only effects IE <= 10. Would ideally have this working in both IE 9 and 10.

**Comment by nehero** [comment]
Adding https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-proto-to-assign fixed the issue.

**Comment by gaearon** [comment]
Note we don’t really encourage inheritance in components at all.
https://facebook.github.io/react/docs/composition-vs-inheritance.html#so-what-about-inheritance

**Comment by gaearon** [comment]
You are basically using `react-select`’s private API by overriding its internal method. It can break in any patch version. Please avoid doing this unless you’re okay with fragile code.

If you need more customization you could send a PR to add any customizations you need to `react-select` as props. If it doesn’t get through, you can fork it and customize it for you use case manually.
