### ISSUE TITLE
[Feature] - Better warning/error message when attempting to "require" an "export"

### ISSUE THREAD

**Issue by damonbauer** [facebook/react#9469]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I converted an old component from `module.exports` to `export default`. However, I forgot to change a `require` to `import` when including the component. I received the following error ([source](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElementValidator.js#L236)):
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of...
```

**What is the expected behavior?**
I'd love to see a more helpful error message, if at all possible. [The error provided on line 223](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElementValidator.js#L223) is super helpful & would be awesome to replicate: 
> You likely forgot to export your component from the file it's defined in.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.4. Tested in Chrome on Mac.

**Comment by bvaughn** [comment]
This error message is already a part of 15.4.2. I assume you're running 15.4.0 or 15.4.1? You should be able to just update to the latest 15.4 patch number.
