### ISSUE TITLE
React Multi threading Issues with Nashorn

### ISSUE THREAD

**Issue by ShashiAachar** [facebook/react#9470]
**Do you want to request a *feature* or report a *bug*?**
Bug. Not sure if it is from React.

**What is the current behavior?**
Using react 15.4.0 with Nashorn Engine on JDK 1.8.092. A request of 500 threads per second throws 2 errors saying

Error 1:
Error: Transaction.closeAll(): Cannot close transaction when none are open. @ /react-dom/~/fbjs/lib/invariant.js?:44

Error 2:
Error: Transaction.perform(...): Cannot initialize a transaction when there is already an outstanding transaction. @ /react-dom/~/fbjs/lib/invariant.js?:44

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
I'm not sure if it is a bug!!. 

**What is the expected behavior?**
Out of 500 requests(10 to 15 fails in Server Side Rendering).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tried with 15.4.0 & 15.5.0. It is basically a server ride rendering fails in multiple thread scenario from Java.
I have attached the exception trace below.
[Error-1.txt](https://github.com/facebook/react/files/945285/Error-1.txt)

[Error-2.txt](https://github.com/facebook/react/files/945286/Error-2.txt)

.

**Comment by gaearon** [comment]
JavaScript itself is single-threaded, isn’t? I can’t imagine this being a concurrency problems since even if your host is multi-threaded, I’d expect environments to be isolated.

**Comment by pixeldrew** [comment]
If anyone else is experiencing this issue with Nashorn, it would be best to make sure your ScriptEngine invocation is wrapped in a syncronized block to avoid any issues with multi-threaded access to the Nashorn Engine.
