### ISSUE TITLE
Calling a function from another component.

### ISSUE THREAD

**Issue by yolohello12** [facebook/react#9481]
Hi,

I need to call a method in a component from another component, how can I do that?

In the below code I need to call the toggle method from a different component onClick, I tried finding a solution but not successful. Any suggestions!!!

Thank you,

```js
    class //extends React.Component {
        constructor() {
            super();
         //
        render() {
         //
            const toggle = () => {
              ///
                    });
                    return;
                }
                this.setState({
               //

                });
            };
            return (
              ////
            )
        }
    }
```

**Comment by bvaughn** [comment]
The section of the docs called ["Refs and the DOM"](https://facebook.github.io/react/docs/refs-and-the-dom.html) will probably be helpful for you.

We suggest you do as much as you can declaratively (through props) but if you need to call a method on an instance of another component, use a `ref`.

**Comment by acdlite** [comment]
@yolohello12 

A child can call a parent method by passing the method from the parent to the child as a prop:


```js
class Parent extends React.Component {
  toggle = () => {
    // update state
  };
  render() {
    return <Child onClick={this.toggle} />;
  }
}

class Child extends React.Component {
  render() {
    // onClick prop is available as this.props.onClick
    return <button onClick={this.props.onClick} />;
  }
}
```

If you need to go the reverse direction and call a child's method from a parent, then refs are one option, but as @bvaughn said, try to avoid refs if you can. Try to use props for data flow whenever possible.
