### ISSUE TITLE
Change the github issue labeling to show issues that have already been claimed 

### ISSUE THREAD

**Issue by tchaffee** [facebook/react#9482]
Not an issue with React, but more a workflow issue for github and the issue tracking workflow. For example, there are plenty of issues labeled `Difficulty: beginner` but when looking through those issues many of them have already been claimed for someone to work on, or in many cases a PR has already been submitted. After digging through a half dozen issues like this, one just tends to give up. It would be helpful to be able to see only issues that are still truly looking for contributors.

**Comment by Calyhre** [comment]
Why not using the built-in assignee feature of Github? You can filter out assigned issues.

**Comment by tchaffee** [comment]
@Calyhre That's a good suggestion in theory, and something I didn't know about. Unfortunately looking at the first three issues at https://github.com/facebook/react/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22Difficulty%3A%20beginner%22%20no%3Aassignee shows people who have already volunteered and opened PRs in some cases. Maybe it's a matter of better discipline in assigning people to issues as soon as they volunteer?

**Comment by aweary** [comment]
> Why not using the built-in assignee feature of Github? You can filter out assigned issues.

Unfortunately, Github doesn't let you assign issues to non-collaborators.

We could add two additional labels, `claimed` and `hasPR`, which is what the Babel repo does. Would that solve this issue for you?

**Comment by laumair** [comment]
@aweary :+1:

**Comment by gaearon** [comment]
Yes, that's what I wanted. I also think "beginner" was a misnomer (based on some discussion on Twitter)—I stopped using that in my repos in favor of "starter" issue. Even if something is a good place to start, "beginner" implies beginner should always be able to do it which is not universally the case.

**Comment by aweary** [comment]
@gaearon is this something you need to get approved internally? I can just create the labels and close this if not.

**Comment by gaearon** [comment]
Not really, please feel free to make them!
In my experience the system we use at https://github.com/facebook/react-devtools works well.

**Comment by gaearon** [comment]
(But Babel system works for us too—let's just make sure they are stylistically similar to existing names, and that we update any links that need updating.)

**Comment by gaearon** [comment]
Done it.
