### ISSUE TITLE
Feature Request: dangerouslySetInnerHTML as a return value

### ISSUE THREAD

**Issue by iamdustan** [facebook/react#9483]
I haven’t fully thought through this yet, so hoping for some feedback on whether it is viable or breaks too many assumptions.

The goal is to create an escape hatch that would support rendering to conditional comments, alternative method for web components, and other unknown and probably bad ideas.

Something along the lines of:

```jsx
const DangerousComment = ({children}) => ({
  dangerouslySetInnerHTML: {__html: `<!-- ${children} -->` }
});

ReactDOMServer.renderToString(
  <head>
    <DangerousComment>
      {"[if lte IE 9]><script src='/public/media.match.js'></script><![endif]"}
    </DangerousComment>
  </head>
); // <head><!--[if lte IE 9]><script src='/public/media.match.js'></script><![endif]--></head>
```

```jsx
const WebComponent = ({children}) => ({
  dangerouslySetInnerHTML: {__html: `<!-- ${children} -->` }
});
ReactDOM.render(() => (
  <WebComponent>`
    <app-toolbar arbitary-prop="sure-y-not">
      <div main-title>Web Components!</div>
    </app-toolbar>
  `</WebComponent>
), document.body.firstChild);
```

The first example is the one I’m more interested at this point in time. The benefit here is this could work on both the DOM and server renderer without userland hacks like https://nemisj.com/conditional-ie-comments-in-react-js/ or `componentDidMount` ref replacement (client only, I believe?).

A couple initial problems I see with this are (may or may not be solvable/avoidable with slight tweaks):

* returning an arbitrary object `render` which isn’t supported
* how will unmounting this work?

Alternative proposal:

Introduce a new DOM-renderer primitive `<comment />` or `<dangerousComment />` (to follow a similar approach to `dangerouslySetInnerHTML` clearly indicating the caveats that come with rendering comments). This alternative solution only solves the conditional comment issue above.

**Comment by zomars** [comment]
This is still a valid issue and we cannot use `div` inside `head` tags.

**Comment by yairEO** [comment]
please someone save this issue from getting lost..
