### ISSUE TITLE
props[register name]

### ISSUE THREAD

**Issue by gopisupreme** [facebook/react#9492]
fetchData() {
    let data = {
            method: 'POST',
            body: JSON.stringify({
                 Token:"KWXaDOyG1EgAAAAAAAAAAAAAAAAAAAAA",
                LanguageId:"2"
            }),
            headers: {
                'Accept':'application/json',
                'Content-Type': 'application/json',
            }
        }
        fetch('http://demo.traineri.com/api/ClientAPI/SupplementsList', data)
     
      .then((responseData) => {
        var react=JSON.parse(responseData._bodyInit)
        

for(i=0;i<reactdemo.length;i++)
{
  react.SupplementList[i].Quantity='1';
  react.SupplementList[i].CartDetailId=i;

}
reactdemo=react.SupplementList;
  this.setState({
          dataSource: this.state.dataSource.cloneWithRows(reactdemo),
          loaded: true,
        });

      })
      .done();
  }
  render() { 
    return (
      <Image  source={require('./../../public/images/BgiPhone@3x.png')} style={styles.Maincontainer}>
      <View style={styles.header}>
      <View style={styles.headersubcontainer}>
      <View style={styles.headerBackArrow}>
      <TouchableOpacity onPress={() => {this._back()}}>
           <Image  source={require('./../../public/images/BackArrow@3x.png')}/>
           </TouchableOpacity>
       </View>
       <View style={styles.headerTrainerimage}>
                <Image  source={require('./../../public/images/LogoNameiPhone@3x.png')}/>
        </View>
<View style={styles.headerCart}>
 <TouchableOpacity onPress={() => {this._cart()}}>
           <Image  source={require('./../../public/images/CartBottomiPhone@3x.png')}/>
           </TouchableOpacity>
       </View>
        </View>
      </View>
      <View style={styles.nofooterContainer}>
          <View style={styles.subheader}>
          <View>
          <Image  source={require('./../../public/images/SupplementriesiPhone@3x.png')}/>
          </View>
          <Text style={styles.subheaderText}>Supplements</Text>
          </View>
<View>
        <ListView style={styles.listView}
        dataSource={this.state.dataSource}
        renderRow={(reactdemo) => 
          <View style={{backgroundColor:'#222222',marginBottom:5,flex:1,marginLeft:10,marginRight:10,flexDirection: 'row'}}>
      <View style={{flex:0.1}}>
      
        <Image
          source={{uri: reactdemo.ImageURL}}
          style={{width:50,height:70,margin:10,borderWidth:2,borderColor:'#f2f2f2'}}></Image>     
      </View>
      <View style={{flex:0.2,paddingLeft:15}} >
      <Text style={{color:'#fff',paddingTop:10}}>{reactdemo.Name}</Text>
        <Text style={{color:'#fff'}}>KD {reactdemo.Price}</Text>
        <View>
        <Text style={{color:'#ccc',fontSize:12}}>{reactdemo.NetWeight} kg</Text>     
        </View>
      </View>
      <View style={{flex:0.2,flexDirection: 'row',top:45}} >
      <Text style={{color:'#ccc',fontSize:12}}>Qty :</Text>
    <View style={{borderWidth:1,borderColor:'red'}}>
       <TouchableOpacity onPress={() => {this.pickuptwo("1",reactdemo.CartDetailId)}}>
      <Image style={{width:20,height:20,marginLeft:10}} source={require('./../../public/images/MinusiPhone@3x.png')}/>
      </TouchableOpacity>
    </View>
        <Text style={{color:'#ccc',marginLeft:7}}>{reactdemo.Quantity}</Text>
      <View style={{borderWidth:1,borderColor:'red'}}>
      <TouchableOpacity onPress={() => {this.pickuptwo("0",reactdemo.CartDetailId)}}>
      <Image  style={{width:20,height:20,marginLeft:10}} source={require('./../../public/images/Plus1iPhone@3x.png')}/>
      </TouchableOpacity>
      </View>
      </View>
      </View>
        }
        />
      </View>      
      </View>
      </Image>

when i click to the "{reactdemo.Quantity}" it appears the error msg like " 
![output](https://cloud.githubusercontent.com/assets/26139405/25302102/19355d54-2754-11e7-9664-60d1eba8093f.png)
"

**Comment by aweary** [comment]
We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

Also, it looks like you're using React Native. This repo is specifically for React core.

**Comment by shukerullah** [comment]
any updated on this issue?
