### ISSUE TITLE
yarn prettier runs a too long command for OS windows

### ISSUE THREAD

**Issue by lamo2k123** [facebook/react#9500]
CLI `yarn prettier` return error too long command.

The problem is only on windows OS. Checked on windows 10 x64 CLI cmd

**Comment by gaearon** [comment]
Thanks for reporting. Not sure how to fix this 😞

**Comment by lamo2k123** [comment]
Use the Node API instead of the CLI API

**Comment by gaearon** [comment]
Good point. Want to send a PR?

**Comment by gaearon** [comment]
See comment in https://github.com/facebook/react/pull/9523#issuecomment-297492838 for proposed solution.

**Comment by gaearon** [comment]
@xjlim Wanna do this one too? Needs the same approach.

**Comment by xjlim** [comment]
@gaearon sure, I will give it a try.
