### ISSUE TITLE
[RFC] Add traversal utility to ReactTestUtils matching toTree shape

### ISSUE THREAD

**Issue by aweary** [facebook/react#9505]
### Problem

The `ReactTestRenderer` now supports a new API, [`toTree`](https://github.com/facebook/react/blob/master/src/renderers/testing/ReactTestRendererFiber.js#L350-L355), which returns an easily traversed tree representing the internal state of the instance and its rendered nodes.

The existing solution for this in `TestUtils` is `findAllInRenderedTree` which traverses the root and lets you provide a test function it will call to reduce a tree based on a predicate. The predicate function is passed the public instance for the node.

The issue with that is that it makes the predicate function polymorphic and requires every consuming utility to check if it's being passed a component instance or a DOM node. 

### Solution

I propose that we implement a new API similar to `findAllInRendererdTree` that calls the predicate function with the result of calling `toTree` on the internal instance instead of the public instance. This would mean:

* the predicate function will always be called with the same data structure (a tree node)
* third-party traversal utilities can be shared between `ReactTestRenderer` and `ReactTestUtils`, since they would operate on the same tree structure
* You could actually assert on functional components, which currently have no instance and just call the predicate with `null`

This new API could just be a pure traversal utility, leaving it up to the consumer to accumulate results.

```js
import { renderIntoDocument, traverseTree } from 'react-dom/test-utils';
var root = renderIntoDocument(<App />);
var results = [];
traverseTree(root, node => {
  if (somePredicate(node) { results.push(node) }
})
```
 
## Implementation

With a brief review, it looks like we could just export the `toTree` function that is currently inlined in `ReactTestRenderer` and provide a way to change:

```js
 var publicInst = node.stateNode;
      if (test(publicInst)) {
        ret.push(publicInst);
      }
```

to:
```js
 var treeNode = toTree(node);
      if (test(treeNode)) {
        ret.push(treeNode);
      }
```

cc @gaearon @bvaughn @lelandrichardson

**Comment by aweary** [comment]
For context, I have a [utility](https://github.com/aweary/react-tester/blob/master/src/selector-parser.js) that can find nodes in a tree based on any CSS selector. If `ReactTestUtils` provided a similar API it could easily be used with test utils as well.

**Comment by aweary** [comment]
I'm happy to implement this, if I can can get some feedback on the idea 🙃

**Comment by sebmarkbage** [comment]
Crazy idea: Lets maintain a completely separate implementation of React's reconciliation specifically for tests. That way it can just expose its entire internals.

The more of these introspection tools we build, the harder it is to maintain optimizations that throw away state in Fiber.

I'd like to be able to completely remove the Fibers from the internal tree for functional components so ability to inspect them would need to have a separate path anyway. So ReactTestUtils can't share the exact implementation with ReactDOM anyway.

**Comment by aweary** [comment]
> Crazy idea: Let's maintain a completely separate implementation of React's reconciliation specifically for tests. That way it can just expose its entire internals.

What would that look like? How much of the reconciliation code could be reused? Providing more low-level APIs for testing utilities to consume sounds useful.

**Comment by aweary** [comment]
That also sounds like a long-term goal. I was hoping to improve the testing story for React 16. With the current API, third party utilities like Enzyme will still have to rely on accessing internal properties to support a traversal API.
