### ISSUE TITLE
Debug issue in react-native android app, Crash befor landing activity

### ISSUE THREAD

**Issue by HamzaDevZubair** [facebook/react#9509]
I am using:
react-native-cli: 2.0.1
react-native: 0.35.0

I am having two issues in react-native.
1- when app launch it work properly. befor landing screen of paypal, app got crash.

![after checkout](https://cloud.githubusercontent.com/assets/27667777/25340657/e44ff630-291f-11e7-98bb-09b96806e07d.PNG)

2- When I try debug my app it's give me error 

![debugger error](https://cloud.githubusercontent.com/assets/27667777/25340704/fdf6f494-291f-11e7-8ce9-22ceb3934362.PNG)

**Comment by aweary** [comment]
Hey @HamzaDevZubair! This repository is for React itself, not React Native, which has [its own repository and issue tracker](https://github.com/facebook/react-native) 👍

**Comment by HamzaDevZubair** [comment]
Thanks for your reply, I found my solution
