### ISSUE TITLE
Why provide different value of 'this' keyword for onChange event handler and other event handlers like onBlur , onClick etc ?

### ISSUE THREAD

**Issue by nikhilgoyal104** [facebook/react#9520]
React binds the 'this' keyword of event handler functions to 'null' explicitly. But what I have noticed is, it calls the function associated with 'onChange' event with 'this' as  'undefined' .For other events such as 'onClick' , 'onBlur' the value of 'this' is bound to 'null' as usual. But there is no extra call to make 'this' as 'undefined' in the associated handler function. What could be the reason for this ? Is this a bug ? . Although both 'null' and 'undefined' are not of any use to the developer as we have to bind it explicitly.

Here's the link for the code on jsfiddle :

https://jsfiddle.net/nikhilgoyal104ah4/69z2wepo/76915/

**Comment by gaearon** [comment]
I’m confused why `this` is `null` in your example. I wouldn’t expect this.
Do you want to follow the stacktrace and look into why it happens?
Might be a bug (even though it’s not important).

**Comment by nikhilgoyal104** [comment]
Yes I followed the stacktrace. So before every handler function is called it is bind to 'null' . The corresponding file where this happens is ReactErrorUtils.js. Line 61 onwards. In the case of onChange, in addition to ReactErrorUtils.js another file is involved named LinkedValueUtils.js which checks explicitly for onChange in props and calls it with 'undefined'. I am providing the corresponding code snippets from these files.

ReactErrorUtils.js

if (process.env.NODE_ENV !== 'production') {
  /**
   * To help development we can get better devtools integration by simulating a
   * real browser event.
   */
  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof document !== 'undefined' && typeof document.createEvent === 'function') {
    var fakeNode = document.createElement('react');
    ReactErrorUtils.invokeGuardedCallback = function (name, func, a) {
      var boundFunc = func.bind(null, a);
      var evtType = 'react-' + name;
      fakeNode.addEventListener(evtType, boundFunc, false);
      var evt = document.createEvent('Event');
      // $FlowFixMe https://github.com/facebook/flow/issues/2336
      evt.initEvent(evtType, false, false);
      fakeNode.dispatchEvent(evt);
      fakeNode.removeEventListener(evtType, boundFunc, false);
    };
  }
}

LinkedValueUtils.js -- here it explicitly checks for onChange in the input props.

executeOnChange: function (inputProps, event) {
    if (inputProps.valueLink) {
      _assertValueLink(inputProps);
      return inputProps.valueLink.requestChange(event.target.value);
    } else if (inputProps.checkedLink) {
      _assertCheckedLink(inputProps);
      return inputProps.checkedLink.requestChange(event.target.checked);
    } else if (inputProps.onChange) {
      return inputProps.onChange.call(undefined, event);
    }
  }
};

In the last line it does ".call(undefined, event)"

So my point is why we want it has been implemented in a different way for onChange. Shouldn't the behaviour be uniform for all event handler functions ?

**Comment by gaearon** [comment]
I see. I think `undefined` actually makes sense here (`this` is supposed to be `undefined` when it’s not specified).

It’s `var boundFunc = func.bind(null, a);` that is confusing to me (and this is what gave you `null`). It does seem like this is [fixed on master](https://github.com/facebook/react/blob/d12c41c7a67f92fd8f6c5f3b9cbf371975bf5830/src/renderers/shared/utils/ReactErrorUtils.js#L47-L49) though.

**Comment by nikhilgoyal104** [comment]
But why react binds the 'this' keyword to 'null' in the first place for event handlers ? Could you clarify on that ?

**Comment by gaearon** [comment]
It shouldn’t, really. (I think.)
That’s why I’m saying this surprised me. But I like I said, it doesn’t seem to do this on master.

**Comment by nikhilgoyal104** [comment]
But this behaviour still seems to be there in the latest version of React .

**Comment by gaearon** [comment]
Master is not released yet. But you can try `react@next` and `react-dom@next` if you’d like to confirm.

**Comment by aweary** [comment]
[Here's a JSFIddle](https://jsfiddle.net/t3r9on4v/) showing this is fixed in the latest React 16 alpha release.
