### ISSUE TITLE
Question: Close ReactJS widget on outside click

### ISSUE THREAD

**Issue by amihaiemil** [facebook/react#9521]
I have a search widget on a website -- it is a standalone react component, the user just puts the script on the site and the box is rendered.

See it at http://www.amihaiemil.com

When a search is performed (e.g. "test"), the results are shown right below the input box. I want to close the search results if the user clicks outside of the widget (anywhere else on the page). But I don't know how to achieve this because the react component doesn't "know" anything about the rest of the page. And also, I cannot just hide the div with jquery, right? Because then I ruin React's virtual dom mechanism?

**Comment by amihaiemil** [comment]
@jquense Maybe you can help? :D

**Comment by jquense** [comment]
React itself doesn't easily lend itself to adding such an event, but it's possible to do in a component. [react-overlays](https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js) has a 'RootCloseWrapper" that responds to clicks outside itself. We use it in overlays and dropdown menu's in react-bootstrap

**Comment by amihaiemil** [comment]
I see. I'll look into it, thanks :)

**Comment by zodiac** [comment]
I've had success using https://github.com/gajus/react-outside-event for this.

**Comment by amihaiemil** [comment]
@zodiac thanks, it also did the trick for me :D
