### ISSUE TITLE
what does total time mean? in console log the total time is less than the sum of the time print by printInclude function

### ISSUE THREAD

**Issue by wNee** [facebook/react#9524]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Radi123** [comment]
@wNee I think have a answer, but I'm not sure at all.
Please send screenshot (total time in the console log)...
I'm waiting for screenshot soon... 

I want @gaearon to review this, too.
Goodbye for now.

**Comment by wNee** [comment]
![image](https://cloud.githubusercontent.com/assets/27800444/25395694/829d0824-2a14-11e7-90c3-826fadacac17.png)
![image](https://cloud.githubusercontent.com/assets/27800444/25395700/859a61fc-2a14-11e7-9538-edc0d6810dab.png)
  I use react perf start(), react perf stop(), printInclude(). I found that total time is less than first component time.  why? I don`t understand the relationship between these cost time of components and total time.

**Comment by gaearon** [comment]
It's including time spent in the library, which is more than time in your components.
