### ISSUE TITLE
`<select multiple>`: don’t demand `onChange` if there is `onMouseDown`

### ISSUE THREAD

**Issue by rauschma** [facebook/react#9541]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** React warns you to add `onChange` to `<select multiple>`, even if there is `onMouseDown` (the child options having `onMouseDown` should also be enough!).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** https://jsfiddle.net/4zy2esnn/

**What is the expected behavior?** There should *not* be the following warning.

> Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `App`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Observed in 15.4.2. I’m assuming all versions of React are affected.

**Comment by Hypnosphi** [comment]
How do you support selecting options with keyboard?

**Comment by pete-otaqui** [comment]
I agree with @Hypnosphi, `onMouseDown` is not enough to cover `onChange`, since not all changes have to come from interacting with the mouse.

**Comment by aweary** [comment]
I agree as well. `onChange` encompasses more than just mouse events, and includes normalizations for browser consistency. I think it's best to leave the warning in this situation.

Thanks for taking the time to submit this issue though @rauschma!
