### ISSUE TITLE
React app not compatible with facebook browser

### ISSUE THREAD

**Issue by BG687** [facebook/react#9543]
When I shared my React site on facebook, the link does not work on facebook's mobile app. It works in any non-facebook browser though, such as Safari, Chrome, etc. 

The error says 'Can't Connect. Link is not working.' 

We have the proper og meta tags, such as og:url, og:title, og:image, etc. Is there something wrong with our site's configuration? Any ideas? 

Thanks a lot, this is a very knowledgeable group and we would appreciate any insight. 

![screen shot 2017-04-27 at 9 33 11 am](https://cloud.githubusercontent.com/assets/19270780/25485712/d1f1b802-2b2c-11e7-8b16-2f02b21f2576.png)

**Comment by gaearon** [comment]
This is a React issue tracker. Are you convinced the problem is specific to React?

**Comment by BG687** [comment]
Hi @gaearon, thanks for the quick response. 

We're not sure, but, as far as I know, there is no way to debug the issue in the facebook browser -- there is no console to print to. 

It's a simple react-redux-webpack app (you can see it [https://www.cohab.it/]) and there is not much  to it that could be causing this issue. We were wondering if other React developers have had the same issue. 

Any suggestions would be appreciated.

**Comment by BG687** [comment]
Fixed, it wasn't a react issue.

**Comment by gaearon** [comment]
Cool! Mind sharing what was causing it if it’s not a secret?
