### ISSUE TITLE
Using node module with react native

### ISSUE THREAD

**Issue by rakibtg** [facebook/react#9551]
As mentioned [here][1] that, 

> Any modules that are pure javascript and run within node.js/io.js are perfectly OK to be run in react-native.

I need to resize and crop an image in react native so i was trying the nodejs [sharp][2] image processing library and i think it should work with reactnative because its in pure node and working with io things.

But while installing it throws errors:

    PS D:\ReactNative\f_sandbox> npm install sharp

    > sharp@0.17.3 install D:\ReactNative\f_sandbox\node_modules\sharp
    > node-gyp rebuild

    D:\ReactNative\f_sandbox\node_modules\sharp>if not defined npm_config_node_gyp (node "G:\Installed\Node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
    es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
    MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
    l Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\ReactNative\f_sandbox\node_modules\sharp\build
    \binding.sln]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (G:\Installed\Node\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    gyp ERR! System Windows_NT 10.0.15063
    gyp ERR! command "G:\\Installed\\Node\\node.exe" "G:\\Installed\\Node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd D:\ReactNative\f_sandbox\node_modules\sharp
    gyp ERR! node -v v6.9.2
    gyp ERR! node-gyp -v v3.4.0
    gyp ERR! not ok
    npm ERR! Windows_NT 10.0.15063
    npm ERR! argv "G:\\Installed\\Node\\node.exe" "G:\\Installed\\Node\\node_modules\\npm\\bin\\npm-cli.js" "install" "sharp"
    npm ERR! node v6.9.2
    npm ERR! npm  v3.10.9
    npm ERR! code ELIFECYCLE

    npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the sharp package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs sharp
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls sharp
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\ReactNative\f_sandbox\npm-debug.log

Is there any fix for this/ whats missing here?

Also on [Stackoverflow](http://stackoverflow.com/questions/43672347/using-node-module-with-react-native)

  [1]: http://stackoverflow.com/a/32293274/981586
  [2]: https://github.com/lovell/sharp

**Comment by aweary** [comment]
It looks like `sharp` uses [libvips](https://github.com/jcupitt/libvips), which is a native C/C++ module. Could that be the problem?

Also, this is the issue tracker for React core. React Native has [its own issue tracker](https://github.com/facebook/react-native). Since this sounds like a usage question I recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/) or [discuss.reactjs.org](https://discuss.reactjs.org/)!

**Comment by DovletAmanov** [comment]
I had same issue, this error was given when I tried to install socket.io in react native, then I used Bash on windows and finally could install package.

**Comment by RuiMRodrigues** [comment]
You had this problem ? sharp.node is in that folder... makes no sente

![teste](https://user-images.githubusercontent.com/6662292/31438919-1ff64fee-ae82-11e7-8cd5-5cb4344108eb.png)
