### ISSUE TITLE
Provide better error for: "Error: Objects are not valid as a React child (found: object with keys.."

### ISSUE THREAD

**Issue by rajaraodv** [facebook/react#9552]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Currently if we by mistake pass a JS object to JSX instead of a string, then we get the following error:
 "Error: Objects are not valid as a React child (found: object with keys.."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
Show a better error that helps solve the issue like in this SO solution.
http://stackoverflow.com/questions/36100702/invariant-violation-objects-are-not-valid-as-a-react-child-for-nested-objects
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
Can you propose a specific wording that would be better?

**Comment by aweary** [comment]
We haven't heard many complaints about this error, and the wording seems to be clear enough. Plus, it gives you a list of keys and a component stack trace so I think this is clear enough unless we here more specific feedback about it.
