### ISSUE TITLE
Presedence is given to child component props

### ISSUE THREAD

**Issue by amjoshi91** [facebook/react#9564]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Button colours are being defined by the ones that are passed in and not by the ones given by definition

**What is the expected behavior?**
```
<Button.Group color="green">
  <Button color="blue" />
  <Button />
  <Button />
  <Button />
  <Button />
</Button.Group>
```

I want the first button to have the colour blue and the rest of them to be green. But that doesn't happen. My idea is to create a group colour for the parent for default could and then if needed specifying colours for each component afterwards where needed

**Comment by aweary** [comment]
Hey @amjoshi91, are you using a specific library that provides a `Button` component? This should be doable using context, which is a common choice for theming. [Here's a small example](https://jsfiddle.net/5sq5an4h/) showing how you can accomplish that.

If you're asking about a specific UI library, you're better off asking in their issue tracker or support forums.

**Comment by amjoshi91** [comment]
I'm using React.cloneElement

**Comment by milocosmopolitan** [comment]
Hello @amjoshi91, I assume that you've created two React Components. I'm not sure if I'm understanding it correctly but you could do this
`
export default class ButtonGroup extends React.Component {
  render(){
    return (
      <div>
      { 
         this.props.children.length && React.Children.map(this.props.children, child => {             
             var childProps = Object.assign({}, child.props);
             if (!childProps.color) childProps.color = this.props.color
             return React.cloneElement(child, childProps);
         })
      }
      </div>
    )
  }
}
`

**Comment by aweary** [comment]
Yeah, you can use `cloneElement` to provide "default" props to children as demonstrated above. Context is frequently used for theming by popular UI libraries. It's technically an unstable API, so consider that before using it, but it does provide a good abstraction for this use case.

This issue tracker is meant for bug reports and feature requests, so if you have additional support or usage questions we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

Feel free to continue the current discussion here though if you have any clarifying questions!
