### ISSUE TITLE
Getting warning about stroke-linecap value

### ISSUE THREAD

**Issue by pencilcheck** [facebook/react#9566]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Shows warning to strokeLinecap with value "butt" when it shouldn't be because it is part of the spec
[link](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap)

```Warning: Failed prop type: Invalid prop `strokeLinecap` of value `butt` supplied to `Progress`, expected one of ["round","square"].```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
Create a path with strokeLinecap, and pass in "butt" in the value. It will show the warning.

**What is the expected behavior?**
It shouldn't show the warning.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.5.4

**Comment by aweary** [comment]
The warning you're getting is a PropType warning, which indicates you're likely using a third party component that has a PropType definition for `strokeLinecap` that restricts it to round or square. You can [see here](https://jsfiddle.net/hbuyc9b1/) that React doesn't warn for `butt`.

Are you using an SVG React library that provides a `Path` component?

**Comment by gaearon** [comment]
Seems like the issue is here: https://github.com/react-component/progress/issues/14.
It’s not an issue with React.
