### ISSUE TITLE
"Error boundary" text is not clear

### ISSUE THREAD

**Issue by darknoon** [facebook/react#9571]
**Error text enhancement request**

**What is the current behavior?**

When an exception is thrown, something like this is printed:

```
React caught an error thrown by <REDACTED>. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.

TypeError: undefined is not an object (evaluating 'flags.<REDACTED>')

The error is located at: 
   <REDACTED>
    in Editor (created by Connect(Editor))
    in Connect(Editor) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

The error was thrown at: 
```

It's not clear what an "error boundary" is. It would be great to link to a docs page that describes what this is and how to do it.

I googled "react error boundary" and ended up with no clear answers in the top few hits.
https://www.google.com/search?client=safari&rls=en&q=react+error+boundary&ie=UTF-8&oe=UTF-8

**Comment by darknoon** [comment]
Seems related to the discussion in https://github.com/facebook/react/issues/2461 , but I'm not able to extract anything actionable from it.

**Comment by gaearon** [comment]
Where do you get this message? It is not meant to be in any stable release. If you are using 16 alpha releases, then please be prepared that some pieces are not in place yet, including docs for any new features.

**Comment by darknoon** [comment]
@gaearon I used `react-native init` to create the react native app structure, then I merged it back into my web project. It seems the latest version of react native depends on a beta version of react?

I tried to downgrade my react-native version but then the Xcode project stopped working.

**Comment by gaearon** [comment]
Oh, I see. I didn’t realize this particular error message was displayed with the old reconciler (which RN still uses). We should get it fixed, but for now please ignore the part about error boundaries, as this feature is not available in RN yet.

**Comment by darknoon** [comment]
@gaearon I should have mentioned here are my versions:

    "react": "16.0.0-alpha.6",
    "react-dom": "^15.5.4",

Is this a bad config to run in?

**Comment by gaearon** [comment]
No, this is fine. (The 'alpha' version of the `react` package is not really relevant because it contains very little code. Don't worry about it.)

I'm still confused where this message gets printed though. Can you provide an exact sequence of steps for me to reproduce this?

**Comment by gaearon** [comment]
In particular I'm confused why you're saying you use RN, but you have a `<div>` there.

**Comment by darknoon** [comment]
@gaearon I'm trying to do a universal codebase. The main code is `react`, but `react-native` powers the iOS app, and they have different entry points.

The log in this bug is about the `react-dom` app.

**Comment by gaearon** [comment]
I see. Can you check which version of `react-dom` are you using, just to be sure?
While using `react@16` in RN apps is fine, using `react-dom@16` is not supported right now.

**Comment by darknoon** [comment]
@gaearon ok, I'm interested in downgrading from `react-dom@16` to a supported version, but the same version must be used with `react-native` as well since they have the same `package.json`. Could you advise me on a working tuple of compatible (`react-native`, `react`, `react-dom`) versions? 

I tried downgrading to `react-native` v0.42, but then I had this warning output:
```
warning "react-native@0.42.3" has incorrect peer dependency "react@~15.4.1".
```

I tried specifying that I wanted react `^15.4.1`, but it `yarn` ended up installing `15.5.4` anyway:

from the yarn.lock:
```
react@^15.4.1:
  version "15.5.4"
  resolved "https://registry.yarnpkg.com/react/-/react-15.5.4.tgz#fa83eb01506ab237cdc1c8c3b1cea8de012bf047"
  dependencies:
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.7"
```

Is there something messed up with my workflow or what?

**Comment by gaearon** [comment]
We have since added a link to the blog post explaining error boundaries.

**Comment by piyushkathayat** [comment]
Hi @gaearon, I am not sure if it´s a react issue or not but I am struggling a lot with this issue. 

https://codepen.io/as3script/pen/VMbNdz?editors=1111

I tried to create just a simple example to post out of my project. 

There are three 4 buttons on the example. 

Create 1 text input from each button and enter a value. 

for example, enter 100 in first, 200 in second and 300 in third.

Now remove first input. 

It should display second and third with 200 and 300. but it´s showing second = 100, third 200.

Thanks in advance

**Comment by gaearon** [comment]
This doesn't sound related to this issue, is it?

If it's just a question about React please ask it on StackOverflow or the community resources linked from the docs.

**Comment by gaearon** [comment]
(Your issue is likely because you're using indexes and keys. The "Lists and Keys" page in the documentation mentions that this isn't usually a good idea, and you should use unique IDs as keys instead.)

**Comment by piyushkathayat** [comment]
Thanks for your quick and prompt suggestion. I will use unique ID´s will go through documentation page. 

Thanks and have a nice time.
