### ISSUE TITLE
[BUG] ref function gets called twice on update (but not on first mount), first call with null value.

### ISSUE THREAD

**Issue by trusktr** [facebook/react#9574]
@gaearon You're [arguing](https://github.com/facebook/react/issues/9328) that `ref` functions need to be called twice (once with `null`) *due to internal implementation details that are insignificant with respect to how end users use React*.

End user don't care how their ref functions are called, just that they work. Honestly having them called twice is strange from a perspective of an end-user who knows nothing about React's internal implementation.

You haven't stated why end users *actually need* to guard against `null` values from duplicate calls to ref functions. It only complicates end-user code.

I would urge for the internal implementation to be modified to stop calling ref functions twice.

**Comment by gaearon** [comment]
I’m happy to continue the discussion in #9328.

However, unless there is something the old issue doesn’t cover, I encourage you not to create duplicate issues as a way to demand attention.

**Comment by aweary** [comment]
Please don't open a duplicate issue just to continue a conversation. Feel free to add your additional comment(s) to your original issue https://github.com/facebook/react/issues/9328
