### ISSUE TITLE
[Fiber] returning functions from render does not throw

### ISSUE THREAD

**Issue by aweary** [facebook/react#9577]
https://jsfiddle.net/3apqnhmw/

```jsx
class Foo extends React.Component {
  render() {
     return <div>Foo</div>
  }
}

class App extends React.Component {
  render() {
    return Foo
  }
}
```

When `App` returns `Foo` instead of `<Foo />` accidentally, Fiber does not catch this.

**Comment by gaearon** [comment]
Looks like a bug. Why does it happen?

**Comment by aweary** [comment]
It looks like `reconcileChildFibers` does [some minimal validation](https://github.com/facebook/react/blob/28bc8860bc259febd835f061c7b5230c5ac9365a/src/renderers/shared/fiber/ReactChildFiber.js#L1327-L1333) behind the `disableNewFiberFeatures` flag, but with the latest alpha release, those paths aren't hit since it's `false` and none of those check if `nextChild` is a function anyways.

So for this issue, it seems like there need to be more strict checks on the return value of `render`.

It does also [check for `undefined`](https://github.com/facebook/react/blob/28bc8860bc259febd835f061c7b5230c5ac9365a/src/renderers/shared/fiber/ReactChildFiber.js#L1384-L1412) but it will actually crash if you try to return `undefined`, which seems like another issue. Try changing `return Foo` to `return undefined` in the example above and it will crash the tab.

**Comment by aweary** [comment]
_Warning, the link below will cause an infinite loop and might crash the tab/browser_

____

@gaearon [Here's an example](https://jsfiddle.net/zcxfjghj/) showing that returning `undefined` will cause an infinite loop. And a screenshot showing the endless barrage of errors:

<details>
<summary>Screenshot</summary>
![screen shot 2017-05-01 at 5 46 17 pm]
(https://cloud.githubusercontent.com/assets/6886061/25597785/758eb908-2e96-11e7-90a1-c1c14750cb00.png)
</details>
<br />

I can open a separate issue for this if you'd like.

**Comment by gaearon** [comment]
The infinite loop is probably https://github.com/facebook/react/issues/9193 or https://github.com/facebook/react/issues/9092.

**Comment by aweary** [comment]
Got it, thanks. As for the function issue, I think this would be fixed if those invariant checks in `ReactChildFiber` were moved out of a `disableNewFiberFeatures` block, or added to the correct code path if this warning should be done elsewhere now.

**Comment by acdlite** [comment]
Right now we treat unknown types as empty. We have a special case for `undefined` since it's almost always a bug. I don't think we decided what we'll do for other unsupported values. We can either warn and treat as empty, or throw.

**Comment by acdlite** [comment]
One disadvantage to throwing versus warning is that it requires an extra check in production, for null.

**Comment by aweary** [comment]
I think using just a warning would make it too easy for components to silently fail. Existing behavior is to throw as well. [The validation logic](https://github.com/facebook/react/blob/28bc8860bc259febd835f061c7b5230c5ac9365a/src/renderers/shared/fiber/ReactChildFiber.js#L1310-L1349) is already in the bundle, it's just dead code right now. Can we safely move it outside of the `disableNewFiberFeatures` check?

**Comment by HoumanKml** [comment]
I was actually about to ask if we could make this type of render work? I have various components (Foo, Goo, Hoo, etc.) that I need to conditionally render. Right now I use `switch` :

```
class Foo extends React.Component {
  render() {
     return <div>Foo</div>
  }
}

class Goo extends React.Component {
  render() {
     return <div>Goo</div>
  }
}

class Hoo extends React.Component {
  render() {
     return <div>Hoo</div>
  }
}

class App extends React.Component {
  render() {
  	console.log(Foo);
    switch (this.props.whatToRender) {
      case Foo: return <Foo />;
      case Hoo: return <Hoo />;
      default: return <div>No match</div>;
		}
  }
}

ReactDOM.render(<App name="world" whatToRender={Foo}/>, document.getElementById('container'));
```

if `render () { return Component }` would work, instead I could use the map method on the components array:
```
// whatToRender = Foo;
components = [Foo, Goo];
render() { return components.find(component => component === whatToRender) }
```

**Comment by gaearon** [comment]
@HunderlineK You can just wrap it in `React.createElement()` for the same effect.

**Comment by gaearon** [comment]
I made a list of different things which I *think* we should (dis)allow as return values.
It's based on what we did in 15, but with added support for numbers/strings/arrays.

```
            return value        child

string      yes                 yes
number      yes                 yes
element     yes                 yes
array       yes                 yes
iterable    yes                 yes
null        yes (ignored)       yes (ignored)
false       yes (ignored)       yes (ignored)
true        no*                 yes (ignored)
undefined   no                  yes (ignored)
function    no*                 yes (ignored)
symbol      no*                 yes (ignored)
object      no                  no
```

The ones with asterisk are the ones we currently silently skip (but used to error on). IMO we should at least warn about them. Need to evaluate how many more conditions this would add.

If it’s not cheap then let’s at least warn. But it doesn’t seem like a big deal to check `typeof` once.

**Comment by gaearon** [comment]
Since `true` seems harmless, and `symbol` seems rare, looks like the actionable item here is just to warn on `function`. Whether as a host child (of a `div`) or as a return value.

**Comment by gaearon** [comment]
https://github.com/facebook/react/pull/10376
