### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by zhuyinjing** [facebook/react#9581]
when i `npm install openseadragon-annotations`
and i use `import 'openseadragon-annotations'`in my project
and its show error in chrome console
`Uncaught TypeError: Super expression must either be null or a function, not undefined`
how should  i do ?
thanks everyone!!!

**Comment by gaearon** [comment]
Sorry, but this is an issue tracker for React. If you have an issue with `openseadragon-annotations`, please file it in the appropriate repository. Thanks!
