### ISSUE TITLE
Examples and Articles in Wiki are outdated/unmaintained

### ISSUE THREAD

**Issue by hriziya** [facebook/react#9583]
I was referring to the Example and came to the page [https://github.com/facebook/react/wiki/Examples](https://github.com/facebook/react/wiki/Examples)  but It has the link for Example is broken. 

Look at the first point "React starter kit Includes several examples which you can view online in our GitHub repository."

**Comment by gaearon** [comment]
Thanks for flagging. Nobody’s really maintaining those Wiki pages, and there’s a lot of stuff there that is outdated, or just plain not recommended. I’ll try to find some good examples and put them there instead.

**Comment by gaearon** [comment]
I deleted the broken link.

But there's a bigger issue of those pages looking official but being completely abandoned. I wonder if someone from the community would be up for taking care of them.

cc @mrscobbler @markerikson @tylermcginnis Would you be interested in helping out? I think we should prune Examples, Articles, and other wiki pages of the outdated, or overly complicated repos, and add good beginner and mid-level content there. As long as it’s free (we can add a separate section for paid content too if it has high quality).

**Comment by mrscobbler** [comment]
I'm on it!

**Comment by tylermcginnis** [comment]
Of course.

**Comment by gaearon** [comment]
I think they're in a better place now.
