### ISSUE TITLE
input type="number" -> decimal number support

### ISSUE THREAD

**Issue by destromas1** [facebook/react#9585]
Need suggestions / probably Bug

```
<PDInputWrapper controllerId="pdNumeric" labelText={props.label} meta={props.meta}
                        tooltip={props.tooltip}>
            <InputGroup>
                <FormControl type="number" step={0.1} value={props.input.value}/>
       </InputGroup>            
</PDInputWrapper>
```

I tried ```<input type="number" className="form-control" step="0.1" ``` too

I am using `react-bootstrap` and `redux-form` .

I tried step={0.1} or step="0.1"
Does not work

I tried React 15.5.4 , 15.4.0

Posted on here `react-bootstrap` first https://github.com/react-bootstrap/react-bootstrap/issues/2603

Is there any bug here ? Any suggestion ?

**Comment by gaearon** [comment]
cc @aweary @nhunzaker

**Comment by pete-otaqui** [comment]
Seems to work fine with `<input value={val} onChange={onChange} type="number" step="0.1" />`

https://jsfiddle.net/69z2wepo/77586/

**Comment by aweary** [comment]
@destromas1 thanks for the report! Can you clarify what you mean when you said it doesn't work? It's hard to debug if we're not sure what behavior you're expecting, or what behavior you're seeing. As @pete-otaqui showed, `step` *appears* to work fine with decimal values in controlled components.

**Comment by destromas1** [comment]
@aweary 
I meant - When I type any decimal `.` then that field goes blank .

**Comment by aweary** [comment]
Can you share a JSFiddle reproducing the behavior? You can use [this](https://jsfiddle.net/84v837e9/) as a template.  Also, can you verify what version of React you're using, because that sounds like a bug that existed in an older release.

**Comment by aweary** [comment]
Closing out due to a lack of response.

**Comment by tigrente** [comment]
I am also seeing this issue.  Expected behavior is that with this: 
`       <FormControl
                            componentClass={'input'}
                            type={'number'}
                            step={'.01'}
                            min={0}
`
That entering 3.14 would be permitted.  However, it doesn't let me enter anything after the '.'.   It seems to take integers only.

**Comment by tigrente** [comment]
Never mind - for others who might see this, I had a 'parseInt' downstream that was forcing this.  Works great.
