### ISSUE TITLE
Possible for component to listen to events from non-descendent elements?

### ISSUE THREAD

**Issue by ldct** [facebook/react#9593]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Components can only attach event listeners (eg onClick) to their descendent DOM elements. Is there a way for a component to listen to events originating from elements that are not descedents?

The use case I have in mind is, I have a bunch of components (marked out with pink borders in the screenshot below) that control their own state, and I want their state to change if a click happens anywhere in the purple region. I could solve this by moving the state up to the parent (the component that renders the purple div) but that seems to be a consequence of the fact that the event-listening tree is tied to the render tree, not that the components state actually interact at all.

![image](https://cloud.githubusercontent.com/assets/130362/25654804/0eeaf44c-3025-11e7-82af-377dffd71b7a.png)

**Comment by Flaque** [comment]
Forgive me if I don't understand your question, but isn't this the expected mentality of react? 

You should pass data down through props. So your purple parent would have an onClick event, which would change it's state. Then your children elements would have that state be associated with their props. 

Example:

```
class Purple extends React.Component {

  constructor(props) {
    super(props)
    this.state = {purpleClick: false};
  }

  handleClick() {
    this.setState(prevState => ({
      purpleClick: !prevState.purpleClick
    })); 
  }
  
  render() {
    return (
      <div className="purple-rect" onClick={this.handleClick}> 
        <child purpleClick={this.state.purpleClick} />
      </div>
    )
  }
}
```

**Comment by aweary** [comment]
I agree with @Flaque, using a listener on a parent component to control state for the children is likely the best option here. Since the event system is meant to implement the same semantics of the browser's event system, it does not provide a way to listen to events on parent elements.

If you have further usage questions, please refer to [Where to Get Support](https://facebook.github.io/react/community/support.html). Thanks!
