### ISSUE TITLE
Add support for ControlList API's controlList attribute

### ISSUE THREAD

**Issue by amcintyre-cs** [facebook/react#9594]
In version 58, Chrome shipped support for the [HTMLMediaElement ControlList API](https://github.com/WICG/controls-list/blob/gh-pages/explainer.md) and, by extension, the controlList attribute on elements like `video` and `audio`.  [Here's how the attribute looks in practice.](https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist)

React <= 15.5.4 does not support this attribute and strips it out with a `Warning: Unknown prop controlsList on <video> tag. Remove this prop from the element.` warning in the console.

Could you add support for this new attribute? This isn't a pressing issue as it's possible to set the attribute via javascript (i.e. by setting it in a `ref` or in a component lifecycle event), but it would be nice to have it recognized as the valid attribute it is.

**Comment by mikecx** [comment]
Just ran into this today as well but inside a stateless/pure component so the ref/lifecycle events really wont work.

**Comment by arsduo** [comment]
Ran into the same issue today. Support for this (and/or a standardized way to specify unknown props as HTML attributes as described in #7311 etc.) would be awesome.

**Comment by nhunzaker** [comment]
@arsduo I'll reference this issue in the description of my PR so that we can be sure to circle back to this issue when it merges.

**Comment by arsduo** [comment]
Thank you very much!

**Comment by Nopzen** [comment]
Ran into this issue aswell, would be amazing to have this!

**Comment by rickyH** [comment]
We also have this issue.

**Comment by rickyH** [comment]
https://github.com/facebook/react/blob/b1768b5a48d1f82e4ef4150e0036c5f846d3758a/src/renderers/dom/shared/HTMLDOMPropertyConfig.js

**Comment by nhunzaker** [comment]
Ah I might have misdiagnosed this. @rickyH is right, it looks like we just need to add these to a whitelist. I'll throw together a PR and get something up for testing.

**Comment by nhunzaker** [comment]
Done in https://github.com/facebook/react/pull/9940. I've also put up a jsfiddle if anyone doesn't mind taking a gander to make sure I haven't missed something:

https://jsfiddle.net/84v837e9/88/

**Comment by nhunzaker** [comment]
Merged the addition. I've also sent out a pull request to ship it in the next minor release:
https://github.com/facebook/react/pull/9941

**Comment by uncleramsay** [comment]
Do we know when this will be released?

**Comment by nhunzaker** [comment]
Good question. I just brought it up in the 15.6.2 release umbrella issue (https://github.com/facebook/react/issues/10040)

**Comment by nhunzaker** [comment]
I've put it into the queue for 15.6.2

**Comment by sassanh** [comment]
Do you have an estimate for when 15.6.2 will be out?
Also do you know if this is solved in 16 beta?

**Comment by aweary** [comment]
This is fixed in 16 and was released in 15.6.2 🎉
