### ISSUE TITLE
setSelectionRange is not a function

### ISSUE THREAD

**Issue by mklopets** [facebook/react#9596]
**Do you want to request a *feature* or report a *bug*?**
Report a bug. 🐛 

**What is the current behavior?**
Trying to move the cursor in a contenteditable div, calling [`setSelectionRange`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) on that div throws a TypeError:
```
element.setSelectionRange is not a function
```

**Example code**
https://jsfiddle.net/9xjma402/

**What is the expected behavior?**
Caret is moved, setSelectionRange is a function

**Environments tested on**
React 15.5.4
Chrome 57, Safari 10
macOS Sierra

**Comment by mklopets** [comment]
Welp, setSelectionRange is of `HTMLInputElement`s and doesn't extend to contenteditable things. My bad, closing.

**Comment by Yordinia** [comment]
okey @mklopets .. is there a solution for contenteditable things ? For their cursor to be at the end of the text content please?
