### ISSUE TITLE
Justification/explanation of immutable props in docs

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/react#9599]
It would be nice if the React docs had a good, concise explanation as to _why_ they decided to make props immutable. I have developer friends using angular who regularly make use of this technique (child mutates a data structure owned by parent) and think its great.

The docs do a great job explaining _that_ you can't do this and what the React way of dealing with this is (passing callbacks). But it would be nice to see some more tangible and specific examples of exactly what problem is solved by making props immutable.

**Comment by gaearon** [comment]
Does this help?

https://facebook.github.io/react/tutorial/tutorial.html#why-immutability-is-important

**Comment by StokeMasterJack** [comment]
Sort of. The first bullet point (Undo/Redo and Time Travel) makes perfect sense.

I'm a bit confused on the second and third bullet points ("Tracking Changes" and "Determining When to Re-render"). They seem like the same thing to me. Isn't the only reason for tracking changes so that you can determine what to re-render? 

Also, my Angular buddy swears that Angular 2 supports mutating props and is able to correctly track changes, re-rendering only what is necessary.  

All of the apps I have created in React (so far) have not needed Undo or shouldComponentUpdate. But beyond those two things, it seems there are other reasons for immutable props. Correct me if I wrong:

1. Unlike some other frameworks, React requires an _explicit_ function call to tell it to re-render (setState or forceUpdate) and there would be no way for a child component to do this since the mutated props in question (if it were possible to mutate props) would effect components higher up the tree.

2. Isn't "immutable props" the thing that gives us "one-way data flow"? Aren't there benefits to this in terms of predictability?

The "passing down a mutable pointer that can be mutated by parent and child alike" is such a common pattern in other frameworks, I think it's worth a few more lines of docs detailing why this is not allowed, the trade offs involved and how to do something semi-equivalent in React.

After talking this out, I feel I could write this up and submit a pull request. I want to make sure I have my facts straight.

**Comment by bvaughn** [comment]
The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Please feel free to open a PR at that new repository if you have suggestions for how we can improve the documentation! If you'd like to discuss proposed changes more first, please open an issue and we can talk more there. 😄
