### ISSUE TITLE
[docs] Update "Profiling Components with Chrome Timeline" 

### ISSUE THREAD

**Issue by himynameisdave** [facebook/react#9601]
Google Chrome 58 just dropped and there is a shiny new **Performance** tab instead of the old **Timeline** tab in devTools. You can read all about it [here](https://developers.google.com/web/updates/2017/03/devtools-release-notes), but there is really not much to read except for:

> ### _"The Timeline panel has been renamed to the Performance panel, to better reflect its purpose."_

As a result, the docs for `optimizing-performance.md` needs to be updated [here](https://github.com/facebook/react/blob/master/docs/docs/optimizing-performance.md) to reflect these new changes. 

I tested by profiling a component in our React app at work, seems to work the same so it's really just a matter of updating the docs. I will submit a PR with the update 👍

**Comment by cbengtson85** [comment]
I have a quick question...not sure if this is the right place to ask though.  How do I see the "printWasted()" from react-addons-perf  in the Chrome timeline?
