### ISSUE TITLE
need better warning message about PropTypes deprication

### ISSUE THREAD

**Issue by DrYSG** [facebook/react#9605]
I have no problem with the removal of the PropTypes from the main React package.

But I do import a lot of packages, and the warning message could help me track down which is the culprit. Right now, it is not to helpful.

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
````

**Comment by gaearon** [comment]
While we plan to improve the wording, it is just not possible for us to give more details in the warning message. We can't know *which* code is importing `PropTypes`.

However it is easy for you to do by yourself. Just click on the message in Chrome. You will see an expanded stack trace. The stack trace will show you which library the warning is coming from.

The actionable item from this is we should add a GIF showing how to do it to the blog post, and we should link to the blog post from the warning.

cc @flarnie

**Comment by DrYSG** [comment]
@gaearon Wow, that was fast. Thanks for the reply. So I am running 
Electron: 1.6.6	Node: 7.4.0	Chromium: 56.0.2924.87	V8: 5.6.326.50, and have the redux and react extensions enabled. But I am not seeing anything on the stack trace, since it is a warning, and does not stop and show the call stack (so it is past that).

![snip](https://cloud.githubusercontent.com/assets/2865368/25707300/11118254-30b1-11e7-99ed-0ca1afc7bd6c.png)

**Comment by gaearon** [comment]
I see. 😞 
Perhaps Electron doesn't retain full stacks for warnings.

**Comment by DrYSG** [comment]
@gaearon (sorry, found it, I need to check off "Pause on Caught Exceptions" which is directly over the Watch and Call Stacks, on the left.
 (I put  this in for others who have the issue)

**Comment by gaearon** [comment]
Aah that explains it, thanks!

**Comment by bertho-zero** [comment]
Node doesn't retain full stacks for warnings too when I use React with SSR.

**Comment by gaearon** [comment]
It might be more practical to look at the stacks on the client side.
An alternative could be to override `console.error` to throw an error, immediately catch it, and print its stack. Dirty but works.

**Comment by iamstarkov** [comment]
@gaearon that will be good. i bet it will be hard for a lot of people to look at stack traces just to investigate which components were not upgraded to use `prop-types`

**Comment by gaearon** [comment]
This doesn't seem very actionable so I'll close.
