### ISSUE TITLE
Boolean element attributes (disabled, checked, etc.) in JSX

### ISSUE THREAD

**Issue by jjt** [facebook/react#961]
This is how I've been conditionally putting the `disabled` attribute on elements, with a boolean variable:

``` jsx
<input disabled={isDisabled} type=... />
```

When `isDisabled` is falsey, the attribute won't be output. When true, it will output the following, which works in browsers but is against the [HTML5 spec](http://www.w3.org/TR/html5/infrastructure.html#boolean-attributes):

``` html
<input disabled="true" type=... />
```

I could get in line with the spec by setting `disabled="disabled"` on the element, but that requires a ternary operation instead of a simple boolean:

``` jsx
<input disabled={isDisabled ? "disabled" : false} ... />
```

Ideally, my current bit of JSX (at the top of this issue) would output this HTML, assuming `disabled` is set to true:

``` html
<input disabled type=... />
```

More generally, if a known boolean attribute gets assigned a variable set to `true` as in my example, JSX should output just the attribute as per the HTML5 spec.

**Comment by KarandikarMihir** [comment]
For those who are looking for work-arounds, for the time being, I found [this](http://stackoverflow.com/a/29103727/5241520) on StackOverflow.

**Comment by eddyerburgh** [comment]
@jjt I had a quick look at #1005. It looks like giving setting an attribute as true. Works for disabled, controls and other values. It doesn't work with the autoplay attribute. https://jsfiddle.net/69z2wepo/61355/

**Comment by jamescharlesworth** [comment]
In react, it appears the 'checked' attribute on checkbox input fields do not set the actual html checked attribute, just the javascript checked property on the element. This causes issues with css selectors depending on the checked selector. 

Take this [example](https://jsfiddle.net/L6odkduo/). The css selector does not see the first element as checked. 

When I create a checkbox in react the `checked="checked"` attribute is missing even though in the jsx i have set `checked={true}`
<img width="657" alt="screenshot 2016-11-02 14 00 16" src="https://cloud.githubusercontent.com/assets/666455/19941066/14781ab6-a105-11e6-9ed5-5c64f0e1bd96.png">

**Comment by wnr** [comment]
@ jamescharlesworth I too have this problem. Did you find any solution to this?

**Comment by jamescharlesworth** [comment]
@wnr dont know if this has been fixed by the React team yet, but the quick and dirty solution was to manually set the attribute value on change

**Comment by kkdatkiran** [comment]
@wnr 
I followed this way.

let disabled = isReadonly ? {'disabled' : 'disabled'} : {};
<input {...disabled} />

**Comment by gaearon** [comment]
>This causes issues with css selectors depending on the checked selector.

You *should not* write CSS selectors like `[checked]`. This is just a wrong way to approach the problem. Browser doesn't guarantee that attributes stay synced with properties.

In your example, instead of 

```css
input:not([checked]):disabled + label::after {
```

you should use `:checked` pseudoclass:

```css
input:not(:checked):disabled + label::after {
```

Then it works with expected when toggled through JS (including React).

**Comment by SophaDev** [comment]
xvcvb

**Comment by shvamabps** [comment]
How to perform disabled style for this type of element in react js

like if I choose a certain value in the dropdown value the style of the toggle must change based on the requirements.
Eg: if the name of the option chosen in the dropdown is Number then it should be disabled else not. Can anyone suggest how to do this with this type of JSX component?  
```
<div
                      className="switch has-switch mr-2 mb-2 mr-2"
                      data-on-label="ON"
                      data-off-label="OFF"
                      onClick={this.handleClick}
                    >
                      <div
                        className={cx("switch-animate", {
                          "switch-on": this.state.isToggleOn,
                          "switch-off": !this.state.isToggleOn,
                        })}
                      >
                        <input type="checkbox" />
                        <span className="switch-left bg-danger">ON</span>
                        <label>&nbsp;</label>
                        <span className="switch-right bg-danger">OFF</span>
                      </div>
                    </div>
```
