### ISSUE TITLE
SUGGESTION Return a promise

### ISSUE THREAD

**Issue by timurtu** [facebook/react#9610]
It would be nice if you could return a promise that resolves to a component in the render function or as the return value of a stateless functional component. It might be complex because components need to rerender and promises get cached when they resolve

**Comment by gaearon** [comment]
"Return Promise from `render`" sounds similar to https://github.com/facebook/react/issues/1739 so let's keep the discussion there. We did a prototype of a slightly different approach in https://github.com/facebook/react/pull/8595, and we might revisit in the future.

**Comment by timurtu** [comment]
Cool true but doesn't using componentWillMount mean it has to be stateful?

**Comment by gaearon** [comment]
The issue is a bit more general (further discussion is not just about `componentWillMount`).
