### ISSUE TITLE
how to remove the warnings in v15.5.4 of unminified file

### ISSUE THREAD

**Issue by 39Er** [facebook/react#9611]
> react.js:3287 
> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
> 
> Warning: LazyRenderBox: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by gaearon** [comment]
Please read this blog post!

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

We’ll add a link to it from the warnings in the next version.

**Comment by 39Er** [comment]
But in my application, I don't use React.PropTypes and React.createClass , why it still gives me warnings...

**Comment by TrySound** [comment]
@39Er It means one of your dependencies use them. Try to update.

**Comment by cri5ti** [comment]
As an observation, when using React with TypeScript, it's typical to do a wildcard import of React: 

    import * as React from 'react';

which gets translated to an _interopRequireWildcard that enumerates the React type, causing the warning to be displayed even if you don't actually use PropTypes.

**Comment by gaearon** [comment]
Oh, interesting. Thanks for sharing this.

**Comment by just-boris** [comment]
@gaearon is there any general recommendation about `import * as React from 'react';` pattern?

This pattern is very common among Typescript developers and a lot of them will get the warning.

**Comment by gaearon** [comment]
It sounds reasonable to me. The PropTypes thing is unfortunate—I'm not sure if there's any way to prevent that?

**Comment by just-boris** [comment]
As I see, the only way is specifying all imports explicitly, like `import {Component, createElement} from 'react'`.

I wish it should be mentioned somewhere in the migration guide, that `import * as React` is not recommended way to import module. By the way in JS with Babel it shows warning too.
