### ISSUE TITLE
There is no possibility to catch start/stop pull-to-refresh gesture event of "RefreshControl" component

### ISSUE THREAD

**Issue by valeriik** [facebook/react#9612]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
There is no possibility to catch start/stop pull-to-refresh gesture event of "RefreshControl" component.

**What is the expected behavior?**
Would be great have something like "onPullStart" and "onPullEnd" event to know the moment of start/stop pull-to-refresh gesture.

Related question on [stackoverflow](http://stackoverflow.com/questions/43784388/is-there-a-way-to-catch-start-stop-event-using-pull-to-refresh-gesture-of-listvi).

![3](https://cloud.githubusercontent.com/assets/24571089/25739204/8f773a20-3189-11e7-9aa7-400002a380f1.jpg)

**Comment by nfcampos** [comment]
@valeriik is it possible you meant to open an issue on the react-native repo instead? https://github.com/facebook/react-native

**Comment by valeriik** [comment]
Sure, sorry, my fault.

**Comment by nfcampos** [comment]
No worries :)
