### ISSUE TITLE
How to get PropType info from a Component (even built in's)

### ISSUE THREAD

**Issue by jdarling** [facebook/react#9614]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Unknown

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

It would be nice if there was something like PropTypes.getPropTypes(Component) that would accept a component and return its PropType definitions.  This should work for anything including default HTML element types.

Something like:

```
PropTypes.getPropTypes('span');
PropTypes.getPropTypes(MyComponent);
```

Even better would be if it worked with elements as well, but that seems like you could just hit the element's prototype.

Currently I can't find a good way to do an "extension" and retain the prop types of the default component, and/or a way to get prop types from HTML elements.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"react-dom": "^15.5.4"

**Comment by gaearon** [comment]
You can read `MyComponent.propTypes` if you need to (note that in production they will all point to the same function because they are replaced with empty shims to save the code size).

This wouldn’t work for DOM components because they accept any props. In current release, we don’t pass unknown props through, but we plan to in the future releases, so you shouldn’t rely on our whitelists.

>Currently I can't find a good way to do an "extension" and retain the prop types of the default component, and/or a way to get prop types from HTML elements.

If you explicitly use those props in your component, you should just declare them in it. If you just pass them though, there is no benefit to writing them explicitly in the outer component, since React will check the inner component anyway.

**Comment by jdarling** [comment]
Well I was trying to get around the warning's being thrown about unknown property types.  But sounds like in future releases that's ok.  So guess I'll just ignore them :)

Thanks

**Comment by gaearon** [comment]
In future releases they’ll just end up in the DOM so you’ll see something like `<div myCustomProp="[object Object]">` in DOM itself. So I would recommend fixing the components that cause the warning rather than figure trying to get around it.

**Comment by jdarling** [comment]
Yeah I was more looking for a way to get the prop types of 'span' or whatever.  I'm building out a property provider and of course populating propTypes when they don't exist becomes difficult.  The only thing I could come up with was if there is no propTypes defined then just send everything over and let React sort it out.  If there were some type of PropTypes.getPropTypeNames or PropTypes.getPropTypes method then it would make things like this and IDE's/Editors easier to implement.

**Comment by gaearon** [comment]
>The only thing I could come up with was if there is no propTypes defined then just send everything over and let React sort it out.

This is pretty much how we intend DOM integration to work.
