### ISSUE TITLE
React + Webpack + Socket.io

### ISSUE THREAD

**Issue by soutomario** [facebook/react#9617]
Hi, i'm working in a personal project, and I want to use webpack-dev-server with hot loader for dev and SSR for production with react-router, and I'm not finding a way of make these things work together.

Does anyone already had this problem or try to build something like this?

**Comment by peterpetre** [comment]
Hi, @soutomario you can check this [https://github.com/verekia/js-stack-from-scratch](https://github.com/verekia/js-stack-from-scratch)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
