### ISSUE TITLE
Why does ReactDOMComponent get compiled to react-dom-server.development and not react-dom.development?

### ISSUE THREAD

**Issue by Flaque** [facebook/react#9618]
If this is the wrong place to ask this, please let me know.

If I put a line like:

```
console.log("OIJWEIOJAREAIJWOE"); 
```

In `src/renderers/dom/stack/client/ReactDOMComponent.js`, and then I run `npm run build`, then search for `OIJWEIOJAREAIJWOE` in the build directory, it appears only in `build/dist/react-dom-server.development.js` or `build/dist/react-dom-server.production.js`. 

Why?

**Comment by gaearon** [comment]
Because `ReactDOMComponent` is only used in the old engine ("Stack"). We switched `react-dom` to use the new engine ("Fiber") on master, and it uses `ReactDOMFiberComponent` instead.

However `react-dom/server` still uses Stack at the moment.
