### ISSUE TITLE
react/PATENTS suck!

### ISSUE THREAD

**Issue by TacB0sS** [facebook/react#9623]
What is wrong with you people... who puts this sort of indirect limitation on an "open source" project... 

I just started to use react and I love it, why on earth this (I don't have the right words for it)...

So if Facebook breaks the rules they will break my projects... this is a lowest thing ever done by you Facebook!

Maybe it is not code related but it is a developer potential abuse!

**Comment by TacB0sS** [comment]
I will not use react unfortunately, and would recommend anyone else to do the same till this issue PATENT rubbish would be more decent... 

I read Google, Microsoft and Apple are OK with this, well good for them, they have Billions of dollars to fight if needed, most companies don't, this is ridicules and unacceptable in my book!

**Comment by gaearon** [comment]
Thanks for feedback.

Just in case you might have a wrong idea about what the patent grant means, we published a FAQ:
https://code.facebook.com/license-faq

I hope this helps!

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
