### ISSUE TITLE
isMounted behavior different with `create-react-class`

### ISSUE THREAD

**Issue by mridgway** [facebook/react#9627]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Calling `this.isMounted()` in `componentWillUnmount` in prior versions would return `true`. Now it returns `false`.

I believe this was untested behavior before, but the new tests that were added may check the wrong value: https://github.com/facebook/react/blob/master/src/isomorphic/classic/class/__tests__/create-react-class-integration-test.js#L417 Changing this line to test for `true` will exhibit the behavior.

The fix would be to defer setting the  `__isMounted` flag to `false` until after all mixins and the `componentWillUnmount` method were called on the component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.5.x and anything using `create-react-class` is broken. Working correctly in 15.4.x with `React.createClass`.

**Comment by mridgway** [comment]
I fixed this locally by splitting the IsMountedMixin into two: 

```js
  var IsMountedPreMixin = {
    componentDidMount: function () {
      this.__isMounted = true;
    }
  };

  var IsMountedPostMixin = {
    componentWillUnmount: function () {
      this.__isMounted = false;
    }
  };
```

Then installing the Post after the spec has been mixed in:

```js
    mixSpecIntoComponent(Constructor, IsMountedPreMixin);
    mixSpecIntoComponent(Constructor, spec);
    mixSpecIntoComponent(Constructor, IsMountedPostMixin);
```

For the life of me I can't find the right repo to PR this against though.

**Comment by gaearon** [comment]
This should be fixed with `create-react-class@15.6.0-rc.0`. Can you please verify?

**Comment by mridgway** [comment]
I don't see that version published yet.

**Comment by gaearon** [comment]
It's not set to `latest` (still an RC) but it exists:

https://unpkg.com/create-react-class@15.6.0-rc.0/

**Comment by mridgway** [comment]
Ah indeed. It's probably our internal registry being slow. I'll try it out soon.

**Comment by mridgway** [comment]
Confirmed working correctly in `create-react-class@15.6.0-rc.0`.

**Comment by gaearon** [comment]
Great. Thanks for sending the fix!
