### ISSUE TITLE
React + Djnogo

### ISSUE THREAD

**Issue by sincsc** [facebook/react#9631]
hello, I use react+djnogo to develop web system, but I meet a issue，it can not upload picture use the form tag with input tag, I put this tags in React render function, I do not know where the problem is. I need help, thanks very much!

**Comment by sincsc** [comment]
I use it this way:
![image](https://cloud.githubusercontent.com/assets/17526484/25836937/50658a76-34bd-11e7-887d-ce034f4625c9.png)

**Comment by learning** [comment]
Could you describe more details on this issue? Such as the error logs, or share a [JSFiddle](https://jsfiddle.net/).

**Comment by gaearon** [comment]
We use the issue tracker for bug reports and feature requests.
If you just need help getting something working, please use the suggested resources:

https://facebook.github.io/react/community/support.html

Cheers!
