### ISSUE TITLE
Warning message for zIndex `[...] unitless number in a future version of React`

### ISSUE THREAD

**Issue by heldrida** [facebook/react#9633]
**Do you want to request a *feature* or report a *bug*?**
report bug
**What is the current behavior?**
warning message
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
when setting css style property z-index to a numerical value the warning is displayed 'Warning: a `img` tag (owner: `Logo`) was passed a numeric string value for CSS property ` zIndex` (value: ` 1`) which will be treated as a unitless number in a future version of React.'
**What is the expected behavior?**
no warning for z-index, because according to CSS | MDN `The z-index property is specified as either the keyword auto or an <integer>.`
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v15.5.4

**Comment by deecewan** [comment]
what is the code you're using?

I have just tried [to replicate](https://jsfiddle.net/ww98ro8z/) and can't get any warning, but given what your warning said, I assume you're passing in a string (as in the first `P` tag in my link).

Do you get the same error if you pass a number?

**Comment by heldrida** [comment]
I was using GSAP and the style value was set through `this.state.style` let's say. The value was a Number. Fixed by changing to zIndex: 'auto', the warning didn't show and as you see is a string.

I'll try to get back to that project and put the code here.

**Comment by gaearon** [comment]
I'll close since there was no followup. If you can reproduce let us know!

**Comment by heldrida** [comment]
Couldn't replicate, thanks ( https://jsfiddle.net/84v837e9/147/ )
