### ISSUE TITLE
Rename ReactEventListener to ReactDOMEventListener

### ISSUE THREAD

**Issue by spicyj** [facebook/react#9639]
Currently, ReactEventListener is a DOM-specific module but it has a generic sounding name that is confusing to contributors (i.e., confusing to me).

Let's rename it to ReactDOMEventListener. This should be pretty easy – just rename the file and update (and re-sort) the imports.

# @philipp-spiess is working on this task.

**Comment by philipp-spiess** [comment]
I'd tackle this 😊

**Comment by spicyj** [comment]
It's yours!
