### ISSUE TITLE
External packages not transforming `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by mridgway** [facebook/react#9641]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`process.env.NODE_ENV` checks are being shipped to the browser.

**What is the expected behavior?**

In React, there is a browserify transform that converts `process.env.NODE_ENV` to the actual environment variable.

In `package.json` of React: 

```
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  }
```

**Packages**
 * [x] prop-types
 * [x] create-react-class
 * [x] react-addons-create-fragment
 * [x] react-transition-group

**Comment by mridgway** [comment]
@acdlite I can do a PR for `create-react-class`, but now I can't find the code for `prop-types`.

**Comment by gaearon** [comment]
It's in https://github.com/reactjs/prop-types.

**Comment by gaearon** [comment]
Does this mean we also need to do this for all addons? Or do they already have them?

**Comment by mridgway** [comment]
I'll look through the addons to see. Only the addons that use `process.env.NODE_ENV` will need to have it and I think most are already proxying to `require('react/foo')`.

**Comment by gaearon** [comment]
>I think most are already proxying to require('react/foo').

They shouldn't—the point of 15.5 release was to decouple (almost all) addons so they can keep existing when React 16 removes /lib/.

**Comment by mridgway** [comment]
I added a list to the description that shows which packages use `process.env.NODE_ENV` that don't include `loose-envify`. I can either add it to all of them or just the ones that use `process.env.NODE_ENV`. Up to you.

**Comment by gaearon** [comment]
Let's only add where necessary.

**Comment by gaearon** [comment]
`create-react-class@15.5.3` and `react-addons-create-fragment@15.5.4` should have the fixes.
Please let us know if this worked!

**Comment by mridgway** [comment]
Looks good. Thanks for the quick turnaround on these!
