### ISSUE TITLE
Need to know when react 16 will get released.

### ISSUE THREAD

**Issue by KalpanaPagariya** [facebook/react#9645]
This is not bug or feature. I have search a lot on internet to find out the release date of React 16.
Can you please mention about it?

I tried to check where I can raise this question, but did not any forum for such questions. So raising here.

Thanks,
Kalpana

**Comment by bjrmatos** [comment]
just for the record, the forum is here https://discuss.reactjs.org/

**Comment by gaearon** [comment]
We don’t have any specific date in mind. We’re hoping to get it out this summer.

**Comment by eugensunic** [comment]
Real time react Fibre launch: http://isfiberreadyyet.com
