### ISSUE TITLE
How to use localStorage in componentWillMount

### ISSUE THREAD

**Issue by BhumiSukhadiya** [facebook/react#9647]
I am learning react js and i want to check if authentication token is set or not in localStorage before the component renders.
Currently i am trying to do it inside componentWillMount method, but it gives me warning that localStorage is not defined.
So how can i access localStorage?

**Comment by Radi123** [comment]
@BhumiSukhadiya View this: http://stackoverflow.com/questions/40853212/react-component-rendering-before-data-received-from-localstorage

Is this helpful?

**Comment by Alexintosh** [comment]
@BhumiSukhadiya  are you accessing it from window.localStorage?

**Comment by Radi123** [comment]
@Alexintosh @BhumiSukhadiya  Yes! You must use ```window.localStorage```

**Comment by aweary** [comment]
Hey @BhumiSukhadiya!

We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

If you're doing server-side rendering then accessing `localStorage` in `componentWillMount` might throw an error on the server. It's usually safest the DOM in `componentDidMount`

**Comment by BhumiSukhadiya** [comment]
@Alexintosh  i'm getting warning that window is not defined if i use window.localStorage in componentWillMount() method

**Comment by yogeshR5** [comment]
@aweary  I used local Storage to get session Id and key based on these only site will load. how to use local storage in componentDidMount?
