### ISSUE TITLE
TestUtils documentation missing

### ISSUE THREAD

**Issue by omerts** [facebook/react#9651]
Hey,

I can't find a link to the TestUtils documentation anywhere in the React website. 
Is it because it is going through some updates?

Omer

**Comment by gaearon** [comment]
I don't think this is intentional.
We probably accidentally removed it from the website index, when we should have updated it.

**Comment by gaearon** [comment]
@flarnie Tagging you since we probably should bring it back as part of 15.6.

**Comment by gaearon** [comment]
For now, you can find it here:

https://facebook.github.io/react/docs/test-utils.html

**Comment by omerts** [comment]
@gaearon Thanks a lot

**Comment by ztanner** [comment]
Yeah...also noticed this for most of the react docs. A google search for "facebook.github.io" "Higher-Order Components" has nothing

**Comment by gaearon** [comment]
We had some weird problems reported about Google search but that seems like a separate issue.

**Comment by flarnie** [comment]
Thanks @omerts and @gaearon for flagging this. About to put them back in the main navigation.

I also noticed the 'shallow renderer' section now seems outdated - not sure if I just missed that or if the update wasn't cherry-picked or something. Fixing that in a separate diff.
https://facebook.github.io/react/docs/test-utils.html#shallow-rendering

**Comment by gaearon** [comment]
It's back up.
