### ISSUE TITLE
Class comparison only works when NODE_ENV = production

### ISSUE THREAD

**Issue by dadamssg** [facebook/react#9652]
I would like to report a bug.

React type/class comparison only seems to work when the NODE_ENV is set to production.

[I have created a repo to illustrate the bug here.](https://github.com/dadamssg/react-class-bug) 

I expect the type/class comparison to work regardless of what NODE_ENV is set to.

**Comment by gaearon** [comment]
This issue is caused by React Hot Loader.
Unfortunately there is currently no good workaround for it.

**Comment by dadamssg** [comment]
interesting that everything works when set to production(including react hot loader) :(

**Comment by gaearon** [comment]
RHL disables itself in production.

**Comment by dadamssg** [comment]
I guess I don't understand how it determines it's running in production. RHL still works if I start the app like below: 

`NODE_ENV=production node_modules/.bin/webpack-dev-server --hot`

**Comment by gaearon** [comment]
It relies on envification. We provide instructions for bundling for production:

https://facebook.github.io/react/docs/optimizing-performance.html#webpack

Note that `webpack-dev-server` is not suitable for production at all (that's why it's a `dev` server).
