### ISSUE TITLE
Concern in rendering nested array

### ISSUE THREAD

**Issue by zhangqibupt** [facebook/react#9662]
I find that no warning is given when render an array nested in another. [this case][3]

    const numbers = [1, 2, 3, 4, 5];
    const listItems = numbers.map((numbers) =>
      <li>{numbers}</li>
    );
    
    // 'listItems' is wrapped in an array
    ReactDOM.render(
      <ul>{[listItems]}</ul>,
      document.getElementById('container')
    );

After debugging, in React, I find `function validateChildKeys`, which is used to validate children's keys:

    /**
     * file path: react/lib/ReactElementValidator.js
     * Ensure that every element either is passed in a static location, in an
     * array with an explicit keys property defined, or in an object literal
     * with valid key property.
     *
     * @internal
     * @param {ReactNode} node Statically passed child of any type.
     * @param {*} parentType node's parent's type.
     */
    function validateChildKeys(node, parentType) {
      if (typeof node !== 'object') {
        return;
      }
      if (Array.isArray(node)) {
        for (var i = 0; i < node.length; i++) {
          var child = node[i];
          if (ReactElement.isValidElement(child)) {
            validateExplicitKey(child, parentType);
          }
        }
      } else {
        // do some other validation
        // ..................
      }
    }
function `ReactElement.isValidElement(child)` is used to check if a child node should be checked.

    ReactElement.isValidElement = function (object) {
      return typeof object === 'object' && object !== null && object.$$typeof === REACT_ELEMENT_TYPE;
    }

When checking nesting array, e.g. `array = [array0,array1,array2]`, array0, array1, array2 are `Array` objects, which have no property named `$$typeof`, so function `validateExplicitKey` will never be called, warning message will never be thrown.

Is it a bug? 
Or does React acquiesce this case?
Giving a warning message is better, maybe.

  [1]: https://facebook.github.io/react/docs/lists-and-keys.html#keys
  [2]: https://facebook.github.io/react/docs/reconciliation.html#recursing-on-children
  [3]: https://jsfiddle.net/neo1102/a9hx8cje/

**Comment by ksmithbaylor** [comment]
It's perfectly valid to pass non-React-elements into a component as children. Here's an example sourced from [here](http://blog.ricardofilipe.com/post/react-callback-render-pattern):

```javascript
const App = () => {
  return (
    <div>
      <FieldItem username='magalhini'>
        {user => user === null
        ? <Loading />
        : <Profile info={user} />}
      </FieldItem>
    </div>
  );
};
```

This is a handy way to defer rendering to a child component instead of needing to (in this example) fetch the user in the parent. See [this](http://reactpatterns.com/#render-callback) for some more use-cases.

What this means is that since children can be anything, checking to make sure they aren't arrays wouldn't make much sense. It would limit the ways children could be used, and likely break backwards compatibility for existing apps.

**Comment by zhangqibupt** [comment]
I totally understand your point, thanks very much for your reply.

In the case of my scenario, it is a common usage to write code like this:
```
<Dialog>
 { iterms.map( ()=>([a,b,c])) }
</Dialog>
```
And I still a little confused that array, as a variable-length structure, different from function, it is clearly declared that a key should be provided to it to help do optimisation in re-rendering, otherwise a warning should be given. In this case, is it better to follow the convention to warn developers be clear about what they are doing and avoid confusion like I had, after all re-render performance is affected indeed.

On the other hand, in this case, even if developers provide an unique key for each item, I don't think there is any improvement on the performance. So is it possible for React to do some optimisation to handle it.

Thanks again for you reply.

**Comment by ksmithbaylor** [comment]
Yeah, I definitely agree that your particular use-case could be confusing. It's a really common error that I've seen in various forms.

But from a library perspective, what if a developer really did want to pass data that was shaped as nested arrays? Doing any sort of checking or coercion of the children would prevent that, and likely result in more confusion. The way it is, you get out exactly what you put in.

In your case, I would suggest making the parent component (that you want to pass nested arrays to) do the flattening itself. That way, users of your component don't have to account for this themselves.

**Comment by zhangqibupt** [comment]
Yeah, totally agreed. And giving a warning to suggest add a unique key to nested arrays without optimisation does not help or make sense. 

It seems that, as you said, making the parent component do the flattening itself is the best choice for the moment.

Thx.

**Comment by maxdeviant** [comment]
@zhangqibupt If your question was answered, would you mind closing out this issue? Helps keeps the issue tracker clean for the React core team :+1:
