### ISSUE TITLE
React's GitHub wiki security issue?

### ISSUE THREAD

**Issue by AviVahl** [facebook/react#9666]
When browsing React's GitHub wiki, we noticed the following:
https://github.com/facebook/react/wiki/chevrolet

How did it get there? Can anyone just edit the wiki without being reviewed?

EDIT: it is linked from the main wiki page.

**Comment by gaearon** [comment]
Page deleted.
Unfortunately that's just how Wikis work.

We could conceivably delete it completely if it's a common issue.

**Comment by AviVahl** [comment]
@gaearon thx for the quick response.
Wikis can still have possible permissions. When checking it now in github, under project management, I found a small checkbox saying:
> * Restrict editing to users in teams with push access only 
> Public wikis will still be readable by everyone.

So it is possible, but in a quite strict way.
Anyhow, thx again.

**Comment by gaearon** [comment]
I see. In this case, I don’t think it would work for us, as we mostly don’t edit the Wiki at all. It contains community resources.

The official docs are at http://facebook.github.io/react and they have strict write access.
