### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by richardtorres314** [facebook/react#9677]
Hi! I just had a couple of questions/requests regarding the tutorial.

1. In the Board's render function (snippets in question show below), while later removed, winner and status both make use of this.state.[value]; should this instead be this.prop.[value]? I understand that it is removed later on, but as I'm trying to follow along and understand the code, this seemed inconsistent.

```
const winner = calculateWinner(this.state.squares);
...
status = 'Next player: ' + (this.state.xIsNext ? 'X' : 'O');
```

2. In the jumpTo function of the Game class, the discussion reads, "_We set xIsNext to true if the index of the move number is an even number_," but then the code given reads ```xIsNext: (step % 2) ? false : true,```. Shouldn’t the line read “_We set xIsNext to true if the index of the move number is an odd number._”?

Thank you!

**Comment by gaearon** [comment]
>In the Board's render function (snippets in question show below), while later removed, winner and status both make use of this.state.[value]; should this instead be this.prop.[value]?

Yea, I guess it's a bit confusing. It's going to be removed, but we're showing an intermediate stage where it still exists. What do you think would work best? We could remove this code snippet and just show `renderSquare` alone, but then people can't quickly check if they made the first bunch of changes correctly.  We could omit contents of methods that haven't changed (`handleClick` and `render`) and just say something like `// This method hasn't changed yet`. Then it's less distracting. Or we could maybe add comments like `// We will move this method to Board soon` and `// We will remove this code soon`. What do you think?

>In the jumpTo function of the Game class, the discussion reads, "We set xIsNext to true if the index of the move number is an even number," but then the code given reads xIsNext: (step % 2) ? false : true,. Shouldn’t the line read “We set xIsNext to true if the index of the move number is an odd number.”?

I guess it's a bit confusing. When the number is even, `(step % 2)` is 0, causing the condition to be `false`, and the ternary to evaluate to `true`. So I think the code is right but this would be more explicit:

```js
      xIsNext: (step % 2) === 0,
```

Would you like to help these issues by editing the tutorial?

**Comment by richardtorres314** [comment]
Hi @gaearon, thanks for the quick response. I think your original solution to my second question regarding xIsNext is perfectly fine, I think I needed to wrap my head around it. I am however still unsure about my first question: The explanation states

> Then change Board so that it takes squares via props...

But it proceeds to use ```const winner = calculateWinner(this.state.squares);``` in Board's render. I guess I'm unsure as to why ```this.state.squares``` is fine to use for ```calculateWinner``` but is replaced in the ```RenderSquares``` function at ```value={this.props.squares[i]}```. Are these referring to two sets of squares, one particular array element (which is handed down from Game) vs. the entire array (which is not passed from Game)? Thank you!

**Comment by gaearon** [comment]
That line is referring to this line specifically:

>Replace this.state.squares[i] with this.props.squares[i] in Board's renderSquare.

Regarding

>I'm unsure as to why this.state.squares is fine to use for calculateWinner

it is not fine—it's just that we haven't touched this method yet. We are removing this part of the code right ahead:

>we can delete `<div className="status">{status}</div>` and the code calculating the status from the Board's render function:

So it didn't make sense to me to change that code right before deleting it. But maybe there's a better way to rephrase it.

To clarify one more time, the snippet you're looking at is not meant to be the final version of the code. It's just the one with these three changes applied:

>* Delete the constructor in Board.
>* Replace this.state.squares[i] with this.props.squares[i] in Board's renderSquare.
>* Replace this.handleClick(i) with this.props.onClick(i) in Board's renderSquare.

and then the next steps fix the issue with `handleClick` and `render`.

**Comment by mroyce** [comment]
Hi @gaearon,

I'd like to share my proposed solution to clarify the transition from storing `state` in `Board` to storing it in `Game`.

It seems unnecessary to show the entire `Board` component after updating `renderSquare`; the only change between now and the last time time the entire `Board` code was shown is the addition of `calculateWinner` in `render` and `calculateWinner` in `handleClick`, which is already shown in a separate snippet.  If you agree with this presumption, I think we can make the following changes:

1. Set up initial state in `Game` and remove the constructor from `Board`
2. Move `handleClick` from `Board` to `Game`
3. Move `calculateWinner` from `Board` to `Game`
4. Replace `this.state` in `renderBlock` with `this.props`
5. Show code blocks for the new `Game` and `Board` components.

If this seems plausible I can go ahead and start working on updating the tutorial.

**Comment by gaearon** [comment]
I’m not 100% sure but if you can demonstrate it working well, let’s do it.

**Comment by gaearon** [comment]
Happy to take a PR for the above, but don't see the sense in keeping the issue open.
