### ISSUE TITLE
onClick unexpected behaviour on text selections

### ISSUE THREAD

**Issue by a-x-** [facebook/react#9678]
*bug*

**Current behavior**

On text selection in the component with `onClick` handler react fires onClick

**steps to reproduce**

http://jsbin.com/hogiquluzo/edit?js,console,output

**What is the expected behavior?**

onClick does not fires on both text selection and double click events;

**versions of React, and browser / OS**

react@latest(16.0.0-alpha.12)

os: macOS@latest

browser: chrome@latest

**Comment by a-x-** [comment]
My workaround:
```
/**
 * React Router onclick workaround
 * @example <div {...OnClick(onClick)}/> 
 */
export const OnClick = (() => {
  let clickTime = 0;
  let pos = {x: 0, y: 0};

  return onClick => ({
    onMouseDown: ({nativeEvent: e}) => {clickTime = Date.now(); pos.x = e.x; pos.y = e.y;},
    onMouseUp: ({nativeEvent: e}) => {Date.now() - clickTime < 200 && pos.x === e.x && pos.y === e.y && onClick()},
  });
})();
```
link: https://github.com/tannerlinsley/react-table/issues/258

**Comment by aweary** [comment]
Hey @a-x-, it looks like this is expected behavior ([reference](https://jsfiddle.net/vkL5optp/)). If I highlight the text it will trigger a `click` event. Can you clarify why you expect different behavior?

**Comment by a-x-** [comment]
hm, you're right, I'm confused. :(
