### ISSUE TITLE
Scrolling gets jammed under specific condittions

### ISSUE THREAD

**Issue by theScottyJam** [facebook/react#9680]
See this fiddle (using chrome): https://jsfiddle.net/gmodvajk/2/

## The bug

This is just a small problem that occurs under very specific conditions. The fiddle shows a scrollable box where half-way down the color of the box is changed from a solid color to a semi-transparent color. When scrolling down (and only down) you will see that it seems to get a little stuck on the way. It becomes much more apparent when using the page down key, where it'll only scroll until the color-change point, and no further, even on repeated pushes of page down. Page up (or going from a semi-transparent color to a solid color) works just fine

## Expected behavior

When scrolling it shouldn't hitch at the color-changing point. When pushing page down it's supposed to scroll the box all the way.

## Recreating the bug

The container must be positioned absolute or relative, and it must have a z-index set. This problem only occurs when going from a solid color to any rgba color (where alpha isn't 1).

## Enviorment

This was tested on Fedora-Linux and on Windows 10. The behavior only seems to occur in chrome. In firefox it works fine.
React version 15.5.4

**Comment by syranide** [comment]
I can't reproduce it in Win10 Chrome, works as expected. I'm not even sure what could possibly cause what you're seeing, you're effectively working outside of React except for the scroll-event. Are you sure this isn't caused by some Chrome plugin of yours?

> This problem only occurs when going from a solid color to any rgba color (where alpha isn't 1).

This sounds like a Chrome bug, opacity causes an element to become a stacking context, possibly there's some bug with that.

**Comment by ndresx** [comment]
Just tested it in Chrome 57/58 and the lag is noticeable here, basically ignores the scroll input completely. However, as @syranide pointed out, this seems to be more a Chrome issue than a bug in React. It also feels like the scrolling with the rgba color is kind of jaggy compared to the solid color.

**Comment by syranide** [comment]
PS. Unless this is a transient bug in Chrome, this may be helpful for you https://developer.mozilla.org/en-US/docs/Web/CSS/will-change (but beware of overuse)

**Comment by theScottyJam** [comment]
I'm so sorry. I've tried a few times before to take the react code out and whenever I did the bug disappeared, but I just did it again in a JSFiddle and it's still there.

Well, thanks anyways. Keep up the good work :).

**Comment by syranide** [comment]
@theScottyJam No problem, would you mind reposting this issue on the Chrome tracker? I'd think they'd be happy to have it. This does not seem like expected behavior (especially for such a trivial example).

**Comment by theScottyJam** [comment]
[It's](https://bugs.chromium.org/p/chromium/issues/detail?id=722701) been reported. Thanks :)

**Comment by syranide** [comment]
@theScottyJam Excellent, "If you disable the smooth scrolling flag in chrome and it will work as expected.", is probably why I didn't see it then, I've disabled it in windows.

**Comment by gaearon** [comment]
Sounds like this wasn't our bug.
