### ISSUE TITLE
Is there an error in document of Optimizing Performance?

### ISSUE THREAD

**Issue by MrErHu** [facebook/react#9682]
![img](https://facebook.github.io/react/img/docs/should-component-update.png)

>Reconciliation:The algorithm React uses to diff one tree with another to determine which parts need to be changed.

The above is what I found about the define of reconciliation.In my opinion, reconciliation contains two part: diff element tree and update actual DOM node.

I think the C8 in picture above need reconciliation, so the color of C8 should be red.

**Comment by DFurnes** [comment]
My understanding is that the diff algorithm and reconciliation are two different things:

The diff algorithm figures out which nodes in the tree have changed. Then reconciliation only occurs for the parts of the tree that we know have changed from the diff, and is the process React uses to update the "real" DOM elements for the component with the fewest amount of mutations.
