### ISSUE TITLE
React.Component undocumented templated class

### ISSUE THREAD

**Issue by barbu110** [facebook/react#9684]
I see that `React.Component` is used with three template parameters that are documented nowhere. (or I simply couldn't find the docs).

I was able to deduce that the second and third are the types of `props` and `state` respectively. However, I coudn't figure it out about the first template parameter.

Are these documented anywhere, please?

**Comment by Hypnosphi** [comment]
[Kinda](https://flow.org/en/docs/frameworks/react/). The first parameter is the type of `defaultProps`

**Comment by barbu110** [comment]
Could you please point me to the internal source file that defines `class Component<...>`? I couldn't find it...

**Comment by Hypnosphi** [comment]
https://github.com/facebook/flow/blob/master/lib/react.js#L16

**Comment by barbu110** [comment]
Strange thing. Thank you very much!

**Comment by gaearon** [comment]
React documentation doesn't have a section about Flow (should it?) So I am not fully sure where you would like to document this.

However, there is a section about React on the Flow website. Does it not help?

**Comment by barbu110** [comment]
@gaearon the section about React on the Flow website is a guide and it does not present the entire API reference. 

And yes, I think React should have a section about Flow. Currently, the React docs section [Typechecking with PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)  explains that 

 > React.PropTypes is deprecated as of React v15.5.

In my opinion this comes as a way to encourage the usage of TypeScript or Flow for static typechecking. Hence, this is part of the reason why there should be a Flow section in the React documentation.  What do you think?

**Comment by gaearon** [comment]
The wording on React doc is really unfortunate. It shouldn't say "deprecated", it should say "moved". We're not deprecating PropTypes—just moving them to a separate package.

Although I agree that in general we think Flow/TS is a better way to do it. I'm open to having a new guide called "Static Type Checking" here that shows how to use React from Flow and from TypeScript, and describes main API definitions. Would you like to work on it?

**Comment by barbu110** [comment]
@gaearon, yes, I would like to help as much as I can!

**Comment by funfor** [comment]
https://m.facebook.com/emma.harrison.507679?tsid see how yous go

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#76

Let's continue the discussion there! Sorry for the inconvenience.
