### ISSUE TITLE
Document how to pass args to event handlers

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/react#9685]
Inside a loop it is common to want to pass a param to an event handler:

```
<button onClick={(event) => this.deleteRow(23)}>Delete Row</button>
<button onClick={this.deleteRow.bind(this,23)}>Delete Row</button>
```

That would be a good thing to add to this doc page:

https://facebook.github.io/react/docs/handling-events.html

Also, how to pass args without triggering a re-render in the child component (i.e. creating a new function every time).

**Comment by lydell** [comment]
The problem I have with https://facebook.github.io/react/docs/handling-events.html is:

> The problem with this syntax [`onFoo={() => this.onFoo()}`] is that a different callback is created each time the `LoggingButton` renders. In most cases, this is fine. However, if this callback is passed as a prop to lower components, those components might do an extra re-rendering. We generally recommend binding in the constructor or using the property initializer syntax, to avoid this sort of performance problem.

If “in most cases, this is fine”, why do you “generally recommend ...” doing it another way? Is it causing a performance problem or not?

---

A related problem I have is this:

When it comes to passing a param to event handlers in a loop, I know of the “trick” to extract another component:

```js
class ItemList extends React.Component {
  constructor(props) {
    super(props);

    this.onClick = this.onClick.bind(this);
  }

  render() {
    return <div>
      {this.props.items.map(item =>
        <Button item={item} onClick={this.onClick} />
      )}
    </div>;
  }

  onClick(itemId) {
    console.log('Clicked item:', itemId);
  }
}

class Button extends React.Component {
  constructor(props) {
    super(props);

    this.onClick = this.onClick.bind(this);
  }

  render() {
    return <button type="button" onClick={this.onClick}>
      {this.props.item.name}
    </button>;
  }

  onClick() {
    this.props.onClick(this.props.item.id);
  }
}
```

Ok, but `Button` hasn’t got any state, so I could just as well make a function component instead, right?


```js
function Button({item, onClick}) {
  return <button type="button" onClick={() => onClick(item.id)}>
    {this.props.item.name}
  </button>;
}
```

Nope, then we’re back on square one again, with a new function being constructed on every render.

Does this mean that it is recommended to switch function components to class components as soon as they take functions as props? If so, the use of function components would decrease a lot for me. Really, it’d be a smarter move to never use function components to avoid having to convert them to classes. For me, it is not uncommon that function components start out as totally non-interactive, but get some event listeners after a while.

---

Personally, I think I’m just gonna go with whatever makes the most readable code and don’t worry about performance until I notice performance problems.

But it would be really nice to clear out the confusion.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved your issue to the new repo: reactjs/reactjs.org#75

Let's continue the discussion there! Sorry for the inconvenience.
