### ISSUE TITLE
Needed Simplified Chinese Documentation.

### ISSUE THREAD

**Issue by DanceSmile** [facebook/react#9692]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by discountry** [comment]
Take a look at [react docs in Chinese](https://discountry.github.io/react/).

We've been working on progress.

**Comment by jiyinyiyong** [comment]
There was a Chinese translation before on http://reactjs.cn/ , before React updated and the docs outdated. After that it is no longer maintained.

Related discussion here http://react-china.org/t/react-js/398/ People need it badly!

![image](https://cloud.githubusercontent.com/assets/449224/26399424/7536ac6a-40af-11e7-9be2-d4df87428aee.png)

**Comment by hyy1115** [comment]
Do you need such a Chinese document?：[https://discountry.github.io/react/](https://discountry.github.io/react/)

**Comment by gaearon** [comment]
We are tracking localization effort in https://github.com/facebook/react/issues/8063.

**Comment by gaearon** [comment]
We've launched our first translations, and many need more contributors.

https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html
