### ISSUE TITLE
Functional .setState() as default in docs, tutorials and first steps guides

### ISSUE THREAD

**Issue by freddi301** [facebook/react#9703]

**Comment by jordanpapaleo** [comment]
@gaearon I'd be happy to update the docs, tutorials, and examples here but I am not sure what the desired outcome is.  Do you want the object setState replaced with the function everywhere?

**Comment by jordanpapaleo** [comment]
Update

- [x] Tutorial.md PR#9731
- [ ] State and Lifecylces

**Comment by jordanpapaleo** [comment]
I was searching through and finding them then putting in PRs for each find.  This is getting tedious.  My last per for this will cover the rest of the docs

**Comment by jordanpapaleo** [comment]
I think I got them all. :)

**Comment by aweary** [comment]
Thanks for doing that @jordanpapaleo! It might be better for the git history if it was all done in a single PR, what do you think @gaearon?

**Comment by freddi301** [comment]
Hi @gaearon,
I can't imagine precisely the outcome but the goal here is to reveal intent.
`this.setState({ ... })` does not communicate that this method is async, and can lead to subtle bugs for devs who do not read carefully the docs.
Meanwhile `this.setState(oldState => ({ updating 'new state' }))` screams: "This method is async".
As functional programming spread in many javascripter's heart a more FP description could say:
```this.setState(functionally => ({ update: 'state', like: 'a monad or reducer' }), () => { console.log("some correlated effect when done") })```
Or more succintly: `{ ..., action/*type*/ (/*payload*/) { this.setState(reducer /*state => state*/, effectThunk) }, ... }` emulating flux/redux namings.
As a rule of thumb where to update the docs i would say that when you need to read previous state to update to use a lambda, while where you update the state regardless of existing one the object version could stay.

**Comment by jordanpapaleo** [comment]
I had no idea it would be so many when I started. Nor did I know that I would get them all done last night.  But at least they are small easy to approve prs ;)



Sent from my smallest computer

On May 21, 2017, at 2:04 AM, Brandon Dail <notifications@github.com> wrote:

Thanks for doing that @jordanpapaleo! It might be better for the git history if it was all done in a single PR, what do you think @gaearon?

**Comment by jordanpapaleo** [comment]
In a fiber presentation I heard that the non functional approach may be going away?  Having all examples in function format would be good in that case.  But I defer to gearon

**Comment by bvaughn** [comment]
As mentioned on the associated PR, the documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org).

I'm going to close this issue for now.
