### ISSUE TITLE
Bug: react-dom still contains reference to React.PropTypes

### ISSUE THREAD

**Issue by funkjunky** [facebook/react#9704]
React sends out a deprecation warning about using React.PropTypes, and the stack trace points to React-Dom.

Because of our webpack config, im not 100% sure where it is, but here are the surrounding lines of code:
See the onChange key.

```javascript
var propTypes = {
  value: function (props, propName, componentName) {
    if (!props[propName] || hasReadOnlyValue[props.type] || props.onChange || props.readOnly || props.disabled) {
      return null;
    }
    return new Error('You provided a `value` prop to a form field without an ' + '`onChange` handler. This will render a read-only field. If ' + 'the field should be mutable use `defaultValue`. Otherwise, ' + 'set either `onChange` or `readOnly`.');
  },
  checked: function (props, propName, componentName) {
    if (!props[propName] || props.onChange || props.readOnly || props.disabled) {
      return null;
    }
    return new Error('You provided a `checked` prop to a form field without an ' + '`onChange` handler. This will render a read-only field. If ' + 'the field should be mutable use `defaultChecked`. Otherwise, ' + 'set either `onChange` or `readOnly`.');
  },
  onChange: React.PropTypes.func
};
```

**Comment by ali-l** [comment]
I think this is the line in the current code:
https://github.com/facebook/react/blob/b1768b5a48d1f82e4ef4150e0036c5f846d3758a/src/renderers/dom/shared/utils/ReactControlledValuePropTypes.js#L63

It was changed on April 11th, by this commit:
https://github.com/facebook/react/commit/2beec2f308e27dbe902a8d68e1fc9f3d70ee9372#diff-ad8e841b7ba800185fa4df86f5887a43L60

Perhaps the version of ReactDOM you are working with is out of date. Or maybe the change hasn't been released yet.

**Comment by nhunzaker** [comment]
Oh no! @bvaughn What do you think? Should this be turned into a manual proptype definition instead of referencing PropTypes?

**Comment by funkjunky** [comment]
You're right ali-l. I was using 15.4, not 15.5. I'm updating it now... and I'll likely close this in a moment when everything works.

**Comment by funkjunky** [comment]
React and React-dom re both 15.5.4 now and the same error still exists.

**Comment by gaearon** [comment]
Both @acdlite and @bvaughn are at React Europe now so this will need a volunteer to look into it.

**Comment by nhunzaker** [comment]
@funkjunky How do you feel about taking this on?

**Comment by funkjunky** [comment]
Sure.

**Comment by funkjunky** [comment]
I was sorta excited to participate, but as Ali-l mentioned it has been patched. I grepped for React.PropTypes and it appears it's been cleaned up everywhere.

I'll close this and just wait for the next release. Thanks for your help everyone.

**Comment by nhunzaker** [comment]
No worries! If you run into something else you want to tackle, feel free to reach out! I'm happy to run through getting things setup, and way finding the code as best I can.

**Comment by funkjunky** [comment]
Thanks nhunzaker :)

I may as well mention that through my grep I found some tests and errors still mentioning React.PropTypes.
