### ISSUE TITLE
ES6 object shorthand as props

### ISSUE THREAD

**Issue by pkrawc** [facebook/react#9707]
Hi there,

I find myself wanting this feature a lot. I will name some const `something` and then find myself having to pass it in like so:

```javascript
<SomeComponent something={something} />
```

I would love to be able to use the es6 shorthand notation for object creation that assumes `{object: object}` if it's just passed in as `{object}`. So in a component it would work like:

```javascript
<SomeComponent {something}/> // === <SomeComponent something={something} />
```

Does anyone else find this a worthwhile change?

**Comment by gaearon** [comment]
Yes, we want to do something like this in the future.
Please see https://github.com/facebook/jsx/issues/23.
