### ISSUE TITLE
Better docs for integrating with jQuery et al

### ISSUE THREAD

**Issue by petehunt** [facebook/react#971]
Apparently the docs aren't too clear on this: https://plus.google.com/+IanBicking/posts/D1W2yqRh3BB

We need to have a section in the docs that talks about how to integrate with third party plugins in more detail, and stress the difference between mounting and updating.

**Comment by gaearon** [comment]
We should do it, but keeping a bunch of old issues around doesn't help visibility.
Putting this as umbrella item in #8060.
