### ISSUE TITLE
BUG: input type="number"

### ISSUE THREAD

**Issue by pingan1927** [facebook/react#9712]
```
render () {
  <input type="number" value={this.props.value} />
}
```

for example, when the original value is '.98', we need format it to '0.98'. but it is not  take effect。

```javascript
class Test extends React.Component {
 state = {
    value: '.98',
  }
 changeValue = () => {
    alert(0.98);
    this.setState({
      value: '0.98',
    });
  }

 render() {
    return <div>
      <input type="number" value={this.state.value} />
      <button onClick={this.changeValue}>changeValue</button>
    </div>;
  }
}

ReactDOM.render(<Test />, mountNode);
```

**Comment by rocky-jaiswal** [comment]
This is working for me - https://codepen.io/anon/pen/LLEzwN?editors=1010

**Comment by pingan1927** [comment]
your example is not same with mine. the key is .98 can't be formated to 0.98. Because as number they are equal.

**Comment by nhunzaker** [comment]
@aweary Just housekeeping. Do we close out issues before a release with the fix has shipped or wait?

**Comment by aweary** [comment]
@nhunzaker typically I close the issue once the has been merged into master 👍

**Comment by nhunzaker** [comment]
Awesome, thanks! @pingan1927 This should land in the next minor release of React: `15.6.0`
