### ISSUE TITLE
Add to license FAQ: Handling the patent grant on redistribution

### ISSUE THREAD

**Issue by smancke** [facebook/react#9715]
Could you please add a clarification to the [License FAQ](https://code.facebook.com/pages/850928938376556) which describes the rights and obligations concerning the patent grant when redistributing ReactJS?

E.g. something like this:
"If I redistribute ReactJS to a third party in any form (e.g. fork and modify it, or incorporate it in my product). Is it allowed to choose only the BSD License as my license and drop the additional patent grant?"

--> My guess: yes!

"If I redistribute ReactJS to a third party in any form (e.g. fork and modify it, or incorporate it in my product). Is it possible to also transfer the additional patent grant to my receivers of the derived work?"

--> My guess: No. The patent grant is only a license between facebook and their direct receivers. Formally you have to delete the patent grant and the third party has to receive this license from the react upstream project.

"Is the Facebook license compatible with the GPLv2?"

--> My guess: Yes it is. Since the BSD-3-Clause is and the patents grant is only an addition.

**Comment by gaearon** [comment]
Can you please email **legal@fb.com** and get in touch with them?
They worked on the FAQ so they’re the best people to respond here.
You can also talk to @lacker if you have concerns.

**Comment by smancke** [comment]
@gaearon thanks, I'll do so.

**Comment by smancke** [comment]
@gaearon I got an auto reply:
"This is an unsupported email alias and our team is unable to receive reports through this channel."

Maybe it's only an internal alias ..

**Comment by lacker** [comment]
In general we suggest asking your own lawyer if you're concerned about specific issues like this. I don't know that our FAQ can be exhaustive, and I wouldn't want to tell you hey hang on and wait for some clarification here. I will bring these questions up and others like them with our internal legal team, to see how straightforward it would be to build out the FAQ in more detail.

**Comment by smancke** [comment]
@lacker Thanks for your engagement on that.
And yes, we are already on making our own decision on that. But an official statement of Facebook about the redistribution would be good on that, anyways.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
