### ISSUE TITLE
Licensing FAQ suggestion: Adding links to remove ambigity

### ISSUE THREAD

**Issue by thomasgwatson** [facebook/react#9716]
Referring to https://code.facebook.com/pages/850928938376556

Specifically:

"Does termination of the additional patent grant in the Facebook BSD+Patents license cause the copyright license to also terminate?

No."

It is unclear as to what the 'copyright license' referred to in that quote is. 

Would directly linking the words 'additional patent grant' to https://github.com/facebook/react/blob/master/PATENTS and the words 'copyright license' to https://github.com/facebook/react/blob/master/LICENSE (or a more appropriate document) be possible/permissible for the Facebook Legal team? (Editing to note that the link would have to be to the Facebook OSS wide versions of these, not just the React specific licenses.)

**Comment by thomasgwatson** [comment]
@lacker I saw you mentioned in relation to patent/legal shenanigans, so pinging you :) 

For context, this would help a multi-national company, who is a partner of Facebook (you guys use our services), use Facebook OSS.

**Comment by gaearon** [comment]
I appreciate the questions, but I would prefer that we don’t use React’s issue tracker for this.
We use it for bug reports and feature requests, and it is not the best venue for legal matters.
I suggest to reach out to @lacker in private if he planned to collect feedback. Thanks!

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
