### ISSUE TITLE
React 16 without ES6, virtually impossible?

### ISSUE THREAD

**Issue by lorenzos** [facebook/react#9721]
On thing I like about React is that we can still use it for micro apps (where small portions of the website need user interaction, but a declarative UIs can still simplify development a lot), without having to setup a whole build environment, that for this use cases looks definitely overkill.

I know I may sound like a grumpy grandpa,but I'm worried that this will be not be true anymore in React 16:

- With the deprecation of `React.createClass` and `React.PropTypes` we will need external modules for sure. Then we need to bundle that modules for the browser and expose them as globals. We can't just load React from a CDN and write code anymore.

- Also when using `create-react-class`, warnings are still issued, like *getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.* Maybe this is in fact a bug?

- Possibly more issues?

Am I wrong? If not, should we stick with React 15, or what? Maybe we can start making React builds specifically for non-ES6 environments, bundling needed external modules, etc?

**Comment by gaearon** [comment]
>Then we need to bundle that modules for the browser and expose them as globals. We can't just load React from a CDN and write code anymore.

They already have bundled versions, you just need to include them as `<script>` tags.

>Maybe this is in fact a bug?

Maybe. File it?

**Comment by lorenzos** [comment]
> Maybe. File it?

I tried to reproduce it in minimal environment for filing the bug, but I failed. Turned out I was intentionally using a development version of React, but with the minified version of `create-react-class`. Therefore `create-react-class` did not set `isReactClassApproved` and React issued the warning :man_facepalming:

**Comment by gaearon** [comment]
Interesting, thanks for explaining!
