### ISSUE TITLE
No warning about missing 'key' prop for array of arrays

### ISSUE THREAD

**Issue by Ogre--** [facebook/react#9727]
I believe the following is a bug.

An array of div elements without 'key' props will correctly result in a warning, but an array of length 1 arrays containing the same div elements will not result in a warning.

For example:
https://jsfiddle.net/ua6Lqn1m/

I believe the correct behavior is for the the array of arrays of div elements to also result in a warning.

React 15.5.4, Firefox

**Comment by gaearon** [comment]
This was fixed in React 16.

<img width="356" alt="screen shot 2017-10-04 at 20 45 16" src="https://user-images.githubusercontent.com/810438/31196254-f56cb372-a944-11e7-9b11-0ccc3c8f8e68.png">
