### ISSUE TITLE
[Docs] Visual re-align

### ISSUE THREAD

**Issue by joecritch** [facebook/react#9728]
Hi folks.

I'm having a shot at a visual re-align for the React docs.

**Goals**

- Create a conservative re-align, that isn't controversial; but still opens up opportunity for future expansion and features (heading towards more of a design system)
- Avoid major architectural changes, which are best handled as separate PR's in the future

**Inspiration**

- GraphQL.org
- Other gridded sites :)

**Process**

- Just mockups at the minute, before I receive the go ahead
- I would then work on the rest of the elements & viewport sizes
- Then write the CSS (from scratch? thoughts?)

**Other notes**

- Moved sidebar to right hand side to improve readability
- Collapsed non-current docs nav categories
- Add an 'intro' paragraph (the first para) to each docs page 
- 5px baseline grid
- 4 column grid
- Proxima Nova (same as current site)
- The footer layout would be tightened up (it's just a screenshot of the current one, atm)

Fire away with your comments.

![react-docs-3](https://cloud.githubusercontent.com/assets/24449/26279438/d4b03fe6-3dab-11e7-9111-0eb6ca565fcb.png)

![react-docs-home-2](https://cloud.githubusercontent.com/assets/24449/26279439/d4b075a6-3dab-11e7-8379-4bc07ec74648.png)

cc @gaearon

**Comment by joecritch** [comment]
The screenshots look a little fuzzy for some reason. Here's the mockups as PDFs.

[docs-home.pdf](https://github.com/facebook/react/files/1016527/docs-home.pdf)
[docs.pdf](https://github.com/facebook/react/files/1016528/docs.pdf)

**Comment by gaearon** [comment]
cc @lacker Would you be interested in this?

**Comment by lorenzos** [comment]
+1 as long as the right sidebar follows page scrolling :smile: [This technique](http://jsfiddle.net/ryanmaxwell/25QaE/) can be useful if the sidebar is quite tall (like the one currently online).

**Comment by joecritch** [comment]
@gaearon Just checking in on this. How do you think we should we move foward? (cc @lacker too :-)

**Comment by bvaughn** [comment]
This looks slick! I'd love to lend a hand with this if you need one.

**Comment by joecritch** [comment]
@bvaughn Glad you're into it! I'd love your help dude. Safe for me to get started, then we'll sync? Any thoughts on writing it with new markup?

**Comment by bvaughn** [comment]
@joecritch I don't have the final say on what happens to the docs site but I've been interested in improving it for a while now too. I'll chat about it with Tom in the next day or so and get some more context.

**Comment by joecritch** [comment]
@bvaughn Cheers Brian 👍

**Comment by joecritch** [comment]
@bvaughn I think we can consider this closed ;)

**Comment by gaearon** [comment]
😻
