### ISSUE TITLE
Can react-proxy be served with a restrictive CSP policy from server without throwing error in Firefox??

### ISSUE THREAD

**Issue by OctopusGunner** [facebook/react#9744]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Firefox throws error when running a react application and using a csp header with script-src set to 'self'. In my case the error looks like this:

> Content Security Policy: The page’s settings blocked the loading of a
> resource at self (“script-src http://localhost:8000”).

(I set the 'self' keyword on script-src which in this error message is translated to localhost:8000)

The error message in FF links to the following row in my react bundle:

    ProxyComponent = new Function('factory', 'instantiate', 'return function ' + displayName + '() {\n         return instantiate(factory, this, arguments);\n      }')(function () {

from the file

> react-proxy/modules/createClassProxy.js

I can get rid of the error in FF by allowing unsafe-eval in my csp policy but I dont want to do that...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Run a react application in FF browser and with CSP policy for script-src set to 'self'. Check the console for errors.

**What is the expected behavior?**

There is a error handling in the source code for the event that execution environment does not allow dynamic evaluation, but it still shows an error in FF

`try {
    // Create a proxy constructor with matching name
    ProxyComponent = new Function('factory', 'instantiate', 'return function ' + displayName + '() {\n         return instantiate(factory, this, arguments);\n      }')(function () {
      return CurrentComponent;
    }, instantiate);
  } catch (err) {
    // Some environments may forbid dynamic evaluation
    ProxyComponent = function ProxyComponent() {
      return instantiate(function () {
        return CurrentComponent;
      }, this, arguments);
    };
  }`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

>   "name": "react-proxy",
>   "version": "3.0.0-alpha.1",

Firefox version 51.0.1 on Ubuntu.

**Comment by gaearon** [comment]
`react-proxy` is not part of React, please file this with https://github.com/gaearon/react-proxy instead.
You are probably using it indirectly through React Hot Loader.

**Comment by OctopusGunner** [comment]
Thanx @gaearon
