### ISSUE TITLE
[Question] Listen all user events (SyntheticEvents)

### ISSUE THREAD

**Issue by lfirek** [facebook/react#9746]
Hello :smile: 

My question is about react synthetic events and how listen all this events in parent component.

I want track my user activity so i want handle all mouse events, wheel events etc.
It's possible to listen this event and if yes how I can do that?

Yes, I can listen window or document events but i can't localize what component make this event.

Or maybe it's possible to localize component by using EventTarget? 

Thanks!

**Comment by ahlusar1989** [comment]
@lfirek If you are looking for an excellent resource and source for understanding how to implement Synthetic Events, here are some potential resources:

- https://github.com/oliviertassinari/react-event-listener

- https://facebook.github.io/react/docs/events.html

A perhaps archaic, and trivial example for handling touch events using ES6, would be as follows: https://codesandbox.io/s/2rVrZkRj

**Comment by lfirek** [comment]
@ahlusar1989 It's not solution for my problem.

I want handle ALL events from childs..childs

**Comment by ahlusar1989** [comment]
Thank you for further clarifying your question @lfirek. What I hear you saying is 1) you would like a child component to bubble up its events to its parent component or 2) you would just use `event.target`, correct?

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
