### ISSUE TITLE
create-react-class cannot be compiled with latest Google Closure Compiler

### ISSUE THREAD

**Issue by elijahsmith** [facebook/react#9750]
When trying to compile create-react-class 15.3.1 with the latest Closure Compiler, the compiler complains:
```
react.js:4782: ERROR - @nosideeffects may only appear in externs files.
  render: SpecPolicy.DEFINE_ONCE,
```
This is related to https://github.com/facebook/react/issues/7551.  The create-react-class npm package needs to be republished with the React 15.5.4 code.

This ticket is spun off of https://github.com/facebook/react/issues/7551#issuecomment-294633325.

**Comment by elijahsmith** [comment]
we are blocked on this issue (our build system relies on the Closure Compiler, and some of our dependencies use create-react-class).  Is there anything I can do to help this process forward?

**Comment by gaearon** [comment]
This is fixed in https://github.com/facebook/react/pull/9933 and will be out with next release.

**Comment by elijahsmith** [comment]
this change is not in 15.6.0 nor the latest build of the create-react-class npm package

https://github.com/facebook/react/blob/v15.6.0/addons/create-react-class/factory.js#L163

do we need to wait for 15.6.1?

**Comment by gaearon** [comment]
See my comment in https://github.com/facebook/react/issues/7551#issuecomment-308272011.

It is in the 15.6.0 RC of addons (it will be released separately today).
