### ISSUE TITLE
ReactLink still using React.PropTypes.

### ISSUE THREAD

**Issue by lrojas94** [facebook/react#9755]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
React is using React.PropTypes even though it states it's going to be deprecated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
https://github.com/facebook/react/blob/15-stable/src/addons/link/ReactLink.js#L62

**What is the expected behavior?**
Should use PropTypes from the `prop-types` package.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.5.4

**Comment by flarnie** [comment]
Thanks for reporting this @lrojas94!

We might want to do a release of that add-on via npm. I can look into that.

**Comment by gaearon** [comment]
We fixed this in https://github.com/facebook/react/pull/9766. Will be out in next release.
