### ISSUE TITLE
Make the docs site responsive

### ISSUE THREAD

**Issue by chenglou** [facebook/react#976]
First because why not =). Second, it'll be good for tools like [Dash](http://kapeli.com/dash) to display the documentation in a smaller window.

**Comment by titoBouzout** [comment]
Impossible to read on mobile, is a pity as reading docs is a task you can do anywhere, but with the  width that covers more than 100% is very hard, and the font size is to tiny.

**Comment by chenglou** [comment]
Flowtype.org is responsive. We should steal that.

**Comment by titoBouzout** [comment]
Kind of workaround that just works for me https://titobouzout.github.io/react/

**Comment by yaycmyk** [comment]
@titoBouzout the nav bar is screwed up, but otherwise looks ok

**Comment by spicyj** [comment]
We'll revisit this when we next redesign the website.
