### ISSUE TITLE
It seems the legal stuff is making things difficult

### ISSUE THREAD

**Issue by paaljoachim** [facebook/react#9760]
Hi

Please make the legal language easier to understand and more user friendly so that anyone can use it without having to worry. 

https://discuss.reactjs.org/t/legal-department-did-not-allow-use-of-react/3309/6

**Comment by gaearon** [comment]
The issues in the repository are read by developers by you, not by lawyers.
We use them for feature requests and bug reports.

Please feel free to contact @lacker for any questions about the license, but for now https://code.facebook.com/license-faq is as much clarification as we could provide.

**Comment by paaljoachim** [comment]
Thanks Dan.
I apologize for my pollution.

@lacker 

Do please readjust the legal language used in react to make it easier for users to use react without worrying about legal trouble. Thanks.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by paaljoachim** [comment]
That is awesome!!
