### ISSUE TITLE
Improve React and ReactNative sync scripts

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#9763]
Follow-up work from PR #9626.

### Sync React to www changes

- [ ] The current process of syncing React to Facebook www involves running a script from within the www repo. It would be nice to relocate that script to the React repo, since it's coupled with the React build process and shims anyway. At this point we could better share code (eg the auto-generated change log) between the React Native sync script and the React sync script.
- [ ] Update/add documentation for the new sync process.

### Sync ReactNative to fbsource changes

- [ ] It should be possible to sync React and ReactNative simultaneously.
- [ ] Update the ReactNative sync script to auto-generate a change log based on the commits in master since the last sync. (This is something the React sync script currently does; once that script has been moved into the React GitHub we can just share the code.)
- [ ] Remove `js1 upgrade react` script from fbsource. Both React and ReactNative should be synced to fbsource in the same way as React is synced to www, using the new central sync scripts.
- [ ] Update/add documentation for the new sync process.

### Secondary goals

* Syncing www and fbsource should be as similar as possible to avoid confusion.
* Would be nice if it was easy for non-core-team members to run sync scripts also.

**Comment by bvaughn** [comment]
cc @gaearon for thoughts about this approach regarding www
cc @yungsters for thoughts regarding fbsource

**Comment by yungsters** [comment]
This sounds like a great idea. Feel free to replace the `js1` command.

**Comment by bvaughn** [comment]
Closing in favor of an internal diff 😄
