### ISSUE TITLE
Example from documentation not working

### ISSUE THREAD

**Issue by sarbull** [facebook/react#9767]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Example from the documentation not working on MacOS in Chrome

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to https://facebook.github.io/react/docs/thinking-in-react.html#step-2-build-a-static-version-in-react, try to filter things by entering data in the input textbox.

**What is the expected behavior?**
Filter out the content.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I don't know.

**Comment by klaasman** [comment]
It's a tutorial with step 2 being a static version.
Scroll further to step 5 to see an actual working example: 
https://facebook.github.io/react/docs/thinking-in-react.html#step-5-add-inverse-data-flow

**Comment by gaearon** [comment]
Yep, this seems expected. If you have ideas about changing wording to be clearer please send a pull request and we will take a look!
