### ISSUE TITLE
[Question] How to make Table Date Scheduler with Previous and Next Button in React

### ISSUE THREAD

**Issue by fgseneres** [facebook/react#9774]
![screen shot 2017-05-25 at 4 33 50 pm](https://cloud.githubusercontent.com/assets/27617963/26442664/0b7fc356-4168-11e7-8a1a-adf54da88893.png)

**Comment by eightfeet** [comment]
I think you need momentjs ，https://momentjs.com

**Comment by fgseneres** [comment]
Thank you @eightfeet I will try

**Comment by aweary** [comment]
Hey @fgseneres! We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
