### ISSUE TITLE
"Orphaned" doc page

### ISSUE THREAD

**Issue by gsklee** [facebook/react#9782]
https://facebook.github.io/react/docs/perf.html

Just found out this page which is not being linked to from anywhere else of the online docs as far as I can tell. Is this an old page needs to be removed or a new page that somehow weren't added properly?

**Comment by gaearon** [comment]
We intentionally hid it as this addon won't make it into React 16. Might've been wise to do it later maybe.

**Comment by flarnie** [comment]
I don't know if we have a clear precedent about where to put docs for deprecated or moved features. How about this - 
1. While there are warnings about a feature in the current version of React, add a note to the docs but leave them accessible in the main navigation.
2. Once they are fully moved/removed in the current released version of React, we "orphan" the doc pages, eventually moving them to gists and setting up redirects.

I think we may have other "orphaned" doc pages for features which are still not fully removed from React.

**Comment by gaearon** [comment]
Yea. At this point I'm not sure if it's worth bringing them back but I guess we can. They're still searchable from Google.
