### ISSUE TITLE
Chrome scroll position not preserved

### ISSUE THREAD

**Issue by josalmi** [facebook/react#9789]
**Do you want to request a *feature* or report a *bug*?**

Bug possibly in React or Google Chrome

**What is the current behavior?**

Scroll position is not preserved when children of an element list change order. Bug seems to apply only when React keys of the child elements are unchanged. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Demo available here: https://jsfiddle.net/930m9grq/3/

Broken case:

0. (Resize the demo window until it's scrollable [if not already])
1. Scroll to bottom of the window
2. Click on the refresh button on the left
3. Window will scroll up automatically

**What is the expected behavior?**

Window should keep the scroll position.

Working case:

0. (Resize the demo window until it's scrollable [if not already])
1. Scroll to bottom of the window
2. Click on the refresh button on the right
3. Window will not scroll up (expected behavior)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested React version was 15.5.4. Older versions were not tested.

Affected browsers:
OSX 10.12.5 / Google Chrome 58.0.3029 (Official Build) (64-bit)
OSX 10.12.6 (Beta 1) / Google Chrome 59.0.3071.71 (Official Build) beta (64-bit)

**Not** affected:
OSX 10.12.6 (Beta 1) / Firefox 53.0.2 (64-bit)
OSX 10.12.6 (Beta 1) / Safari Version 10.1.2 (12603.3.1)

**Comment by gaearon** [comment]
How did you isolate this to be a bug in React? If you do the same manipulations with just DOM methods, do you not have the same issue?

**Comment by syranide** [comment]
I can't reproduce this on Windows.

**Comment by aweary** [comment]
I'm unable to reproduce this on OSX 10.12.2 (16C67) running Chrome 58.0.3029.110 (64-bit)

**Comment by josalmi** [comment]
Sorry! Seems to be issue with Chrome as I was able to reproduce the bug using dom manipulations manually. For those who are interested: https://jsfiddle.net/6hbhgxjt/

![GIF](https://cloud.githubusercontent.com/assets/5629299/26506024/b50ae874-4253-11e7-9c27-2e5bf750d252.gif)
