### ISSUE TITLE
Non-Sensical Code in Official React Blog post: How to submit a PR for the official React blog?

### ISSUE THREAD

**Issue by idibidiart** [facebook/react#9801]
Hey guys,

A while back I came across this post on the official React blog that contained a code example that made no sense and did not implement the intent expressed in the blog post, which is to cancel a Promise in ComponentWillMount so setState is only invoked while component is mounted. I ignored it back then, but I just remembered again after I saw a tweet today about the same topic from @gaearon  (https://twitter.com/dan_abramov/status/868635169955119105)

The blog post in question is: 

https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

The non-sensical/non-working code is:

```js
// If you use ES6 promises, you may need to wrap your promise in order to make it cancelable.

const cancelablePromise = makeCancelable(
  new Promise(r => component.setState({...}}))
);

cancelablePromise
  .promise
  .then(() => console.log('resolved'))
  .catch((reason) => console.log('isCanceled', reason.isCanceled));

cancelablePromise.cancel(); // Cancel the promise

// Where makeCancelable is defined by @istarkov as:

const makeCancelable = (promise) => {
  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve, reject) => {
    promise.then((val) =>
      hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
    );
    promise.catch((error) =>
      hasCanceled_ ? reject({isCanceled: true}) : reject(error)
    );
  });

  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
}; 
```

Try it:

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=const%20cancelablePromise%20%3D%20makeCancelable(%0A%20%20new%20Promise(r%20%3D%3E%20setTimeout(()%20%3D%3E%20alert(%22we%20should%20not%20see%20this%22)%2C%202000))%0A)%3B%0A%0AcancelablePromise%0A%20%20.promise%0A%20%20.then(()%20%3D%3E%20console.log('resolved'))%0A%20%20.catch((reason)%20%3D%3E%20console.log('isCanceled'%2C%20reason.isCanceled))%3B%0A%0AcancelablePromise.cancel()%3B%20%2F%2F%20Cancel%20the%20promise%0A%0Aconst%20makeCancelable%20%3D%20(promise)%20%3D%3E%20%7B%0A%20%20let%20hasCanceled_%20%3D%20false%3B%0A%0A%20%20const%20wrappedPromise%20%3D%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20promise.then((val)%20%3D%3E%0A%20%20%20%20%20%20hasCanceled_%20%3F%20reject(%7BisCanceled%3A%20true%7D)%20%3A%20resolve(val)%0A%20%20%20%20)%3B%0A%20%20%20%20promise.catch((error)%20%3D%3E%0A%20%20%20%20%20%20hasCanceled_%20%3F%20reject(%7BisCanceled%3A%20true%7D)%20%3A%20reject(error)%0A%20%20%20%20)%3B%0A%20%20%7D)%3B%0A%0A%20%20return%20%7B%0A%20%20%20%20promise%3A%20wrappedPromise%2C%0A%20%20%20%20cancel()%20%7B%0A%20%20%20%20%20%20hasCanceled_%20%3D%20true%3B%0A%20%20%20%20%7D%2C%0A%20%20%7D%3B%0A%7D%3B

The blog post is even referenced from a StackOverflow answer that was given 21 points. This is pretty ridiculous for a non-working, non-sensical example code.

AFAIK, other than using schemes that rely on Promise.race (with own limitations/issues, see here: https://esdiscuss.org/topic/cancel-promise-pattern-no-cancellable-promises) there is no way to *cancel* ES6 Promises. AFAIK, the Cancellable Promise ES Proposal had been withdrawn.

The right way to do Promise cancellation is with userland Promise implementations. I'd recommend Bluebird Promise library. For details see: http://bluebirdjs.com/docs/api/cancellation.html

**Comment by gaearon** [comment]
All posts are in the docs folder, you can send PRs against them. It would help if you clarified which part of the code doesn't make sense to you.

**Comment by aweary** [comment]
I can clarify what problems I think @idibidiart is pointing out:

* `makeCancelable` uses `const` so it's not hoisted, so it throws an error since its used at the top of the file.
* The example uses a promise that doesn't resolve, so `cancelablePromise.promise.then` is never called. If you do use resolve then you get some cancellation behavior where the `then` chained on the wrapped promise isn't called and `catch` is when canceled.
* This may just be a point of confusion, but the code within the original Promise will execute no matter what you do. So cancellation doesn't prevent the wrapped promise from resolving, it just manages whether `then` or `catch` will be called once it does resolve.

**Comment by gaearon** [comment]
Happy to take a PR changing this to a working approach. (I think this was just copy pasted from comments and I don't know if the person who merged it have tested it.)

**Comment by aweary** [comment]
It's worth noting that even with bluebird, cancellation does not mean that the original Promise callback does not execute. If you have a `setTimeout()` or other code that produces side-effects cancellation will not prevent that.

It will only control whether `then` is called. We could continue using the same example if we moved the `setState` into the `then` callback, instead of doing it in the Promise itself.

**Comment by idibidiart** [comment]
@aweary @gaearon 

The hoisting aside (I had just copied/pasted the code fron the blog post while on the plane yesterday without paying any attention), the other point @aweary stated are the obvious things that do not make sense relative to how ES6 Promise spec.

The very premise that you can cancel an ES6 promise is invalid relative to the ES6 Promise spec and not possible without some AST manipulation of the callback function to conditionally nullify it based on cancellation state in the outer scope. I did consider that the intent may have been to preempt the .then which is more straight forward with Bluebird and other userland implementations that support that kind of "cancellation" (a misnomer imo, should be called 'then cancellation' not 'Promise cancellation')

> We could continue using the same example if we moved the setState into the then callback, instead of doing it in the Promise itself.

But you will need to add Promise resolution so that if cancel is not called the .then would be actually reached! 

Like so:

```js
const makeCancelable = (originalPromise) => {

  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve, reject) => {
   
    originalPromise.then((val) => {
      hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
    }
    );
    originalPromise.catch((error) => {
      hasCanceled_ ? reject({isCanceled: true}) : reject(error)
    }
    );
  });

  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
};

const cancelablePromise = makeCancelable(
  new Promise((resolve, reject) => {
    setTimeout(() => alert("original promise was executed"), 2000)
    resolve()
  })
);

cancelablePromise
  .promise
  .then(() => console.log('resolved'))
  .catch((reason) => console.log('isCanceled', reason.isCanceled));

cancelablePromise.cancel(); // Cancel the promise
```

**Comment by idibidiart** [comment]
I fixed the comment to say "Cancel the .then" :)

**Comment by idibidiart** [comment]
@gaearon please make sure when you do take a PR that the language is informative and not misleading. There is nothing like "cancel the promise" It just does not exist in ES land.

**Comment by idibidiart** [comment]
Also, for the purpose of that blog post, I believe the setState should be in the cancellable .then not in the originalPromise which I assume is some XHR call or other async call that returns a promise. This way, the blog post would actually make sense in that it would demonstrate how to avoid setting state when a promisified xhr or other promisified async call is bound to succeed but the component is being unmounted. 

Makes sense?

**Comment by gaearon** [comment]
@idibidiart 

Thanks for explaining. I am well aware that promises are not really cancelable and that the language is somewhat misleading. There is no need to repeat this in every comment, we agree with your point 😉 .

If you feel very strongly about it you are welcome to submit a PR that does a better job at explaining this snippet (or even replace this snippet with another snippet that would make more sense to you). We’ll be happy to review and merge it.

This is not a high priority issue for us because this is a pretty old blogpost, and we have a ton of work to do to bring React 16 closer. So I’m sorry but we won’t be spending our time on this any time soon. But we are happy to take your contributions!

**Comment by idibidiart** [comment]
It's a huge pain point in ES spec discussions that we still have not arrived at consensus for cancellable promise. It is a huge issue with Promise spec, so I can scream it from the roof top because it is that painful. Cancellable Promise would simplify so much concurrent code, and make things fun again...  

Anyway, reason it came up besides your tweet reminding me of it is I encountered it with the latest version of React Native's ExNavigation.  I have apps built on that but now (without me using setState anywhere) I get a warning about it saying I should not call setState in unmounting component etc and when I trace it it goes back to ExNavigation's replaceImmediately (forgot exact method name) ... So it is a frustrating problem in React in general and I think it does not to be surfaced and taken care of. I'm moving to React Navigation so I'm not going to invest time in fixing the warning I'm getting from ExNavigation but ... I feel this is a common problem in React... common enough for me to cry out loud about it. But feel free to set the context for me... maybe I am mis-imagining the consequence of the lack of Cancellability in the ES6 Promise spec 

Hmm. Close this? Happy to make a PR if @aweary doesn't get to it first. :)

**Comment by aweary** [comment]
> Hmm. Close this? Happy to make a PR if @aweary doesn't get to it first. :)

Feel free to submit a PR, it's all yours! We can close this once the change has landed 👍

**Comment by idibidiart** [comment]
Great. Done. @aweary please feel free to review

**Comment by gaearon** [comment]
Seems like #9813 stalled. I don't feel strongly about fixing this, but as I said in #9813 I'm happy to just remove a misleading example if somebody sends a PR.
