### ISSUE TITLE
array.map() has not render in v15.5.4

### ISSUE THREAD

**Issue by phaptq** [facebook/react#9802]
My code:

![screenshot_3](https://cloud.githubusercontent.com/assets/19235110/26543857/bf6fb2c6-4489-11e7-88af-2c4fb88ae4e3.png)

and screen + console
![screenshot_4](https://cloud.githubusercontent.com/assets/19235110/26544000/56f80cd8-448a-11e7-8cde-e7ac3259ff95.png)

show for me that problem. Please.
Thanks!

**Comment by ematipico** [comment]
You have to place a return inside your `map` function

**Comment by phaptq** [comment]
Thanks @ematipico

**Comment by gaearon** [comment]
This is what the warning in the console says too. :wink:
I recommend reading those warnings as they often point out mistakes.
