### ISSUE TITLE
React ignores CSS grid properties in style attribute

### ISSUE THREAD

**Issue by jonrimmer** [facebook/react#9805]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using [CSS grid properties](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) in an element's style attribute does not work. React ignores them.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

http://plnkr.co/edit/JaMCvqj9znnwuDyTnB9Z?p=preview

**What is the expected behavior?**

React should include CSS grid properties, and all other CSS properties, in the rendered DOM.

If React only intends to support a subset of CSS, then this should be made clear in the documentation, and the supported properties should be enumerated. As it is, there is nothing to suggest that certain properties will work, and others won't (without any error message or warning indicating that they have been ignored).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v15.5.0

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react/pull/9185 and will be a part of 15.6.
