### ISSUE TITLE
[Fiber]ref(instance) cause error

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9807]
**Do you want to request a *feature* or report a *bug*?**
I am not sure,maybe a bug.

**What is the current behavior?**
```
Uncaught TypeError: ref is not a function
    at commitAttachRef (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:13520:7)
    at commitAllLifeCycles (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:13995:9)
    at HTMLUnknownElement.boundFunc (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:229:14)
    at invokeGuardedCallback (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:243:16)
    at invokeGuardedCallback (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:278:34)
    at commitAllWork (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:14101:19)
    at completeUnitOfWork (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:14241:11)
    at performUnitOfWork (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:14273:14)
    at workLoop (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:14395:26)
    at HTMLUnknownElement.boundFunc (eval at 18 (vendor.bf495772693e68a40763.js:746), <anonymous>:229:14)
```

And when I debugger,I find below:

![Imgur](http://i.imgur.com/VMCfXAb.jpg)

![Imgur](http://i.imgur.com/QyT4Hsx.jpg)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I use react-16.0.0-alpha.12. windows-64,chrome-canary-61.0.3113.0

**Comment by aweary** [comment]
@NE-SmallTown can you please provide an example reproducing your issue? It's difficult to debug without knowing what the source code is 😃 You can use [this JSFiddle](https://jsfiddle.net/wg43ch12/) which is running the latest alpha release.

**Comment by NE-SmallTown** [comment]
I will try,but that's a little tough,give a some times,thanks.

**Comment by gaearon** [comment]
I've seen this happen when you have duplicate `react` package. For example if you symlink to React build folder so you pull in both a stable and an unstable version by mistake. Delete your local `react` in `node_modules` and try again, assuming you are building from master. Also run `npm ls react` to check for duplicates.

**Comment by NE-SmallTown** [comment]
@gaearon Thanks.

But I am a little confused.You say "delete your local react in node_modules and try again",but if I delete,I think my project won't work.If I am wrong,please let me know.

And the result of `npm ls react` is 

```
+-- UNMET PEER DEPENDENCY react@16.0.0-alpha.12
`-- UNMET PEER DEPENDENCY react-dom@16.0.0-alpha.12

npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0-0, required by chai-enzyme@0.6.1
npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.8.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0-0, required by react-css-themr@2.1.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-router@3.0.5
npm ERR! peer dep missing: react@0.14.x || 15.x.x, required by react-rte@0.11.0
npm ERR! peer dep missing: react@^15.5.4, required by react-scroll@1.5.2
npm ERR! peer dep missing: react@0.14.x, required by react-spark-scroll@3.0.2
npm ERR! peer dep missing: react@0.14.x, required by react-spark-scroll-rekapi@3.0.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by redbox-react@1.3.6
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0-0, required by chai-enzyme@0.6.1
npm ERR! peer dep missing: react-dom@^15.4.2, required by react-addons-test-utils@15.5.1
npm ERR! peer dep missing: react-dom@0.14.x || 15.x.x, required by react-rte@0.11.0
npm ERR! peer dep missing: react-dom@^15.5.4, required by react-scroll@1.5.2
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by redbox-react@1.3.6
npm ERR! code 1
```

**Comment by gaearon** [comment]
If you install it back, what does npm ls react say?

**Comment by NE-SmallTown** [comment]
@gaearon 

After I delete react and react-dom,the `npm ls react` says:

```
+-- UNMET DEPENDENCY react@^16.0.0-alpha.12
`-- UNMET DEPENDENCY react-dom@^16.0.0-alpha.12

npm ERR! missing: react@^16.0.0-alpha.12, required by react-QuietWater-demo@
npm ERR! missing: react-dom@^16.0.0-alpha.12, required by react-QuietWater-demo@
npm ERR! code 1
```

And after re-install:

```
+-- UNMET PEER DEPENDENCY react@16.0.0-alpha.12
`-- UNMET PEER DEPENDENCY react-dom@16.0.0-alpha.12

npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0-0, required by chai-enzyme@0.6.1
npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.8.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0-0, required by react-css-themr@2.1.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-router@3.0.5
npm ERR! peer dep missing: react@0.14.x || 15.x.x, required by react-rte@0.11.0
npm ERR! peer dep missing: react@^15.5.4, required by react-scroll@1.5.2
npm ERR! peer dep missing: react@0.14.x, required by react-spark-scroll@3.0.2
npm ERR! peer dep missing: react@0.14.x, required by react-spark-scroll-rekapi@3.0.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by redbox-react@1.3.6
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0-0, required by chai-enzyme@0.6.1
npm ERR! peer dep missing: react-dom@^15.4.2, required by react-addons-test-utils@15.5.1
npm ERR! peer dep missing: react-dom@0.14.x || 15.x.x, required by react-rte@0.11.0
npm ERR! peer dep missing: react-dom@^15.5.4, required by react-scroll@1.5.2
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by redbox-react@1.3.6
npm ERR! code 1
```

**Comment by gaearon** [comment]
Eh, that’s annoying. npm doesn't print ls if there are unsatisfied peer dependencies 😞 

Basically what I’m saying is you have two Reacts somewhere. I’m pretty sure about it. I suggest you to check your Sources pane in browser console looking for React—you should see more than two different directories with it. Delete the extra one and it’ll be good.

If you’re sure it’s a React bug please provide your project and I’ll reopen.

**Comment by abbiranjan** [comment]
> Eh, that’s annoying. npm doesn't print ls if there are unsatisfied peer dependencies 😞
> 
> Basically what I’m saying is you have two Reacts somewhere. I’m pretty sure about it. I suggest you to check your Sources pane in browser console looking for React—you should see more than two different directories with it. Delete the extra one and it’ll be good.
> 
> If you’re sure it’s a React bug please provide your project and I’ll reopen.

I am also getting it for running project like if I give cmd like npm ls react
It used to give error like above even though I do not have multiple react version.

![Capture-11](https://user-images.githubusercontent.com/20059747/79776522-81b70180-8353-11ea-9203-59dc7e0d5c5b.PNG)
