### ISSUE TITLE
Returns the undefined question under this.props.form.getFieldsValue ()

### ISSUE THREAD

**Issue by LikeYakult** [facebook/react#9810]
### 1. Version：
antd , 2.10.2
### 2. Environment：
Chrome 58 , window 10
### 3.What did you do?
Use this.props.form.getFieldsValue () to take the value in the form
### 4.The code is as follows:
```
import React, { Component } from 'react';
import { Form, Input, Button } from 'antd';
const FormItem = Form.Item;
lass Demo extends Component{
    handleSubmit = (e) => {
        // 阻止事件冒泡
        e.preventDefault();
        var formData = this.props.form.getFieldsValue();
        console.log(formData);
    };
    render()  {
        const { getFieldDecorator } = this.props.form;
        return (
            <Form layout="horizontal" onSubmit={this.handleSubmit}>
                <FormItem label="Account">
                    <Input placeholder="please input the account"
                        {...getFieldDecorator('userName')}/>
                </FormItem>
                <FormItem label="Password">
                    <Input type="password" placeholder="Please input the pasword"
                        {...getFieldDecorator('passWord')}/>
                </FormItem>
                <Button type="primary" htmlType="submit">Submit</Button>
            </Form>
        );
    }
}
export default Demo = Form.create()(Demo);
```
### 5.The result you expect is:
Use this.props.form.getFieldsValue () to take the value in the form
### 6.The actual result is:
![qq 20170530182002](https://cloud.githubusercontent.com/assets/22496926/26579048/da026f26-4564-11e7-8eea-fe58fca2aa26.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by ummahusla** [comment]
I assume you copy and pasted incorrectly `lass Demo extends Component{`. Moreover, I guess this issue related more to the `react-form`?

**Comment by coluccini** [comment]
This is not directly related to React. Try asking in the corresponding repo:

https://github.com/ant-design/ant-design

**Comment by LikeYakult** [comment]
@ummahusla I also think to react-form question will be better, but it shut my question, how can I do, I am also very helpless ...

**Comment by LikeYakult** [comment]
@coluccini Thank you, I take a closer look

**Comment by ummahusla** [comment]
@LikeYakult Try https://stackoverflow.com/

**Comment by aweary** [comment]
Hey @LikeYakult! We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow, as mentioned above.

**Comment by LikeYakult** [comment]
@ummahusla Thank you

**Comment by LikeYakult** [comment]
@aweary OK, Thank you
