### ISSUE TITLE
Fix function arity issues

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#9817]
Flow 0.46+ supports [verifying the number of arguments passed to a function](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/).

Enabling this feature (`experimental.strict_call_arity=true`) and updating to Flow ^0.46.0 in master results in 40 arity errors.

- [x] PR #9816 reduces this to 28 errors.
- [ ] Fix remaining errors

**Comment by iamdustan** [comment]
Want me to rebase #9815 later?

**Comment by bvaughn** [comment]
Oh hey! Didn't see that PR yet.

PR #9816 resolves a few of the issues but not all of them. Happy to help track down the others.

**Comment by gaearon** [comment]
So did #9815 enable arity checks? Or do they need explicit opt in?

**Comment by bvaughn** [comment]
Looks like #9815 turned them on, based on [this](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/) which says:

> Flow v0.47.0 will ship with strict function call arity turned on and the `experimental.strict_call_arity` flag will be removed.

I'm guessing that means we can close this now?
