### ISSUE TITLE
Optimize defaultProps with propTypes

### ISSUE THREAD

**Issue by Stupidism** [facebook/react#9818]
**Do you want to request a *feature* or report a *bug*?**
feature, 
PropTypes.string('default string');
**What is the current behavior?**
Two statics representing the same thing is kind of Trivial. 
```js
Component.propTypes = {
  foo: T.string,
  bar: T.number.isRequired,
};
Component.defaultProps = {
  foo: '12',
}
```
Sometimes people write useless code with this design. And you can't tell what is the author wanted.
```js
Component.propTypes = {
  foo: T.string,
  bar: T.number.isRequired, // unnecessary isRequired.
};
Component.defaultProps = {
  foo: '12',
  bar: 12, // or unnecessary defaultProp.
}
```
**What is the expected behavior?**
Make defaultProps work with propTypes. One static other than two statics will be much easier for HOC and Developers to customize, modify or remove. 
```
Component.propTypes = {
  foo: T.string('12'),
  bar: T.number.isRequired,
  // or
  foo: T.string.default('12'),
};
```

**Comment by cdlewis** [comment]
Proptypes are being moved to a separate package in React 16. Perhaps you should file your issue there: https://github.com/facebook/prop-types.

**Comment by Stupidism** [comment]
goto prop-types repo: https://github.com/facebook/prop-types/issues/67
