### ISSUE TITLE
"componentDidMount" not being triggered on initial render.

### ISSUE THREAD

**Issue by sourabhChourasiya** [facebook/react#9820]
Below is the code in which i am facing the issue with all the life cycle method.
I am using electrode JS as a framework to make it render server side .

i am facing a random behaviour with the life cycle methods, some time it triggered some time not.

class BannersList extends React.Component {
  constructor(props) {
    super(props);
    this.createTable = this.createTable.bind(this);
    this.onChangePage = this.onChangePage.bind(this);
    this.state = {
      skip: 0,
      limit: 5,
    };
  }
  componentDidMount() {
    this.onChangePage(1);
  }
  onChangePage(page) {
    let skip = (page - 1) * this.state.limit;
    this.props.setBanner(endPoints.adminBanner, {}, skip, this.state.limit);
    this.setState({currentPage: page, skip: skip,});
  }
  createTable(row, index) {
    return (
      <tr key={index}>
        <td><img width="75px" height="100px" src={row.banner_image && row.banner_image} alt={row.title}
                 className="img-responsive img-thumbnail"/></td>
        <td>{row.title ? row.title : 'NA'}</td>
        <td>{row.display_section ? row.display_section : 'NA'}</td>
        <td>
          <StatusLabel isActive={row.status} labelText={{active: "Active", inactive: 'Inactive',}}/>
        </td>
        <td>{moment(row.createdAt, 'x').format('DD/MM/YYYY')}</td>
        <td><a className='btn btn-sm btn-info pull-right' href={'/admin/banner/edit/' + row._id}>Edit</a></td>
        <td><a className='btn btn-sm btn-danger' href={'/admin/banner/delete/' + row._id}>Delete</a></td>
      </tr>
    );
  }
  render() {
    let data = this.props.getBanners &&
      this.props.getBanners.data &&
      this.props.getBanners.data.items &&
      this.props.getBanners.data.items.length > 0 &&
      this.props.getBanners.data.items.map(this.createTable);

    return (
      <div>
        <section className="content-header">
          <h1>
            Banner
          </h1>
          <ol className="breadcrumb">
            <li><a href="/admin/dashboard"><i className="fa fa-dashboard"></i> Home</a></li>
            <li><a href="/admin/banner/list">Banner</a></li>
            <li className="active">List</li>
          </ol>
        </section>
        <section className="content">
          <div className="row">
            <div className="col-xs-12">
              <div className="box">
                <div className="box-header">
                  <h3 className="box-title"></h3>
                  <div className="box-tools">
                    <div className="input-group input-group-sm">
                      <input name="table_search" className="form-control pull-right" placeholder="Search" type="text"/>

                      <div className="input-group-btn">
                        <button type="submit" className="btn btn-default"><i className="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="box-body table-responsive">

                  <table className="table table-hover table-striped table-bordered">
                    <tbody>
                    <tr>
                      <th>Image</th>
                      <th>Title</th>
                      <th>Display Section</th>
                      <th>Status</th>
                      <th>Created At</th>
                      <th>&nbsp;</th>
                      <th>&nbsp;</th>
                    </tr>
                    {data && data}
                    </tbody>
                  </table>

                </div>
                <div className="box-footer text-center">
                  <Paginator limit={this.state.limit}
                             max={this.props.getBanners.data.total_count ? this.props.getBanners.data.total_count : 0}
                             onChange={this.onChangePage}/>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    );
  }
}

**Comment by nitish24p** [comment]
Can you format the code a bit better so that its comprehensible
```javascript
//JS code here
```

**Comment by ahlusar1989** [comment]
+1 @nitish24p

**Comment by aweary** [comment]
@sourabhChourasiya there is too much code here for us to reasonably help you. If lifecycle methods aren't being called, your application may be silently failing (check for errors being swallowed).

If you can provide a reduced test case ([here's a template to start with](https://jsfiddle.net/84v837e9/) demonstrating an issue with React, that would be great.

But it sounds like this is a usage/support question. We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

I'll be happy to reopen this if you can provide a test case demonstrating an issue with React. Thanks!
