### ISSUE TITLE
Unable to get property 'getHostNode' of undefined or null reference when built react application is accessed in IE

### ISSUE THREAD

**Issue by AjayU** [facebook/react#9822]
Getting this error in IE. Moreover, the react application works fine in IE when used as standalone webpack dev server but the built js file using webpack and babel fails to navigate when used inside of a jsp file inside our application.

The build application works fine in mozilla and chrome. I have read other replies for this topic which talks about the promise raising an unhandled exception. But that is not the case with the application coz the home page doesn't have any promise calls. Understand that this has to do with component error or syntax error but since the application is working fine in mozilla and chrome not able to find out the exact issue. We built our react application with testing it all along in chrome and only recently started testing it on IE.

Using below versions of libraries
react": "^15.4.0",
"react-redux": "^5.0.1",
"react-router": "^3.0.0",
"react-router-redux": "^4.0.7",
    "webpack": "^1.14.0",
    "webpack-dev-server": "^1.16.2",
    "babel-core": "^6.20.0",
    "babel-loader": "^6.2.9",
    "babel-runtime": "^6.20.0",
    "babel-polyfill": "^6.20.0",

**Comment by gaearon** [comment]
>But that is not the case with the application coz the home page doesn't have any promise calls.

You could be catching errors somewhere else. There have been many reports of this issue and they *always* are caused by this so far. Please provide a reproducing project if you think this is a bug in React. Thanks!

**Comment by AjayU** [comment]
I am using redux provider component containing IntlProvider of react-intl, which contains the MuiThemeProvider followed by react-router to start the app. 

When I debug the code the home page render call works fine till the return statement(home page contains only a single render method with a empty div return) but it fails after that with this error when I am navigating to the other page using react router. 

Even the page which I am navigating to, doesn't contain any promise calls. Are you aware if the react router call might be failing internally which could be using promise?

I am dispatching the action "push" of redux-router with pathname as the configured path of the second page. Since this is in IE 11, do I have to do some specific settings for babel or include some polyfills for this scenario?

My current .babelrc is 
{
	"presets": ["es2015", "stage-0", "react"],
	"plugins": ["react-hot-loader/babel","transform-object-assign"]
}

If this input can be used to assist towards finding the area where issue could be, then it would be of great help. Meanwhile I would work on creating a subset of our project to have the minimum reproducible scenario.

**Comment by gaearon** [comment]
We'll need a reproducible example to proceed with this.
I'll close for now since this is impossible to investigate, but if you create one I can reopen.
Thanks!
