### ISSUE TITLE
Add React.Children.find

### ISSUE THREAD

**Issue by mjackson** [facebook/react#9834]
I think a `React.Children.find` method would be really useful in situations where you need to iterate over your children and find just one that satisfies a particular condition. I'm running into this situation more and more often in my React code. A few examples:

- In [React Router](https://reacttraining.com/react-router), the `<Switch>` component [iterates over its children](https://github.com/ReactTraining/react-router/blob/c46e51bfd61343611ddbc173207952e980b81aec/packages/react-router/modules/Switch.js#L38-L49) to figure out which `<Route>` matches the URL.
- In [a `<Select>` component we use in our training workshops](https://github.com/ReactTraining/react-subjects/blob/44614bc3c6c8ca1de813e0bd1e14f86a74a5c0fb/subjects/Select/solution.js#L24-L37), we need to iterate over the `<Option>`s to figure out which label we should show in the select box.

I wonder if there would be any interest from others in seeing something like this.

**Comment by markerikson** [comment]
Would calling `React.Children.toArray(children).find(....)` be too much overhead?

**Comment by mjackson** [comment]
@markerikson `toArray` is semantically different to a `find` operation because it adds keys.

**Comment by markerikson** [comment]
*looks at docs*.... ah, yes, so it does :)   Interesting, hadn't noted that before.

Sure, this seems like a useful addition.

**Comment by FezVrasta** [comment]
Why do you need to find the selected element? Should you already know which one is selected thanks to an "onChange" callback?

You know the data that is being used to render the children, it seems wrong to read back from the tree.

**Comment by mjackson** [comment]
@FezVrasta no onChange events have fired on the initial render

**Comment by jharris4** [comment]
I've run into the need to search for both single/plural children. So maybe `React.Children.filter` would make sense to complement `React.Children.find` ?

Basically, the use case was that a consumer of a library I was building was adamant that they wanted to be able to use a Navigation component like this:

```
<Navigation>
  <NavigationBrand title="A Title"/>
  <NavigationPrimary title="Primary">
    <NavigationLink to="/linkA" label="Link A"/>
    <NavigationLink to="/linkB" label="Link B"/>
  </NavigationPrimary>
  <NavigationSecondary title="Secondary" collapsible={true}>
    <NavigationLink to="/linkC" label="Link C"/>
    <NavigationLink to="/linkD" label="Link D"/>
  </NavigationSecondary>
</Navigation>
```

My initial implementation was to build the Navigation to just take the parts as props like this:
```
<Navigation brand={} primary={} secondard={}/>
```

But the (somewhat valid?) argument was that this was much less readable.

To achieve the desired structure, I ended up writing a couple of helper functions to scan the children to find the ones with the appropriate types, like so:

```
let typesAreEqual = (typeA, typeB) => typeA === typeB;

if (process.env.NODE_ENV !== 'production') {
  // workaround for proxies used by react-hot-loader
  typesAreEqual = (typeA, typeB) => typeA === typeB || typeA.name === typeB.name;
}

function getChildrenWithType(children, type) {
  let childrenWithType = [];
  React.Children.forEach(children, child => {
    if (child && typesAreEqual(type, child.type)) {
      childrenWithType.push(child);
    }
  });
  return childrenWithType;
}

function getChildWithType(children, type, strict = true) {
  let childrenWithType = getChildrenWithType(children, type);
  if (childrenWithType.length === 1) {
    return childrenWithType[0];
  }
  else if (strict) {
    throw new Error('getChildWithType ' + type + ' had child count: ' + childrenWithType.length);
  }
  else {
    return null;
  }
}

```

**Comment by sebmarkbage** [comment]
@mjackson You probably __do__ want to add the expanded key like `toArray` does.

Imagine we use your `<Select />` example like this:

```js
let SelectWithDefault = props => <Select><Option>Default</Option>{props.children}</Select>;
let Foo = () => <SelectWithDefault><Option>Foo</Option><Option>Bar</Option></SelectWithDefault>;
```

Now let's make the label have a CSS animation that fades in when it's created. That way it is stateful but you can choose any other way to make it stateful.

The animation won't play when we switch between items because they all have the same key.

A variant of this is if you add explicit keys:

```js
let SelectWithDefault = props => <Select><Option key="0">Default</Option>{props.children}</Select>;
let Foo = () => <SelectWithDefault><Option key="0">Foo</Option><Option key="1">Bar</Option></SelectWithDefault>;
```

Now, when we switch between Foo and Bar the animation will play. But if you switch between Foo and Default it won't because they have the same key.

`toArray` and `map` avoids this problem by encoding the nesting in the key. So even if we did have `find` or `filter` it would probably semantically do what `toArray` does.

That said, I think the use case of traversing over children will be better handled by coroutines in Fiber. Fragments help too for things like `filter`.

**Comment by sebmarkbage** [comment]
I think that touches on the expectation one might have of React children. Is `Switch` using JSX simply as a syntax sugar but not borrowing any of the semantics of React? Should it be semantically equivalent to something like:

```js
<div>
  <Route ... component={Dashboard}/>
  <Route ... component={Dashboard}/>
</div>
```

The *sometimes* part is what bothers me. There's no intuition right now and you basically just have to test it to see what happens because different components might do different things or even accidentally switch behavior between releases.

**Comment by syranide** [comment]
Can I just add that handling routes with React/JSX seems like a bad idea? Perhaps it looks nice, but the concept doesn't seem sound. Regular JS would be a much better for fit it and would allow you to define the exact semantics you want. Or am I being crazy?

**Comment by mjackson** [comment]
Yes, `<Switch>` uses `<Route>` as syntax sugar, but standalone `<Route>`s are also able to render themselves, so they're not purely syntax sugar as they were in previous versions of the router.

This is a bit off topic, but the reason we decided to re-use `<Route>` components inside `<Switch>` was to make it easier on people upgrading from previous versions or refactoring. Imagine you have a few routes that render independently:

```jsx
<Route path="/home" component={Home}/>
...
<Route path="/home" component={Sidebar}/>
```

That's great for just dropping content in distant places in the app that both need to render at the same URL. This is a strong use case and we make it really convenient because you don't have to use any other components to make everything work.

Another strong use case is choosing between a few different routes, as is common in most routers. Instead of inventing new syntax for this use case, we decided to re-use a bunch of `<Route>` components inside a `<Switch>`.

**Comment by Negan1911** [comment]
On my case, that is a View that renders tabs, we already ask for the childrens to have a key (since it's going to match with the header), but doing `React.Children.toArray(children).find(....) `  results in the `key` value changed, so having a `.find()` method would be really useful

**Comment by gaearon** [comment]
I don’t really see this issue progressing without an RFC.
So if someone feels strongly about this, please create one:
https://github.com/reactjs/rfcs

Thanks!

**Comment by govindrai** [comment]
@mjackson I do see your point. I'm trying to understand if I'm in the same boat here. I am using [Formik](https://github.com/jaredpalmer/formik) (a react form library that I am sure you've heard of) into my project. The thing that is very bothersome is that I have to pass onblur, onchange, and onfocus props that are passed down to me from the `Formik` parent component to each input in my form. Not only does this create a bunch of repetition, it overall feels outright wrong as I know Formik's parent component _could_ pass those props to my form inputs for me (it also makes my component file longer and more to read). 

I wanted to avoid Formik for this very reason and started writing my own form library where I would pass repeated properties to children. However, when trying to solve this, I think I came to the reason why Formik is passing props to my input elements: I don't think there is an easy way to filter through and manipulate [potentially [deeply] nested] children without having to recursively look through the entire childrens prop tree (which could potentially be very nested) and pass props where conditions match. Is there a better way?  This is definitely a case where some sort of _find and manipulate_ functionality would bring a lot of value. 

Just like `Switch` I think think this is another edge case. Maybe I'm just dreading the work with recursively traversing `props.children`, but honestly hoping there's probably a better way of doing what I want to do, and still trying to understand why `Formik` hasn't done it in the first place.

 @gaearon if you see merit in this comment, I would definitely be up for creating a RFC. Any thoughts would be super appreciated!I
