### ISSUE TITLE
Add .setStateDeep?

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#984]
You know people want it…

**Comment by nuragic** [comment]
Mmmh I know it's a bit old discussion but :+1: for @spicyj proposal :smile:

**Comment by spicyj** [comment]
@nuragic We're not planning to add this, sorry.

**Comment by nuragic** [comment]
@spicyj :sob: Ok, thanks for the update! Anyway, just for the sake of curiosity... how are you usually do the same without it?

**Comment by bronson** [comment]
This is the rendered version: https://facebook.github.io/react/docs/update.html

Not as easy as setStateDeep might have been but I guess it's the best we can get.
