### ISSUE TITLE
Error in 'Using Immutable Data Structures' section of Docs

### ISSUE THREAD

**Issue by kastentx** [facebook/react#9844]
**Do you want to request a *feature* or report a *bug*?**
- Report a bug.

**What is the current behavior?**
- In the Optimizing Performance section of the docs, there is a sub-section called Using Immutable Data Structures. At the end there is a sentence _"In this case, since a new reference is returned when mutating x, we can safely assume that x **has changed**."_

The sentence should read, if my assumption is correct, _"... we can safely assume that x **has not changed**_ 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
- The doc in question is posted here: https://facebook.github.io/react/docs/optimizing-performance.html

**What is the expected behavior?**
As described above,  _"... we can safely assume that x **has not changed**_ 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by Assitan** [comment]
Hello, I'm working on it (first contribution).

**Comment by aweary** [comment]
Hey @Assitan! Just a heads up, there's already an open PR for this fix: https://github.com/facebook/react/pull/9845

**Comment by Assitan** [comment]
Ok :)

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/9845.
