### ISSUE TITLE
Browser compatibility issue in Jquery 3.2.1 version

### ISSUE THREAD

**Issue by ankitacroit09** [facebook/react#9848]
report a bug or need to confirm

**What is the current behavior?**
I am getting the following error in console when I am using the jquery 3.2.1 min .js  

at line
var I=C.fn.remove;D=C.browser.mozilla&&(parseFloat(C.browser.version)<1.9);
Uncaught TypeError: Cannot read property 'remove' of undefined

**Comment by rocky-jaiswal** [comment]
Can you provide more details (version of react etc.), I cannot see an error if I create something with react, react-dom and jquery like here - https://codepen.io/anon/pen/WObZYJ

**Comment by aweary** [comment]
Hey @ankitacroit09! As mentioned, please provide an example reproducing the issue you're having ([here's a template you can start with](https://jsfiddle.net/84v837e9/)). We don't explicitly support compatibility with other libraries like jQuery, but I don't think there's anything React does that would prevent interop.


It sounds like maybe you're having trouble getting them to work together. We try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

**Comment by aweary** [comment]
Closing since there has been no response.
