### ISSUE TITLE
ReactPlayer autoplay muted video on mobile

### ISSUE THREAD

**Issue by Thargarius** [facebook/react#9855]
I can't manage to autoplay video on mobile browser, I dont have any audio and there is my code :
```
<div className="react-video" ref={el => this.videoWrapper = el}>
    <ReactPlayer width={this.state.width} height={this.state.height}
        url='https://atmost.fr/assets/video/yosemite720.webm' fileConfig={{ attributes: { "muted": "true", "autoPlay": "true" } }} muted playinline playing={this.state.playing} loop autoplay />
</div>
```

When I inspect my page I only see this :
`<video src="https://atmost.fr/assets/video/yosemite720.webm" preload="auto" loop autoplay style="width: 100%; height: 100%; display: block;"></video>`

**Comment by bvaughn** [comment]
Your code specifies `muted` attribute true
```
fileConfig={{ attributes: { "muted": "true", "autoPlay": "true" } }} muted
```

**Comment by aweary** [comment]
@Thargarius what is `ReactPlayer`? Can you share the source for that component? It looks like you've muted the video using the `muted` prop, is that the problem? Please provide an example reproducing your issue. You can use https://jsfiddle.net/84v837e9/ as a starting point.

**Comment by bvaughn** [comment]
Hi @Thargarius,

I can't tell from this description if this is an issue with your application code, the third party library `ReactPlayer` is in, or React. Maybe you can provide a reduced test case ([here's a template to start with](https://jsfiddle.net/84v837e9/)) that narrows things down to React?

If React renders the HTML snippet you provided above, that looks correct.

**Comment by Thargarius** [comment]
Oh I just realized I published my issue in the wrong repo, sorry for inconvenience.
