### ISSUE TITLE
We have fully translated the latest version of react docs into Chinese.

### ISSUE THREAD

**Issue by discountry** [facebook/react#9860]
You can see the Chinese docs here: [react docs in Chinese](https://discountry.github.io/react/)

Translated from the `v15.5.4` docs.

We've directly modified the original markdown files, so it's hard to pull request and merge the official docs.

Is there any plans to add i18n feature to the jekyll doc website?

**Comment by NE-SmallTown** [comment]
Thanks.But I notice that the `CONTRIBUTING` and `REFERENCE` sections are not be translated,I think they are very important to help developers to understand React.

**Comment by discountry** [comment]
@NE-SmallTown Thanks for reminding me. We'll continue our translation work and keep up with coming React v16 updates.

**Comment by gaearon** [comment]
Awesome! Please keep track of https://github.com/facebook/react/issues/8063.
We plan to use a tool for translation, just like Jest did.

**Comment by discountry** [comment]
@gaearon OK. We'll keep track of that.
