### ISSUE TITLE
Investigate why CI got broken on master but PR passed

### ISSUE THREAD

**Issue by gaearon** [facebook/react#9864]
See this PR: https://github.com/facebook/react/pull/9550.

It passed CI on PR, but when merged to master, it had a test failure (which I later fixed in https://github.com/facebook/react/pull/9854).

I wonder if we're missing some check in PRs.

**Comment by trueadm** [comment]
This puzzling me. I don't understand how the test failed for us now when on the CI run, it ran the test and showed it as passing:

![screen shot 2017-06-07 at 11 24 16](https://user-images.githubusercontent.com/1519870/26874035-f33ef940-4b73-11e7-8727-c01580e8ae70.png)

Although, my best guess is that it's related to the CI change we made to the Jest task runner not turning an exit:

https://github.com/facebook/react/blob/7052d7c71071710ad396cf52d3ded9898c3d057d/scripts/tasks/jest.js

**Comment by gaearon** [comment]
Thanks for investigating!
To clarify: the issue is that the PR's merge base did not include the fix from https://github.com/facebook/react/pull/9663.

We might have some more PRs like this, so need to be mindful (and ideally rebase old PRs before merging).
