### ISSUE TITLE
Remove streaming renderer from fb builds

### ISSUE THREAD

**Issue by flarnie** [facebook/react#9868]
We shouldn't get `html/shared/react/ReactDOMServerStream-prod.js` and `html/shared/react/ReactDOMServerStream-dev.js` in the fb builds. Correct me if this is wrong.

**Comment by gaearon** [comment]
For now we shouldn't (since I don't think anybody checked those bundles for extra/bloated code which I believe they have). 

But in close future we'll need to fix them and then just replace the old DOMServerRenderer with them (and completely remove the old bundles from build process).

**Comment by flarnie** [comment]
Good point. We should just make sure to do something to fix them in the next two weeks, so we don't have to manually exclude them when running a sync.

**Comment by gaearon** [comment]
Yea, either way works. Disabling them for now should be as easy as removing `FB_DEV` and `FB_PROD` from `types` of corresponding bundles.
