### ISSUE TITLE
Order of linting and prettier in contributing docs

### ISSUE THREAD

**Issue by wdhorton** [facebook/react#9876]
**Do you want to request a *feature* or report a *bug*?**
This is more of a documentation discussion

**What is the current behavior?**
Currently, the contributing guide lists the lint step before running prettier. For example, `.github/PULL_REQUEST_TEMPLATE.md` says:
```
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
I think it would make more sense to run prettier first, since it can automatically get rid of certain lint errors (like single-quotes or comma-dangle). A first-time contributor following the steps in order might waste time fixing things manually at the lint step before proceeding to the formatting step.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by gaearon** [comment]
Happy to take PR fixing it.

**Comment by monkindey** [comment]
Thanks to @wdhorton reminding, I make a PR for it.

**Comment by gaearon** [comment]
Seems like this was fixed.
