### ISSUE TITLE
unstable_handleError: Cannot read property 'listeners' of null

### ISSUE THREAD

**Issue by ambar** [facebook/react#9877]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
> TypeError: Cannot read property 'listeners' of null

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

https://jsfiddle.net/ambarli/une20v6v/1/

**What is the expected behavior?**

renders error text.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.5.4 ~ 16.0.0-alpha.12

**Comment by gaearon** [comment]
Works for me with `react@next` and `react-dom@next` (both pointing to latest alpha).
https://jsfiddle.net/xa7kg3nt/

**Comment by ambar** [comment]
`@next` breaks server rendering: https://jsfiddle.net/ambarli/xa7kg3nt/1/

**Comment by gaearon** [comment]
It's expected, if it fully worked it wouldn't have been an alpha :-). You are describing a new feature. The name itself says it's not stable yet.

**Comment by gaearon** [comment]
That said I don't think we currently support error boundaries in server renderer at all. Might be worth raising a separate issue.
