### ISSUE TITLE
Input type="number", when initial value is `"0"` or `0`, and value changes to empty string "", value does not update

### ISSUE THREAD

**Issue by brendoncrawford** [facebook/react#9884]
Example of bug here:
https://jsfiddle.net/69z2wepo/80380/

My best guess is that maybe React is doing some truthiness checking which thinks that 0 is the same as "", so it is not updating the value of the component.

**Comment by aweary** [comment]
Thanks for the report @brendoncrawford!

I believe this will be resolved by https://github.com/facebook/react/pull/9714

**Comment by gaearon** [comment]
This was fixed in https://github.com/facebook/react/pull/9714 and no longer reproduces.
