### ISSUE TITLE
viewBox of inline SVG sometimes rendered as viewbox

### ISSUE THREAD

**Issue by aaronshaf** [facebook/react#9885]
React.js doesn't seem to be consistently rendering `viewBox` as camel-cased `viewBox`; it instead of rendered as `viewbox`.

Sample code:

https://gist.github.com/aaronshaf/d161800bee8e6244111a1e06c8f1dc84#file-color-button-js-L51

It works in Chrome, but not in Firefox or IE11.

Any ideas?

Version: 15.5.4

**Comment by aweary** [comment]
@aaronshaf thanks for the report. We [map to the camel-cased `"viewBox"`](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/shared/SVGDOMPropertyConfig.js#L247) in all cases. Can you share a small example reproducing your issue? I [created a small example](https://jsfiddle.net/r1hxxtmz/) and see it rendered as `viewBox` in Chrome and Firefox.

The issue template contained [a link to a JSFiddle](https://jsfiddle.net/84v837e9/) you can use as a template for the example. For future reference, it'd be great if you could provide all the information it requested when opening an issue.

Thanks!

**Comment by aaronshaf** [comment]
Looks like it was interference from the https://github.com/webcomponents/custom-elements polyfill.
