### ISSUE TITLE
Number.isNaN() in IE11

### ISSUE THREAD

**Issue by QuantumHive** [facebook/react#9888]
`Number.isNaN()` is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#Browser_compatibility) in Internet Explorer 11.

In a code sample from the [Lifting State Up](https://github.com/facebook/react/blob/master/docs/docs/lifting-state-up.md) documentation, `Number.isNaN()` is used. Specifically in the [Writing Conversion Functions](https://facebook.github.io/react/docs/lifting-state-up.html#writing-conversion-functions) section (see the `tryConvert` function).

I'm following the Quick Start guide using [Visual Code](https://code.visualstudio.com/) 1.12.2 as editor with [create-react-app](https://github.com/facebookincubator/create-react-app). When using Internet Explorer 11 to test the `Calculator` component after completing the Lifting State Up section, I'm getting the following error:

> TypeError: Object doesn't support property or method 'isNaN'

 This can be fixed when using reguler `isNaN()` in IE11, should the doc be updated to use this?

**Comment by gaearon** [comment]
`isNaN` has [confusing behavior](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Description) and I’d rather avoid using it in docs.

We use ES2015 in the documentation, and indeed some runtime methods may not be available in older browsers like IE11. I feel like we’re willing to live with it for examples, as most people use modern browsers when learning. It’s just a single occurrence and doesn’t seem like something most people would run into, so I’ll close this, but we can reconsider if people keep bumping into this issue.
