### ISSUE TITLE
Lost setNativeProp and others methods when I create personal Component with Child nodes

### ISSUE THREAD

**Issue by tufik2** [facebook/react#9890]
Hi there, I am creating a custom Component 
```
<MyCompoent onChange={(index)=>{ this.onChangeTab(index) }} style={{height:global.heightTabBar}} >
            <Text ref='text1'>Text1</Text>
            <Text ref='text2'>Text2</Text>
            <Text ref='text3'>Text3</Text>
            <Text ref='text4'>Text4</Text>
</MyCompoent >
```
Inside MyComponent I loop over all Childs refs with the next code:
```
{ 
              this.childrens.map((element, key)=>{
                return(
                  <TouchableWithoutFeedback key={key} onPress={this.onPress.bind(this, key)}  >
                    <View ref={"tab"+key}>
                        {element}
                    </View>
                  </TouchableWithoutFeedback>
                )
              })
          } 
```
But when I try to use setNativeProp in `<Text>` inside my component. SetNativeProp is undefined

I am using the next code to reach the child inside of any method.

`this.refs.tab0.children[0],`

Another way I tried was putting up refs to each text but, I lost the refs also.

`this.refs.text1 // undefined`

There is any way to draw the Nodes without loss properties?

Or there are any form to rebuilt/create the Node with the same characteristics inside `this.childrens`?

**Comment by gaearon** [comment]
If you believe this is a bug in React please create an example reproducing it.

**Comment by bvaughn** [comment]
I assume the `{element}` in question is an instance of your `MyCompoent`? And you're expecting refs to those instances (of `MyComponent`) to define `setNativeProps`?

Components you create in your own app (by extending `React.Components`) don't automatically inherit methods like `setNativeProp`. That method (and others like it) are only available on the default components exported by React Native itself - ones that are backed by native views.

You might find the example on [this page](https://facebook.github.io/react-native/docs/direct-manipulation.html#forward-setnativeprops-to-a-child) useful as it deals with this issue specifically.

Apologies if I have misunderstood your question 😄

**Comment by gaearon** [comment]
I’ll close as I think @bvaughn addressed the question. If you still have issues please create an example reproducing the problem. Thanks!
