### ISSUE TITLE
JavaScript Responsible of rendering html issue

### ISSUE THREAD

**Issue by ahmed32ali** [facebook/react#9892]
I have a question Related to binding html in JavaScript and making JavaScript responsible of creating the dom that's hiding this resources from the browser , it's all blocked in JavaScript which lead to opting html out of optimization which the browser do like background parsing of html in a separate thread so when you bind html in JavaScript you just bind with your own code am I Understand react dom manipulation well or not ?

**Comment by bvaughn** [comment]
Hi @ahmed32ali,

We try to keep GitHub issues focused on either bug reports or discussion around requirements for new features. This is more of a question than an actionable issue so I'm going to close it.

I suggest re-posting this question in one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.

Cheers!
