### ISSUE TITLE
Cursor jumps to end on controlled component

### ISSUE THREAD

**Issue by alshain** [facebook/react#9894]
**Do you want to request a *feature* or report a *bug*?**
Bug as per https://github.com/facebook/react/issues/6445#issuecomment-281864796

**What is the current behavior?**
When typing inside a controlled input component, the cursor will jump to the end if the value is modified in `handleChange()`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
I have modified the [Controlled Components example](https://facebook.github.io/react/docs/forms.html#controlled-components) as described in the documentation with `toUpperCase()`, which you can see in [my fork of the codepen](https://codepen.io/anon/pen/ZybobE?editors=0010).

* Type: `abc123` (transformed automatically to `ABC123`)
* Place cursor as follows: `ABC|123`
* Insert lower case `d` after the `c` character
* Observe how the cursor jumps to the end

The cursor only jumps to the end if a lower case character is inserted. On any other modification, the cursor remains where it is, presumably because the value isn't "overwritten" by react.

**What is the expected behavior?**
The cursor should remain at the current position.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 15.3.1
Browser: Chrome 58
OS: Win 7

**Comment by gaearon** [comment]
If you modify the input text (such as the case with `toUpperCase()` transform), I think this is expected.

There is no way React can guess that your particular transform preserves the number of characters. From React’s point of view, the text was completely replaced after typing, so it puts cursor at the end. You can get around it by manually managing DOM selection using a ref. This is explained in more detail here: https://github.com/facebook/react/issues/955#issuecomment-160703606.

So I don’t think this is a bug, and I encourage you to participate in discussion in #955 if you have more thoughts to add. Cheers!
