### ISSUE TITLE
Mouseleave events fire unexpectedly when mousing into descendant node with a different React root

### ISSUE THREAD

**Issue by greglittlefield-wf** [facebook/react#9901]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When mousing into a descendant DOM node that has a different React root, the mouseLeave event on the parent React DOM component is fired unexpectedly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Demo: https://codesandbox.io/s/lqm3M147

1. Open the console to see the logs printed.
2. Mouse from the "Parent" into the "Normal Child", and then back out, and note that `mouseLeave` __does not__ fire
2. Mouse from the "Parent" into the "Portal Child", rendered by embedding a new React root, and note that `mouseLeave` __does__ fire. Mouse back out, and note that it fires again. Sometimes, it fires multiple times for the enter/exit step.

**What is the expected behavior?**
`mouseLeave` should not fire when entering/exiting the "Portal Child", since it is a descendant node of "Parent".

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested with the following, and the issue is reproducible in all cases
* React 15.4.1 and 15.5.3
* Latest Chrome, Firefox, Safari

**Comment by aweary** [comment]
This doesn't appear to be an issue using the new portal API, `ReactDOM.createPortal` https://jsfiddle.net/Luktwrdm/.
