### ISSUE TITLE
Is it possible to delay the propTypes isRequired validation before constructor() got called?

### ISSUE THREAD

**Issue by benpptung** [facebook/react#9904]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When element is wrapped like following:
```
<Parent>
  <Child />
</Parent>
```

In Child,
```
Child.propTypes = {
  height: propTypes.number.isRequired
}
```
Will receive waring:
```
Warning: Failed prop type: The prop `height` is marked as required in `Child`, but its value is `undefined`.
```
I understand this is an expected behavior, however, the warning is really annoying.

**What is the expected behavior?**
Delay the propTypes validation till `willMount` or `rendered` or `didMount` to avoid unnecessary warnings. Or maybe, before the `constructor()` got called?

Since the `Child` is wrapped in `Parent`, The `Parent` can use `React.cloneElement(props.children, {height})` to merge and render the `Child` with `height` prop merged, so we won't see a lot of unnecessary warnings, and keep `isRequired` as a mark in Child.propTypes. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.5.4

**Comment by gaearon** [comment]
No, it’s not possible.
Please see https://github.com/facebook/react/issues/6653 for the past discussion.
