### ISSUE TITLE
react-addons-update 15.5.2 uses Object.assign

### ISSUE THREAD

**Issue by balloob** [facebook/react#9913]
**Do you want to request a *feature* or report a *bug*?**
Undocumented breaking change for IE11

**What is the current behavior?**
Starting `react-addons-update` v15.5 the package has been changed from depending on an internal file from the `react` package (`react/lib/update.js`) to actually include the full implementation.

While the internal implementation depended on the `object-assign` polyfill, the external one actually calls `Object.assign` directly, breaking support with IE 11.

- [`react-addons-update@15.4.2`](https://unpkg.com/react-addons-update@15.4.2)
- [`react@15.4.2/lib/update.js`](https://unpkg.com/react@15.4.2/lib/update.js)
- [`react-addons-update@15.2.2`](https://unpkg.com/react-addons-update@15.5.2)

This requires users that support IE11 to polyfill `Object.assign`. This was not mentioned in the [release blog post of React 15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#react-addons).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

–

**What is the expected behavior?**

Add a mention of this to the release blog post.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.5+. Worked fine in React 15.4.

**Comment by gaearon** [comment]
This is a bug an unintentional. cc @flarnie

**Comment by gaearon** [comment]
It happened because we have a Babel transform turning it into `require('object-assign')` calls. But we didn't transpile addons when we extracted them. We should fix this in 15.6.

**Comment by gaearon** [comment]
Closing since this was fixed in https://github.com/facebook/react/pull/9932.

**Comment by gaearon** [comment]
This should be fixed with `react-addons-update@15.6.0-rc.0`. Can you please verify?

**Comment by flarnie** [comment]
Inspecting the 'unpkg' seems to confirm this is fixed:
The `15.5.2` (latest) version of `react-addons-update` has `Object.assign` in two places: https://unpkg.com/react-addons-update@15.5.2/react-addons-update.js

The `15.6.0-rc.0` version of `react-addons-update` has the polyfill inline, and no other references to it: https://unpkg.com/react-addons-update@15.6.0-rc.0/react-addons-update.js

I have a few minutes, can try and pull it into something in IE11 on my windows laptop to see if any other issues come up.

**Comment by flarnie** [comment]
I didn't find a quick way to test loading this module - let me know how? So I can do that tomorrow if that would be helpful. Was trying to load it in a JS fiddle from unpkg but didn't get it right.

**Comment by balloob** [comment]
Yes, this has been fixed. Thanks!

**Comment by gaearon** [comment]
Thanks for reporting!
