### ISSUE TITLE
Non-shouldComponentUpdate for state AND prop updates.

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#9922]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The only render-independent lifecycle hook that is called for both state and prop updates is `shouldComponentUpdate`.

**What is the expected behavior?**

There are certain cases where it currently makes sense to run some code whenever state or props update, even if a render won't happen. E.g. a context-providing component which needs to update its child subscribers even if it's best not to re-render the immediate child due to the frequency of updates.

**Why are you using state for this?** *In my case*, I'm re-rendering only while my component is not passed any children - then the component renders an instance of a shallow child component, passed props based on our internal state. When `children` *is* passed in, I don't want to update since I would be re-rendering a potentially large component tree for no reason - but I still want to notify any context subscribers that the state changed.

It's workable to use `shouldComponentUpdate`, but that's not what this lifecycle method is for.

**ETA:** maybe `componentWillReceiveState` or similar? Only called for state updates. Should be called *after* `componentWillReceiveProps` (which may have updated the `nextState`), and *before* `shouldComponentUpdate`. No `setState` allowed.

**Comment by aweary** [comment]
Hey @benwiley4000, thanks for taking the time to write out your suggestion. We have [an umbrella issue for new lifecycle method ideas](https://github.com/facebook/react/issues/7678). Could you post your proposal there instead?

Thanks!
