### ISSUE TITLE
If ReactCSSTransitionGroup children has text, IE(IE10, edge) will be a false effect

### ISSUE THREAD

**Issue by lemonleon** [facebook/react#9925]
**Do you want to request a *feature* or report a *bug*?**
I think may be a bug？ Or is it IE problem？I'm not sure.
**What is the current behavior?**
When ReactCSSTransitionGroup children has text(any text)， IE(IE10, edge) will be a false effect；

like this：
```javascript
<ReactCSSTransitionGroup transitionName='testIE' transitionEnterTimeout={600} transitionLeaveTimeout={600} >
    <p key={active} >any text in here， IE will be a false effect</p>
</ReactCSSTransitionGroup>
```

And if no text in there, it will be ok

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
OS: win7
React: 15.4.2

**Comment by gaearon** [comment]
Thanks for report, but we no longer maintain TransitionGroup in this repository.
Please report to https://github.com/reactjs/react-transition-group instead.
Cheers!
