### ISSUE TITLE
Inconsistencies among the documentation

### ISSUE THREAD

**Issue by rosenfeld** [facebook/react#9926]
Hi, I'm trying to figure out whether adopting React would be a safe or risky choice. It's very important to me to being able to draw the boundaries, i.e., to be able to define which node elements should be managed by React and which ones should not. It's pretty important that I should be able to integrate well with non-react components. So, I was trying to understand what guarantees I get when using React and noticed two sections in the documentation that don't seem to be compatible:

https://facebook.github.io/react/docs/integrating-with-other-libraries.html

> To prevent React from touching the DOM after mounting, we will return an empty < div /> from the render() method. The <div /> element has no properties or children, so React has no reason to update it, leaving the jQuery plugin free to manage that part of the DOM

So, it suggests using the mount/unmount hooks in order to initialize and destroy the the third-party components, however this is not enough to guarantee the integration will succeed. I'll get more into that later.

https://facebook.github.io/react/docs/reconciliation.html

> It is important to remember that the reconciliation algorithm is an implementation detail. React could rerender the whole app on every action; the end result would be the same.

https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate

> Currently, if shouldComponentUpdate() returns false, then componentWillUpdate(), render(), and componentDidUpdate() will not be invoked. Note that in the future React may treat shouldComponentUpdate() as a hint rather than a strict directive, and returning false may still result in a re-rendering of the component.

This is a problem to me. If I can't really rely on the reconciliation algorithm to not touch the elements React is not supposed to manage, then I have no guarantees that it would be possible to integrate React with third-party components in the future. This is a big concern.

So, let me give you an example to illustrate that. Suppose I want to integrate with a very lightweight multi-options autocomplete component that only provides 3 public APIs, a constructor, a desctructor and some onChange hook. It's an stateful component but we don't have direct access to its state so that we can restore it after destroying and recreating it. It opens a menu with several items containing a checkbox and the item label. As you click on the items, checking its checkbox, onChange would be triggered, which we could use to change the state of some ancestor component managed by React.

While responding to the state change event, if React simply decides to re-render the ancestor component, without respecting `shouldComponentUpdate`, or ignoring the diff algorithm, it means it would probably call `componentWillUnmount` in the autocomplete component wrapper, which would only be able to destroy that component. Then, after `componentDidMount` we would only be able to initialize the component again, but we would have lost all of its state, like the scroll position and currently selected items and so on. In other words, that means React wouldn't be able to play nice with third-party components. In order to have such a guarantee, we need to have more guarantees from React itself. The reconciliation algorithm shouldn't be just an implementation detail without any guarantees. `shouldComponentUpdate` shouldn't be considered just a hint. Otherwise, how are we supposed to wrap third-library components in a reliable way?

I'm really scared to start migrating our application to use React unless I feel confident that I'll always be able to integrate with third-party stateful components. Could you please review such statements in the documentation?

**Comment by gaearon** [comment]
>While responding to the state change event, if React simply decides to re-render the ancestor component, without respecting shouldComponentUpdate, or ignoring the diff algorithm, it means it would probably call componentWillUnmount in the autocomplete component wrapper, which would only be able to destroy that component.

I don't understand this part. When documentation says "re-render" it refers to calling the render method and reconciling the changes, not unmounting and mounting components. React never unmounts components unless key or type changes.

While we can't guarantee that React won't be calling render in more cases, we can pretty much guarantee that:

1. If component key and type doesn't change, React won't unmount the component.
2. If you manually touch the DOM that React doesn't manage (e.g. imperatively change an attribute that doesn't exist on React side), React won't blow away your changes on re-rendering.

In our experience of maintaining 30,000 components, many of which are interfacing with non-React code and depend on this behavior, these rules are enough to keep the code working even as we make changes to the algorithm. For example, we recently completely rewrote the implementation to unlock some long requested features, but only a dozen of those 30,000 components required changes. We think it's a reasonable price for pushing the library forward.

I'm not sure if this helps you, but I hope so. We don't want to overpromise that nothing will change, but we also have a lot of code that needs to keep working, and relies on these patterns. If there's a way to clarify the docs with regards to the two guarantees above, I'd be happy to take a PR.

**Comment by gaearon** [comment]
(Also, if you have specific concerns please create examples and we'll be happy to discuss them. The problem with issues like this is they often get philosophical and people start talking past each other about completely different things. So I want to make sure we are discussing the same cases.)

**Comment by rosenfeld** [comment]
> In our experience ... these rules are enough to keep the code working even as we make changes to the algorithm.

Yes, I definitely agree, I see where the confusion is coming from. Take a look at this snippet from the documentation and try to think like someone new to React would take it:

> It is important to remember that the reconciliation algorithm is an implementation detail. React could rerender the whole app on every action; the end result would be the same.

When I read this I didn't understand it was talking about calling the `render()` method of the component because rendering usually means taking the virtual tree and transforming it to the DOM representation, while rerendering at a first glance would mean dropping the old DOM tree and recreate it from scratch. I wasn't the only one that got this interpretation. If you don't mind I'd like to submit a PR to clarify that part of the documentation. If rerendering only means calling render in all components, I'm completely fine with that and I wouldn't fear React.

Thanks for the explanation :)

**Comment by gaearon** [comment]
Sure, a PR would be great! I'm sorry it was confusing. "Rendering" is a bit overloaded term.

The challenge is to phrase it in a way that would both be understandable for beginners and provided enough information to more advanced users.

**Comment by rosenfeld** [comment]
I just suggested some changes to that part.

**Comment by rosenfeld** [comment]
I've also updated that article to reflect my misunderstanding, sorry for the confusion.
