### ISSUE TITLE
Stateless React components with controlled input

### ISSUE THREAD

**Issue by iamtekeste** [facebook/react#9930]
I have asked this question on Stackoverflow but did not get any response, so I am trying my luck here.

Currently to make controlled inputs work inside Stateless React components I am wrapping the stateless component inside a Sate full component.

For example,

```js
const InputComponent = (props) => {
  return (
    <input value={props.name} onChange={props.handleChange} />
  );
}

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: 'Tekeste'
    };
    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(event) {
    this.setState({
      name: event.target.value
    });
  }
  render() {
    return (
      <InputComponent name={this.state.name} handleChange={this.handleChange} />
    );
  }
}
```
What I would like to know is a couple of things.

Is this a good pattern?
If not how can I achieve my goal i.e to have controlled inputs inside stateless components.

**Comment by robertistok** [comment]
This section is for issues with the React framework, not for tips and best practices. You should join to https://www.reactiflux.com, there is a huge React community where you can chat about issues like this. 

But to answer your post, this is a good pattern for having controlled inputs. Unfortunately you can't make a controlled input only with a stateless component in other way.

**Comment by aweary** [comment]
As @robertistok mentioned, we try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, we recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
