### ISSUE TITLE
Refs not working properly in componentDidMount

### ISSUE THREAD

**Issue by MarkSMT** [facebook/react#9944]
**Do you want to request a *feature* or report a *bug*?**
Bug or user failure

**What is the current behavior?**
this.input.click() only happens when one child component is rendered, it fails on the first one

**If the current behavior is a bug, please provide the steps to reproduce...** https://www.webpackbin.com/bins/-KmX1MtJi0LSB43lN3k1

**What is the expected behavior?**
the first component should open dialog box

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome on macOs
"react": "^15.5.4",
"react-dom": "^15.5.4",

> In our application this comes up in a deeply nested component
> some times the dialog box shows up when the component actually unmounts
> weird thing is, this still works on an older version of the application..

**Comment by sanniassin** [comment]
@MarkSMT In your example you set the same state in both onClick handlers, so state actually changes only on first click. That's why componentDidMount executed only once.
```jsx
<button onClick={() => this.setState({ current: 2})}>1</button>
<button onClick={() => this.setState({ current: 2})}>2</button>
```

**Comment by MarkSMT** [comment]
I updated the code, but that's actually not the issue.
The file upload dialog should show when the site loads..

Component 'one' gets loaded when the site gets loaded, but the dialog box doen't appear.
That's the bug i am referring to..

**Comment by sanniassin** [comment]
I guess it's due security restrictions in browsers and not related to React. You can call ```fileInput.click()``` only inside handler of actual click.

https://stackoverflow.com/questions/25886480/trigger-click-on-input-file

Vanilla js demo: https://www.webpackbin.com/bins/-Km_gSgZ8ecpt38Y4uU2
