### ISSUE TITLE
Fix `systemjs.html` fixture on `15.*` branch

### ISSUE THREAD

**Issue by flarnie** [facebook/react#9947]
**Do you want to request a *feature* or report a *bug*?**
This is some kind of bug, either in React or in the `systemjs.html` fixture.

**What is the current behavior?**
When you open `fixtures/systemjs.html` there is an error in the console and React does not load:
```
Uncaught (in promise) Error: (SystemJS) XHR error loading file:///Users/flarnie/Code/wrapper-around-fresh-react-project/react/build/react-with-addons.js
	Error: XHR error loading file:///Users/flarnie/Code/wrapper-around-fresh-react-project/react/build/react-with-addons.js
	    at Promise (<anonymous>)
	Error loading file:///Users/flarnie/Code/wrapper-around-fresh-react-project/react/build/react-with-addons.js
	    at Promise (<anonymous>)
	Error loading file:///Users/flarnie/Code/wrapper-around-fresh-react-project/react/build/react-with-addons.js
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
Step 1: Check out `15-dev` or `15.6-dev1
Step 2: Run `yarn install && yarn build`
Step 3: Open `fixtures/systemjs.html`

**What is the expected behavior?**
You should see 'Hello World' appear

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This was also present in the last release of React 15.5, and is still present in React 15.6.0.

**Comment by gaearon** [comment]
I think the issue is that you [need to use the local server](https://github.com/facebook/react/tree/master/fixtures/packaging#how-to-run)—`file://` doesn't work because of some XHR cross domain stuff.

**Comment by flarnie** [comment]
Thanks @gaearon - that is the one fixture that requires running the local server. Looks like all fixtures are good to go after all. :)
