### ISSUE TITLE
How safe is React Native with React 16 Alpha?

### ISSUE THREAD

**Issue by ryanhomer** [facebook/react#9948]
I am currently on React Native **0.42.3**. Since then 0.43, 0.44, 0.45 have been released as stable and 0.46 is around the corner. RN 0.42.3 uses React **15.4.2**. March saw the release of RN 0.43 which started using the React 16.0.0-alpha series and completely skipped version 15.5. This has prevented me from updating React Native as I've been waiting for a official "stable" release of React 16.

We're now in mid June and the official stable Release of React is **15.5.4**. It appears that version 15.6.0 is now entering RC1 and version 16.0.0 is still in alpha.

So, the React world in using React 15.5.4 and the React-Native world is using React 16.0.0-alpha.

1. Does anyone know why React 15.5 was skipped?
2. Is it safe to use a version of React Native 0.43 and up in production?
3. What's the deal with React 16 anyway? It's not even mentioned in the list of [React releases](https://github.com/facebook/react/releases).

**Comment by ryanhomer** [comment]
Sorry, should have posted this on React Native side.

**Comment by ryanhomer** [comment]
https://github.com/facebook/react-native/issues/14496

**Comment by gaearon** [comment]
See reply in https://github.com/facebook/react-native/issues/14496#issuecomment-308179958.
