### ISSUE TITLE
Ignore whitespace in the container element when reusing markup

### ISSUE THREAD

**Issue by Rowno** [facebook/react#996]
At the moment, if there's any whitespace around a pre-rendered component inside it's container, the HTML won't be reused. This is because `getReactRootElementInContainer()` uses `Node.firstChild` which will return a `TEXT_NODE` instead of an `ELEMENT_NODE` in this case.

For example, this HTML won't be reused:

``` html
<div class="wrapper">
    <div class="component" data-reactid=".r[1wtmm]" data-react-checksum="490228448">...</div>
</div>
```

If you want, I can send through a pull request that changes `getReactRootElementInContainer()` to look for the first `ELEMENT_NODE` instead of just any `Node`.

**Comment by aweary** [comment]
Closing this out since #1912 implemented a warning that would cover this situation ([exampe](https://jsfiddle.net/88t13ync/))
