### ISSUE TITLE
Error: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by abusada** [facebook/react#9967]
started getting this error right after upgrading to 15.6.0:

> Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by gaearon** [comment]
I’m sorry for asking—but just in case, can you confirm that you’ve read the message? For example, it says you might have two copies of React. Have you run `npm ls react` and verified this is not the case?

**Comment by abusada** [comment]
Yes, that was indeed the issue, i deleted `node_modules` and ran `yarn install` again, it fixed the issue!
