### ISSUE TITLE
Expose ShouldComponentUpdate from PureComponent

### ISSUE THREAD

**Issue by juangl** [facebook/react#9972]
It'd be nice to have the following API:

```javascript
class ComponentA extends PureComponent {
  shouldComponentUpdate(newProps, newState) {
   if (this.props.anyProp.nestedObject !== newProps.anyProp.nestedObject) {
      return true
    }
    return super.shouldComponentUpdate(newProps, newState) // super pureComponent
  }
  render() {
     return <ComponentB propToB={this.props.anyProp} />
  }
}
```

**Comment by gaearon** [comment]
We provide `react-addons-shallow-compare` which you can use for this.

```js
class ComponentA extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
   if (this.props.anyProp.nestedObject !== newProps.anyProp.nestedObject) {
      return true;
    }
    return shallowCompare(this, nextProps, nextState);
  }
 
  render() {
    return <ComponentB propToB={this.props.anyProp} />
  }
}
```

I don't think we will be adding embrace inheritance like this in the API, as this is not consistent with any other React methods.

We might also interpret `PureComponent`s in some special way in the future, and allowing to override `shouldComponentUpdate` clashes with this, and we might support a form of “purity” annotations for functional components which wouldn’t work with inheritance either.

Thanks for suggestion though!
