### ISSUE TITLE
same modules in react and react-dom

### ISSUE THREAD

**Issue by fedeoo** [facebook/react#9975]
**Do you want to request a *feature* or report a *bug*?**
No
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.6.1

I just analyze my bundle file with webpack. I came across that serval modules exist in both react and react-dom. I guess these files are ignored. These files are listed here:

reactProdInvariant.js
KeyEscapeUtils.js
traverseAllChildren.js
ReactElementSymbol.js
ReactPropTypesSecret.js
getIteratorFn.js

**Comment by gaearon** [comment]
This is currently intentional (although with time there'll be less of them).
