### ISSUE TITLE
*bug* fontFamily wraps font names in nested double-quotes (Chrome only)

### ISSUE THREAD

**Issue by grese** [facebook/react#9979]
**Bug**

**Current Behavior**
When the fontFamily declaration is used in React, any multi-word fonts are wrapped in double-quotes in Chrome ONLY.  Nested double quotes are not valid in HTML attributes, so React shouldn't be creating the style attribute this way.

**Steps to Reproduce**
1. Open this React Fiddle in Chrome https://jsfiddle.net/grese/69z2wepo/80972/
2. Inspect the text that was rendered by React in the "result" pane.
3. You'll notice that in the style declaration, the words 'Times New Roman' are in double quotes.  This results in nested double quotes (i.e. style="font-family: Georgia, "Times New Roman", serif;"), which is not really valid.  The original font-family declaration did not have these quotes.
4. Open the same React Fiddle in Safari, or Firefox.  You'll notice that the nested double quotes do not happen.  The font-family declaration is left as-is.

**More evidence:**
1. Now, open this simple fiddle in Chrome:  https://jsfiddle.net/grese/mmp457jk/1/
2. Inspect the text rendered in the "result" pane.  You'll notice that Chrome did not add the nested double quotes around 'Times New Roman'.  So, it doesn't seem to be the browser doing this.  It seems to be only when React is used.

**What is the expected behavior?**
I would expect that one of two things should happen...
1. The multi-word fonts would be left as-is (i.e. style="font-family: Georgia, Times New Roman, serif;")
2. The multi-word fonts would be wrapped in a single quote instead of double (i.e. style="font-family: Georgia, 'Times New Roman', serif;")

**React Versions**
We are seeing this in React version 15.4.2.  I do not know if this was working in previous versions of react.

**Comment by gaearon** [comment]
This is just a quirk of how Chrome displays values set from JavaScript. React does not actually generate a `style` string attribute—it sets the DOM `style` properties.

You can verify with this fiddle:

https://jsfiddle.net/g1euqx5b/

It uses DOM APIs without quotes, but Chrome displays the same result.

**Comment by grese** [comment]
@gaearon - Looks like the fiddle you posted was the same content that I had in my fiddle above.  If I understand you correctly though, this is what you meant:

https://jsfiddle.net/grese/qhw0mxtt/

**Comment by gaearon** [comment]
Oops, I must have forgotten to hit save 😄
