### ISSUE TITLE
Ensure the npm command `weigh` results in the expected result

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#9980]
Just creating this issue to track this thread https://twitter.com/_developit/status/875098596328255488

Currently some tools don't properly DCE the npm bundle branching. We'll need to combine the dev and prod bundle into one file.

**Comment by gaearon** [comment]
Do we need one file specifically or would https://github.com/facebook/react/pull/9969 help?

**Comment by sebmarkbage** [comment]
I guess it's not critical but you'd still pay for the extra module overhead for 3 modules instead of 1.

**Comment by sebmarkbage** [comment]
6 instead of 2 I guess. Since it's two packages. That overhead probably isn't significant in bundles but it'll add unnecessary numbers to a comparison result like this tool.

**Comment by trueadm** [comment]
I'm not sure combining files is the right approach here at all. Combining modules in a single file will definitely impact the startup performance of using React on NPM as a Node module.

I feel `weigh` should move way from using Browserify if it wants to get more accurate results (i.e. use webpack).

**Comment by gaearon** [comment]
Seems like `weight` is fine now. The "uncompressed" size grew but the minified ones are down.

<img width="641" alt="screen shot 2017-07-27 at 22 49 59" src="https://user-images.githubusercontent.com/810438/28693726-1f4c7da6-731e-11e7-91e3-ca99b0d51e13.png">
<img width="645" alt="screen shot 2017-07-27 at 22 50 12" src="https://user-images.githubusercontent.com/810438/28693727-1f5134fe-731e-11e7-9497-3349aa2fd1b4.png">
