### ISSUE TITLE
No compatible version found: create-react-class@'>=15.6.0 <16.0.0

### ISSUE THREAD

**Issue by UglyTroLL** [facebook/react#9981]
Is this only my env or the package on npm is actually missing?

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
```
npm ERR! notarget No compatible version found: create-react-class@'>=15.6.0 <16.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.1.0","1.1.1","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","15.5.0","15.5.1","15.5.2","15.5.3","15.5.4","15.6.0-rc.0"]
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
npm should install it with no problem
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.6.0

**Comment by UglyTroLL** [comment]
It works now on my end

**Comment by gaearon** [comment]
This probably means your custom npm registry hasn't been updated yet.
