### ISSUE TITLE
What should be the proper compatibale version of react, react-addons-test-utils, react-dom.

### ISSUE THREAD

**Issue by brahamshakti** [facebook/react#9986]
I tried various package version but I am still getting error when I run `npm test`:

    console.error node_modules/fbjs/lib/warning.js:45
        Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types`

What is causing the issue, my `package.json` file  looks like

    {
      "name": "test",
      "version": "1.1",
      "description": "test",
      "devDependencies": {
        "babel-jest": "^18.0.0",
        "babel-preset-es2015": "^6.1.2",
        "babel-preset-react": "^6.1.2",
        "babel-preset-stage-2": "^6.1.2",
        "babelify": "^7.2.0",
        "browserify": "^12.0.1",
        "browserify-incremental": "^3.0.1",
        "enzyme": "^2.7.1",
        "eslint": "^3.0.0",
        "jest": "^18.1.0",
        "react-addons-test-utils": "^0.14.2",
        "redux-socket.io": "^1.2.0",
        "sinon": "2.3.4",
        "socket.io-client": "^1.4.8"
      },
      "dependencies": {
        "history": "^3.0.0",
        "prop-types": "15.5",
        "react": "^15.5",
        "react-dom": "^15.5",
        "react-redux": "^4.4.5",
        "react-router-dom": "^4.0.0-beta.8",
        "redux": "^3.6.0",
        "redux-thunk": "^2.2.0"
      },
      "scripts": {
        "test": "jest"
      }
    }

And when I update my ` react-addons-test-utils: "^15.5"` I am getting this error.

    Cannot find module 'react-dom/lib/ReactTestUtils' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-addons-test-utils/index.js:75:18)
      at node_modules/enzyme/build/react-compat.js:143:21

May I know what is causing this issue, is there any dependency issue which i don't know.

**Comment by gaearon** [comment]
It is not supported to mix `0.14` and `15` packages. Please ensure they're all on the same version.
If you make all of them `^15.6.1` it should work.

If you have more issues please provide a project reproducing them.

**Comment by brahamshakti** [comment]
I tried changing the version to 
    
      "react-addons-test-utils": "^15.6.0"
    },
    "dependencies": {
      "react": "^15.6.1",
      "react-dom": "^15.6.1",
      "react-redux": "^4.4.5",
      "react-router-dom": "^4.0.0-beta.8",
    }
And As I have written previously I am getting this error:

    Cannot find module 'react-dom/lib/ReactTestUtils' from 'index.js

No I can not share my project as I dont have liberty to do so. if you need some more information I can do so.

**Comment by gaearon** [comment]
If you can't share your project, please share a minimal example reproducing this.
You can create a new project with the same `package.json`, add one test to it, and verify you still have this issue.

**Comment by milesj** [comment]
Replace `react-addons-test-utils` with `react-test-renderer` and `react-dom/test-utils`.

**Comment by gaearon** [comment]
Did you run `npm install` after changing versions? I'm pretty sure you have some different version of `react-dom`.

The file you say is missing is definitely there:

https://unpkg.com/react-dom@15.6.0/lib/ReactTestUtils.js

So something is wrong with either the versions that really got installed, or with your bundler configuration.

I'll close because there's nothing more we can do. If you provide a project reliably reproducing this I could take another look.

**Comment by zhoulujun** [comment]
https://www.zhoulujun.cn/html/tools/webpack/2016_0217_6459.html
  "react": "^16.7.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.7.0",
react-dom 16 根本就没有lib/ReactTestUtils 这玩意儿。
于是修改，react-addons-test-utils index 文件,坑还是未填好
//module.exports = require('react-dom/lib/ReactTestUtils');
module.exports = require('react-dom/test-utils');
最好还是降级到15.x ，期待官方修复！
