### ISSUE TITLE
Regression: onChange doesn't fire with defaultChecked and radio inputs

### ISSUE THREAD

**Issue by ThisIsMissEm** [facebook/react#9988]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In React 15.6.1, this behaviour is changed; In 15.5.4, it fires the change event reliably.

15.6.1 - https://codesandbox.io/embed/VPA42ZnRo
15.5.4 - https://codesandbox.io/embed/JZ0mnE5oy

You'll need to have the console open to get the debugger statement.

In 15.6.1, the first change fires, but all subsequent changes do not fire. In 15.5.4, all changes fire.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.6.1 vs React 15.5.4; Chrome latest stable.

**Comment by gaearon** [comment]
cc @jquense

**Comment by jquense** [comment]
I'm not sure..this is a weird kinda case, The problem seems to be that if you don't control the the group the onChange event doesn't fire (but the value is correct). cc @insin as well since he also noticed this.

**Comment by jquense** [comment]
Ah fairly certain I know what's happening. The `checked` value is tracked for each individual input, but when another radio is checked, there is no update to the last checked value so it remains `true` when you click back to it aect thinks it was already checked and so doesn't update it...I think this needs a simple call in `updateCousins` in ReactDOMInput

**Comment by jquense** [comment]
addendum this only happens with uncontrolled groups because the `updateCousins` method triggers an update on the component instance but since there is no value state changing (from the perspective of the instance) nothing changes.

I wish uncontrolled inputs didn't exist ;)

**Comment by MadaraUchiha** [comment]
Managed to reproduce this in a simpler test case, defaultChecked is not needed.

```jsx
var Hello = React.createClass({
  render: function() {
    return <div>
    	<input type="radio" name="foo" onChange={() => console.log(1)} />
      <input type="radio" name="foo" onChange={() => console.log(2)} />
    </div>;
  }
});

ReactDOM.render(
  <Hello name="World" />,
  document.getElementById('container')
);
```

Changing between the radio buttons back and forth will only log 1 or 2 once. @linkgoron 

See Fiddle for example: https://jsfiddle.net/aaqfzzjg/

**Comment by nandoacoelho** [comment]
Managed to reproduce the problem with 15.3.1 vs 15.6.1 also without defaultChecked
15.3.1 - https://codepen.io/nandoacoelho/pen/XgVMxL
15.6.1 - https://codepen.io/nandoacoelho/pen/EXoWrY

**Comment by jquense** [comment]
To sum up the problem is uncontrolled radio/checkbox groups.

should probably update the issue title

**Comment by davidyu85** [comment]
Will this issue be fixed down the track? 

Because this problem is affecting my web app and now I am stuck with the v15.4.1 to make my radio buttons work.

**Comment by MadaraUchiha** [comment]
The easy workaround is to manage the radio buttons with component state, instead of relying on the underlying DOM. But yes, this is a bit annoying.

**Comment by rhinoceraptor** [comment]
This is especially annoying for Redux/MobX users where DOM state is never used.

**Comment by jquense** [comment]
It sure what you mean by that... An app that doesn't use DOM state won't have this problem since it would be using only controlled componenta

**Comment by rhinoceraptor** [comment]
You're right, I meant to say component state.
