### ISSUE TITLE
Set initial state to undefined

### ISSUE THREAD

**Issue by borela** [facebook/react#9991]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Initial state is null.

**What is the expected behavior?**
Initial state is undefined. We can manually set the state to undefined in the class, but it would make sense to be out of the box as it would allow destructuring without errors.

**Version:**
React 15.6.1
React-Dom 15.6.1

Sorry if this has been suggested before.

**Comment by gaearon** [comment]
Can you provide a code example that would benefit from this? It's not clear to me what you want to destructure.

**Comment by borela** [comment]
This suggestion can be closed, [I worked around it using decorators and a completely different design](https://github.com/borela/presentable).

```js
import React, { Component } from 'react'

class SomeComponentA extends Component {
  // Maybe this component adds the special flag later at the life cycle methods...
}

class SomeComponentB extends Component {
  state = { specialFlag: true }
  // Maybe this component removes the special flag later at the life cycle methods...
}

class Container extends Component {
  render() {
    let { specialFlag } = this.foo.state
    let PassedComponent = this.props.passMeAComponent
    if (specialFlag) {
      // Do something special...
    }
    return <PassedComponent ref={x => this.foo = x} />
  }
}

<Container passMeAComponent={SomeComponentA} />
<Container passMeAComponent={SomeComponentB} />
```

This example is too simplistic but the idea was to make state itself optional.

**Comment by gaearon** [comment]
Oh, I see. Generally I wouldn’t recommend reaching into `state` of another component. This makes them coupled too tightly.

**Comment by borela** [comment]
Yes, but that example doesn't show exactly the intent at the time, I was trying to separate the template from the component logic and the presenter decorator simplified the whole process.
