### ISSUE TITLE
createReactClassIntegration-test fails

### ISSUE THREAD

**Issue by vritant24** [facebook/react#9997]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
on running npm test on master branch, createReactClassIntegration-test fails

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
I just installed the repo after cloning it, ran npm install, and then npm test.

**What is the expected behavior?**
Test should pass

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest version as of commit  00ba97a

**Comment by gaearon** [comment]
It probably fails because you run `npm install` rather than `yarn` so you get the latest version (which included a bugfix). We need to cherrypick 07fe7ad6d78b55982c83ddc89a93a70fe0ffa579 and 76b916bf328a793ac41778ba6515921db0d2c91d to master I think.

**Comment by gaearon** [comment]
This should be fixed by https://github.com/facebook/react/pull/9629.
